### PR TITLE
[Flight] Allow Temporary References to be awaited

### LINKED ISSUE #33534: Bug: Server functions error when returning a client reference
Returning a temporary client reference from a server function causes an error.

My understanding of the issue is that `async` functions will automatically check return values for `.then()` methods in order to flatten nested promises. However, client references in server functions guard access to any property.

Image

React version: 19.1.0

## Steps To Reproduce

1. Create a server function which would return a client reference.
2. Call the server function from the client with a client reference (non-RSC-serializable value).

Link to code example:
https://codesandbox.io/p/devbox/server-function-cant-return-client-reference-477k4c

## The current behavior
The server function errors before returning a client reference.

## The expected behavior
The server function should return the same client reference without error. Client references should not guard accessing the `then` property, and should instead return `undefined`.

### PR DESCRIPTION
**Pull request by sebmarkbage**
Fixes #33534.

`.then` method can be tested when you await a value that's not a Promise. For regular Client References we have a way to mark those as "async" and yield a reference to the unwrapped value in case it's a Promise on the Client.

However, the realization is that we never serialize Promises as opaque when passed from the client to the server. If a Promise is passed, then it would've been deserialized as a Promise (while still registered as a temporary reference) and not one of these Proxy objects.

Technically it could be a non-function value on the client which would be wrong but you're not supposed to dot into it in the first place.

So we can just assume it's `undefined`.

### CODE REVIEW

**Comment by sebmarkbage** [comment]
Same as #33761 basically. I just saw it. I landed that one but rebased with my test/comment which has a bit more coverage.

**Review by rickhanlonii — APPROVED** [review]

File: packages/react-server/src/ReactFlightServerTemporaryReferences.js [hunk 1]
```diff
@@ -70,8 +70,12 @@ const proxyHandlers = {
             `Instead, you can export a Client Component wrapper ` +
             `that itself renders a Client Context Provider.`,
         );
-      // Allow returning a temporary reference from an async function
       case 'then':
+        // Allow returning a temporary reference from an async function
+        // Unlike regular Client References, a Promise would never have been serialized as
+        // an opaque Temporary Reference, but instead would have been serialized as a
+        // Promise on the server and so doesn't hit this path. So we can assume this wasn't
+        // a Promise on the client.
```
Comment (eps1lon) [inline packages/react-server/src/ReactFlightServerTemporaryReferences.js:78]: The actual diff is in https://github.com/facebook/react/pull/33761. This is just about adding an explainer
