### PR TITLE
[playground] Fixes #31331

### LINKED ISSUE #31331: [Compiler Bug]: `"use no memo"` Directive ignored by React Compiler Playground
### What kind of issue is this?

- [X] React Compiler core (the JS output is incorrect, or your app works incorrectly after optimization)
- [ ] babel-plugin-react-compiler (build issue installing or using the Babel plugin)
- [x] eslint-plugin-react-compiler (build issue installing or using the eslint plugin)
- [ ] react-compiler-healthcheck (build issue installing or using the healthcheck script)

### Link to repro

https://playground.react.dev/#N4Igzg9grgTgxgUxALhAMygOzgFwJYSYAEAwhALYAOhCmOAFAJRHAA6xRrIUYCRmEIuQTkIXANzsiROITA4iAbVlYcAGiK8cZVQF0iAXiI8EAZRwBDHAnoAGRpI4wEOWMQA8AEzwA3AHzAKnQAvu4A9N7+jsEgwUA

### Repro steps

To reproduce the issue, create a simple React component and add the `"use no memo"` directive at the top of the function, like this:
```jsx
function Component() {
  "use no memo";
  const [count, setCount] = useState(0);
  return <div>{count}</div>;
}
```
Even though the directive is there, the component still gets compiled, which shouldn’t happen according to the documentation. I’ve also tried placing the directive at the top of the file, and the behavior doesn't change.

To confirm, I tested this in different components and even in a fresh project, but the components keep getting compiled regardless of the directive.

The same result appears in the React Compiler Playground, showing that the `"use no memo"` directive is being ignored.

### How often does this bug happen?

Every time

### What version of React are you using?

19

### What version of React Compiler are you using?

19.0.0-beta-8a03594-20241020

### PR DESCRIPTION
**Pull request by subbu963**
## Summary
There is a bug in playground(https://github.com/facebook/react/issues/31331) which doesnt support 'use memo' or 'use no memo' directives. Its misleading while debugging components in the playground

## How did you test this change?
Ran test cases and added a few extra test cases as well

## Changes
1) Adds support for 'use memo' and 'use no memo'
2) Cleanup E2E test cases a bit
3) Adds test cases for use memo
4) Added documentation to run test cases

## Implementation
`parseFunctions` returns a set of functions to be compiled. But, it doesnt filter out/handle memoized opted/un-opted functions using directives.

ive just created a `compile` flag to enable/disable compiling [here](https://github.com/facebook/react/pull/31561/files#diff-305de47a3fe3ce778e22d5c5cf438419a59de8e7f785b45f659e7b41b1e30b03R113)

Then I am just skipping those functions from getting compile [here](https://github.com/facebook/react/pull/31561/files#diff-305de47a3fe3ce778e22d5c5cf438419a59de8e7f785b45f659e7b41b1e30b03R253)

### CODE REVIEW

File: compiler/apps/playground/components/Editor/EditorImpl.tsx [hunk 1]
```diff
@@ -98,7 +114,46 @@ function parseFunctions(
...
+      return {
+        compile: [
+          MemoizeDirectiveState.Enabled,
+          MemoizeDirectiveState.Undefined,
+        ].includes(parentDirectiveCheck),
+        fn,
+      };
+    }
+    return {compile: false, fn};
+  });
```
Comment (poteto) [inline compiler/apps/playground/components/Editor/EditorImpl.tsx:156]: rather than map over this list again, it might be more straightforward to do this in the traversal above and change the type of `items` to be your new return type

File: compiler/apps/playground/components/Editor/EditorImpl.tsx [hunk 2]
```diff
@@ -59,20 +70,25 @@ function parseInput(input: string, language: 'flow' | 'typescript'): any {
...
-  | NodePath<t.ArrowFunctionExpression>
-  | NodePath<t.FunctionExpression>
-> {
-  const items: Array<
-    | NodePath<t.FunctionDeclaration>
-    | NodePath<t.ArrowFunctionExpression>
-    | NodePath<t.FunctionExpression>
-  > = [];
+): Array<{
+  compile: boolean;
```
Comment (poteto) [inline compiler/apps/playground/components/Editor/EditorImpl.tsx:88]: I think something like `compilationEnabled/Disabled` might be more accurate?

File: compiler/apps/playground/components/Editor/EditorImpl.tsx [hunk 3]
```diff
@@ -98,7 +114,46 @@ function parseFunctions(
...
+
+      if (!parentWithDirective) return {compile: true, fn};
+      const parentDirectiveCheck = checkExplicitMemoizeDirectives(
+        (parentWithDirective.node as t.Program | t.BlockStatement).directives,
+      );
+      return {
+        compile: [
+          MemoizeDirectiveState.Enabled,
+          MemoizeDirectiveState.Undefined,
+        ].includes(parentDirectiveCheck),
```
Comment (poteto) [inline compiler/apps/playground/components/Editor/EditorImpl.tsx:151]: nit: This is inefficient since it allocates a new array each time and iterates over it, maybe consider switching `MemoizeDirectiveState` to a module scoped `Set` instead.  `checkExplicitMemoizeDirectives` can just return a string

File: compiler/apps/playground/__tests__/e2e/page.spec.ts [hunk 4]
```diff
@@ -8,42 +8,79 @@
...
+test('editor should open successfully', async ({page}) => {
+  await page.goto(`/`, {waitUntil: 'networkidle'});
   await page.screenshot({
     fullPage: true,
-    path: 'test-results/00-on-networkidle.png',
+    path: 'test-results/00-fresh-page.png',
   });
+});
+test('editor should compile from hash successfully', async ({page}) => {
+  const STORE: Store = {
```
[the remark this answers is not in the document]
Comment (subbu963) [reply compiler/apps/playground/__tests__/e2e/page.spec.ts]: yeah makes sense. changed it

File: compiler/apps/playground/components/Editor/EditorImpl.tsx (hunk 1 above)
Comment (subbu963) [reply compiler/apps/playground/components/Editor/EditorImpl.tsx]: Good point @poteto . changed it

File: compiler/apps/playground/components/Editor/EditorImpl.tsx (hunk 2 above)
Comment (subbu963) [reply compiler/apps/playground/components/Editor/EditorImpl.tsx]: done

File: compiler/apps/playground/components/Editor/EditorImpl.tsx (hunk 3 above)
Comment (subbu963) [reply compiler/apps/playground/components/Editor/EditorImpl.tsx]: Moved those arrays to separate sets

**Review by poteto — COMMENTED** [review]
Could you add a few more tests covering module scoped "use no memo" and a nested one?

**Comment by subbu963** [comment]
@poteto added a few more test cases like you asked

**Comment by poteto** [comment]
Thanks!
