### PR TITLE
Fix uSES hydration in strict mode

### LINKED ISSUE #26095: Bug: useSyncExternalStore will cause hydration missmatch in `StrictMode` if `serverSnapshot` is different from `snapshot`
## React version
React version: 18.3.0-next-b0671f9ea-20230130

## Problem
In `StrictMode`,  when using hydrateRoot to render a component that using `useSyncExternalStore` it seems that useSES will do hydration twice. 

But in second hydration process,  useSES does not use the result of `getServerSnapshot` as initial state, which will cause hydration error.

This problem will only happen in `development` mode, 

## Reproduce
Link to code example:
https://codesandbox.io/s/useses-18-3-rojznv

It works well in react 18.2
https://codesandbox.io/s/useses-18-2-13iskc

### PR DESCRIPTION
**Pull request by sophiebits**
Previously, we'd call and use getSnapshot on the second render resulting in `Warning: Text content did not match. Server: "Nay!" Client: "Yay!"` and then `Error: Text content does not match server-rendered HTML.`.

Fixes #26095. Closes #26113. Closes #25650.

### CODE REVIEW

**Comment by sophiebits** [comment]
Not sure I understand the test failure.

**Review by eps1lon — APPROVED** [review]
🥳

**Comment by eps1lon** [comment]
Variant tests produce different results though.

**Comment by rickhanlonii** [comment]
@sophiebits I'm not sure exactly why, but the feature flag causing the failure is `enableSyncDefaultUpdates`. This is the flag we use to test both the OSS "sync by default" behavior (when true), and the old internal "concurrent by default" behavior (when false). So for some reason, when we're concurrent by default, the `Nah` logs twice.

**Comment by rickhanlonii** [comment]
It's the same as:

```
React.startTransition(() => {
  ReactDOMClient.hydrateRoot(container, element);
});
```

I'm kinda confused by this though. I think I would expect the log to have 'Nay!' twice (like in the failure) because of double rendering on mount in Strict Mode. Which behavior is "right" and why are they different with and without startTransition?

**Comment by sophiebits** [comment]
Hm, it's because of this check:

https://github.com/facebook/react/blob/7ac5e9a602347f3b7d26c60a549c483d3bc88bbf/packages/react-reconciler/src/ReactFiberWorkLoop.js#L935-L941

**Comment by sophiebits** [comment]
OK, now I think this might be right.

File: packages/react-reconciler/src/ReactFiberHooks.js [hunk 1]
```diff
@@ -1799,15 +1797,28 @@ function updateSyncExternalStore<T>(
...
-  if (__DEV__) {
-    if (!didWarnUncachedGetSnapshot) {
-      const cachedSnapshot = getSnapshot();
-      if (!is(nextSnapshot, cachedSnapshot)) {
-        console.error(
-          'The result of getSnapshot should be cached to avoid an infinite loop',
-        );
-        didWarnUncachedGetSnapshot = true;
+  let nextSnapshot;
+  const isHydrating = getIsHydrating();
```
Comment (acdlite) [inline packages/react-reconciler/src/ReactFiberHooks.js:1801]: I think this was a regression when I made it so that the "rerender" dispatcher is used during the strict mode double render. Originally the idea was to keep the `getIsHydrating` out of the update path because it's always false during an update.

Right now there is no special "rerender" implementation of useSES, but if we add one we can keep this extra check out of the common path.

Comment (sophiebits) [reply packages/react-reconciler/src/ReactFiberHooks.js:1801]: I am skeptical that the double implementations are good for perf (we should benchmark it sometime) but I can change it.

Comment (acdlite) [reply packages/react-reconciler/src/ReactFiberHooks.js:1801]: You mean because of the code size? Execution wise I don't see why it would be slower

Comment (sophiebits) [reply packages/react-reconciler/src/ReactFiberHooks.js:1801]: Code size and because the function dispatch call is more dynamic so I imagine it can’t inline a jump.

Comment (sophiebits) [reply packages/react-reconciler/src/ReactFiberHooks.js:1801]: Also, where do we stop? Should we have a fourth implementation for the rerender-on-initial-mount case instead of combining it with the rerender-on-update one like we do today? Right now updateEffect has a branch for currentHook === null.

File: packages/react-reconciler/src/ReactFiberHooks.js [hunk 2]
```diff
@@ -3991,7 +4079,11 @@ if (__DEV__) {
     ): T {
       currentHookNameInDev = 'useSyncExternalStore';
       updateHookTypesDev();
-      return updateSyncExternalStore(subscribe, getSnapshot, getServerSnapshot);
+      return rerenderSyncExternalStore(
```
Comment (sophiebits) [inline packages/react-reconciler/src/ReactFiberHooks.js:4082]: (also noticed that these should also maybe wrap in InvalidNestedHooksDispatcher although idk why you would try to use a hook in getSnapshot)

**Review by sophiebits — COMMENTED** [review]
updated

File: packages/react-reconciler/src/ReactFiberHooks.js (hunk 1 above)
Comment (acdlite) [reply packages/react-reconciler/src/ReactFiberHooks.js:1801]: Oh I was just thinking the rerender implementation would check `currentHook` and call the mount or update ones as appropriate. I agree it's not worth duplicating the entire update implementation.

Like I did here for rerenderOptimisticHook:

https://github.com/facebook/react/blob/df12d7eac40c87bd5fdde0aa5a739bce9e7dce27/packages/react-reconciler/src/ReactFiberHooks.js#L2049-L2052

The main reason we added the separate phases was to keep the _mount_ path fast, not so much the update one. But subjectively I also prefer it for code organization reasons because the logic does end up being significantly different in a lot of the hooks.

Comment (acdlite) [reply packages/react-reconciler/src/ReactFiberHooks.js:1801]: Ultimately though my original comment was only a factoring nit. I'd probably structure this differently if I were doing it myself, but I liked how you had it before more than this way, so you could just revert it back to that and if I really want to I can submit a follow up PR later.

The important thing is the fix itself, and the regression test you added.

Comment (sophiebits) [reply packages/react-reconciler/src/ReactFiberHooks.js:1801]: Happy to change it to what you just described! That way makes sense to me. Wasn’t sure if you approved of the fix originally.

Comment (sophiebits) [reply packages/react-reconciler/src/ReactFiberHooks.js:1801]: Hmm I'm actually not sure the best way to reuse the mount code on rerender because we need it to call updateWorkInProgressHook including for the interior mountEffect. Gonna land it with the unified update+rerender code like I had before but would be happy to review a refactor if you have one in mind.

**Comment by reccanti** [comment]
Has this been included in a release yet? I'm encountering a similar issue but I'm not sure it's related
