### PR TITLE
[react-dom] Include all Node.js APIs in Bun entrypoint for `/server`

### LINKED ISSUE #33612: Bug: renderToPipeableStream is missing in Bun exports
React version:

## Steps To Reproduce

1. Run under Bun and Node and see the export differense without a reason

```ts
import { createServer } from "node:http";
import { renderToPipeableStream } from "react-dom/server.node";

function App() {
  return <div>Hello World</div>;
}

function handleRequest(res) {
  // ... in your server handler ...
  const stream = renderToPipeableStream(<App />, {
    onShellReady() {
      res.statusCode = 200;
      res.setHeader("Content-type", "text/html");
      stream.pipe(res);
    },
    // ...
  });
}

const http = createServer((req, res) => handleRequest(res));

http.listen(3000, () => {
  console.log("Server is running on port 3000");
});
```

```bash
> bun .\a.tsx
1 | (function (entry, fetcher)
              ^
SyntaxError: Export named 'renderToPipeableStream' not found in module '...\node_modules\react-dom\server.bun.js'.
      at loadAndEvaluateModule (1:11)

Bun v1.2.17-canary.50+41d10ed01 (Windows x64)
> bunx tsx .\a.tsx
Server is running on port 3000
```

as we can see it really missing here: https://github.com/facebook/react/blob/main/packages/react-dom/src/server/ReactDOMFizzServerBun.js

It works fine if you force .node export:

```ts
import { createServer } from "node:http";
import { renderToPipeableStream } from "react-dom/server.node";

function App() {
  return <div>Hello World</div>;
}

function handleRequest(res) {
  // ... in your server handler ...
  const stream = renderToPipeableStream(<App />, {
    onShellReady() {
      res.statusCode = 200;
      res.setHeader("Content-type", "text/html");
      stream.pipe(res);
    },
    // ...
  });
}

const http = createServer((req, res) => handleRequest(res));

http.listen(3000, () => {
  console.log("Server is running on port 3000");
});
```

## The current behavior

Export named 'renderToPipeableStream' not found in module '...\node_modules\react-dom\server.bun.js'.

## The expected behavior

It should works as in node export

### PR DESCRIPTION
**Pull request by RiskyMH**
## Summary

fixes https://github.com/remix-run/react-router/issues/12568, fixes #33612

The custom bun export condition seems to be missing some of the newer apis that normal node one has, so this PR adds the missing exports so that users of bun don't have errors.

## How did you test this change?

used the built output and verified the functions are now present in the bun bundles

### CODE REVIEW

File: scripts/rollup/bundles.js [hunk 1]
```diff
@@ -398,7 +398,7 @@ const bundles = [
     global: 'ReactDOMServer',
     minifyWithProdErrorCodes: false,
     wrapWithModuleBoundaries: false,
-    externals: ['react', 'react-dom'],
+    externals: ['react', 'util', 'crypto', 'async_hooks', 'react-dom'],
```
Comment (eps1lon) [inline scripts/rollup/bundles.js]: Bun doesn't implement `createHook` in `async_hooks` (https://bun.com/docs/runtime/nodejs-apis) so I don't think this works. Need a dedicated implementation for methods imported from Fizz Server for Node.js.

Comment (RiskyMH) [reply scripts/rollup/bundles.js]: Oh yeah your right, Bun doesn't support it right now. I just copied the key for node externals as it was erroring in build, but I believe I can simply remove that async_hooks one and it should still work as the functions I'm exporting don't need it.

File: packages/react-dom/src/server/react-dom-server.bun.js [hunk 2]
```diff
@@ -8,3 +8,15 @@
  */
 
 export * from './ReactDOMFizzServerBun.js';
+export {
+  renderToPipeableStream,
+  resumeToPipeableStream,
+  // $FlowFixMe[cannot-resolve-module]
```
Comment (RiskyMH) [inline packages/react-dom/src/server/react-dom-server.bun.js]: I did try to add it to `inlinedHostConfigs.js`, but then I got weird errors that didn't make too much sense to me. If it worked in normal node and the built one included the exports (that are usable correctly), then I can't understand how bun fails when exporting it.

<details>
<summary>An error</summary>

```ts
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ packages/react-dom/src/server/ReactDOMFizzServerNode.js:50:38

Cannot call startFlowing with destination bound to destination because: [incompatible-call]
 • Either stream$Writable [1] is incompatible with ReadableStreamController [2].
 • Or MightBeFlushable [3] is incompatible with ReadableStreamController [2].

        packages/react-dom/src/server/ReactDOMFizzServerNode.js
        47│ ensureCorrectIsomorphicReactVersion();
        48│
        49│ function createDrainHandler(destination: Destination, request: Request) {
        50│   return () => startFlowing(request, destination);
        51│ }
        52│
        53│ function createCancelHandler(request: Request, reason: string) {

        packages/react-server/src/ReactServerStreamConfigBun.js
    [2] 12│ type BunReadableStreamController = ReadableStreamController & {

        packages/react-server/src/ReactServerStreamConfigNode.js
 [1][3] 19│ export type Destination = Writable & MightBeFlushable;


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ packages/react-dom/src/server/ReactDOMFizzServerNode.js:50:38

Cannot call startFlowing with destination bound to destination because: [incompatible-call]
 • Either inexact stream$Writable [1] is incompatible with exact object type [2].
 • Or inexact MightBeFlushable [3] is incompatible with exact object type [2].

        packages/react-dom/src/server/ReactDOMFizzServerNode.js
        47│ ensureCorrectIsomorphicReactVersion();
        48│
        49│ function createDrainHandler(destination: Destination, request: Request) {
        50│   return () => startFlowing(request, destination);
        51│ }
        52│
        53│ function createCancelHandler(request: Request, reason: string) {

        packages/react-server/src/ReactServerStreamConfigBun.js
    [2] 12│ type BunReadableStreamController = ReadableStreamController & {
        13│   end(): mixed,
        14│   write(data: Chunk | BinaryChunk): void,
        15│   error(error: Error): void,
        16│   flush?: () => void,
        17│ };

        packages/react-server/src/ReactServerStreamConfigNode.js
 [1][3] 19│ export type Destination = Writable & MightBeFlushable;


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ packages/react-dom/src/server/ReactDOMFizzServerNode.js:151:29

Cannot call startFlowing with destination bound to destination because stream$Writable [1] is incompatible with
ReadableStreamController [2]. [incompatible-call]

     packages/react-dom/src/server/ReactDOMFizzServerNode.js
 [1] 143│     pipe<T: Writable>(destination: T): T {
        :
     148│       }
     149│       hasStartedFlowing = true;
     150│       prepareForStartFlowingIfBeforeAllReady(request);
     151│       startFlowing(request, destination);
     152│       destination.on('drain', createDrainHandler(destination, request));
     153│       destination.on(
     154│         'error',

     packages/react-server/src/ReactServerStreamConfigBun.js
 [2]  12│ type BunReadableStreamController = ReadableStreamController & {


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ packages/react-dom/src/server/ReactDOMFizzServerNode.js:151:29

Cannot call startFlowing with destination bound to destination because inexact stream$Writable [1] is incompatible with
exact object type [2]. [incompatible-exact]

     packages/react-dom/src/server/ReactDOMFizzServerNode.js
 [1] 143│     pipe<T: Writable>(destination: T): T {
        :
     148│       }
     149│       hasStartedFlowing = true;
     150│       prepareForStartFlowingIfBeforeAllReady(request);
     151│       startFlowing(request, destination);
     152│       destination.on('drain', createDrainHandler(destination, request));
     153│       destination.on(
     154│         'error',

     packages/react-server/src/ReactServerStreamConfigBun.js
 [2]  12│ type BunReadableStreamController = ReadableStreamController & {
      13│   end(): mixed,
      14│   write(data: Chunk | BinaryChunk): void,
      15│   error(error: Error): void,
      16│   flush?: () => void,
      17│ };


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ packages/react-dom/src/server/ReactDOMFizzServerNode.js:233:35

Cannot call startFlowing with writable bound to destination because stream$Writable [1] is incompatible with
ReadableStreamController [2]. [incompatible-call]

     packages/react-dom/src/server/ReactDOMFizzServerNode.js
 [1] 224│       let writable: Writable;
        :
     230│               createFakeWritableFromReadableStreamController(controller);
     231│           },
     232│           pull: (controller): ?Promise<void> => {
     233│             startFlowing(request, writable);
     234│           },
     235│           cancel: (reason): ?Promise<void> => {
     236│             stopFlowing(request);

     packages/react-server/src/ReactServerStreamConfigBun.js
 [2]  12│ type BunReadableStreamController = ReadableStreamController & {


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ packages/react-dom/src/server/ReactDOMFizzServerNode.js:233:35

Cannot call startFlowing with writable bound to destination because inexact stream$Writable [1] is incompatible with
exact object type [2]. [incompatible-exact]

     packages/react-dom/src/server/ReactDOMFizzServerNode.js
 [1] 224│       let writable: Writable;
        :
     230│               createFakeWritableFromReadableStreamController(controller);
     231│           },
     232│           pull: (controller): ?Promise<void> => {
     233│             startFlowing(request, writable);
     234│           },
     235│           cancel: (reason): ?Promise<void> => {
     236│             stopFlowing(request);

     packages/react-server/src/ReactServerStreamConfigBun.js
 [2]  12│ type BunReadableStreamController = ReadableStreamController & {
      13│   end(): mixed,
      14│   write(data: Chunk | BinaryChunk): void,
      15│   error(error: Error): void,
      16│   flush?: () => void,
      17│ };


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ packages/react-dom/src/server/ReactDOMFizzServerNode.js:344:29

Cannot call startFlowing with destination bound to destination because stream$Writable [1] is incompatible with
ReadableStreamController [2]. [incompatible-call]

     packages/react-dom/src/server/ReactDOMFizzServerNode.js
 [1] 337│     pipe<T: Writable>(destination: T): T {
     338│       if (hasStartedFlowing) {
     339│         throw new Error(
     340│           'React currently only supports piping to one writable stream.',
     341│         );
     342│       }
     343│       hasStartedFlowing = true;
     344│       startFlowing(request, destination);
     345│       destination.on('drain', createDrainHandler(destination, request));
     346│       destination.on(
     347│         'error',

     packages/react-server/src/ReactServerStreamConfigBun.js
 [2]  12│ type BunReadableStreamController = ReadableStreamController & {


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ packages/react-dom/src/server/ReactDOMFizzServerNode.js:344:29

Cannot call startFlowing with destination bound to destination because inexact stream$Writable [1] is incompatible with
exact object type [2]. [incompatible-exact]

     packages/react-dom/src/server/ReactDOMFizzServerNode.js
 [1] 337│     pipe<T: Writable>(destination: T): T {
     338│       if (hasStartedFlowing) {
     339│         throw new Error(
     340│           'React currently only supports piping to one writable stream.',
     341│         );
     342│       }
     343│       hasStartedFlowing = true;
     344│       startFlowing(request, destination);
     345│       destination.on('drain', createDrainHandler(destination, request));
     346│       destination.on(
     347│         'error',

     packages/react-server/src/ReactServerStreamConfigBun.js
 [2]  12│ type BunReadableStreamController = ReadableStreamController & {
      13│   end(): mixed,
      14│   write(data: Chunk | BinaryChunk): void,
      15│   error(error: Error): void,
      16│   flush?: () => void,
      17│ };


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ packages/react-dom/src/server/ReactDOMFizzServerNode.js:393:35

Cannot call startFlowing with writable bound to destination because stream$Writable [1] is incompatible with
ReadableStreamController [2]. [incompatible-call]

     packages/react-dom/src/server/ReactDOMFizzServerNode.js
 [1] 384│       let writable: Writable;
        :
     390│               createFakeWritableFromReadableStreamController(controller);
     391│           },
     392│           pull: (controller): ?Promise<void> => {
     393│             startFlowing(request, writable);
     394│           },
     395│           cancel: (reason): ?Promise<void> => {
     396│             stopFlowing(request);

     packages/react-server/src/ReactServerStreamConfigBun.js
 [2]  12│ type BunReadableStreamController = ReadableStreamController & {


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ packages/react-dom/src/server/ReactDOMFizzServerNode.js:393:35

Cannot call startFlowing with writable bound to destination because inexact stream$Writable [1] is incompatible with
exact object type [2]. [incompatible-exact]

     packages/react-dom/src/server/ReactDOMFizzServerNode.js
 [1] 384│       let writable: Writable;
        :
     390│               createFakeWritableFromReadableStreamController(controller);
     391│           },
     392│           pull: (controller): ?Promise<void> => {
     393│             startFlowing(request, writable);
     394│           },
     395│           cancel: (reason): ?Promise<void> => {
     396│             stopFlowing(request);

     packages/react-server/src/ReactServerStreamConfigBun.js
 [2]  12│ type BunReadableStreamController = ReadableStreamController & {
      13│   end(): mixed,
      14│   write(data: Chunk | BinaryChunk): void,
      15│   error(error: Error): void,
      16│   flush?: () => void,
      17│ };



Found 10 errors
Flow failed for the dom-bun renderer
```


</details>

Comment (eps1lon) [reply packages/react-dom/src/server/react-dom-server.bun.js]: The type errors don't seem surprising to me considering you're using Node interfaces with Bun's implementation. These don't necessarily match.

Comment (RiskyMH) [reply packages/react-dom/src/server/react-dom-server.bun.js]: Ah, so you're saying I should update those types to make it work and not error anywhere? I just didn't want to do a refactor in case it broke other stuff. I kind of thought it was already consistent tbh, but maybe more consistency is better to do!

From my testing, I believe the actual code itself works which is good I think.

Comment (RiskyMH) [reply packages/react-dom/src/server/react-dom-server.bun.js]: fixed the types to work better - it still has some FlowFixMe's because it doesn't seem to understand the union as nice as could have & the types are semi outdated for whats actually supported

**Comment by RiskyMH** [comment]
https://github.com/facebook/react/blob/8a8e9a7edf16fabc1335c9910bddfef66737ee4e/scripts/error-codes/codes.json#L209-L210

i wonder if these can be removed/edited now that bun actually supports node:stream well and thus the same apis as node (just with extra perf in some web api cases).

**Comment by eps1lon** [comment]
> i wonder if these can be removed/edited now that bun actually supports node:stream well and thus the same apis as node (just with extra perf in some web api cases).

These codes need to work for older versions of React. It seems like this message is specific to browser builds not Bun builds.

File: packages/react-dom/npm/server.bun.js [hunk 3]
```diff
@@ -12,6 +12,10 @@ if (process.env.NODE_ENV === 'production') {
 
 exports.version = b.version;
 exports.renderToReadableStream = b.renderToReadableStream;
+exports.renderToPipeableStream = b.renderToPipeableStream;
+if (b.resumeToPipeableStream) {
```
Comment (eps1lon) [inline packages/react-dom/npm/server.bun.js]: This is now stable so we can remove the conditional assignment

Comment (RiskyMH) [reply packages/react-dom/npm/server.bun.js]: Oh nice, fixed!

**Comment by janhesters** [comment]
Thanks @RiskyMH for creating this!
