### PR TITLE
fix: restore selection should consider the window of the container

### LINKED ISSUE #30864: Bug: Focus restore after elements are reordered does not work in child windows
This affects various Microsoft products that use child windows, and is an accessibility bug for users because focus is lost when they interact with an app and the active element is moved in DOM by React.

React version: 18.3.1

## Steps To Reproduce

1. Clone the repro repo https://github.com/ling1726/react-child-window-focus-repro
2. Run `npm install`
3. Run `npm run dev`
4. Open the demo app in `http://localhost:5173/`
5. Reorder the items with `ArrowUp` and `ArrowDown`
6. Open example in child window
7. Reorder the items with `ArrowUp` and `ArrowDown`
8. Notice that focus is lost immediately after reordering

Recording: 
focus repro

Link to code example: https://github.com/ling1726/react-child-window-focus-repro

## The current behavior
The current `getActiveElementDeep` always uses the global `window` keyword. **Note this snippet is from the React codebase**
https://github.com/facebook/react/blob/4f604941569d2e8947ce1460a0b2997e835f37b9/packages/react-dom-bindings/src/client/ReactInputSelection.js#L59-L71

This fails focus restore when the active element is moved by React because it never gets the correct active element in a child window. 

## The expected behavior

When React moves an active element it should restore focus to the active element in a child window

### PR DESCRIPTION
**Pull request by ling1726**
## Summary

Fixes #30864 

Before this PR the active elemen was always taken from the global `window`. This is incorrect if the renderer is in one window rendering into a container element in another window. The changes in this PR adds another code branch to use a `defaultView` of the container element if it exists so that `restoreSelection` after a commit will actually restore to the correct window.

## How did you test this change?

I patched these changes to the repro repo in the linked issue #39864 https://github.com/ling1726/react-child-window-focus-repro/blob/master/patches/react-dom%2B18.3.1.patch.

I followed the same repro steps in the linked issue and and could not repro the reported problem. Attaching screen recordings below:

Before
focus repro

After
after

### CODE REVIEW

**Comment by ling1726** [comment]
I'm not sure how to test child windows in Jest, would appreciate any guidance from maintainers

File: packages/react-dom-bindings/src/client/ReactInputSelection.js [hunk 1]
```diff
@@ -56,9 +56,12 @@ function isSameOriginFrame(iframe) {
   }
 }
 
-function getActiveElementDeep() {
+function getActiveElementDeep(containerInfo) {
   let win = window;
-  let element = getActiveElement();
+  if (containerInfo?.ownerDocument?.defaultView) {
+    win = containerInfo.ownerDocument.defaultView
+  }
```
Comment (josephsavona) [inline packages/react-dom-bindings/src/client/ReactInputSelection.js:63]: Note that we try to minimize optional chaining in the runtime because of how it expands when transpiled, and this case does it twice. Maybe:

```js
let win = containerInfo?.ownerDocument?.defaultView ?? window;
```

File: packages/shared/ReactVersion.js [hunk 2]
```diff
@@ -1,15 +1 @@
...
-
-// TODO: this is special because it gets imported during build.
-//
-// It exists as a placeholder so that DevTools can support work tag changes between releases.
-// When we next publish a release, update the matching TODO in backend/renderer.js
-// TODO: This module is used both by the release scripts and to expose a version
-// at runtime. We should instead inject the version number as part of the build
-// process, and use the ReactVersions.js module as the single source of truth.
-export default '19.0.0';
+export default '19.0.0-rc-d6cb4e77-20240911';
```
Comment (josephsavona) [inline packages/shared/ReactVersion.js:1]: revert

**Review by josephsavona — COMMENTED** [review]
The fix seems reasonable but we really need a test to prevent regressions. Have you tried using `window.open()` in Jest? What happens?

**Comment by rickhanlonii** [comment]
If `window.open()` doesn't work, you could probably use an iFrame

**Comment by rickhanlonii** [comment]
Here's a similar test: https://github.com/facebook/react/blob/378b305958eb7259cacfce8ad0e66eec07e07074/packages/react-dom/src/__tests__/ReactDOMFiber-test.js#L1169

File: packages/shared/ReactVersion.js (hunk 2 above)
Comment (ling1726) [reply packages/shared/ReactVersion.js]: Done in https://github.com/facebook/react/pull/30951/commits/c8f573e554d019af6db44062b9d2f00ede67d5c3

File: packages/react-dom-bindings/src/client/ReactInputSelection.js (hunk 1 above)
Comment (ling1726) [reply packages/react-dom-bindings/src/client/ReactInputSelection.js]: Done in https://github.com/facebook/react/pull/30951/commits/edd9d8a33cdec0c01e3d4dbdcd0b1dc592d0aa83

**Comment by ling1726** [comment]
@josephsavona  @rickhanlonii I've added a test in https://github.com/facebook/react/pull/30951/commits/e545af8ae358768e0df940aa902933b4593f8c42 please take a look 🙏🙏

`window.open` is not implemented in JSDOM, but I was able to just create a new JSDOM instance to get a new window to run this test on. I also ran the test without the fix and it fails as expected with focus on the new document's `body`

File: packages/react-dom/src/__tests__/ReactDOMFiber-test.js [hunk 3]
```diff
@@ -1272,4 +1283,48 @@ describe('ReactDOMFiber', () => {
...
+    await act(() => {
+      root.render(<Test />);
+    });
+
+    newWindow.document.getElementById('a').focus();
+    await act(() => {
+      newWindow.document.getElementById('a').click();
+    });
+
+    expect(newWindow.document.activeElement).not.toBe(newWindow.document.body);
```
Comment (josephsavona) [inline packages/react-dom/src/__tests__/ReactDOMFiber-test.js:1327]: formatting looks it might be off here but lets see what CI says

File: packages/react-dom/src/__tests__/ReactDOMFiber-test.js [hunk 4]
```diff
@@ -1272,4 +1283,48 @@ describe('ReactDOMFiber', () => {
     });
     expect(didCallOnChange).toBe(true);
   });
+
+  it('should restore selection in the correct window', async () => {
+    // creating new JSOM instance to get a second window as window.open is not implemented
```
Comment (josephsavona) [inline packages/react-dom/src/__tests__/ReactDOMFiber-test.js:1288]: nit: JSDOM

File: packages/react-dom/src/__tests__/ReactDOMFiber-test.js (hunk 3 above)
Comment (josephsavona) [reply packages/react-dom/src/__tests__/ReactDOMFiber-test.js:1327]: yup, `yarn run prettier` should do it

File: packages/react-dom/src/__tests__/ReactDOMFiber-test.js (hunk 4 above)
Comment (ling1726) [reply packages/react-dom/src/__tests__/ReactDOMFiber-test.js]: Done in https://github.com/facebook/react/pull/30951/commits/9e79394f2d7c75fe9458f2dcb425bba812bd4a04

File: packages/react-dom/src/__tests__/ReactDOMFiber-test.js (hunk 3 above)
Comment (ling1726) [reply packages/react-dom/src/__tests__/ReactDOMFiber-test.js:1327]: Done in https://github.com/facebook/react/pull/30951/commits/9e79394f2d7c75fe9458f2dcb425bba812bd4a04

**Review by josephsavona — APPROVED** [review]

**Comment by josephsavona** [comment]
Thanks for the PR!
