### PR TITLE
Fix window.event in development (#11687)

### LINKED ISSUE #11687: react-dom: Ability to access window.event in development
Imported from https://github.com/facebook/react/issues/10474#issuecomment-345331144 at request of @gaearon 

**Do you want to request a *feature* or report a *bug*?** Bug

**What is the current behavior?**

In development mode React uses `invokeGuardedCallback` to be able to catch errors without interrupting the normal "break on uncaught exceptions" feature of devtools.

In the current implementation of `invokeGuardedCallback` an event is created and dispatched, which allows for error handling without a `try{ } catch` block.

Unfortunately it has the side effect of overriding `window.event`, and so you are unable to access `window.event` within guarded callbacks when running React in development mode. In production mode it works fine.

We would like to access window.event at Superhuman to be able to detect where DOM focus is from the user's point of view. Usually this is document.activeElement, but in a few cases (like during a blur event, or when clicking between two iframes) the focus will end up in a different place.

This works fine in production, and we currently work around this in development mode by overriding `ReactDOM.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED.ReactDOMEventListener.handleTopLevel` and maintiaining a reference to the event. In production mode we just use window.event.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template for React 16: https://jsfiddle.net/Luktwrdm/, template for React 15: https://jsfiddle.net/hmbg7e9w/).**

in development: https://jsfiddle.net/n782L2qg/, in production: https://jsfiddle.net/kqt2o7pr/. In both cases I would expect the alert to say `window.event.type: click`, but in development it says `window.event.type: react-invokeguardedcallback`

**What is the expected behavior?**

I would like a way to access window.event in development. I'm happy for this to be somewhat obscure, but ideally I would not have to use the secret internals to make this work.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?** Development 0.15 and 0.16 at least. probably before.

### PR DESCRIPTION
**Pull request by ConradIrwin**
Fixes #11687

The code change is relatively simple, but I had to add a fixture to test
this as window.event is not supported by JSDom.

I included a commented-out test copying the pattern of another test in
that file, but I'm not sure how much value that adds so would happily
remove it.

### CODE REVIEW

File: packages/shared/ReactErrorUtils.js [hunk 1]
```diff
@@ -185,6 +190,9 @@ if (__DEV__) {
         // nested call would trigger the fake event handlers of any call higher
         // in the stack.
         fakeNode.removeEventListener(evtType, callCallback, false);
+        if (windowEvent && window.event !== windowEvent) {
+          window.event = windowEvent;
```
Comment (aweary) [inline packages/shared/ReactErrorUtils.js]: Have you verified that the browsers that support `window.event` define it as a writable property?

Comment (ConradIrwin) [reply packages/shared/ReactErrorUtils.js]: I've verified that the fixture works in Chrome, Safari and IE 11. Firefox does not support this. Is there a complete list of browsers I should try and support, or any support for running the tests/fixtures in a large set of real browser environments?

Comment (aweary) [reply packages/shared/ReactErrorUtils.js]: It might be good to test in IE9 and IE10 as well if they support it.

Does this get properly reset after the event dispatch is complete? We need to be sure that `window.event` doesn't start persisting, since it should only be defined while an event is in progress.

Comment (ConradIrwin) [reply packages/shared/ReactErrorUtils.js]: Good call on checking. It does not work in IE 9 or 10 or 11 (I'm not sure how I persuaded myself that it did before), as it fails with "Assignment to read-only properties is not allowed in strict mode".

The event does get reset correctly in Chrome and Safari, and I've added a check for that to the fixture.

There are two other approaches I considered, but neither seem to work:

* Instead of `window.event = `, defining a property on window that returns the correct event. This works to return the correct event object (as far as I can tell), but the event object is unusable in IE 9 or 10 (it does work in IE 11) because any attempt to access the event's properties throws "Member not found".
* Instead of creating a new fake event to dispatch, just re-dispatching window.event. (this fails with an error that "event is already being dispatched")

For now I've updated this pull request to not preserve window.event in IE at all. If it would be preferred, I can make it work in IE 11 using `window.defineProperty` — it still will not work in IE9 or 10, but it can be made to not crash.

File: packages/shared/ReactErrorUtils.js [hunk 2]
```diff
@@ -185,6 +190,9 @@ if (__DEV__) {
         // nested call would trigger the fake event handlers of any call higher
         // in the stack.
         fakeNode.removeEventListener(evtType, callCallback, false);
+        if (windowEvent && window.event !== windowEvent) {
```
Comment (gaearon) [inline packages/shared/ReactErrorUtils.js]: I would prefer a strict check here (e.g. `typeof windowEvent !== 'undefined' || windowEvent !== null`, depending on what actually happens).

File: packages/shared/__tests__/ReactErrorUtils-test.internal.js [hunk 3]
```diff
@@ -55,6 +55,34 @@ describe('ReactErrorUtils', () => {
     expect(context.didCall).toBe(true);
   });
 
+  if (!__DEV__ && window.hasOwnProperty('event')) {
```
Comment (gaearon) [inline packages/shared/__tests__/ReactErrorUtils-test.internal.js]: So is this always `false`? Then this shouldn't be a test at all if it never executes.

You could, however, "polyfill" `window.event` in jsdom yourself somehow.

**Comment by aweary** [comment]
Re: https://github.com/facebook/react/pull/11696#discussion_r153686685

If we can't find a solution that works consistently it may be better for us to document this as a limitation of the synthetic event system. Even though `window.event` has decent browser support, it's non-standard, which is why we have these inconsistencies.

**Comment by gaearon** [comment]
Could you please fix the CI and merge conflicts?

**Comment by ConradIrwin** [comment]
Will do.

**Comment by ConradIrwin** [comment]
done!

**Comment by ibash** [comment]
@gaearon It looks like `setHandleTopLevel` has been removed. Would love to have this PR merged so we can upgrade!

**Comment by ConradIrwin** [comment]
@aweary @gaearon This is blocking our ability to upgrade to React 16.3. Is there any chance of merging this?

File: packages/shared/invokeGuardedCallback.js [hunk 4]
```diff
@@ -106,6 +111,16 @@ if (__DEV__) {
         // nested call would trigger the fake event handlers of any call higher
         // in the stack.
         fakeNode.removeEventListener(evtType, callCallback, false);
+
+        // We check for window.hasOwnProperty('event') to prevent the window.event assignment
+        // in IE as it crashes in strict mode.
+        if (
+          typeof window.event !== 'undefined' &&
+          window.hasOwnProperty('event')
```
Comment (gaearon) [inline packages/shared/invokeGuardedCallback.js]: What's the story behind this?
Why does `window.hasOwnProperty('event')` tell us whether it's *writable*?

Comment (ConradIrwin) [reply packages/shared/invokeGuardedCallback.js]: @gaearon Thanks for looking into this.

It is useful for two reasons, only one of which I added to the comment:

1. Running `window.event = event` on IE <= 10 throws an error `"SCRIPT3: Member Not Found"`. As far as I can tell, this has nothing to do with anything other than "running in IE <= 10". So I needed at least a feature check for these browsers.
2. Firefox does not support `window.event` at all. So I wanted a check for browsers that usually have an event property on window.

By happy coincidence this check does both. I've updated the comment, and rebased over your latest changes.

Please let me know if I can improve this more, as this is currently the main thing holding us back on 16.2.

**Comment by react-linter** [comment]
<details>
  <summary>Details of bundled changes.</summary>

  <p>Comparing: 5550ed4a8f33ff562e807175b8f35a1f9e037670...1a710d343782072fd29069f909044fbd7edf31a9</p>


  
## react-dom
File | Filesize Diff | Gzip Diff | Prev Size | Current Size | Prev Gzip | Current Gzip | ENV
 ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  --- 
react-dom.development.js | +0.1% | +0.1% | 643.46 KB | 644.05 KB | 151.44 KB | 151.6 KB | UMD_DEV
react-dom.development.js | +0.1% | +0.1% | 639.59 KB | 640.19 KB | 150.29 KB | 150.45 KB | NODE_DEV

## react-art
File | Filesize Diff | Gzip Diff | Prev Size | Current Size | Prev Gzip | Current Gzip | ENV
 ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  --- 
react-art.development.js | +0.1% | +0.2% | 434.94 KB | 435.54 KB | 98.73 KB | 98.9 KB | UMD_DEV
react-art.development.js | +0.2% | +0.2% | 367.46 KB | 368.06 KB | 81.67 KB | 81.84 KB | NODE_DEV

## react-test-renderer
File | Filesize Diff | Gzip Diff | Prev Size | Current Size | Prev Gzip | Current Gzip | ENV
 ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  --- 
react-test-renderer.development.js | +0.2% | +0.2% | 363.36 KB | 363.95 KB | 80.07 KB | 80.24 KB | UMD_DEV
react-test-renderer.development.js | +0.2% | +0.2% | 359.49 KB | 360.08 KB | 79.11 KB | 79.28 KB | NODE_DEV

## react-reconciler
File | Filesize Diff | Gzip Diff | Prev Size | Current Size | Prev Gzip | Current Gzip | ENV
 ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  --- 
react-reconciler.development.js | +0.2% | +0.2% | 348.48 KB | 349.07 KB | 75.74 KB | 75.9 KB | NODE_DEV
react-reconciler-persistent.development.js | +0.2% | +0.2% | 347.09 KB | 347.69 KB | 75.18 KB | 75.35 KB | NODE_DEV

## react-native-renderer
File | Filesize Diff | Gzip Diff | Prev Size | Current Size | Prev Gzip | Current Gzip | ENV
 ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  --- 
ReactNativeRenderer-dev.js | +0.1% | +0.2% | 482.65 KB | 483.27 KB | 106.88 KB | 107.05 KB | RN_FB_DEV
ReactNativeRenderer-dev.js | +0.1% | +0.2% | 482.38 KB | 483 KB | 106.83 KB | 107 KB | RN_OSS_DEV
ReactFabric-dev.js | +0.1% | +0.2% | 472.86 KB | 473.48 KB | 104.45 KB | 104.62 KB | RN_FB_DEV
ReactFabric-dev.js | +0.1% | +0.2% | 472.89 KB | 473.52 KB | 104.46 KB | 104.63 KB | RN_OSS_DEV

  </details>
  
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by gaearon** [comment]
Which browsers have you tested this on?

**Comment by ConradIrwin** [comment]
Lastest Chrome, Safari, Firefox, IE 11, 10, 9

**Comment by gaearon** [comment]
Can you please also test iOS Safari and Android?

**Comment by ConradIrwin** [comment]
Also checked on my iPhone's Safari, and a friend's Android Chrome at it works as expected.

**Comment by gaearon** [comment]
Cool. Thanks!

**Comment by ConradIrwin** [comment]
👍 Thank you for all your help!
