### PR TITLE
Fix #6950, work around IE missing innerHTML on SVG nodes

### LINKED ISSUE #6950: Using React 15, under IE, dangerouslySetInnerHTML doesn't work on any SVG tag
Hi,

Since React15, DOM reconciliation produce deep DOM manipulation instead of setting innerHTML of higher level html DOM node. Every DOM mutation is done exactly where it has to be done, either for HTML element or SVG element.
As a side effect, when you use dangerouslySetInnerHTML on any SVG element, React create the SVG element using document.createElementNS then set the innerHTML element of the new element. That's pretty cool on any recent browser, except IE. IE11 doesn't support innerHTML on any SVG tag. There is no script error as assigning an unknown property is always allowed on any Object. But nothing is added in the DOM tree.

for example, this stateless component produce an empty svg on IE:

```
var Icon = ({svg}) => {
  return (
    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" enableBackground="new 0 0 512 512" style={{width: "128px", height: "128px", fill: "red"}}>
      <title>a red icon</title>
      <g dangerouslySetInnerHTML={{__html: svg}}/>
    </svg>
  )
}

var svgPath = '<path d="M207.436,50v98.074h98.136V50H207.436z M364.429,148.074H462V50h-97.571V148.074z M148.578,148.074V50H50v98.074H148.578z M50,206.932h412V462H50V206.932z"/>'

ReactDOM.render(
  <Icon svg={svgPath} />,
  document.body
)
```

[here is a codepen demonstrating this issue](http://codepen.io/lgra/pen/OXPgoQ)

The goal is to add a string containing a literal SVG path (svgPath in the code) into a g tag wrapper inside a svg generic React component.

The first red icon is created using React15.
The second green icon is created using direct DOM manipulation and setting innerHTML on a g tag.
The third blue icon is created using direct DOM manipulation, without using the innerHTML on a g tag.

Avery modern browser is able to display the 3 icons, except Internet Explorer (any version), which is only capable to display the blue one.

The blue one use a hack to not use innerHTML directly on the g tag.
- embed the literal SVG path between svg literal tag
- create a temporary div tag
- set the innerHTML of this div tag
- loop on any div.svg.childNodes and append them to the g tag.

```
var ieDivWrapper = document.createElement("div")
ieDivWrapper.innerHTML = "<svg>" + svgPath + "</svg>"
Array.prototype.forEach.call(ieDivWrapper.firstChild.childNodes, (child) => {
  ieElemG.appendChild(child)
})
```

Here is a way to know if the browser supports or not innerHTML on svg tag:
```
var svg = document.createElementNS("http://www.w3.org/2000/svg", "svg")
var supportInnerHtml = svg.innerHTML !== undefined && !svg.hasOwnProperty("innerHTML")
```

A way to avoid this issue with current React 15 in a statefull component is to embed the hack describe here in the componentDidMount and eventually the componentDidUpdate methods.
Considering the exemple provided here, this statefull version is working:
```
class IconIE extends React.Component {
  static propTypes = {
    svg: React.PropTypes.string.isRequired
  };
  setInnerSvg() {
    var ieDivWrapper = document.createElement("div")
    ieDivWrapper.innerHTML = "<svg>" + this.props.svg + "</svg>"
    Array.prototype.forEach.call(ieDivWrapper.firstChild.childNodes, (child) => {
      this.refs.itemG.appendChild(child)
    })
  }
  componentDidMount() {
    this.setInnerSvg()
  }
  componentDidUpdate(prevProps) {
    if (prevProps.svg !== this.props.svg) {
      this.setInnerSvg()
    }
  }
  render() {
    return (
      <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" enableBackground="new 0 0 512 512" style={{width: "128px", height: "128px", fill: "blue"}}>
        <title>a blue icon</title>
        <g ref="itemG" dangerouslySetInnerHTML={{__html: ""}}/>
      </svg>
    )
  }
}

ReactDOM.render(
  <IconIE svg={svgPath} />,
  document.getElementById('PATCHEDcontainer')
)
```
[and the codepen.io](http://codepen.io/lgra/pen/KMwEMo)

Please notes that it's partially a regression, as dangerouslySetInnerHTML on an svg tag was working before React15 at the initial render (the svgPath string was added to the virtual DOM string, the whole virtual DOM generated by the render method was added to the real DOM using innerHTML of one of the the parents node). It was not working on a props update, except setting a key props on the high level svg tag, forcing react to use innerHTML of its parent (I was doing that without knowing why. Now, I do know).

Regards.

### PR DESCRIPTION
**Pull request by joshhunt**
Fixes #6950, where `dangerouslySetInnerHTML` doesn't work on any SVG tag. I updated `setInnerHTML` to use the method hashed out by @spicyj, and updated DOMLazyTree's use of `node.innerHTML` to use `setInnerHTML` instead.

I was hesitant about updating DOMLazyTree to use the `setInnerHTML` util, but it seemed to make the most sense. If it's not appropriate I'll just make the workaround local to DOMLazyTree.

If this looks good I'll go ahead and add some tests to make sure it continues to work.

> 1. Fork the repo and create your branch from `master`. ✅ 
> 2. If you've added code that should be tested, add tests! ✅
> 3. If you've changed APIs, update the documentation.  
> 4. Ensure the test suite passes (`grunt test`). ✅ 
> 5. Make sure your code lints (`grunt lint`) - we've done our best to make sure these rules match our internal linting guidelines. ✅ 
> 6. If you haven't already, complete the [CLA](https://code.facebook.com/cla). ✅

### CODE REVIEW

**Comment by spicyj** [comment]
This looks generally correct. Can we detect when .innerHTML is missing and only do this workaround in that case? Otherwise I think this is right. It might be hard to cover this with our unit test setup.

**Comment by joshhunt** [comment]
That sounds a lot better, and makes things neater. I only added the `typeof SVGElement` check because SVGElement is actually not present in the testing environment, so at least that should be easier to work with. I'll have a go at adding tests and report back.

File: src/renderers/dom/client/utils/setInnerHTML.js [hunk 1]
```diff
@@ -28,7 +31,19 @@ var createMicrosoftUnsafeLocalFunction = require('createMicrosoftUnsafeLocalFunc
  */
 var setInnerHTML = createMicrosoftUnsafeLocalFunction(
   function(node, html) {
-    node.innerHTML = html;
+    // IE does not have innerHTML for SVG nodes, so instead we inject the
+    // new markup in a temp node and then move the child nodes across into
+    // the target node
+    if (typeof SVGElement !== 'undefined' && node instanceof SVGElement) {
+      reusableSVGContainer = reusableSVGContainer || document.createElement('div');
+      reusableSVGContainer.innerHTML = '<svg>' + html + '</svg>';
```
Comment (syranide) [inline src/renderers/dom/client/utils/setInnerHTML.js]: Am I missing something, why not create the `svg` directly and drop the `div`?

Comment (joshhunt) [inline src/renderers/dom/client/utils/setInnerHTML.js]: IE [does not support innerHTML on SVG Elements](http://stackoverflow.com/a/28130626/2592), so we wrap the markup to make it a 'complete' svg string, pop that into a temp container node, then copy across the children of the `<svg>`.

File: src/renderers/dom/client/utils/setInnerHTML.js [hunk 2]
```diff
@@ -28,7 +31,20 @@ var createMicrosoftUnsafeLocalFunction = require('createMicrosoftUnsafeLocalFunc
  */
 var setInnerHTML = createMicrosoftUnsafeLocalFunction(
   function(node, html) {
-    node.innerHTML = html;
+    if ('innerHTML' in node) {
```
Comment (syranide) [inline src/renderers/dom/client/utils/setInnerHTML.js]: @spicyj Perhaps it makes sense to check for the SVG namespace as well?

Comment (spicyj) [inline src/renderers/dom/client/utils/setInnerHTML.js]: Yeah let's do…

```
if (node.namespaceURI === DOMNamespaces.svg && !('innerHTML' in node)) {
  // workaround
} else {
  node.innerHTML = html;
}
```

Then I think this looks good if you have done manual testing that reproduces the original issue and confirms this fixes it.

File: src/renderers/dom/client/utils/__tests__/setInnerHTML.js [hunk 3]
```diff
@@ -0,0 +1,36 @@
...
+      setInnerHTML(node, html);
+      expect(node.innerHTML).toBe(html);
+    });
+  });
+
+  // SVGElements on IE don't have innerHTML
+  describe('when the node does not innerHTML property', () => {
+    it('sets innerHTML on it', function() {
+      var node = document.createElement('svg');
+      delete node.innerHTML;
```
Comment (spicyj) [inline src/renderers/dom/client/utils/__tests__/setInnerHTML.js]: Do you know if this actually does anything? I'd guess that `.innerHTML` lives on the prototype and so this does nothing.

File: src/renderers/dom/client/utils/setInnerHTML.js (hunk 2 above)
Comment (syranide) [inline src/renderers/dom/client/utils/setInnerHTML.js]: Hmm... is it possible that this could break due to improper namespaces or does HTML enforce the SVG namespace on descendants of an SVG-element? I think not? But perhaps the element does not work correctly either without a proper namespace?

Comment (spicyj) [inline src/renderers/dom/client/utils/setInnerHTML.js]: I don't believe SVG elements work with an incorrect namespace, and the parser should assign it automatically in most cases.

Comment (joshhunt) [inline src/renderers/dom/client/utils/setInnerHTML.js]: what would be the advantage of checking the namespace as opposed to just checking if the node is a `SVGElement `?

Comment (spicyj) [inline src/renderers/dom/client/utils/setInnerHTML.js]: Either would be fine. Namespace works better in jsdom but if you prefer instanceof SVGElement that seems fine too.

File: src/renderers/dom/client/utils/__tests__/setInnerHTML.js (hunk 3 above)
Comment (joshhunt) [inline src/renderers/dom/client/utils/__tests__/setInnerHTML.js]: You're right - I knew it wouldn't work in the browser but was hoping that it would work under the fake JSDOM environment and I meant to confirm, but missed out.

I'm kinda stuck for how to accurately test this then, apart from creating a complete mock node like

```
var node = { appendChild: spy() };
expect(node.appendChild).toHaveBeenCalled();
```

Seems like a bit of a pointless test though if I'm not even passing in a real node.

JSDOM also seems to lack `SVGElement` which makes it slightly harder as well

Comment (spicyj) [inline src/renderers/dom/client/utils/__tests__/setInnerHTML.js]: Yeah, I dunno. Let's go with the fake node and store what appendChild is called with and make sure .outerHTML on that child matches what we expected to add.

**Comment by facebook-github-bot-9** [comment]
@joshhunt updated the pull request.

File: src/renderers/dom/client/utils/__tests__/setInnerHTML.js (hunk 3 above)
Comment (joshhunt) [inline src/renderers/dom/client/utils/__tests__/setInnerHTML.js]: Ended up using defineProperty to 'remove' the getter to make innerHTML undefined, and then assert on node.outerHTML. On second though I guess I could have asserted on node.firstChild.outerHTML, but I think this is is fine.

Comment (spicyj) [inline src/renderers/dom/client/utils/__tests__/setInnerHTML.js]: The check is worse now because it forces innerHTML to be computed just to check if it is undefined. That's too slow.

**Comment by facebook-github-bot-5** [comment]
@joshhunt updated the pull request.

**Comment by facebook-github-bot-5** [comment]
@joshhunt updated the pull request.

**Comment by spicyj** [comment]
Looks great, thank you!

File: src/renderers/dom/client/utils/setInnerHTML.js [hunk 4]
```diff
@@ -28,7 +32,19 @@ var createMicrosoftUnsafeLocalFunction = require('createMicrosoftUnsafeLocalFunc
...
+    // IE does not have innerHTML for SVG nodes, so instead we inject the
+    // new markup in a temp node and then move the child nodes across into
+    // the target node
+    if (node.namespaceURI === DOMNamespaces.svg && !('innerHTML' in node)) {
+      reusableSVGContainer = reusableSVGContainer || document.createElement('div');
+      reusableSVGContainer.innerHTML = '<svg>' + html + '</svg>';
+      var newNodes = reusableSVGContainer.firstChild.childNodes;
+      for (var i = 0; i < newNodes.length; i++) {
+        node.appendChild(newNodes[i]);
+      }
```
Comment (zpao) [inline src/renderers/dom/client/utils/setInnerHTML.js]: As @jp7837 pointed out in https://github.com/facebook/react/issues/7358#issuecomment-243289105 - this is going to get every other child - childNodes is a live NodeList. This should be a while loop. I can confirm this is what is happening in IE11.
