### PR TITLE
[DevTools] Avoid Stringifying Objects during Strict Mode Double Logging

### LINKED ISSUE #24302: Console dimming on second StrictMode render forces string cast
React version: 18.0.0 (congrats on the release ☺️)

## Steps To Reproduce

1. During rendering of a component, log something that doesn't naturally cast to a string (e.g., `console.log(new Set())`).
2. Wrap the tree in `StrictMode`.
3. Observe the console.

Link to code example: https://codesandbox.io/s/magical-roman-wyeud7?file=/src/App.js

Note that the console dimming isn't applied to the inline CodeSandbox dev tools, so to see the issue, you need to visit the "fullscreen view" here: https://wyeud7.csb.app

## The current behavior

In Chrome:

Screen Shot 2022-04-07 at 4 19 09 PM

As expected, there are two console logs, one dimmed. Unfortunately, the way that the dimming works forces the second log to be serialized to a string. This has two issues:
1. It can result in two of the "same" logs looking very "different" from each other, which is confusing to developers. For example, in the screenshot above, it's pretty surprising that those two console lines occur from the same `console.log` call.
2. It prevents browser dev tools introspection. This can make it inconvenient or impossible to compare the two values if the string cast doesn't include the value, as in the screenshot above. This is problematic because a key use case of printing both values is to check whether they're the same.

You can kind of work around the second issue by writing your own string cast at the log callsite, but you lose the DX of introspection, which is pretty unfortunate especially in the case of large/deeply-nested objects, etc. Easier to compare two native console values than two `JSON.stringify` dumps.

## The expected behavior

While there is a new (appreciated!) dev tools option to suppress logging for the second render entirely, there is no way to disable the dimming feature.

Any of the following options would solve the issue:
1. Provide a dev tools option to disable dimming.
2. Remove the dimming feature entirely. (So that both logs are always printed the same way.)
3. Update the dimming implementation so that it doesn't force a string cast. (Guessing this isn't possible.)
4. Improve serialization of complex values. (IMO this isn't a great option because it doesn't solve the issue of consistency/confusion, but it would be better than the current behavior if all other options are ruled out.)

Thanks for considering.

### PR DESCRIPTION
**Pull request by lunaruan**
Fixes #24302 based on #24306.
---

The current implementation for strict mode double logging stringiness and dims the second log. However, because we stringify everything, including objects, this causes objects to be logged as `[object Object]` etc.

This PR creates a new function that formats console log arguments with a specified style. It does this by:
1. The first param is a string that contains %c: Bail out and return the args without modifying the styles. We don't want to affect styles that the developer deliberately set.
2. The first param is a string that doesn't contain %c but contains string formatting: `[`%c${args[0]}`, style, ...args.slice(1)]` Note: we assume that the string formatting that the developer uses is correct.
3. The first param is a string that doesn't contain string formatting OR is not a string: Create a formatting string where:
   -  boolean, string, symbol -> %s
   -  number -> %f OR %i depending on if it's an int or float
   -  default -> %o
---
Co-authored-by: Billy Janitsch <billy@kensho.com>

### CODE REVIEW

File: packages/react-devtools-shared/src/backend/utils.js [hunk 1]
```diff
@@ -156,6 +156,60 @@ export function serializeToString(data: any): string {
...
+//                 default -> %o
+export function formatWithStyles(
+  inputArgs: $ReadOnlyArray<any>,
+  style?: string,
+): $ReadOnlyArray<any> {
+  if (
+    inputArgs === undefined ||
+    inputArgs === null ||
+    inputArgs.length === 0 ||
+    (typeof inputArgs[0] === 'string' && inputArgs[0].includes('%c')) ||
```
Comment (billyjanitsch) [inline packages/react-devtools-shared/src/backend/utils.js:183]: Might want to check that the matching string isn't `%%c` (`%%` is an escaped `%`).

**Review by billyjanitsch — COMMENTED** [review]
Thanks @lunaruan for fixing this up. ☺️

File: packages/react-devtools-shared/src/backend/utils.js (hunk 1 above)
Comment (lunaruan) [reply packages/react-devtools-shared/src/backend/utils.js:183]: Ah good call! Thanks!

File: packages/react-devtools-shared/src/__tests__/utils-test.js [hunk 2]
```diff
@@ -110,4 +113,81 @@ describe('utils', () => {
...
+      ]);
+      expect(formatWithStyles(['%%c'], 'color: gray')).toEqual([
+        '%c%s',
+        'color: gray',
+        '%%c',
+      ]);
+      expect(formatWithStyles(['%%c%c'], 'color: gray')).toEqual(['%%c%c']);
+    });
+  });
 });
```
Comment (bvaughn) [inline packages/react-devtools-shared/src/__tests__/utils-test.js:193]: I'm sure you're aware of this, but it looks like this change broke some pre-existing tests in CI:
https://app.circleci.com/pipelines/github/facebook/react/26207/workflows/06a6279f-0816-4dfc-81c5-b2f9228474c1/jobs/471951

**Review by bvaughn — APPROVED** [review]

File: packages/react-devtools-shared/src/backend/utils.js [hunk 3]
```diff
@@ -156,6 +156,62 @@ export function serializeToString(data: any): string {
...
+    inputArgs.length === 0 ||
+    // Matches any of %c but not %%c
+    (typeof inputArgs[0] === 'string' && inputArgs[0].match(/([^%]|^)(%c)/g)) ||
+    style === undefined
+  ) {
+    return inputArgs;
+  }
+
+  // Matches any of %(o|O|i|s|f), but not %%(o|O|i|s|f)
+  const REGEXP = /([^%]|^)(%([oOdisf]))/g;
```
Comment (sophiebits) [inline packages/react-devtools-shared/src/backend/utils.js:191]: I’m not sure checking for %% this way is quite what you want – eg `%%%s` is an escaped `%` followed by a string value.

Comment (lunaruan) [reply packages/react-devtools-shared/src/backend/utils.js:191]: Ooh good call

Comment (devildp333) [reply packages/react-devtools-shared/src/backend/utils.js:191]: ...
