### PR TITLE
Do not fail `yarn linc` for ignored file warning (#11615)

### LINKED ISSUE #11615: yarn linc shouldn't fail because of file-has-not-changed warning
Just saw this after modifying ESLint config and running `yarn linc`:

```
/Users/gaearon/p/react/.eslintrc.js
  0:0  warning  File ignored by default.  Use a negated ignore pattern (like "--ignore-pattern '!<relative/path/to/filename>'") to override

✖ 1 problem (0 errors, 1 warning)

Lint failed for changed files.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
react)            
```

We should not treat this particular warning as an error.

### PR DESCRIPTION
**Pull request by HeroProtagonist**
Resolves #11615

**Problem**
This error happens because by default eslint ignores [dotfiles](https://github.com/eslint/eslint/blob/master/lib/cli-engine.js#L246). The `yarn linc` command can supply dotfiles like `.eslintrc.js` causing this error because of the mismatch between the ignore patterns and what is being given as lint input. [This](https://github.com/eslint/eslint/issues/4828) eslint thread talks about this issue with this [PR](https://github.com/eslint/eslint/pull/6844) resolving it.

**Solution**
Hidden files will now be linted, but not hidden folders. As of now the only hidden `.js` file seems to be the `.eslintrc.js`, but this will prevent this from happening if any are added in the future. As a bonus the `rc` file will be linted going forward.

Happy Thanksgiving! 🦃

### CODE REVIEW

**Comment by gaearon** [comment]
>The yarn linc command can supply dotfiles like .eslintrc.js causing this error because of the mismatch between the ignore patterns and what is being given as lint input.

Hmm. What if the changed files are in an ESLint-ignored folder? I guess in that case we'd still see this issue, wouldn't we?

I think the right fix for this would have been to disable this particular rule. At least when running on changed files.

**Comment by gaearon** [comment]
Or maybe we should still exit with the zero code if the only failing rule is this one? I think printing this information is still useful.

Assuming my analysis in https://github.com/facebook/react/pull/11641#issuecomment-346914182 is right. If it's not let me know!

**Comment by HeroProtagonist** [comment]
>What if the changed files are in an ESLint-ignored folder? I guess in that case we'd still see this issue, wouldn't we?

It would display [this](https://github.com/eslint/eslint/blob/master/lib/cli-engine.js#L246) very similar issue `"File ignored because of a matching ignore pattern. Use \"--no-ignore\" to override."` I tested this by making some changes in `scripts/bench/benchmarks` directory.

> I think the right fix for this would have been to disable this particular rule.

From my looking into eslint, it seems this cannot be disabled because it is not so much a rule as it is eslint being told one thing and then supplied another.

> Or maybe we should still exit with the zero code if the only failing rule is this one?

This is what the code now reflects. I made a function that will validate the warnings from the eslint report. If all the warnings contain the `File ignored` text the warnings will be displayed as before, but the lint will now pass.

**Comment by gaearon** [comment]
Sorry--do you mind rebasing on top of master? Thanks!

**Comment by HeroProtagonist** [comment]
Done!

File: scripts/eslint/index.js [hunk 1]
```diff
@@ -11,9 +11,22 @@ const CLIEngine = require('eslint').CLIEngine;
...
 
-module.exports = function lintOnFiles(filePatterns) {
+function lintOnFiles(filePatterns) {
   const report = cli.executeOnFiles(filePatterns);
   const formattedResults = formatter(report.results);
   console.log(formattedResults);
   return report;
+}
+
+function validWarnings(report) {
```
Comment (gaearon) [inline scripts/eslint/index.js]: Let's move this to where it's used?
Also let's rename to something like `getSourceCodeWarnings`.

In fact I would just inline this logic in the script that uses it, and add a comment explaining why it exists.

Comment (HeroProtagonist) [reply scripts/eslint/index.js]: Changes reflect this. Do you prefer to have function declaration vs definition?

**Comment by gaearon** [comment]
Thanks!
