### PR TITLE
Fixes #9667: Updated createTextInstance to create the text node on correct document

### LINKED ISSUE #9667: Cant't mount text node components
Cant't mount text node components in a child window in **IE11** and **Edge**.

http://jsfiddle.net/69z2wepo/78456/

```jsx
const SomeComponent = () => (
  <div>
    <span>This will be displayed</span>
    <br/>
    This will not be displayed (This is the text node that will break the mounting)
    <br/>
    <span>This will not be displayed because the mounting has stopped</span>
  </div>
);

class PopoutWindow extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      openedWindow: null
    };
  }

  componentDidMount() {
    var win,
        container,
        openedWindow = {};

    var onLoadHandler = () => {
      container = win.document.createElement('div');
      container.id = 'test';
      win.document.body.appendChild(container);
      ReactDOM.render(this.props.children, container);
      openedWindow.update = newComponent => {
        ReactDOM.render(newComponent, container);
      };
      this.setState({openedWindow: openedWindow});
    };

    win = window.open('about:blank', 'Test', 'width: 600px; height: 600px'); 

    win.onload = onLoadHandler;

    // call onload handler in case it's not been called
    setTimeout(onLoadHandler, 0);
  }

  componentDidUpdate() {
    this.state.openedWindow.update(this.props.children);
  }

  render() {
    return <div />;
  }
}

ReactDOM.render((
  <PopoutWindow title="Test">
    <SomeComponent />
  </PopoutWindow>
), container);
```

It throws the following error: `SCRIPT87: Invalid argument.`

Debugging the stack trace I've noticed that the fragment creation (`ownerDocument.createDocumentFragment()`, line 7923, `react-dom.js`) is resulting in a malformed fragment. Later, when trying to append this "malformed" fragment to the DOM (`parentNode.insertBefore(tree.node, referenceNode)`, line 1623, `react-dom.js`), it fails and throws that error.

I tried to replace the fragment by a span element for this specific case (IE11 and child window) and it worked. Could this be a solution?

### PR DESCRIPTION
**Pull request by kenotron**
Second try: this time update the Fiber reconciler to create the text node on the correct ownerDocument so that when it is being appendChild()'ed / insertBefore()'ed, it will succeed on IE / Edge.

### CODE REVIEW

**Comment by kenotron** [comment]
@gaearon Alright, second try! I think this fixes up the issue on Edge / IE...

**Comment by kenotron** [comment]
Related to  #9667

File: src/renderers/dom/fiber/__tests__/ReactDOMFiber-test.js [hunk 1]
```diff
@@ -16,6 +16,7 @@ var ReactDOM = require('react-dom');
 var ReactDOMFeatureFlags = require('ReactDOMFeatureFlags');
 var ReactTestUtils = require('react-dom/test-utils');
 var PropTypes = require('prop-types');
+var JSDom = require('jsdom');
```
Comment (kenotron) [inline src/renderers/dom/fiber/__tests__/ReactDOMFiber-test.js]: jsdom is needed here to create a brand new document because by default jest-jsdom assumes every test is on the same document.

File: src/renderers/dom/fiber/__tests__/ReactDOMFiber-test.js [hunk 2]
```diff
@@ -1117,5 +1118,22 @@ describe('ReactDOMFiber', () => {
           'to empty a container.',
       );
     });
+
+    it('should render a text component with a text DOM node on the same document as the container', () => {
```
Comment (kenotron) [inline src/renderers/dom/fiber/__tests__/ReactDOMFiber-test.js]: I've verified that this test case fails in the current master.

**Comment by kenotron** [comment]
@gaearon all green!

File: src/renderers/dom/fiber/ReactDOMFiberEntry.js [hunk 3]
```diff
@@ -368,7 +368,13 @@ var DOMRenderer = ReactFiberReconciler({
       const hostContextDev = ((hostContext: any): HostContextDev);
       validateDOMNesting(null, text, null, hostContextDev.ancestorInfo);
     }
-    var textNode: TextInstance = document.createTextNode(text);
+
+    var doc = rootContainerInstance;
+    if (rootContainerInstance.nodeType !== DOCUMENT_NODE && doc.ownerDocument) {
```
Comment (syranide) [inline src/renderers/dom/fiber/ReactDOMFiberEntry.js]: Can `rootContainerInstance` even be `DOCUMENT_NODE`?

Comment (syranide) [inline src/renderers/dom/fiber/ReactDOMFiberEntry.js]: Why test for `doc.ownerDocument`? I don't know why it would ever be falsy and if it is then your could would break, because you would be trying to call `createTextNode` on some random element.

Comment (syranide) [inline src/renderers/dom/fiber/ReactDOMFiberEntry.js]: PS. `rootContainerInstance` should changed to `doc` for consistency.

Comment (syranide) [inline src/renderers/dom/fiber/ReactDOMFiberEntry.js]: Also, is it really guaranteed that `rootContainerInstance` belongs to the same document? I would think that rendering an iframe and into it would break this assumption... or has this changed?

Comment (kenotron) [reply src/renderers/dom/fiber/ReactDOMFiberEntry.js]: line 101: type Container = Element | Document; 

I think so.

Comment (kenotron) [reply src/renderers/dom/fiber/ReactDOMFiberEntry.js]: We don't have to, I guess from the same flow typing info, it can only be an Element (which HAS ownerDocument) or it's a Document which is the document itself.

Comment (kenotron) [reply src/renderers/dom/fiber/ReactDOMFiberEntry.js]: That's a good call out, but I'm actually removing that ownerDocument and changing the name for short.

Comment (kenotron) [reply src/renderers/dom/fiber/ReactDOMFiberEntry.js]: From the way it WAS written before, Fiber would have broken the iframe case. If you looked at the ReactDOMFiberComponent's `createElement()`, you'd see that the semantics there for retrieving "ownerDocument" is the same as what I have written here:

```js
 var ownerDocument: Document = rootContainerElement.nodeType ===
      DOCUMENT_NODE
      ? (rootContainerElement: any)
      : rootContainerElement.ownerDocument;
```
I'm going to reuse this bit of code for clarity inside fiberentry

**Comment by gaearon** [comment]
@kenotron Is there a way to rewrite the test to not use jsdom APIs directly? Maybe there’s some cases with an iframe that would reproduce it?

**Comment by acdlite** [comment]
Conflicts are fine, I've already accepted I'll have to rebase/rewrite a lot of my work it before it lands :D

**Comment by kenotron** [comment]
@gaearon I honestly don't know how to create a brand new document without doing manual jsdom monkeying. Maybe a feature request for jest itself :)

**Comment by sophiebits** [comment]
I think you can copy what src/renderers/dom/shared/eventPlugins/__tests__/EnterLeaveEventPlugin-test.js does.

**Comment by kenotron** [comment]
@sophiebits I've tried this route:

```js
it('should render a text component with a text DOM node on the same document as the container', () => {
      // Arrange
      var textContent = ' world ';

      var iframe = document.createElement('iframe');
      document.body.appendChild(iframe);

      var iframeDocument = iframe.contentDocument;

      iframeDocument.write(
        '<!DOCTYPE html><html><head></head><body><div></div></body></html>',
      );
      iframeDocument.close();

      // Act
      ReactDOM.render(
        <div><span id="pre">hello</span>{textContent}<span>again</span></div>,
        iframeDocument.body.getElementsByTagName('div')[0]
      );

      // Assert
      var textNode = iframeDocument.getElementById('pre').nextSibling;

      expect(textNode.textContent).toBe(textContent);
      expect(textNode.ownerDocument).toBe(iframeDocument);
      expect(textNode.ownerDocument).not.toBe(document);
    });
```

But I noticed that when I ran this test, it **didn't** fail for react master. It can only mean that jsdom is doing the "right thing" like many all non-MS browsers (sigh!!). So, to simulate the effect of actually unrelated documents not able to appendNode() / insertBefore() from another (related) document, I had to drop down to the level of jsdom directly creating an unrelated document.

**Comment by sophiebits** [comment]
Can you do ReactDOM.render(text, container) and mock out `container.appendChild` and assert on its argument's .ownerDocument?

**Comment by gaearon** [comment]
Thanks for the updated test. Do you mind also addressing this comment from @sophiebits?

>Can we make a helper function ReactDOMFiberComponent.createTextNode like how createElement works? I think the parallel structure would be clearer.

File: src/renderers/dom/fiber/__tests__/ReactDOMFiber-test.js [hunk 4]
```diff
@@ -1117,5 +1117,38 @@ describe('ReactDOMFiber', () => {
...
+      var actualDocument;
+      var textNode;
+      iframeContainer.appendChildBackup = iframeContainer.appendChild;
+
+      spyOn(iframeContainer, 'appendChild').and.callFake(node => {
+        actualDocument = node.ownerDocument;
+        textNode = node;
+      });
+
+      // Act
```
Comment (gaearon) [inline src/renderers/dom/fiber/__tests__/ReactDOMFiber-test.js]: Nit: we can remove Arrange/Act/Assert comments as we don't use them in other tests.

Comment (kenotron) [reply src/renderers/dom/fiber/__tests__/ReactDOMFiber-test.js]: done :)

Comment (kenotron) [reply src/renderers/dom/fiber/__tests__/ReactDOMFiber-test.js]: I've also addressed the parallel structure comment from @sophiebits. Since now we have repeated code to do that same thing, I've also factored that out into a function.

File: src/renderers/dom/fiber/ReactDOMFiberComponent.js [hunk 5]
```diff
@@ -296,10 +304,9 @@ var ReactDOMFiberComponent = {
   ): Element {
     // We create tags in the namespace of their parent container, except HTML
     // tags get no namespace.
-    var ownerDocument: Document = rootContainerElement.nodeType ===
-      DOCUMENT_NODE
-      ? (rootContainerElement: any)
-      : rootContainerElement.ownerDocument;
+    var ownerDocument: Document = getOwnerDocumentFromRootContainer(
```
Comment (sophiebits) [inline src/renderers/dom/fiber/ReactDOMFiberComponent.js]: Can you put the annotation on the function getOwnerDocumentFromRootContainer's definition? It's necessary to "cancel out" the `: any` cast.

File: src/renderers/dom/fiber/__tests__/ReactDOMFiber-test.js [hunk 6]
```diff
@@ -1117,5 +1117,35 @@ describe('ReactDOMFiber', () => {
...
+      var iframeDocument = iframe.contentDocument;
+      iframeDocument.write(
+        '<!DOCTYPE html><html><head></head><body><div></div></body></html>',
+      );
+      iframeDocument.close();
+      var iframeContainer = iframeDocument.body.firstChild;
+
+      var actualDocument;
+      var textNode;
+      iframeContainer.appendChildBackup = iframeContainer.appendChild;
```
Comment (sophiebits) [inline src/renderers/dom/fiber/__tests__/ReactDOMFiber-test.js]: nit: remove

File: src/renderers/dom/fiber/__tests__/ReactDOMFiber-test.js [hunk 7]
```diff
@@ -1117,5 +1117,35 @@ describe('ReactDOMFiber', () => {
...
+
+      spyOn(iframeContainer, 'appendChild').and.callFake(node => {
+        actualDocument = node.ownerDocument;
+        textNode = node;
+      });
+
+      ReactDOM.render(textContent, iframeContainer);
+
+      expect(textNode.textContent).toBe(textContent);
```
Comment (sophiebits) [inline src/renderers/dom/fiber/__tests__/ReactDOMFiber-test.js]: Can we add an assertion on the number of calls for iframeContainer.appendChild here?

Comment (kenotron) [reply src/renderers/dom/fiber/__tests__/ReactDOMFiber-test.js]: would you like to see anything else in the test?

File: src/renderers/dom/fiber/ReactDOMFiberComponent.js (hunk 5 above)
Comment (kenotron) [reply src/renderers/dom/fiber/ReactDOMFiberComponent.js]: would I still need this `Document` type? I think flow should be able to infer, right?

File: src/renderers/dom/fiber/__tests__/ReactDOMFiber-test.js (hunk 6 above)
Comment (kenotron) [reply src/renderers/dom/fiber/__tests__/ReactDOMFiber-test.js]: good catch - goober from a previous attempt at it.

File: src/renderers/dom/fiber/__tests__/ReactDOMFiber-test.js (hunk 7 above)
Comment (kenotron) [reply src/renderers/dom/fiber/__tests__/ReactDOMFiber-test.js]: @sophiebits ping?

File: src/renderers/dom/fiber/ReactDOMFiberComponent.js (hunk 5 above)
Comment (sophiebits) [reply src/renderers/dom/fiber/ReactDOMFiberComponent.js]: Right, we don't need this one any more.

**Comment by sophiebits** [comment]
Thanks!

**Comment by kenotron** [comment]
YAY!
