### PR TITLE
Fixed a batched-state update bug with getDerivedStateFromProps

### LINKED ISSUE #12047: Write blog post about new async UNSAFE_ and static lifecycles
Follow up item for PR #12028

This blog post should correspond with the 16.3 release. Its primary purpose is to let people know how to prepare for subsequent 16.4 release.

For **application developers**, this post should explain how to run the codemod to rename the deprecated methods (reactjs/react-codemod/pull/195) as well as general strategies for how to use the new lifecycle(s) instead.

For **library maintainers**, this should provide recommended update and release strategies including:
* What kinds of code can be moved into `render` (to remain backwards compatible) vs what needs to either remain in `UNSAFE_componentWillReceiveProps` or moved to the new `static getDerivedStateFromProps` method.
* When peer dependency version changes are required.
* What versions of React will support the new `UNSAFE_` methods.

### PR DESCRIPTION
**Pull request by bvaughn**
Addresses a batched state update bug reported in #12047.

### CODE REVIEW

**Comment by bvaughn** [comment]
Once this PR is approved and merged- (assuming it is)- I'll cut another alpha release with it and the recent context infinite loop bugfix (#12402).

File: packages/react-reconciler/src/ReactFiberClassComponent.js [hunk 1]
```diff
@@ -908,27 +900,38 @@ export default function(
...
-          ? derivedStateFromProps
-          : Object.assign({}, newState, derivedStateFromProps);
+          ? derivedStateFromCatch
+          : Object.assign({}, newState, derivedStateFromCatch);
     }
-    if (derivedStateFromCatch !== null && derivedStateFromCatch !== undefined) {
+
+    let derivedStateFromProps;
+    if (oldProps !== newProps) {
+      // In this case, the prevState parameter should be the partially updated state,
```
Comment (acdlite) [inline packages/react-reconciler/src/ReactFiberClassComponent.js]: Conceptually, what you're calling `prevState` is the work-in-progress state. So your comment here applies to all cases; it's not special.

File: packages/react-reconciler/src/ReactFiberClassComponent.js [hunk 2]
```diff
@@ -867,19 +867,11 @@ export default function(
       }
     }
 
-    let derivedStateFromProps;
```
Comment (acdlite) [inline packages/react-reconciler/src/ReactFiberClassComponent.js]: Why did you change the order of `getDerivedStateFromCatch` and `getDerivedStateFromProps`? The new order seems correct, just curious what led you to make the change in this diff.

It looks like the order in the "resume mount" path is different now, though. Should be consistent regardless.

File: packages/react-reconciler/src/ReactFiberClassComponent.js (hunk 1 above)
Comment (bvaughn) [reply packages/react-reconciler/src/ReactFiberClassComponent.js]: "in this case" just referred to the _update_ case. The other two invocations of this method are _mounting_ cases. But I'll re-word the comment.

File: packages/react-dom/src/__tests__/ReactComponentLifeCycle-test.js [hunk 3]
```diff
@@ -830,4 +830,49 @@ describe('ReactComponentLifeCycle', () => {
...
+      handleChange = value => {
+        this.setState({value});
+      };
+      render() {
+        return <Child remote={this.state.value} onChange={this.handleChange} />;
+      }
+    }
+
+    const instance = ReactTestUtils.renderIntoDocument(<Parent />);
+    const element = ReactDOM.findDOMNode(instance);
```
Comment (acdlite) [inline packages/react-dom/src/__tests__/ReactComponentLifeCycle-test.js]: Nit: let's not use `findDOMNode`. Maybe a ref instead? I know it's just a test, but we should still try to avoid using legacy APIs :D

File: packages/react-reconciler/src/ReactFiberClassComponent.js (hunk 2 above)
Comment (bvaughn) [reply packages/react-reconciler/src/ReactFiberClassComponent.js]: > Why did you change the order of `getDerivedStateFromCatch` and `getDerivedStateFromProps`?

This was incidental. I changed the order of `processUpdateQueue` and `getDerivedStateFromProps`. I did that because it seemed easier to get the correct partial state value that way than trying to mess with the update queue and it's memoized vs base state.

> It looks like the order in the "resume mount" path is different now, though. Should be consistent regardless.

Fair 👍

**Comment by bvaughn** [comment]
Back to you @acdlite 😄

File: packages/react-reconciler/src/ReactFiberClassComponent.js (hunk 2 above)
Comment (acdlite) [reply packages/react-reconciler/src/ReactFiberClassComponent.js]: One more thing: can you add a test so the order doesn't incidentally change in the future?

**Comment by bvaughn** [comment]
Chatted in meat space. Merging!
