### PR TITLE
Validate built bundles exists

### LINKED ISSUE #11443: Ensure linted bundles exist
I added validation of built bundles in https://github.com/facebook/react/pull/11432.

However I actually messed it up, and ESLint wasn't running on any files because of invalid arguments. I fixed that here: https://github.com/facebook/react/commit/61d35ce1f3f9c0706ed3630a2650d578497ae8c2#diff-edcddc0e0143d5a5a93d0951fd599794

We should fail the build if the glob patterns it's searching for don't exist.

### PR DESCRIPTION
**Pull request by misoguy**
Fix #11443

### CODE REVIEW

**Comment by gaearon** [comment]
This is great. Thanks.

File: scripts/rollup/validate/index.js [hunk 1]
```diff
@@ -36,7 +37,43 @@ function run(format, filePatterns) {
...
+  filePatterns.map(pattern => {
+    console.log(`Check if files exist in ${pattern}`);
+    const files = glob.sync(pattern);
+    if (files.length === 0) {
+      console.error(
+        chalk.red(
+          `No files found in glob pattern ${pattern} in ${format} bundle.`
+        )
+      );
+      process.exit();
```
Comment (gaearon) [inline scripts/rollup/validate/index.js]: Note this doesn't actually fail the build. Should be `process.exit(1)` instead.
I fixed in https://github.com/facebook/react/commit/646781b0b4f95d90cf08b7799bbd196e16136f06.

Comment (misoguy) [reply scripts/rollup/validate/index.js]: Thank you for the review! Well noted 😄
