### PR TITLE
[compiler] Validate against component/hook factories

### LINKED ISSUE #33978: [Compiler Bug]: Component defined inside function cause incorrect optimization
### What kind of issue is this?

- [x] React Compiler core (the JS output is incorrect, or your app works incorrectly after optimization)
- [ ] babel-plugin-react-compiler (build issue installing or using the Babel plugin)
- [ ] eslint-plugin-react-compiler (build issue installing or using the eslint plugin)
- [ ] react-compiler-healthcheck (build issue installing or using the healthcheck script)

### Link to repro

https://playground.react.dev/#N4Igzg9grgTgxgUxALhASwLYAcIwC4AEASggIZyEBmMEGBA5DGRfQNwA6AdlwgB474ClKJwpoInAgHMEeAJKcsUPAApSASgLAuBAnAlhCAdRiksWBDAIBeAis3WAfFp269BwgAtSnACYAbBABhb04ZGzsHZ21JN11SADoJEJ8Zew5Y3QBfDK5XXSY8WEkVfLcAHjRFZTK45NCZa2BQgOCGhCzagkcu8oB6KqU8HsyCdQzs3NjC4oITMwsYLk7OECygA

### Repro steps

Source code:
```
import React from 'react';

export function getInput(a) {
  const Wrapper = () => {
    const handleChange = () => {
      a.onChange();
    };


    return (
      <input
        onChange={handleChange}
      >
      </input>
    );
  };

  return Wrapper
}

```

After React Compiler, the `handleChange` function was hoisted with function level variables(here is the argument `a`, but it can be any variables defined inside `getInput`)
```
import { c as _c } from "react/compiler-runtime";
import React from "react";

export function getInput(a) {
  const Wrapper = () => {
    const $ = _c(1);
    const handleChange = _temp;
    let t0;
    if ($[0] === Symbol.for("react.memo_cache_sentinel")) {
      t0 = <input onChange={handleChange} />;
      $[0] = t0;
    } else {
      t0 = $[0];
    }
    return t0;
  };

  return Wrapper;
}
function _temp() {
  a.onChange(); // a is not defined in this scope
}

```

### How often does this bug happen?

Every time

### What version of React are you using?

React 18

### What version of React Compiler are you using?

19.1.0-rc.2

### PR DESCRIPTION
**Pull request by poteto**
Previously, the compiler would incorrectly attempt to compile nested components/hooks defined inside non-React functions. This would lead to scope reference errors at runtime because the compiler would optimize the nested React function without understanding its closure over the parent function's variables.

This PR adds detection when non-React functions declare components or hooks, and reports a clear error before compilation. I put this under a new compiler flag defaulting to false. I'll run a test on this internally first, but I expect we should be able to just turn it on in both compiler (so we stop miscompiling) and linter.

Closes #33978

Playground example: https://react-compiler-playground-git-pr34305-fbopensource.vercel.app/#N4Igzg9grgTgxgUxALhAejQAgAIDcCGANgJYAm+ALggHIQAiAngHb4C2xcRhDAwjApQSkeEVgAcITBEwpgA8jAASECAGswAHSkAPCTAqYAZlCZwKxSZgDmCCgEkmYqBQAU+AJSZgWzJjiSwAwB1GHwxMQQYTABeTBdPaIA+Lx9fPwCDAAt8JlJCBB5sphsYuITk7yY0tPwAOklCnJt4gG5U3wBfNqZ2zH4KWCqAHmJHZ0wGopto4CK8gqmEDsw0RO7O7tT+wcwQsIiYbo6QDqA

### CODE REVIEW

File: compiler/packages/babel-plugin-react-compiler/src/Entrypoint/Program.ts [hunk 1]
```diff
@@ -494,8 +494,27 @@ function findFunctionsToCompile(
...
+      if (fnType === null || fnType === 'Other') {
+        validateNoNestedComponentsOrHookFactories(fn, pass, programContext);
+      }
+    }
+
+    if (fnType === null) {
+      return;
+    }
+
+    if (programContext.alreadyCompiled.has(fn.node)) {
```
Comment (jorge-cab) [inline compiler/packages/babel-plugin-react-compiler/src/Entrypoint/Program.ts]: How does `alreadyCompiled` works? I'm guessing it keep a cache of all compiled functions to avoid repeating work?

File: compiler/packages/babel-plugin-react-compiler/src/Entrypoint/Program.ts [hunk 2]
```diff
@@ -494,8 +494,27 @@ function findFunctionsToCompile(
 ): Array<CompileSource> {
   const queue: Array<CompileSource> = [];
   const traverseFunction = (fn: BabelFn, pass: CompilerPass): void => {
+    // In 'all' mode, compile only top level functions
+    if (
+      pass.opts.compilationMode === 'all' &&
+      fn.scope.getProgramParent() !== fn.scope.parent
```
Comment (jorge-cab) [inline compiler/packages/babel-plugin-react-compiler/src/Entrypoint/Program.ts:500]: What would `fn.scope.getProgramParent === fn.scope.parent` mean vs. what you wrote in this line?

File: compiler/packages/babel-plugin-react-compiler/src/Entrypoint/Program.ts [hunk 3]
```diff
@@ -494,8 +494,27 @@ function findFunctionsToCompile(
...
+    ) {
+      return;
+    }
+
     const fnType = getReactFunctionType(fn, pass);
-    if (fnType === null || programContext.alreadyCompiled.has(fn.node)) {
+
+    if (pass.opts.environment?.validateNoComponentOrHookFactories) {
+      if (fnType === null || fnType === 'Other') {
```
Comment (jorge-cab) [inline compiler/packages/babel-plugin-react-compiler/src/Entrypoint/Program.ts]: This makes it so we don't try to validate top level React Components/Hooks right?

File: compiler/packages/babel-plugin-react-compiler/src/Entrypoint/Program.ts [hunk 4]
```diff
@@ -839,6 +858,67 @@ function shouldSkipCompilation(
...
+          `or ensure the parent function follows React naming conventions (PascalCase for components, ` +
+          `"use" prefix for hooks)`,
+        loc: nestedFn.node.loc ?? null,
+      });
+    }
+
+    nestedFn.skip();
+  };
+
+  fn.traverse({
```
Comment (jorge-cab) [inline compiler/packages/babel-plugin-react-compiler/src/Entrypoint/Program.ts:915]: If I understand correctly `fn: BabelFn` is an AST node here and you just traverse recursively to check if you have an `n` deep React Component/Hook and parentName is always the direct parent of the nested function, is this accurate?

**Comment by poteto** [comment]
> A more general question. When does `Program.ts` run? does it run in-between compiler passes?

It runs right at the start of compilation, before we lower the AST into HIR, and after we parse the compiler options. The babel plugin calls [`Program:compileProgram`](https://github.com/facebook/react/blob/488a54bfee5ec9e670d5d2015e918defa16b7d0c/compiler/packages/babel-plugin-react-compiler/src/Babel/BabelPlugin.ts#L67) which then kicks off the core compiler passes.

I needed to make this fix at the AST level, since we were already skipping over non-React functions there (and thus wouldn't have been available within the core compiler pipeline, since it wouldn't have been a part of the HIR).

File: compiler/packages/babel-plugin-react-compiler/src/Entrypoint/Program.ts (hunk 1 above)
Comment (poteto) [reply compiler/packages/babel-plugin-react-compiler/src/Entrypoint/Program.ts]: Yeah, it's just a simple Set containing all the functions we had already compiled. We added this a long time ago when we saw functions getting compiled multiple times.

File: compiler/packages/babel-plugin-react-compiler/src/Entrypoint/Program.ts (hunk 2 above)
Comment (poteto) [reply compiler/packages/babel-plugin-react-compiler/src/Entrypoint/Program.ts:500]: `scope.getProgramParent()` is a Babel API that returns the `Program` node. Comparing these 2 nodes just checks if the `fn` is in module scope (if it was in module scope, it's parent would also be the Program), or if it's nested within another scope (such as in a BlockStatement). These [ASTexplorer console logs](https://astexplorer.net/#/gist/e483b3d2e6479b25c09f8184a180b9fc/3dbed0766ec7b22b5011fb61a3acb7bf82ba88ac) might help visualize that better

File: compiler/packages/babel-plugin-react-compiler/src/Entrypoint/Program.ts (hunk 3 above)
Comment (poteto) [reply compiler/packages/babel-plugin-react-compiler/src/Entrypoint/Program.ts]: Yeah, for now this validation just checks to see if the parent of a component/hook is a non-React function.

File: compiler/packages/babel-plugin-react-compiler/src/Entrypoint/Program.ts (hunk 4 above)
Comment (poteto) [reply compiler/packages/babel-plugin-react-compiler/src/Entrypoint/Program.ts:915]: yeah this would traverse any nested Functions and just check each parent/child pair to see if the parent and child are both React functions

File: compiler/packages/babel-plugin-react-compiler/src/Entrypoint/Program.ts (hunk 1 above)
Comment (josephsavona) [inline compiler/packages/babel-plugin-react-compiler/src/Entrypoint/Program.ts]: nit: merge these?

File: compiler/packages/babel-plugin-react-compiler/src/Entrypoint/Program.ts [hunk 5]
```diff
@@ -494,8 +494,27 @@ function findFunctionsToCompile(
...
+      pass.opts.compilationMode === 'all' &&
+      fn.scope.getProgramParent() !== fn.scope.parent
+    ) {
+      return;
+    }
+
     const fnType = getReactFunctionType(fn, pass);
-    if (fnType === null || programContext.alreadyCompiled.has(fn.node)) {
+
+    if (pass.opts.environment?.validateNoComponentOrHookFactories) {
```
Comment (josephsavona) [inline compiler/packages/babel-plugin-react-compiler/src/Entrypoint/Program.ts]: `environment` shouldn't be nullable here, right? I'm asking bc if it actually is nullable that's a bug (types say it's not, BabelPlugin.ts checks the environment).

File: compiler/packages/babel-plugin-react-compiler/src/Entrypoint/Program.ts [hunk 6]
```diff
@@ -839,6 +858,67 @@ function shouldSkipCompilation(
...
+    if (nestedFnType === 'Component' || nestedFnType === 'Hook') {
+      const nestedFnNameExpr = getFunctionName(nestedFn as BabelFn);
+      const nestedName =
+        nestedFnNameExpr !== null && nestedFnNameExpr.isIdentifier()
+          ? nestedFnNameExpr.node.name
+          : '<anonymous>';
+
+      CompilerError.throwInvalidReact({
+        category: ErrorCategory.Factories,
+        reason: `Cannot compile nested ${nestedFnType.toLowerCase()} inside a non-React function`,
```
Comment (josephsavona) [inline compiler/packages/babel-plugin-react-compiler/src/Entrypoint/Program.ts]: A couple things here:
* The message feels a bit unclear as to whether it's user error or a compiler todo. How about something like "Components and hooks cannot be created dynamically"
* For aggregation purposes we've tried to keep `reason` as a static string and put all the dynamic bits into the description or the `withDetails()` calls. 
* Using the new CompilerDiagnostic type for the error would allow controlling the output more, and let us point to multiple locations. I can imagine something like:

```
Error: Components and hooks cannot be created dynamically

Components and hooks must be static functions. Dynamically created components or hooks can result in those component or hook changing over time, leading to unnecessary re-renders and resetting state unexpectedly.

file.js:0:0
1 | function factory() {
    ^^^^^^ this function dynamically created a component/hook
2 |   return Component() { 
           ^^^^^ the component is created here
```

(with the arrows pointing to the right place)

File: compiler/packages/babel-plugin-react-compiler/src/Entrypoint/Program.ts [hunk 7]
```diff
@@ -839,6 +858,67 @@ function shouldSkipCompilation(
...
+        description:
+          `The function \`${nestedName}\` appears to be a React ${nestedFnType.toLowerCase()}, ` +
+          `but it's defined inside \`${parentName}\`, which is not a React component or hook. ` +
+          `The compiler cannot optimize nested React functions when the parent function is not compiled, ` +
+          `as this leads to scope reference errors. Either move \`${nestedName}\` to the module level, ` +
```
Comment (josephsavona) [inline compiler/packages/babel-plugin-react-compiler/src/Entrypoint/Program.ts]: Related, this describes compiler implementation details that aren't relevant to the user. If we think we should support factories then we can make this a todo, but otherwise let's focus on why the pattern is bad.

**Review by josephsavona — COMMENTED** [review]
The validation logic looks good, but i think we should be more clear on how we frame the error to the user

File: compiler/packages/babel-plugin-react-compiler/src/Entrypoint/Program.ts (hunk 5 above)
Comment (poteto) [reply compiler/packages/babel-plugin-react-compiler/src/Entrypoint/Program.ts]: Oh yeah oops, left over from some earlier debugging

File: compiler/packages/babel-plugin-react-compiler/src/Entrypoint/Program.ts (hunk 6 above)
Comment (poteto) [reply compiler/packages/babel-plugin-react-compiler/src/Entrypoint/Program.ts]: good call, added both locations

File: compiler/packages/babel-plugin-react-compiler/src/Entrypoint/Program.ts (hunk 1 above)
Comment (poteto) [reply compiler/packages/babel-plugin-react-compiler/src/Entrypoint/Program.ts]: done

File: compiler/packages/babel-plugin-react-compiler/src/Entrypoint/Program.ts (hunk 7 above)
Comment (poteto) [reply compiler/packages/babel-plugin-react-compiler/src/Entrypoint/Program.ts]: done

File: compiler/packages/babel-plugin-react-compiler/src/Entrypoint/Program.ts [hunk 8]
```diff
@@ -839,6 +852,73 @@ function shouldSkipCompilation(
...
+          details: [
+            {
+              kind: 'error',
+              message: 'this function dynamically created a component/hook',
+              loc: fn.node.loc ?? null,
+            },
+            {
+              kind: 'error',
+              message: 'the component is created here',
+              loc: nestedFn.node.loc ?? null,
```
Comment (josephsavona) [inline compiler/packages/babel-plugin-react-compiler/src/Entrypoint/Program.ts]: I wonder about trying to target the location of the function name, and falling back to the full function scope only if there was no name. Unfortunately Babel doesn't provide a location for the `function` keyword that we could target.

Comment (poteto) [reply compiler/packages/babel-plugin-react-compiler/src/Entrypoint/Program.ts:905]: Yeah I was thinking about this, but function expressions don't have names associated. I can write a small helper (if we don't have one already) to get the identifier if its available or fallback to the full function location

Comment (poteto) [reply compiler/packages/babel-plugin-react-compiler/src/Entrypoint/Program.ts]: I was thinking about that too. I think we can use the identifier if its present or fallback to the entire function if there's nothing available to use.

Comment (poteto) [reply compiler/packages/babel-plugin-react-compiler/src/Entrypoint/Program.ts]: updated!
