### PR TITLE
Fix ReactPerf.printOperations() crash

### LINKED ISSUE #6742: ReactPrerfTools: 15.1.0-alpha.1
I was testing latest refactor of PerfTools.
When using printOperations() often (but not always) I get 

```
Uncaught TypeError: Cannot read property 'displayName' of undefined
```

in getOperations() on the line:

```
var {displayName, ownerID} = treeSnapshot[instanceID];
```

### PR DESCRIPTION
**Pull request by gaearon**
This fixes #6742. It was caused by a composite changing from rendering `null` to rendering a native component. We don’t register the empty components in the devtool (as they are a temporary implementation detail), but we used to report them in some events, which caused the aggregation code to fail.

I fixed the problem and added a few remedies for the future:

1. Tests for these particular cases.
2. `ReactPerf` tests now call all aggregation methods just in case so if they throw, the tests will fail.
3. We now warn if the `debugID` passed to devtools is zero. We use zero for implementation details like TopLevelWrapper and empty components, and we don’t want to leak information about them.
4. Fixed a few remaining callsites that passed zero or undefined (mostly in tests).

Reviewers: @sebmarkbage @spicyj

### CODE REVIEW

File: src/isomorphic/__tests__/ReactPerf-test.js [hunk 1]
```diff
@@ -208,6 +215,32 @@ describe('ReactPerf', function() {
     });
   });
 
+  it('should not count replacing null with a native as waste', function() {
+    var element = null;
```
Comment (spicyj) [inline src/isomorphic/__tests__/ReactPerf-test.js]: These would be clearer if `element` was a prop.

File: src/renderers/dom/shared/__tests__/DOMPropertyOperations-test.js [hunk 2]
```diff
@@ -174,10 +174,12 @@ describe('DOMPropertyOperations', function() {
 
   describe('setValueForProperty', function() {
     var stubNode;
+    var stubInstance;
 
     beforeEach(function() {
       stubNode = document.createElement('div');
-      ReactDOMComponentTree.precacheNode({}, stubNode);
+      stubInstance = {_debugID: 1};
+      ReactDOMComponentTree.precacheNode(stubInstance, stubNode);
```
Comment (spicyj) [inline src/renderers/dom/shared/__tests__/DOMPropertyOperations-test.js]: Why did these need to change?

File: src/test/ReactTestUtils.js [hunk 3]
```diff
@@ -376,9 +376,12 @@ ReactShallowRenderer.prototype.getMountedInstance = function() {
   return this._instance ? this._instance._instance : null;
 };
 
+var nextDebugID = 0;
```
Comment (spicyj) [inline src/test/ReactTestUtils.js]: Can this start at 1? Since this doesn't reset for each shallow renderer it seems prudent to make all of them have non-0 IDs.

**Comment by spicyj** [comment]
I think this looks fine, just confused about a couple things.

File: src/renderers/dom/shared/__tests__/DOMPropertyOperations-test.js (hunk 2 above)
Comment (gaearon) [inline src/renderers/dom/shared/__tests__/DOMPropertyOperations-test.js]: The stub instances used to be plain `{}` which doesn’t have `debugID` so it turned out to be `undefined`. I err on the side of specifying them where necessary rather than omitting them for convenience, so that we can have stronger warnings in `ReactDebugTool`.

File: src/test/ReactTestUtils.js (hunk 3 above)
Comment (gaearon) [inline src/test/ReactTestUtils.js]: Oh, it should’ve been `1`.

File: src/isomorphic/__tests__/ReactPerf-test.js (hunk 1 above)
Comment (gaearon) [inline src/isomorphic/__tests__/ReactPerf-test.js]: Ha, I should’ve realized this before I wrote hundreds of tests using this pattern 😄 .

File: src/renderers/dom/shared/__tests__/DOMPropertyOperations-test.js (hunk 2 above)
Comment (spicyj) [inline src/renderers/dom/shared/__tests__/DOMPropertyOperations-test.js]: Got it, I missed the warning you added.

**Comment by spicyj** [comment]
lgtm

**Comment by facebook-github-bot-6** [comment]
@gaearon updated the pull request.

**Comment by facebook-github-bot-2** [comment]
@gaearon updated the pull request.
