### PR TITLE
Fix #6114 - Calling setState inside getChildContext should warn

### LINKED ISSUE #6114: Warn if calling setState in getChildContext
This code causes a maximum call stack:

```
getChildContext() {
  this.setState({
    foo: 'bar',
  });

  return {
    foo: this.state.foo,
  };
}
```

These sort of errors are hard to track down as the stack trace is deep in react. Is this a place we can give a user an invariant to let them know what they did wrong?

### PR DESCRIPTION
**Pull request by raineroviir**
It doesn't pass one of the tests, but I'm curious if this is the right direction or not.

### CODE REVIEW

File: src/renderers/shared/reconciler/ReactCompositeComponent.js [hunk 1]
```diff
@@ -498,6 +498,7 @@ var ReactCompositeComponentMixin = {
     var inst = this._instance;
     var childContext = inst.getChildContext && inst.getChildContext();
     if (childContext) {
+      ReactCurrentOwner.processingChildContext = true;
```
Comment (jimfb) [inline src/renderers/shared/reconciler/ReactCompositeComponent.js]: Probably don't want to attach this to ReactCurrentOwner, since it has nothing to do with owners.  But conceptually, yes, we want to set some sort of value when we start a `getChildContext`.

I think it probably makes sense to use the new devtools api here.  You can emit an event when you start/end getting the child context, and keep the state in a devtool instead of tying it into the core.  Devtool api details: https://github.com/facebook/react/pull/5590/files

File: src/renderers/shared/reconciler/ReactCompositeComponent.js [hunk 2]
```diff
@@ -521,6 +522,7 @@ var ReactCompositeComponentMixin = {
       }
       return assign({}, currentContext, childContext);
     }
+    ReactCurrentOwner.processingChildContext = null;
```
Comment (jimfb) [inline src/renderers/shared/reconciler/ReactCompositeComponent.js]: Bad to have an API that is null or true.  If it is a boolean api, all values should be booleans.

Comment (raineroviir) [inline src/renderers/shared/reconciler/ReactCompositeComponent.js]: Cool!Thanks for the notes I'll fix this

File: src/renderers/shared/reconciler/ReactCompositeComponent.js (hunk 1 above)
Comment (raineroviir) [inline src/renderers/shared/reconciler/ReactCompositeComponent.js]: Are there any examples of the Devtool api used in React code?  
Would I be writing my own devtool function or do I use something like `ReactDOMInstrumentation.debugTool.onSetValueForProperty(inst, 'processingChildContext', true)`

Comment (gaearon) [inline src/renderers/shared/reconciler/ReactCompositeComponent.js]: >Would I be writing my own devtool function or do I use something like ReactDOMInstrumentation.debugTool.onSetValueForProperty(inst, 'processingChildContext', true)
 
I think both. Here’s another example of adding a devtool for warnings: https://github.com/facebook/react/commit/251d6c30b51c6aa9a406f9076c0f895570a710b3

`onSetValueForProperty()` will not be relevant here, it’s only called this way because it is called when React sets a value for DOM property.

In your case, you can add `onBeginProcessingChildContext()` and `onEndProcessingChildContext()`, and a new `ReactInvalidSetStateWarningDevTool` (or something like this) that would set the flag.

Also, since it’s related to `React` and not `ReactDOM` in particular, perhaps it makes sense to use `ReactInstrumentation` introduced in #6068 instead of `ReactDOMInstrumentation`.

Comment (raineroviir) [inline src/renderers/shared/reconciler/ReactCompositeComponent.js]: Cool , Thanks!  

So I notice I can't extend the internalInstance object to add the flag. What is a good object to add the flag to?

File: src/isomorphic/ReactDebugTool.js [hunk 3]
```diff
@@ -48,6 +48,12 @@ var ReactDebugTool = {
       }
     }
   },
+  onBeginProcessingChildContext(instance, boolean) {
```
Comment (jimfb) [inline src/isomorphic/ReactDebugTool.js]: `boolean` is a type.  A good variable name would be something like `isPprocessingChildContext`.  But why does this variable exist at all?  Isn't it always true in this function and always false in the other?

File: src/isomorphic/devtools/ReactInvalidSetStateWarningDevTool.js [hunk 4]
```diff
@@ -0,0 +1,19 @@
...
+if (__DEV__) {
+  var warnInvalidSetState = function(instance, boolean) {
+    instance._processingChildContext = boolean
+    return;
+  }
+}
+
+var ReactInvalidSetStateWarningDevTool = {
+  onBeginProcessingChildContext(instance, boolean) {
+    warnInvalidSetState(instance, boolean)
```
Comment (jimfb) [inline src/isomorphic/devtools/ReactInvalidSetStateWarningDevTool.js]: Should set a scope-local variable on the devtool, not warn and/or set variables on the instance.

File: src/isomorphic/devtools/ReactInvalidSetStateWarningDevTool.js [hunk 5]
```diff
@@ -0,0 +1,19 @@
...
+  },
+  onEndProcessingChildContext(instance, boolean) {
+    warnInvalidSetState(instance, boolean)
```
Comment (jimfb) [inline src/isomorphic/devtools/ReactInvalidSetStateWarningDevTool.js]: Should set a scope-local variable on the devtool, not warn and/or set variables on the instance.

File: src/isomorphic/modern/class/ReactComponent.js [hunk 6]
```diff
@@ -72,6 +72,12 @@ ReactComponent.prototype.setState = function(partialState, callback) {
       'instead, use forceUpdate().'
     );
   }
+  if (__DEV__) {
+    warning(
```
Comment (jimfb) [inline src/isomorphic/modern/class/ReactComponent.js]: Should emit a setState event, warn within the devtool.

Comment (raineroviir) [inline src/isomorphic/modern/class/ReactComponent.js]: Thank you for the notes!

File: src/isomorphic/devtools/ReactInvalidSetStateWarningDevTool.js [hunk 7]
```diff
@@ -0,0 +1,32 @@
...
+var warning = require('warning');
+
+if (__DEV__) {
+  var processingChildContext = false;
+
+  var warnInvalidSetState = function() {
+    if (processingChildContext === false) {
+      return;
+    }
+    warning(
```
Comment (gaearon) [inline src/isomorphic/devtools/ReactInvalidSetStateWarningDevTool.js]: It might be more compact to write

```js
warning(
  !processingChildContext,
  'setState(...): Cannot call setState inside getChildContext()'
);
```

**Comment by gaearon** [comment]
This looks great to me! Let’s hear what @jimfb has to say.

File: src/isomorphic/devtools/ReactInvalidSetStateWarningDevTool.js (hunk 7 above)
Comment (raineroviir) [inline src/isomorphic/devtools/ReactInvalidSetStateWarningDevTool.js]: You're right, Thanks

**Comment by raineroviir** [comment]
I am failing a test locally not sure why it isn't failing in travis.  Is that kinda worrying?

``` FAIL  src/renderers/shared/reconciler/__tests__/ReactCompositeComponent-test.js (3.028s)
● ReactCompositeComponent › it should pass context when re-rendered
  - Expected: 1 toBe: 0
        at Spec.eval (src/renderers/shared/reconciler/__tests__/ReactCompositeComponent-test.js:843:46)```

File: src/isomorphic/ReactDebugTool.js [hunk 8]
```diff
@@ -10,7 +10,7 @@
  */
 
 'use strict';
-
+var ReactInvalidSetStateWarningDevTool = require('./devtools/ReactInvalidSetStateWarningDevTool');
```
Comment (jimfb) [inline src/isomorphic/ReactDebugTool.js]: Normally we would just do `require('ReactInvalidSetStateWarningDevTool')`, so this seems weird.  I'm assuming you did this because `require('ReactInvalidSetStateWarningDevTool')` didn't work for you because you didn't have an `@providesModule` at the top of that file.

If you add the standard copyright header to `ReactInvalidSetStateWarningDevTool.js` and specify the `@providesModule`, we should be able to fix this line.

Comment (raineroviir) [inline src/isomorphic/ReactDebugTool.js]: Got it. That providesModule thing is super cool

**Comment by jimfb** [comment]
I looked into the failing unit test, it looks like a valid failure caused by this change (ie. needs to be fixed before we can merge).  That test is not invoking `setState()` during `getChildContext`, but the warning appears to be firing.

I'm not sure why it didn't fail travis (cc @zpao).

File: src/renderers/shared/reconciler/__tests__/ReactCompositeComponent-test.js [hunk 9]
```diff
@@ -783,7 +812,7 @@ describe('ReactCompositeComponent', function() {
 
       render: function() {
         var output = <Child />;
-        if (!this.state.flag) {
+        if (this.state.flag) {
```
Comment (jimfb) [inline src/renderers/shared/reconciler/__tests__/ReactCompositeComponent-test.js]: What is going on here?  Why this change?

Comment (raineroviir) [inline src/renderers/shared/reconciler/__tests__/ReactCompositeComponent-test.js]: I wanted to see why the test was throwing the warning 
1. in the original test we rendered `<Parent> <Child /> <Parent>`, and on `setState` we change the render to `<Parent><span>Child</span></Parent>`
2. in the changed test which doesn't create a warning we go from `<P><span>Child</span> </P>` to `<P><Child /><P>`

Comment (jimfb) [inline src/renderers/shared/reconciler/__tests__/ReactCompositeComponent-test.js]: Ok, well, we still need to fix so the original test passes.

Comment (raineroviir) [inline src/renderers/shared/reconciler/__tests__/ReactCompositeComponent-test.js]: Yeah! I will make the original test pass

**Comment by jimfb** [comment]
Ping @raineroviir

**Comment by raineroviir** [comment]
I've tried many things I'm not sure how to go about fixing the test.

**Comment by raineroviir** [comment]
Wow I spent so long on this problem.  I looked at some awesome code that vslinko wrote to fix this issue and it was so simple, I just did not fully understand the issue I was fixing.  I made an early assumption of where the code should go and tried everything to make it work.  Sigh.  Like trying to stick a square peg in a round hole

File: src/renderers/shared/reconciler/__tests__/ReactCompositeComponent-test.js [hunk 10]
```diff
@@ -424,6 +424,35 @@ describe('ReactCompositeComponent', function() {
...
+        return <div />;
+      },
+    });
+    expect(console.error.calls.length).toBe(0);
+    var instance = ReactDOM.render(<Component />, container);
+    expect(renderPasses).toBe(2);
+    expect(instance.state.value).toBe(1);
+    expect(console.error.calls.length).toBe(1);
+    expect(console.error.argsForCall[0][0]).toBe(
+      'Warning: setState(...): Cannot call setState inside getChildContext()'
```
Comment (gaearon) [inline src/renderers/shared/reconciler/__tests__/ReactCompositeComponent-test.js]: Nitpicking: let’s add `()` for consistency? As in `Cannot call setState() inside getChildContext()`.

**Comment by gaearon** [comment]
The earlier problem was likely due to `return` later in the method which caused `onEnd*` to be missing. You fixed it correctly by wrapping just the `getChildContext()` call.

Great job! Thank you for following through with this.

**Comment by gaearon** [comment]
Would you mind squashing it as a single commit?

File: src/renderers/shared/reconciler/__tests__/ReactCompositeComponent-test.js (hunk 10 above)
Comment (raineroviir) [inline src/renderers/shared/reconciler/__tests__/ReactCompositeComponent-test.js]: Sure

**Comment by raineroviir** [comment]
I totally just squashed all those commits! Thanks for all the great comments guys, no better way to learn how to do this stuff than by doing

**Comment by jimfb** [comment]
This looks great to me, thanks @raineroviir!
