### PR TITLE
DevTools always overrides the dispatcher when shallow rendering

### LINKED ISSUE #19911: Bug: devtools Profiler causes unexpected errors
We noticed that our app would behave differently during profiling runs and trigger errors. I'm not totally sure what the underlying issue is but I was able to put together a example app to reproduce. As far as I can tell it has to do with how devtools is overriding `console.warn` and `console.error`. In that case `describeNativeComponentFrame()` will call a function component with no args. This works fine as the error is caught in `describeNativeComponentFrame()` but in it looks like a `useEffect()` that accesses those `props` is still triggered and it does not expect `props` to be undefined. 

I realize that having `props` in the dependencies array of the `useEffect` doesn't really make sense but I still think it probably shouldn't error.

React version: 16.13.1
React devtools version: 4.8.2 

## Steps To Reproduce

1. Open link to code example below
2. Click "Open In New Window" from the "Browser" tab
3. Observe a simple app with only `<h1>Hello World</h1>`
3. Open the React devtools Profiler tab
4. Click "Reload and start profiling"
5. Observe an error `Uncaught TypeError: Cannot read property 'foo' of undefined`

Link to code example:

https://codesandbox.io/s/cool-sun-wdrry

## The current behavior

wdrry csb app_

## The expected behavior

The app should work as it while not profile. It should render a `<h1>Hello World</h1>`

### PR DESCRIPTION
**Pull request by bvaughn**
This is done so that any effects scheduled by the shallow render are thrown away.

Unlike the code this was forked from (in ReactComponentStackFrame) DevTools should override the dispatcher in production mode as well, because app code might log errors or warnings.

Resolves #19911

### CODE REVIEW

**Comment by bvaughn** [comment]
I am going to try to capture this in a test too.

File: packages/react-devtools-shared/src/__tests__/componentStacks-test.js [hunk 1]
```diff
@@ -0,0 +1,106 @@
...
+        '\n    in Parent (at **)' +
+        '\n    in Grandparent (at **)',
+    );
+  });
+
+  /** This test should have caught #19911
+      but didn't because both DevTools and ReactDOM are running in the same memory space,
+      so the case we're testing against (DevTools prod build and React DEV build) doesn't exist.
+      It would be nice to figure out a way to test this combination at some point...
+  it('should disable the current dispatcher before shallow rendering so no effects get scheduled', () => {
```
Comment (gaearon) [inline packages/react-devtools-shared/src/__tests__/componentStacks-test.js:83]: Maybe `xit` instead of commenting out?

File: packages/react-devtools-shared/src/backend/DevToolsComponentStackFrame.js [hunk 2]
```diff
@@ -85,14 +85,16 @@ export function describeNativeComponentFrame(
...
-    // for warnings.
-    currentDispatcherRef.current = null;
-    disableLogs();
-  }
+
+  // Override the dispatcher so effects scheduled by this shallow render are thrown away.
+  //
+  // Note that unlike the code this was forked from (in ReactComponentStackFrame)
+  // DevTools should override the dispatcher in production mode as well,
+  // because app code might log errors or warnings.
```
Comment (gaearon) [inline packages/react-devtools-shared/src/backend/DevToolsComponentStackFrame.js:93]: I think this comment isn't entirely clear. I read "in production mode" as "when app runs in production mode". Maybe you could say "should override the dispatcher when DevTools is compiled in production mode, because the app itself may be in development mode and log errors".

File: packages/react-devtools-shared/src/__tests__/componentStacks-test.js (hunk 1 above)
Comment (bvaughn) [reply packages/react-devtools-shared/src/__tests__/componentStacks-test.js:83]: Sure.
