### PR TITLE
Consider components in jsx as missing dependencies in @typescript-eslint/parser@4.x

### LINKED ISSUE #18051: Bug: [eslint-plugin-react-hooks] exhaustive-deps false positive on "unnecessary" dependency if its a React component
## Steps to reproduce

1. create a memoized value using `useMemo`
2. a React component is used in the creation of this value, in a JSX expression
3. specify the React component in the dependency array

Link to code example: https://github.com/zeorin/eslint-plugin-react-hooks-repro

## The current behavior

```
React Hook useMemo has an unnecessary dependency: 'Component'. Either exclude it or remove the dependency array react-hooks/exhaustive-deps
```

## The expected behavior

No lint errors.

## More details

A simple repro (taken from the link above) is:

```javascript.jsx
function Foo({ component: Component }) {
	const memoized = useMemo(() => ({
		render: () => <Component />
	}), [Component]);

	return memoized.render();
}
```

## Workarounds

If one changes the component to lowercase, the lint error goes away. It does also mean that we need to change the way we render the component:

```javascript.jsx
function Foo({ component }) {
	const memoized = useMemo(() => ({
		render: component
	}), [component]);

	return memoized.render();
}
```

Alternatively we can decide not to use JSX, in which case the lint rule functions correctly, too:

```javascript.jsx
function Foo({ component: Component }) {
	const memoized = useMemo(() => ({
		render: () => React.createElement(Component)
	}), [Component]);

	return memoized.render();
}
```

## Impact

Currently it is hard to use props that are components in a JSX expression if one is using the `exhaustive-deps` rule.

This is also compounded by the fact that this rule has a ESLint fix that removes the dependency, thus changing the behaviour of the code and leading to bugs. See https://github.com/facebook/react/issues/16313 for that bug report.

### LINKED ISSUE #19810: Bug: eslint-plugin-react-hooks "Cannot read property parent of null"
This seems to happen when
1. I take a component as a prop
2. I use that component as a JSX constructor in a hook

Minimal repro:
```jsx
export const Foo = ({ Component }) => {
  React.useEffect(() => {
    console.log(<Component />);
  }, []);
};
```

```
    "eslint-plugin-react-hooks": "^4.1.1",
```

---

Interestingly, this does NOT cause the error:
```jsx
export const Foo = ({ component }) => {
  React.useEffect(() => {
    const Component = component;
    console.log(<Component />);
  }, []);
};
```

### PR DESCRIPTION
**Pull request by eps1lon**
## Summary

Closes #19810

1. extract flow tests from `tests`
  This results in 3 test suites for JS, Flow and TypeScript. I originally thought #19810 was only  failing with TS parsers. So I wanted to also run all JS tests with the TS parsers (since any JS is also valid TS) but `tests` included some tests written for flow which isn't valid TS. Turns out the test in question only fails with a specific major of `@typyescript-eslint/parser` so that effort isn't strictly necessary for this PR but it increases test coverage nonetheless.
2. add minimal repro from https://github.com/facebook/react/issues/19810#issue-698822399 to failing tests
  Turns out this only crashes in `@typescript-eslint/parser@4.x`. All other parsers incorrectly mark this as valid which is tracked in https://github.com/facebook/react/issues/18051
3. Fix failing test by supporting `JSXIdentifier` 

## Test Plan

- [x] CI green

### CODE REVIEW

File: packages/eslint-plugin-react-hooks/src/ExhaustiveDeps.js [hunk 1]
```diff
@@ -1779,7 +1779,7 @@ function isNodeLike(val) {
 
 function isSameIdentifier(a, b) {
   return (
-    a.type === 'Identifier' &&
+    (a.type === 'Identifier' || a.type === 'JSXIdentifier') &&
```
Comment (eps1lon) [inline packages/eslint-plugin-react-hooks/src/ExhaustiveDeps.js:1782]: That is a bit hacky since it would return true when comparing `isSameIdentifier(Component, <Component />)`. Can't imagine a path that would lead to this though.

Comment (gaearon) [reply packages/eslint-plugin-react-hooks/src/ExhaustiveDeps.js:1782]: That sounds odd. Can we find a way to tighten it up?

Comment (eps1lon) [reply packages/eslint-plugin-react-hooks/src/ExhaustiveDeps.js:1782]: Added a check that makes sure `a` and `b` are the same kind of identifier. `isSameIdentifier-ish` is probably more accurate at this point.

**Comment by gaearon** [comment]
Are you saying this fixes https://github.com/facebook/react/issues/18051? Why?

**Comment by eps1lon** [comment]
> Are you saying this fixes #18051? 

It fixes it only for `@typescript-eslint/parser@4.x`. Any version below (or other parsers) don't fix it.

> Why?

Isn't #18051 similar to the test I added?

```jsx
function Foo({ Component }) {
  React.useEffect(() => {
    console.log(<Component />);
  }, [Component]);
};
```

I tried the added test with `@typescript-eslint/parser@3.x` and with that parser the code is (falsely) considered valid. I can restructure how the tests are partitioned so that it's more obvious that one test is invalid with one parser but valid with another one.

**Comment by gaearon** [comment]
>  For any version below (or other parsers) this PR has no effect.

That’s what I was missing. We should make sure we don’t accidentally close that issue then. 

Is this good to go?

**Comment by eps1lon** [comment]
> > For any version below (or other parsers) this PR has no effect.
> 
> That’s what I was missing. We should make sure we don’t accidentally close that issue then.
> 
> Is this good to go?

Oh, I understand the confusion. I didn't intend to reference #18051 for automatic closing but #19810

**Comment by eps1lon** [comment]
> Is this good to go?

Should be. Not a fan of how the test suite is growing. I hope it doesn't get too confusing.
