### PR TITLE
Provide warning when using styles containing a semicolon

### LINKED ISSUE #2862: Style updates silently fail with trailing semicolon in style
On the first render it works, but then the update silently fails.  Expected would be the semicolon being removed, or an error/warning in the development build.  

Tested on Chrome latest, Firefox latest, with 0.12.1 and master.

Minimal: [jsbin](http://jsbin.com/butuwazuca/2/edit?js,output)

```js
var App = React.createClass({
  getInitialState: function(){
    return {color: 'red'}
  },
  
  handleClick : function() {
    console.log('hello world');
    this.setState({
      color: 'blue'
    });
  },
  
  render: function() {
    console.log('rendering');
    var style = {
      backgroundColor: this.state.color
    };
    
    if (this.props.withsemi) {
      style.backgroundColor += ";";
    }

    return (
    <div>
      <div style={style} onClick={this.handleClick}></div>
    </div>
    )
  }
});
```

@rabishah ran into (on IRC).

### PR DESCRIPTION
**Pull request by mzabriskie**
Closes #2862

### CODE REVIEW

**Comment by zpao** [comment]
Awesome! A few comments incoming, but overall it looks good.

File: src/browser/ui/dom/CSSPropertyOperations.js [hunk 1]
```diff
@@ -37,7 +37,11 @@ if (__DEV__) {
   // 'msTransform' is correct, but the other prefixes should be capitalized
   var badVendoredStyleNamePattern = /^(?:webkit|moz|o)[A-Z]/;
 
+  // style values shouldn't contain a semicolon
+  var badStyleValueWithSemicolonPattern = /;(\s*)$/;
```
Comment (zpao) [inline src/browser/ui/dom/CSSPropertyOperations.js]: I think we can leave out the parens since we're not using that matching group anywhere. But good call on making the regex a bit more robust with the space checks.

File: src/browser/ui/dom/CSSPropertyOperations.js [hunk 2]
```diff
@@ -64,6 +68,33 @@ if (__DEV__) {
...
+  var warnStyleValueWithSemicolon = function(name, value) {
+    if (warnedStyleValues.hasOwnProperty(value) && warnedStyleValues[value]) {
+      return;
+    }
+    
+    warnedStyleValues[value] = true;
+    warning(
+      false,
+      'Style property values shouldn\'t contain a semicolon. Try "' +
+      name + ': ' + value.replace(badStyleValueWithSemicolonPattern, '') + '" instead.'
```
Comment (zpao) [inline src/browser/ui/dom/CSSPropertyOperations.js]: I know you're just copying the pattern from above, but let's make use of `%s` instead of doing the concats (we're going to fix the others up in #2941)

File: src/browser/ui/dom/CSSPropertyOperations.js [hunk 3]
```diff
@@ -64,6 +68,33 @@ if (__DEV__) {
...
+    );
+  };
+
+  /**
+   * @param {string} name
+   * @param {string|number} value
+   */
+  var assertValidStyle = function(name, value) {
```
Comment (zpao) [inline src/browser/ui/dom/CSSPropertyOperations.js]: I think it might be better to call it something with `warn` in the name. `assert` has the connotation that an error will be thrown.

Also, I think you'll probably want `@param {*} value` (unless we're doing a validation before this). There's nothing actually stopping you from saying `style={{foo: [1,2,3]}}`

File: src/browser/ui/dom/CSSPropertyOperations.js (hunk 2 above)
Comment (mzabriskie) [inline src/browser/ui/dom/CSSPropertyOperations.js]: How should this be handled if the message itself is > 80 max-len? Ok to concatenate actual message to avoid lint failures?

```js
warning(
  false,
  'Style property values shouldn\'t contain a semicolon. ' +
  'Try "%s: %s" instead.',
  name,
  value.replace(badStyleValueWithSemicolonPattern, '')
);
```

**Comment by zpao** [comment]
Awesome, thanks! I think this will be helpful.
