### PR TITLE
Issue/#19545

### LINKED ISSUE #19545: Bug: Proxy on Context throws an error in DevTools
React version: 16.12.0

## Steps To Reproduce

1. Create an app with a `Proxy` function that has a `get` method that returns a function stored in Context
2. Attempt to look at Provider component in devtools

Link to code example:
https://codesandbox.io/s/stoic-jepsen-7jjfn?file=/src/App.js
https://7jjfn.csb.app/

## The current behavior
When using the devtools to inspect the `Context.Provider`, devtools throw an error:
```
Uncaught DOMException: Failed to execute 'postMessage' on 'Window': function () {
        return null;
      } could not be cloned.
```
Components using the context do not show info in devtools and show "Loading..." instead.

## The expected behavior
No error is thrown.

## Possibly Related
#16691

### PR DESCRIPTION
**Pull request by pfongkye**
## Summary

Fixes #19545 
The data.name in a given payload should not be a function since window.postMessage  would throw an error.

If I'm on the right path, should we modify `formatDataForPreview` to take into consideration the fact that data.name can be an anonymous function?
image

## Test Plan

- [x] Tests to be added

### CODE REVIEW

File: packages/react-devtools-shared/src/hydration.js [hunk 1]
```diff
@@ -151,7 +151,10 @@ export function dehydrate(
         inspectable: false,
         preview_short: formatDataForPreview(data, false),
         preview_long: formatDataForPreview(data, true),
-        name: data.name || 'function',
+        name:
+          typeof data.name === 'function' || !data.name
+            ? 'function'
+            : data.name,
```
Comment (omarsy) [inline packages/react-devtools-shared/src/hydration.js:157]: The javascript Proxy wraps the name attribute. I think instead of using `data.name` you can replace  it by `data.prototype.constructor.name`. It is the same thing but the difference is the constructor.name is not wrapped by the proxy.

Comment (bvaughn) [reply packages/react-devtools-shared/src/hydration.js:157]: > The javascript Proxy wraps the name attribute.

Oh that's very interesting! Nice find.

> I think instead of using `data.name` you can replace  it by `data.prototype.constructor.name`. It is the same thing but the difference is the constructor.name is not wrapped by the proxy.

I'm wary of using `data.prototype.constructor.name` because not all objects have a prototype (e.g. `Object.create(null)`

**Comment by bvaughn** [comment]
> If I'm on the right path, should we modify `formatDataForPreview` to take into consideration the fact that data.name can be an anonymous function?

Yes. Sounds worth doing.

**Comment by pfongkye** [comment]
@bvaughn I had some tests failing before the modifications. I fixed some. There are two remaining. I wanted to check with you if these are the new expected behaviors before fixing them: 
[snapshot failing](https://github.com/pfongkye/react/blob/6c9945e87e8efc0edd7bd337490b27cbf6db35df/packages/react-devtools-shared/src/__tests__/storeComponentFilters-test.js#L168)
[expecting 3 but received 1](https://github.com/pfongkye/react/blob/6c9945e87e8efc0edd7bd337490b27cbf6db35df/packages/react-devtools-shared/src/__tests__/ownersListContext-test.js#L228)

**Comment by bvaughn** [comment]
@pfongkye I'm not sure I understand what you're asking about those two tests. How do they fail? Hard for me to say if the failure would be expected or not without having more context. The second one in particular though (expected 3 but got 1) does not seem expected, I think.

File: packages/react-devtools-shared/src/__tests__/bridge-test.js [hunk 2]
```diff
@@ -43,7 +43,7 @@ describe('Bridge', () => {
     jest.runAllTimers();
     expect(wall.send).not.toHaveBeenCalled();
     expect(console.warn).toHaveBeenCalledWith(
-      'Cannot send message "should not send" through a Bridge that has been shutdown.',
+      'Warning: Cannot send message "should not send" through a Bridge that has been shutdown.',
```
Comment (bvaughn) [inline packages/react-devtools-shared/src/__tests__/bridge-test.js:46]: Why are you adding "Warning:" prefixes to these tests?

**Comment by pfongkye** [comment]
> @pfongkye I'm not sure I understand what you're asking about those two tests. How do they fail? Hard for me to say if the failure would be expected or not without having more context. The second one in particular though (expected 3 but got 1) does not seem expected, I think.

Sorry. So I don't know why but I was having those two tests failing on my computer (OS is Windows 10 Professional): 
image
image

But after running `build-for-devtools`, I'm still having the following test failing:
image

I'm going to revert commit https://github.com/pfongkye/react/commit/6b36d98067c8893098ad923997868ead206c99bf#diff-ab5ee5655b2aac3260e1f836546a13c9 and hopefully find out why the tests are failing.

**Comment by bvaughn** [comment]
FWIW, I checked out your branch and reverted that commit locally– and when I ran DevTools tests, they all passed.

**Comment by pfongkye** [comment]
> Any other changes you looking to include? (I see the PR is still in "Draft" status)
Nope. It was because of the tests :)

**Comment by pfongkye** [comment]
Thanks a lot!
Guess I'll have to run the tests in docker (or maybe on WSL2) next time 😅
