### PR TITLE
Trap click events for portal root

### LINKED ISSUE #11918: Click events don't bubble from Portal content on mobile Safari
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
In mobile Safari, DOM events originating from elements rendered through a Portal do **not** bubble (propagate) up the React component tree.

**If the current behavior is a bug, please provide the steps to reproduce....**
Please see the following JSFiddle: https://jsfiddle.net/zebulonj/wf7orwan/

In this JSFiddle, the expected behavior (seen in a desktop browser) is that clicking on the portal content (appearing as a modal, including backdrop) should toggle to the "On" or "Off" indicator rendered in the main content. However, in mobile Safari (iOS 11.1.1), the click events do not propagate.

**What is the expected behavior?**
Click events should propagate up the React component tree.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Affected: React 16.2
iOS 11.1.1

### PR DESCRIPTION
**Pull request by aweary**
Should resolve #11918 

Still need to run the build in iOS Safari to verify, but I'm 90% sure it will since an empty click handler fixed it in the JSFiddle provided for the issue.

### CODE REVIEW

File: packages/react-dom/src/client/ReactDOM.js [hunk 1]
```diff
@@ -1125,6 +1126,7 @@ function createPortal(
     isValidContainer(container),
     'Target container is not a DOM element.',
   );
+  trapClickOnNonInteractiveElement(((container: any): HTMLElement));
```
Comment (gaearon) [inline packages/react-dom/src/client/ReactDOM.js]: Hmm, not sure we want to introduce side effects there.

Comment (aweary) [reply packages/react-dom/src/client/ReactDOM.js]: Is there another place to perform DOM-specific effects when a portal is mounted?

Comment (gaearon) [reply packages/react-dom/src/client/ReactDOM.js]: Something like `appendToContainer` in the renderer?

File: packages/react-dom/src/client/ReactDOM.js [hunk 2]
```diff
@@ -760,7 +761,11 @@ const DOMRenderer = ReactFiberReconciler({
     ): void {
       if (container.nodeType === COMMENT_NODE) {
         (container.parentNode: any).insertBefore(child, container);
+        trapClickOnNonInteractiveElement(
+          ((container.parentNode: any): HTMLElement),
+        );
```
Comment (aweary) [inline packages/react-dom/src/client/ReactDOM.js]: @gaearon is using a comment node as a mount point supported for portals as well?

File: packages/react-dom/src/client/ReactDOM.js (hunk 1 above)
Comment (gaearon) [reply packages/react-dom/src/client/ReactDOM.js]: Hmm maybe? Idk :-(

File: packages/react-dom/src/client/ReactDOM.js (hunk 2 above)
Comment (gaearon) [reply packages/react-dom/src/client/ReactDOM.js]: Worth supporting for consistency I guess

File: packages/react-dom/src/client/ReactDOM.js [hunk 3]
```diff
@@ -756,7 +757,11 @@ const DOMRenderer = ReactFiberReconciler({
...
       } else {
+        trapClickOnNonInteractiveElement(((container: any): HTMLElement));
```
Comment (gaearon) [inline packages/react-dom/src/client/ReactDOM.js]: What if it already has `onclick`? Is it expected that rendering into it overrides `onclick`?

Comment (aweary) [reply packages/react-dom/src/client/ReactDOM.js]: I guess if it already has `onclick` we don't need to trap click events, so I'll wrap this in a null check.

Comment (gaearon) [reply packages/react-dom/src/client/ReactDOM.js]: Should we do the same in `trapClickOnNonInteractiveElement` itself then?

Comment (aweary) [reply packages/react-dom/src/client/ReactDOM.js]: Yeah that's what I was doing :) my only hesitation is that `trapClickOnNonInteractiveElement` is also called on elements that React controls (which shouldn't have `onclick` making the check redundant in most cases).

Comment (gaearon) [reply packages/react-dom/src/client/ReactDOM.js]: Yeah, I guess you're right

Comment (gaearon) [reply packages/react-dom/src/client/ReactDOM.js]: By the way do we do this regardless of whether we're mobile safari? Is that good? Should we check the browser somehow?

Comment (aweary) [reply packages/react-dom/src/client/ReactDOM.js]: Right now we do it regardless of the browser. There's an [existing TODO for adding browser detection](https://github.com/facebook/react/blob/master/packages/react-dom/src/client/ReactDOMFiberComponent.js#L263). It might be a good time to address that, assuming browser detection is fast/reliable enough.

**Comment by gaearon** [comment]
I don't understand this fix.

In the existing code we set `onclick` handlers on the *target* nodes. That is, on the nodes that would be clicked.

Here, we set `onclick` on the *container* node of the portal. Why is this helpful?

**Comment by aweary** [comment]
It's been awhile, but see [this JSFiddle from the issue](https://jsfiddle.net/zebulonj/02p6x5kk/) @gaearon. Attaching an event listener to the _container_ allows the event to bubble 🤷‍♂️

**Comment by gaearon** [comment]
We need to have a rational explanation first. 😄

**Comment by aweary** [comment]
Is "because iOS Safari" rational enough? 😅

I'll have to dig into this again to make any sense of it.

**Comment by gaearon** [comment]
>Is "because iOS Safari" rational enough

Scare tactics.

**Comment by gaearon** [comment]
It does work though. WHY

**Comment by gaearon** [comment]
https://github.com/facebook/react/issues/12989#issuecomment-414003408

**Comment by gaearon** [comment]
Seems fine. I added a comment for why this works.

**Comment by react-linter** [comment]
ReactDOM: size: 0.0%, gzip: :small_red_triangle:+0.1%


  <details>
  <summary>Details of bundled changes.</summary>

  <p>Comparing: 0da5102cf02890a4e006f4d949ae4fbf2bfd85af...4893ae2781d036dd9d22e81457846ce7a1ef4d56</p>


  
## react-dom
File | Filesize Diff | Gzip Diff | Prev Size | Current Size | Prev Gzip | Current Gzip | ENV
 ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  --- 
react-dom.development.js | +0.1% | +0.1% | 649.27 KB | 649.95 KB | 152.41 KB | 152.57 KB | UMD_DEV
**react-dom.production.min.js** | **0.0%** | **:small_red_triangle:+0.1%** | **95.6 KB** | **95.64 KB** | **31.24 KB** | **31.28 KB** | **UMD_PROD**
react-dom.development.js | +0.1% | +0.1% | 645.41 KB | 646.09 KB | 151.28 KB | 151.45 KB | NODE_DEV
**react-dom.production.min.js** | **0.0%** | **:small_red_triangle:+0.1%** | **95.59 KB** | **95.64 KB** | **30.98 KB** | **31 KB** | **NODE_PROD**
ReactDOM-dev.js | +0.1% | +0.1% | 652.7 KB | 653.38 KB | 149.44 KB | 149.63 KB | FB_WWW_DEV
**ReactDOM-prod.js** | **:small_red_triangle:+0.1%** | **:small_red_triangle:+0.1%** | **288.52 KB** | **288.67 KB** | **53.42 KB** | **53.45 KB** | **FB_WWW_PROD**
react-dom.profiling.min.js | 0.0% | +0.1% | 96.79 KB | 96.83 KB | 31.37 KB | 31.4 KB | NODE_PROFILING
ReactDOM-profiling.js | +0.1% | +0.1% | 290.87 KB | 291.01 KB | 54.02 KB | 54.05 KB | FB_WWW_PROFILING

  </details>
  
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>
