### PR TITLE
Backport input fix

### LINKED ISSUE #6614: Upgrading from React 14 to 15 breaks IE11 autofill behavior with controlled inputs
I have a sign in form with controlled inputs that works fine using React 14. When I upgrade to React 15, autofill behavior in IE11 no longer triggers onChange. Strangely, if I change document mode from "Edge (Default)" to "10" React 15 still behaves as expected.

Reading the changelog for R15, this change sounds like it could be related:

> Input events are handled more reliably in IE 10 and IE 11; spurious events no longer fire when using a placeholder.
> @jquense in #4051

### LINKED ISSUE #6822: onChange not firing properly in React 15 + IE11 when clearing input with X button or rightclick -> Delete
The onChange event for inputs does not seem to be working correctly in React 15 when using the clear (X) button provided by IE (I'm using IE11). Clicking the clear button does not fire an immediate onChange at the time of click; rather, it seems that it "queues" an onChange that fires the next time text is entered, effectively rapid-firing two onChanges in succession. This becomes a problem when using a component that maps its state to two (or more, probably) inputs' values.

I made two fiddles with different versions of React and ReactDOM.
React 15 fiddle (buggy): https://jsfiddle.net/yde4wgaa/3/
React 0.14 fiddle (working): https://jsfiddle.net/f0tv528v/1/

In the React 15 fiddle, you can reproduce in IE11 by:
1. typing a value into the left input box
2. typing another value into the right input box
3. clicking the X button to clear the right input box
4. typing whatever in the left input box

You should see that the right input box reverts to its value before you clicked X. You can also see this happening if, instead of clicking X to clear the right input, you highlight the input text, right click, and click 'Delete'. Both the X button and right-click -> delete cases work fine with React 0.14 (tested both fiddles with the exact same browser and code).

### LINKED ISSUE #7211: onChange not firing properly in React 15.2.0 + IE11 when paste text into textarea
Hello. On IE11/React 15.2.0 when copy/paste data from keyboard to a textarea, onChange not firing, 
this works fine in Chrome and FF

I've included a test link:
 https://jsfiddle.net/wxwawpkn/
(a log msg should happen when you copy/paste data into textarea)

Thanks!

### PR DESCRIPTION
**Pull request by jquense**
cc @aweary

fixes #7211 fixes #6822 fixes #6614

we should make sure it doesn't break #3926 any worse (or works with #8438)

### CODE REVIEW

**Comment by jquense** [comment]
CI seems like not my fault :P

**Comment by gaearon** [comment]
If you added new tests please run `./scripts/fiber/record-tests` and commit the result.
It’s how we keep track of Fiber regressions.

**Comment by Aweary** [comment]
@gaeron these tests already exists in `master`, this PR is open against the `15-dev` branch.

**Comment by gaearon** [comment]
Oops, I didn't realize that.

**Comment by jquense** [comment]
ping, anything I can do here? I'm not sure what the issue with CI is but it doesn't seem related.

**Comment by jquense** [comment]
If it helps, there are only a few lines of new code on top of #5746

https://github.com/facebook/react/pull/8575/files#diff-d7d43033e0c4300df2b535a9df27b8edR127

and

https://github.com/facebook/react/pull/8575/files#diff-5e825edec102e25dc133910960c7f37eR325

**Comment by aweary** [comment]
Sorry for the delay @jquense, I haven't had too much free time unfortunately. I reviewed it and it looks 👍 to me, but haven't actually pulled it down and tested how it might affect https://github.com/facebook/react/issues/3926 yet

**Comment by jquense** [comment]
no worries, just wanted to make sure it wasn't blocked by me :)

**Comment by gaearon** [comment]
@sebmarkbage You wanted to have another look at this?

**Comment by aweary** [comment]
@jquense Alright, I finally got a chance to verify behavior locally in regards to #3926. Without any changes it doesn't make the issue any worse (still fires before composition event finishes). But I cherry picked https://github.com/facebook/react/pull/8438/commits/ae543389523086137bf56a9d153a089da291fbd7 from https://github.com/facebook/react/pull/8438 and after minimal changes (making sure `nativeEvent` was getting passed correctly at a few places) it seems to work. `onChange` doesn't fire until the composition event ends.

I tested with the native  Pinyin keyboard provided by OS X (10.12.2).

I'll continue to look at it and verify that there are no regressions, but I think this looks good 👍 

@gaearon @sebmarkbage if either of you want to give it a second review let me know and I can hold off on moving forward with this.

**Comment by gaearon** [comment]
Does this work with Fiber too?

**Comment by aweary** [comment]
I'm not super familiar with how Fiber interfaces with the existing event system, but I can switch on the flag and test it out.

**Comment by gaearon** [comment]
You can see `ReactDOMComponent` being forked as `ReactDOMFiberComponent`, the rest of the code is mostly reused. Let me know if you have any specific questions. Thanks!

We’d need Fiber parity to ship.

**Comment by aweary** [comment]
This change is already in master too btw, so you may have already been testing with it.

**Comment by gaearon** [comment]
Oooh. I didn’t realize this was against `15-dev`, sorry.
Then Fiber parity doesn’t matter that much I guess.

**Comment by jquense** [comment]
the meat of this is already in and functions with v16, so it should be ok? 

If the event marshaling bit here (the code on top of #5746) is a problem for fiber we can _remove_ it. It is convenient but not really needed except to prevent a small but technically breaking change in tests.

**Comment by gaearon** [comment]
I wonder why CI is failing. Could you rebase? Might be the old version of `15` branch.

**Comment by sebmarkbage** [comment]
Why is it important to have the getter/setter on the `.value`/`.checked` properties? Couldn't we just compare it to React's internal state of the prop?

Is it that you want to protect against manual mutation of the value? What scenario does that happen that is common enough to warrant this?

My concern is that the input value tracker code is:

- Rather big and we'll want to address file size by minimizing code of little used features.
- Complex so it's kind of difficult to follow along and be sure that everything is covered.
- There are attach/detach phases which is not great for Fiber because we explicitly don't have a clean up phase for DOM nodes in most cases and instead rely on GC.
- It can probably be slow to do all that object property descriptor stuff on critical paths like initialization.

I wonder if we could sacrifice one of the edge cases for a smaller solution that only compares to the internal state of the React prop?

**Comment by jquense** [comment]
@sebmarkbage the orginal PR https://github.com/facebook/react/pull/5746 covers the reasons why in a lot more detail, but you can will miss updates in certain cases, which is much worse than the original problem of getting to many updates.

Much of the code could be simplified if we didn't support changing the value via javascript (or outside react) but that's probably not feasible. There are a ton of edge cases related to autofill, interop with password managers, analyitics, etc. 

**again this code has already been reviewed and in master for almost year** this is merely a backport to a lot of fix edge cases caused by earlier attempts to fix these problems

**Comment by nhunzaker** [comment]
> There are a ton of edge cases related to autofill, interop with password managers, analytics, etc.

I mean no criticism here, but I would love to get more specific about these challenges. I hit some ambiguity with these issues when addressing number inputs #7359. I think it would be a huge win if we could setup some fixtures with specific test instructions. I'd certainly like to better understand the problem.

**Comment by jquense** [comment]
> I would love to get more specific about these challenges

sure, me too, and I think we've started on down that road! Just noting that there is a long history of supporting the "change value from javascript" input case that far far pre-dates my involvement in React :P

**Comment by dangonzo** [comment]
can you help me submit 

Sent from my iPhone Dan 

On Jan 31, 2017, at 12:14 PM, Jason Quense <notifications@github.com> wrote:

I would love to get more specific about these challenges

sure, me too, and I think we've started on down that road! Just noting that there is a long history of supporting the "change value from javascript" input case that far far pre-dates my involvement in React :P

**Comment by sebmarkbage** [comment]
@jquense Sorry, I should clarify the reason for this ad-hoc review. A big push from us after Fiber is likely going to be minimizing code size of the DOM integration. As part of that we may need to make some compromises on what we can support and make some breaking changes as a result.

Since this fix was never released it would be easier to address this first.

**Comment by jquense** [comment]
Ya I'm definitely on board with simplifying the code base, and understand the caution here :) I'm happy to talk about the constraints and reasons for this change. I will say tho that I'm not the best person to defend those constraints since they predate me. I wouldn't feel comfortable quantifying the cost of removing the "support imperative value changes" invariant. Personally tho I'd like to see it go, if possible. It is the cause of a lot of complexity in the change plugin. that said password managers are the first thing that comes to mind as a reason to keep it

**Comment by gaearon** [comment]
IMO supporting password managers and autofill is pretty important. I remember having issues with those in React projects.

**Comment by jquense** [comment]
Some more context as well. My first pass at this fix was much simpler (https://github.com/facebook/react/pull/4051) but ended up breaking as many edge cases as it fixed (ugh the DOM). So this is were we landed for a robust fix.

Also, a bit unrelated, but a lot of the ChangePlugin code is ie8/9 code. If we were ok with edge cases for ie9 you'd gain back a lot of ground that way

**Comment by bvaughn** [comment]
> Also, a bit unrelated, but a lot of the ChangePlugin code is ie8/9 code. If we were ok with edge cases for ie9 you'd gain back a lot of ground that way

ReactDOM officially stopped supporting IE8 with v15. IMO it's a good idea to remove any IE8-specific hacks going forward, especially if they greatly simplify parts of the codebase, like `ChangeEventPlugin`.

**Comment by aweary** [comment]
So coming back to this, where does everybody stand on getting this merged? I understand we want to simplify the codebase, but this is already in master FWIW so I think it would make sense to release sooner than later, since otherwise it will be released in the next major which already has significant changes.

**Comment by gaearon** [comment]
>but this is already in master FWIW so I think it would make sense to release sooner than later

The concern is here:

>Since this fix was never released it would be easier to address this first. As opposed to releasing a fix now only to undo some of it later.

The landscape has changed quite a bit in the past year, and a lot of people would prefer `react-dom` to be smaller than covering more browser normalization surface. We are already exploring some file size optimization techniques, and it is likely rethinking our approach to DOM polyfills will be the next step. As such, we’re wary of including this in 15 if we’re not sure whether we’re going to break it again in 16 or not.

This is still on our radar, and we’ll come back to this after the ReactConf.

**Comment by jquense** [comment]
this is mostly a bug fix tho, not a feature. for many people v15 is broken for Internet Explorer when using inputs. 

again there is no breaking change. this backcourt demonstrates that's its not a breaking change, and removing it wouldn't be either. there was only one potentially breaking change and that was related to simulateNative in test utils, not core. 

the alternative is that folks are stuck with a set of inputs that don't work on even modern IE/edge

**Comment by jquense** [comment]
sorry for the quick comments (on a phone),but I think the problem here is that while context has changed it also keeps getting lost as a consequence of the long time to ship on this. 

the only reason this code isn't already in React since 15.0.0 is the 3 additional lines of code this PR adds on top of the original PR. that small change here makes a tiny breaking change on the edges not exist.

im all for reevaluating the DOM polyfills but removing any of them is going to be a huge breaking change and this smoothing over doesn't make that any worse, considering how far off the react onChange event is from the native one. 

in the meantime tho folks are feeling real pain in using react with stuff just not working on major browsers. I totally appreciate not painting oneself into a corner on apis, I'm also trying to speak up a bit for the folks that just gotta make stuff work and the value of shipping bug fixes admit the larger conversations about scope and direction.

**Comment by syranide** [comment]
> We are already exploring some file size optimization techniques, and it is likely rethinking our approach to DOM polyfills will be the next step. As such, we’re wary of including this in 15 if we’re not sure whether we’re going to break it again in 16 or not.

@gaearon As far as I understand it the `onChange` polyfill is rather complicated and not easily done in userspace. Considering how vital it is to controlled components it seems like the most important polyfill in React. Anyway, this is not the right forum for it, but I'm a little bummed that such a gaping issue has been ignored for so long now.

I agree with @jquense on this, this is a bugfix, not a feature. Even if you break it again in v16 I would still consider it a good thing to have it fixed for now.

**Comment by gaearon** [comment]
We’ll be discussing this after the conf, when we start preparing for 15.5 and 16.

**Comment by slorber** [comment]
Hi,

This fix is waited for a long time and affects a lot of users. Lib providers like [react-contenteditable](https://github.com/lovasoa/react-contenteditable/issues/43) can't easily address this.

Personnally, on the tech side, I'm excited for React Fiber, but in term of business, fixing the onChange has more impact. It's quite frustrating to have broken IE11 features in my app :)

**Comment by nitelite** [comment]
Just wanted to mention that I am in the same boat as @slorber and a whole lot of other users of React 15. We have quite a few corporate users with IE11 that are unable to type reliably in our input boxes right now. I applaud @jquense for bringing up this problem and working towards getting it merged. I am hoping that after being present for months, that we are not somehow closer to getting the 3 lines of code merged.

**Comment by nhunzaker** [comment]
@nitelite @slorber I'm right there with you. Correctness and user experience have to come first. 

@aweary @gaearon I vote we get this in to 15.5. That gives us plenty of time to figure out how to write a less complicated solution with the confidence that existing applications work in IE11 (which is a pretty modest requirement). Especially now that we have a broader set of test fixtures.

From there, we could evaluate simplifying the ChangeEventPlugin code, but I'm curious how many other places we could look first, like dropping IE8 support, checking to see what SyntheticEvent patches could be removed, etc.

**Comment by jquense** [comment]
I'm also in agreement with @syranide that _this_ particular plugin is probably not low hanging fruit for byte savings. Controlled components _deeply_ depend on the behavior here, and much of the React web ecosystem depends on controlled inputs. 

We absolutely should examine everything for places to trim code but (imo) it's a higher priority to make sure major stakeholders are supported and receiving bug fixes, if they are going to trust React for projects.

**Comment by sebmarkbage** [comment]
I'm going to prioritize working on an alternative fix for this next week. Does anyone have ideas of an alternative, smaller, fix that uses less getter/setter overhead?

I'm a bit disappointed that we haven't seen an alternative approach. One thing I've noticed at FB and elsewhere is a pattern where when one solution exists, we stop looking for others and pile on against any pushback. I don't expect @jquense to put more work into this after already putting a lot of hard work into this but we shouldn't collectively stop exploring.

Any individual change isn't going to be "significant". The only way to address the file size and perf issues is to push back on everything and find the minimal solution.

**Comment by jquense** [comment]
With all due respect, the solutions here aren't just the first thing we all thought of. They are the result of talking with a bunch of folks, including FB ppl. I **personally** put forward 3 PR's of varying complexity and scope. Had calls with @jimfb, and talked through a bunch of approaches (to the extent I could get answers) with @spicyj 

I don't appreciate having the work me and many others have done over the past **two years** on this is be dismissed off hand, as if this was just the first thing we hacked together. 

The main reason why you don't see "alternative approaches" and it's because the pace of review and feedback from core team members is so slow and limited it actually takes years to bikeshed and evolve a single attempt.

**Comment by sebmarkbage** [comment]
Yea, sorry I didn't mean to imply it was a first attempt. I know that there was a lot of conversations involved, several iterations and that the core team didn't agree on direction neither.

**Comment by jquense** [comment]
I am still not sure if anyone knows the actual context for how we got here over the last 2 years so I'm summarize again, in hopes that new solutions don't retread the same bad paths. And someone fixes this. 

- In the beginning React was wildly inconsistent with firing the onChange event. Range inputs, checkboxes, etc, all fired `onChange` events to often, or at weird times. Placeholder changes, for instance triggered a change in IE11+

- An intrepid but naive developer tried to address some of these issues with: https://github.com/facebook/react/pull/4051 but that only created more issues (linked above) and no tests, or the internal FB test suite caught them.

- Next we tried https://github.com/facebook/react/pull/5746 which more robustly covers the use cases while maintaining the various invariants that value but that broken a small edge case in the test utils

- here we are.

I hope ya'll can come up with a better option. I'm pretty tired of being the obscure input bug champion for React, and this experience has been super off-putting overall. Please someone fix the dang event system so that more than 3 people understand it.

**Comment by nhunzaker** [comment]
>  I'm pretty tired of being the obscure input bug champion for React

Hey I thought that was becoming my job :P

But I agree. Controlled inputs are an extremely complicated, error-prone, edge-case ridden feature. There is so much collective knowledge you must know about DOM inputs, the event system, the React event system, and how they vary by browser. It makes contributing extremely difficult, I can only really make meaningful contributions having worked casually on this part of React for 2 years.

Fiber has commanded a lot of attention, and I think it's ground breaking work, but I'm really looking forward to when the team can focus that brain-power on this (I'm happy to help). 

What can we do, be it code, documentation, or otherwise, to improve this?

**Comment by nitelite** [comment]
Am I correct in assuming that this did not manage to make it into 15.5?

**Comment by bvaughn** [comment]
Correct. This PR hasn't been merged and didn't belong to the 15-hipri milestone.

**Comment by mbrookes** [comment]
@sebmarkbage How's the alternative implementation [you've been working on](https://github.com/facebook/react/pull/8575#issuecomment-290170603) coming along? 

Disappointing that this fix or your alternative didn't make it into 15.5.x. @gaearon What was the outcome of your [discussion](https://github.com/facebook/react/pull/8575#issuecomment-284392747)?

**Comment by gaearon** [comment]
The outcome is @sebmarkbage is going to work on this. I’m sorry but we’re split very thin right now with all the work preparing 15.5 and 16, and putting out fires. So sometimes we say “next week” and it ends up a few weeks later.

**Comment by mbrookes** [comment]
> and putting out fires

Yes, thanks for jumping those so quickly, especially over the weekend. 

No more big releases on a Friday? 😄

**Comment by gaearon** [comment]
Hell no. 😅

**Comment by flarnie** [comment]
Just a heads up - we are still hoping to find a solution here, and appreciate everyone's hard work on this issue. I am in the middle of some other work but will ping the rest of the team and either me or someone else will get back to this in the next couple of weeks.

**Comment by sebmarkbage** [comment]
We're going to merge this into the release of 15.6. We really should've done this way early. I apologize for that. We didn't fully understand the consequences but I think I have a good grasp of it now.

In the future we will likely stop supporting the use case for a polyfilled `onChange` on uncontrolled components and with use of ref mutation. See https://github.com/facebook/react/issues/9657 for more detail. This would allow us to get rid of the value tracking approach in a future version. However, to preserve the existing APIs and fix the relevant issues in 15.x we'll need this approach as identified.

**Comment by flarnie** [comment]
Just tried rebasing this onto 15.6 and the only conflicts seem related to the 'prettier' syntax changes we made on 15.6. 

I'm not sure what the CI failure here is. Going to try and get this merged into 15.6. Thanks everyone for your patience on this PR. :)

**Comment by flarnie** [comment]
Makes sense that 'prettier' is failing, since this was originally made against a branch where prettier was failing. I'll make a separate commit to run 'prettier' after merging this.

File: src/renderers/dom/client/inputValueTracking.js [hunk 1]
```diff
@@ -0,0 +1,133 @@
...
+    // (needed for certain tests that spyOn input values)
+    if (node.hasOwnProperty(valueField)) {
+      return;
+    }
+
+    Object.defineProperty(node, valueField, {
+      enumerable: descriptor.enumerable,
+      configurable: true,
+      get: function() {
+        return descriptor.get.call(this);
```
Comment (gaearon) [inline src/renderers/dom/client/inputValueTracking.js]: This is reported to crash iOS Safari: https://github.com/facebook/react/issues/9956
