### PR TITLE
Fix: Activity should hide portal contents

### LINKED ISSUE #35000: Activity mode=“hidden” does not hide nested portals
React's `<Activity>` component does not hide portals when they are nested under another element. Only direct portal children are hidden, causing inconsistent behavior.

React version: 19.2.0

## Steps To Reproduce

1. Wrap a parent `<div>` inside `<Activity mode="hidden">`
2. Inside that `<div>`, render any regular child and a portal via `createPortal(...)`
3. Observe: regular child is hidden but the portal remains visible
4. Remove the additional wrapper and observe that the portal is now hidden correctly

Link to code example: https://codesandbox.io/p/sandbox/hwt3pl

Minimal reproduction:

```jsx
import { createPortal } from "react-dom";
import { Activity } from "react";

export default function App() {
  return (
    <Activity mode="hidden">
      <div>
        <h1>Hello</h1>
        {createPortal(<p>Portal child (should be hidden)</p>, document.body)}
      </div>
    </Activity>
  );
}
```

## The current behavior

Portals nested within another element inside  remain visible when Activity is in “hidden” mode.

## The expected behavior

All children of an element, including portals nested at any depth, should be hidden and restored consistently when using “hidden” mode.

---

## Notes

Not sure if this is a bug or expected behavior, though. But I feel like we should either find a way to hide the portal or update the docs to mention this on the "unwanted side effects" section. Thoughts?

### PR DESCRIPTION
**Pull request by acdlite**
Fixes https://github.com/facebook/react/issues/35000

This PR updates the behavior of Activity so that when it is hidden, it hides the contents of any portals contained within it.

Previously we had intentionally chosen not to implement this behavior, because it was thought that this concern should be left to the userspace code that manages the portal, e.g. by adding or removing the portal container from the DOM. Depending on the use case for the portal, this is often desirable anyway because the portal container itself is not controlled by React.

However, React does own the _contents_ of the portal, and we can hide those elements regardless of what the user chooses to do with the container. This makes the hiding/unhiding behavior of portals with Activity automatic in the majority of cases, and also benefits from aligning the DOM mutations with the rest of the React's commit phase lifecycle.

The reason we have to special case this at all is because usually we only hide the direct DOM children of the Activity boundary. There's no reason to go deeper than that, because hiding a parent DOM element effectively hides everything inside of it. Portals are the exception, because they don't exist in the normal DOM hierarchy; we can't assume that just because a portal has a parent in the React tree that it will also have that parent in the actual DOM.

So, whenever an Activity boundary is hidden, we must search for and hide _any_ portal that is contained within it, and recursively hide its direct children, too.

To optimize this search, we use a new subtree flag, PortalStatic, that is set only on fiber paths that contain a HostPortal. This lets us skip over any subtree that does not contain a portal.

### CODE REVIEW

File: packages/react-reconciler/src/ReactFiberCommitWork.js [hunk 1]
```diff
@@ -1182,66 +1183,105 @@ function commitTransitionProgress(offscreenFiber: Fiber) {
...
-        (node.memoizedState: OffscreenState) !== null &&
-        node !== finishedWork
-      ) {
+function hideOrUnhideAllChildrenOnFiber(fiber: Fiber, isHidden: boolean) {
+  if (!supportsMutation) {
+    return;
+  }
+  switch (fiber.tag) {
+    case HostComponent:
+    case HostHoistable: {
```
Comment (rickhanlonii) [inline packages/react-reconciler/src/ReactFiberCommitWork.js:1205]: Before we were only doing the HostHoistable when `supportsResources` was true, is that still needed (not sure why it was there)?

File: packages/react-reconciler/src/ReactFiberCommitWork.js [hunk 2]
```diff
@@ -1182,66 +1183,105 @@ function commitTransitionProgress(offscreenFiber: Fiber) {
...
-        if (hostSubtreeRoot === null) {
-          commitShowHideSuspenseBoundary(node, isHidden);
-        }
-      } else if (
-        (node.tag === OffscreenComponent ||
-          node.tag === LegacyHiddenComponent) &&
-        (node.memoizedState: OffscreenState) !== null &&
-        node !== finishedWork
-      ) {
+function hideOrUnhideAllChildrenOnFiber(fiber: Fiber, isHidden: boolean) {
```
Comment (rickhanlonii) [inline packages/react-reconciler/src/ReactFiberCommitWork.js:1199]: Do you know why the old code tracked the `hostSubtreeRoot`? tbh the old code doesn't make sense to me, and the new code is very clean but it's hard to know if there are subtle bugs.

File: packages/react-reconciler/src/ReactFiberCommitWork.js [hunk 3]
```diff
@@ -1182,66 +1183,105 @@ function commitTransitionProgress(offscreenFiber: Fiber) {
...
+      return;
+    }
+    case DehydratedFragment: {
+      commitShowHideSuspenseBoundary(fiber, isHidden);
+      return;
+    }
+    case OffscreenComponent:
+    case LegacyHiddenComponent: {
+      const offscreenState: OffscreenState | null = fiber.memoizedState;
+      if (offscreenState !== null) {
```
Comment (rickhanlonii) [inline packages/react-reconciler/src/ReactFiberCommitWork.js:1232]: This had a `node !== finishedWork` check before? Not sure why?

File: packages/react-reconciler/src/ReactFiberCommitWork.js [hunk 4]
```diff
@@ -1182,66 +1183,105 @@ function commitTransitionProgress(offscreenFiber: Fiber) {
...
+  }
+  switch (fiber.tag) {
+    case HostPortal: {
+      // Found a portal. Switch back to the normal hide/unhide algorithm to
+      // toggle the visibility of its children.
+      hideOrUnhideAllChildrenOnFiber(fiber, isHidden);
+      return;
+    }
+    case OffscreenComponent:
+    case LegacyHiddenComponent: {
```
Comment (rickhanlonii) [inline packages/react-reconciler/src/ReactFiberCommitWork.js]: Could we omit `LegacyHidden` from this? Want to limit the risk of breaking changes and if they need this feature they should convert to Activity.

**Review by rickhanlonii — APPROVED** [review]
Looks good, could we add a test? Also seems risky, is it ok to revert if it breaks the sync or could we add a killswitch for the meta builds?

File: packages/react-reconciler/src/ReactFiberCommitWork.js (hunk 1 above)
Comment (acdlite) [reply packages/react-reconciler/src/ReactFiberCommitWork.js:1205]: I think it was just the dead code eliminate the tag check, not really necessary since it’s all the same code as for HostComponent. Seems to match what we do in the other functions in this file.

**Comment by acdlite** [comment]
Yeah I wrote some tests just forgot to stage the file

File: packages/react-reconciler/src/ReactFiberCommitWork.js (hunk 3 above)
Comment (acdlite) [reply packages/react-reconciler/src/ReactFiberCommitWork.js:1232]: It was to prevent the traversal from going deeper than the nearest host components, which is now solved via recursion instead

File: packages/react-reconciler/src/ReactFiberCommitWork.js (hunk 2 above)
Comment (acdlite) [reply packages/react-reconciler/src/ReactFiberCommitWork.js:1199]: It was to prevent the traversal from going deeper than the nearest host components, which is now solved via recursion instead

I put the conversion from iterative loop to recursion in its own commit

**Comment by acdlite** [comment]
and yes you can revert if it breaks the Meta sync. Assuming it's due to a bug rather than due to the intentional behavior change. If something is relying on the portal not being hidden then I'd prefer not the revert and we should find some other solution for whatever that code is trying to do. (We could revert with a Meta-only flag in the meantime.)

**Comment by ziyak97** [comment]
Is this already out? Will this fix - https://github.com/vercel/next.js/discussions/85502#discussioncomment-15397404

If it’s not out any ETA

**Comment by abed-daloopa** [comment]
When will this be released?
