### PR TITLE
Fix switching between dangerouslySetInnerHTML and children

### LINKED ISSUE #1232: Switching from dangerouslySetInnerHTML to children
I tripped on a strange error when, in one state, a component uses HTML to specify children (from rendering Markdown) and in another state it uses child components (for interactive content, itself with some inner HTML). I reduced the testcase down to this: http://jsfiddle.net/BCp36/1/

### PR DESCRIPTION
**Pull request by spicyj**
With this, ReactMultiChild handles all of the children-related operations for ReactDOMComponent so that we don't process operations out of order. This is necessary because ReactMultiChild does its own batching so there's no way without its cooperation to get the timing right here.

Ideally we'll factor this logic out a bit better in subsequent updates but this is the simplest way to fix #1232 which has embarrassingly been open for over a year.

### CODE REVIEW

File: src/renderers/dom/client/utils/DOMChildrenOperations.js [hunk 1]
```diff
@@ -123,10 +124,16 @@ var DOMChildrenOperations = {
             update.toIndex
           );
           break;
+        case ReactMultiChildUpdateTypes.SET_MARKUP:
```
Comment (zpao) [inline src/renderers/dom/client/utils/DOMChildrenOperations.js]: I think we need to add `SET_MARKUP` to `ReactMultiChildUpdateTypes` :wink:

Comment (spicyj) [inline src/renderers/dom/client/utils/DOMChildrenOperations.js]: Done.
