### PR TITLE
DevTools: Replaced WeakMap with LRU for inspected element cache

### LINKED ISSUE #22099: [DevTools Bug] Could not inspect element with id "1335"
### Website or app

Web app we are developing for a client.

### Repro steps

Open the components tab - no components will display
Close the components tab
Open the components tab again, this time the the components show but the error shows on the right pane.

### How often does this bug happen?

Often

### DevTools package (automated)

react-devtools-extensions

### DevTools version (automated)

4.14.0-d0ec283819

### Error message (automated)

Could not inspect element with id "1335"

### Error call stack (automated)

_No response_

### Error component stack (automated)

```text
InspectedElementContextController@testErrorStack.js:109842:43
Suspense
ErrorBoundary_ErrorBoundary@testErrorStack.js:108452:5
div
InspectedElementErrorBoundaryWrapper@testErrorStack.js:108838:46
NativeStyleContextController@testErrorStack.js:111206:38
div
div
OwnersListContextController@testErrorStack.js:106680:37
SettingsModalContextController@testErrorStack.js:107121:40
Components_Components@testErrorStack.js:113123:52
ErrorBoundary_ErrorBoundary@testErrorStack.js:108452:5
PortaledContent@testErrorStack.js:108571:34
div
div
ProfilerContextController@testErrorStack.js:112748:35
TreeContextController@testErrorStack.js:103336:31
SettingsContextController@testErrorStack.js:103939:35
ModalDialogContextController@testErrorStack.js:108901:38
DevTools_DevTools@testErrorStack.js:115897:27
```

### GitHub query string (automated)

```text
https://api.github.com/search/issues?q=Could not inspect element with id  in:title is:issue is:open is:public label:"Component: Developer Tools" repo:facebook/react
```

### PR DESCRIPTION
**Pull request by bvaughn**
We use an LRU for this rather than a WeakMap because of how the "no-change" optimization works.

When the frontend polls the backend for an update on the element that's currently inspected, the backend will send a "no-change" message if the element hasn't updated (rendered) since the last time it was asked. In this case, the frontend cache should reuse the previous (cached) value. Using a WeakMap keyed on Element generally works well for this, since Elements are mutable and stable in the Store. This doesn't work properly though when component filters are changed, because this will cause the Store to dump all roots and re-initialize the tree (recreating the Element objects).

So instead we key on Element ID (which is stable in this case) and use an LRU for eviction.

Resolves #22099

### CODE REVIEW

**Review by lunaruan — APPROVED** [review]
Yay you figured it out!

File: packages/react-devtools-shared/src/__tests__/inspectedElement-test.js [hunk 1]
```diff
@@ -1895,6 +1895,60 @@ describe('InspectedElement', () => {
...
+    // to read the TreeDispatcherContext and update the selected ID that way.
+    // We're testing the inspected values here, not the context wiring, so that's ok.
+    testRendererInstance = TestRenderer.create(null, {
+      unstable_isConcurrent: true,
+    });
+
+    // Select/inspect the same element again
+    inspectedElement = await inspectElementAtIndex(0);
+    expect(inspectedElement).toMatchInlineSnapshot(`
+      Object {
```
Comment (jstejada) [inline packages/react-devtools-shared/src/__tests__/inspectedElement-test.js:1940]: just cuirious, what part of this snapshot is the relevant assertion here? what was the result before?

File: packages/react-devtools-shared/src/inspectedElementMutableSource.js [hunk 2]
```diff
@@ -25,15 +27,21 @@ import type {
...
-// Both this map and the inspected objects in it are mutable.
-// They should never be read from directly during render;
-// Use a Suspense cache to ensure that transitions work correctly and there is no tearing.
-const inspectedElementMap: WeakMap<
-  Element,
+// Maps element ID to inspected data.
+// We use an LRU for this rather than a WeakMap because of how the "no-change" optimization works.
+// When the frontend polls the backend for an update on the element that's currently inspected,
+// the backend will send a "no-change" message if the element hasn't updated (rendered) since the last time it was asked.
+// In thid case, the frontend cache should reuse the previous (cached) value.
```
Comment (jstejada) [inline packages/react-devtools-shared/src/inspectedElementMutableSource.js:34]: this* case

File: packages/react-devtools-shared/src/inspectedElementMutableSource.js [hunk 3]
```diff
@@ -25,15 +27,21 @@ import type {
...
+// Using a WeakMap keyed on Element generally works well for this, since Elements are mutable and stable in the Store.
+// This doens't work properly though when component filters are changed,
+// because this will cause the Store to dump all roots and re-initialize the tree (recreating the Element objects).
+// So instead we key on Element ID (which is stable in this case) and use an LRU for eviction.
+const inspectedElementCache: LRUCache<
+  number,
   InspectedElementFrontend,
-> = new WeakMap();
+> = new LRU({
+  max: 25,
```
Comment (jstejada) [inline packages/react-devtools-shared/src/inspectedElementMutableSource.js:43]: why only a max of 25?

**Review by jstejada — COMMENTED** [review]
late to the party, but this is sweet! just had a few questions

File: packages/react-devtools-shared/src/__tests__/inspectedElement-test.js [hunk 4]
```diff
@@ -1895,6 +1895,60 @@ describe('InspectedElement', () => {
...
+        "hooks": null,
+        "id": 2,
+        "owners": null,
+        "props": Object {},
+        "state": null,
+      }
+    `);
+
+    await utils.actAsync(async () => {
+      // Ignore transient warning this causes
```
[the remark this answers is not in the document]
Comment (bvaughn) [reply packages/react-devtools-shared/src/__tests__/inspectedElement-test.js:1920]: Fair enough.

Basically there's a small period of time where (potentially) the element has been removed from the Store but the UI hasn't yet re-rendered with this knowledge and may query the Store for the element.

File: packages/react-devtools-shared/src/inspectedElementMutableSource.js (hunk 3 above)
Comment (bvaughn) [reply packages/react-devtools-shared/src/inspectedElementMutableSource.js:43]: Arbitrary.

File: packages/react-devtools-shared/src/__tests__/inspectedElement-test.js (hunk 1 above)
Comment (bvaughn) [reply packages/react-devtools-shared/src/__tests__/inspectedElement-test.js:1940]: You can see the same snapshot above.

Really the only thing we _need_ to do is verify that an error isn't thrown (like it was before) but this snapshot assertion goes a step further to verify that we can (re)inspect the same element after filters have changed.
