### PR TITLE
Fix controlled/uncontrolled validation for radio+checkbox inputs

### LINKED ISSUE #6779: Warning is changing a uncontrolled input of type radio to be controlled...
I have this code
```
       <input name='test' value={1} type='radio' />
       <input name='test' value={2} type='radio' defaultChecked />
```
https://jsfiddle.net/69z2wepo/42137/

And when I click on radio it gives me warning
Warning: Test is changing a uncontrolled input of type radio to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-components

So its not clear why or is it a bug ?

### PR DESCRIPTION
**Pull request by jimfb**
Fix controlled/uncontrolled validation for radio+checkbox inputs

Fixes #6779

### CODE REVIEW

**Comment by jimfb** [comment]
cc @spicyj

**Comment by facebook-github-bot-2** [comment]
@jimfb updated the pull request.

File: src/renderers/dom/client/wrappers/ReactDOMInput.js [hunk 1]
```diff
@@ -48,6 +48,11 @@ function warnIfValueIsNull(props) {
   }
 }
 
+function isControlled(props) {
+  return ((props.type === 'checkbox' || props.type === 'radio') && props.checked !== undefined) ||
+    (props.type !== 'checkbox' && props.type !== 'radio' && props.value !== undefined);
+}
```
Comment (spicyj) [inline src/renderers/dom/client/wrappers/ReactDOMInput.js]: This spacing isn't FB style and this would be clearer anyway; can you change it?

```
function isControlled(props) {
  var usesChecked = props.type === 'checkbox' || props.type === 'radio';
  return usesChecked ? props.checked !== undefined : props.value !== undefined;
}
```

**Comment by facebook-github-bot-6** [comment]
@jimfb updated the pull request.

File: src/renderers/dom/client/wrappers/__tests__/ReactDOMInput-test.js [hunk 2]
```diff
@@ -662,6 +662,43 @@ describe('ReactDOMInput', function() {
...
+    ReactDOM.render(<input type="radio" checked={false} onChange={() => null} />, container);
+    ReactDOM.render(
+      <input
+        type="radio"
+        value="value"
+        defaultChecked={true}
+        checked={false}
+        onChange={() => null} 
+      />, container);
+    console.log(console.error.calls.argsFor(0)[0]);
```
Comment (Aweary) [inline src/renderers/dom/client/wrappers/__tests__/ReactDOMInput-test.js]: Did you mean to leave this `console.log` call here? 😃

Comment (jimfb) [inline src/renderers/dom/client/wrappers/__tests__/ReactDOMInput-test.js]: Pssh, thanks.  https://github.com/facebook/react/pull/7006

Comment (jimfb) [inline src/renderers/dom/client/wrappers/__tests__/ReactDOMInput-test.js]: We need a lint rule for that.

**Comment by spicyj** [comment]
semver labels on this and #7006 please?
