### PR TITLE
Warn on missing event handler properties

### LINKED ISSUE #3548: Add warnings on incorrect casing of event handler properties
Hi,

React currently warns about incorrect casing of properties like `tabIndex`.
However, it doesn't warn about this problem on event handlers, like `onKeyDown`.

Being used to the "html way" of writing those attributes, I often wrote something like `onKeydown`. Sadly, attached event handlers were not called, but I didn't get any warning from React, and it took me quite some time to find my mistake.

You can see an example here: http://jsfiddle.net/oj5eec84/.
Just focus on an element, and try to press a key.

### PR DESCRIPTION
**Pull request by ali**
Fixes #3548. Warns on properties that are case-insensitive matches for registered event names (e.g. "onclick" instead of "onClick").

### CODE REVIEW

File: src/renderers/shared/event/EventPluginRegistry.js [hunk 1]
```diff
@@ -265,6 +279,16 @@ var EventPluginRegistry = {
         delete registrationNameModules[registrationName];
       }
     }
+
+    if (__DEV__) {
+      var getPossibleRegistrationName = EventPluginRegistry
```
Comment (spicyj) [inline src/renderers/shared/event/EventPluginRegistry.js]: style nit: Can you break after the equals sign instead of before the dot and indent only two spaces?

File: src/renderers/dom/shared/DOMPropertyOperations.js [hunk 2]
```diff
@@ -87,6 +88,18 @@ if (__DEV__) {
       standardName
     );
 
+    var registrationName = (
```
Comment (spicyj) [inline src/renderers/dom/shared/DOMPropertyOperations.js]: nit: can we format this as

```
    var registrationName =
      EventPluginRegistry.getPossibleRegistrationName.hasOwnProperty(
        lowerCasedName
      ) ?
      EventPluginRegistry.getPossibleRegistrationName[lowerCasedName] :
      null;
```

which is closer to standard FB style.

File: src/renderers/shared/event/EventPluginRegistry.js [hunk 3]
```diff
@@ -128,6 +128,12 @@ function publishRegistrationName(registrationName, PluginModule, eventName) {
   EventPluginRegistry.registrationNameModules[registrationName] = PluginModule;
   EventPluginRegistry.registrationNameDependencies[registrationName] =
     PluginModule.eventTypes[eventName].dependencies;
+
+  if (__DEV__) {
+    var lowerCasedName = registrationName.toLowerCase();
+    EventPluginRegistry.getPossibleRegistrationName[lowerCasedName] =
```
Comment (spicyj) [inline src/renderers/shared/event/EventPluginRegistry.js]: `possibleRegistrationNames` is a little shorter and aligns better with the naming of the surrounding code – can we go with that?

**Comment by spicyj** [comment]
Looks good – thanks so much! Just a couple nits inline. If you could fix those and squash your commits, I think this is good to go.

File: src/renderers/dom/shared/DOMPropertyOperations.js (hunk 2 above)
Comment (spicyj) [inline src/renderers/dom/shared/DOMPropertyOperations.js]: (Your parens here are actually unnecessary but this is fine too.)

**Comment by spicyj** [comment]
Looks great, thank you so much!

File: src/renderers/dom/shared/DOMPropertyOperations.js (hunk 2 above)
Comment (ali) [inline src/renderers/dom/shared/DOMPropertyOperations.js]: Fixed, I used the formatting you suggested.

[Line 78][78] seems to hint that I should be indenting the lines after the `?` with two spaces:

```js
var registrationName = (
  EventPluginRegistry.possibleRegistrationNames.hasOwnProperty(
    lowerCasedName
  ) ?
    EventPluginRegistry.possibleRegistrationNames[lowerCasedName] :
    null
);
```

Let me know if you prefer this formatting instead and I'll change it.

[78]: https://github.com/ali/react/blob/9ad4be0316d36e446eabd280f680a1b8632323c5/src/renderers/dom/shared/DOMPropertyOperations.js#L78

**Comment by ali** [comment]
Happy to, thanks for taking the time to review my change!

File: src/renderers/dom/shared/DOMPropertyOperations.js (hunk 2 above)
Comment (spicyj) [inline src/renderers/dom/shared/DOMPropertyOperations.js]: Eh, I suppose either would be fine. I merged it already though. :)
