### PR TITLE
[DevTools] fix useDeferredValue to match reconciler change

### LINKED ISSUE #24623: [DevTools Bug] When inspecting, hook values after `useDeferredValue` are offset
### Website or app

https://github.com/Alduino/React-useDeferredValue-DevTools-Reprod

### Repro steps

1. Start the app in either dev or production mode.
2. Open the React dev tools
3. Click on the "App" component
4. The first Memo has the value `3.14` (the value that the second Memo should have) instead of `1.41`

If you want it to throw an error instead of just looking at the values, you can set `window.throwIfIncorrect = true` before DevTools inspects the component.

I tried in CodeSandbox's embedded React dev tools as well - the issue happens in React 18.0 (though the first hook has no value and the second has the first hook's value) but it doesn't happen in 18.1.

### How often does this bug happen?

Every time

### DevTools package (automated)

react-devtools-extensions

### DevTools version (automated)

4.24.0-82762bea5

### Error message (automated)

First is 3.14 when it should be 1.41

### Error call stack (automated)

```text
I@moz-extension://38b0497f-37d9-49e7-9147-393888469493/build/react_devtools_backend.js:14022:6
exports.inspectHooksOfFiber@moz-extension://38b0497f-37d9-49e7-9147-393888469493/build/react_devtools_backend.js:14090:12
inspectElementRaw@moz-extension://38b0497f-37d9-49e7-9147-393888469493/build/react_devtools_backend.js:8847:65
inspectElement@moz-extension://38b0497f-37d9-49e7-9147-393888469493/build/react_devtools_backend.js:9130:38
agent_Agent/<@moz-extension://38b0497f-37d9-49e7-9147-393888469493/build/react_devtools_backend.js:11002:56
emit@moz-extension://38b0497f-37d9-49e7-9147-393888469493/build/react_devtools_backend.js:4137:18
Bridge/this._wallUnlisten<@moz-extension://38b0497f-37d9-49e7-9147-393888469493/build/react_devtools_backend.js:4780:14
listener@moz-extension://38b0497f-37d9-49e7-9147-393888469493/build/react_devtools_backend.js:12986:11
EventListener.handleEvent*listen@moz-extension://38b0497f-37d9-49e7-9147-393888469493/build/react_devtools_backend.js:12989:14
Bridge@moz-extension://38b0497f-37d9-49e7-9147-393888469493/build/react_devtools_backend.js:4778:31
setup@moz-extension://38b0497f-37d9-49e7-9147-393888469493/build/react_devtools_backend.js:12979:18
welcome@moz-extension://38b0497f-37d9-49e7-9147-393888469493/build/react_devtools_backend.js:12958:8
EventListener.handleEvent*@moz-extension://38b0497f-37d9-49e7-9147-393888469493/build/react_devtools_backend.js:12961:8
__webpack_require__@moz-extension://38b0497f-37d9-49e7-9147-393888469493/build/react_devtools_backend.js:20:30
@moz-extension://38b0497f-37d9-49e7-9147-393888469493/build/react_devtools_backend.js:84:18
@moz-extension://38b0497f-37d9-49e7-9147-393888469493/build/react_devtools_backend.js:87:10
```

### Error component stack (automated)

```text
InspectedElementContextController@moz-extension://38b0497f-37d9-49e7-9147-393888469493/build/main.js:39159:43
Suspense
ErrorBoundary_ErrorBoundary@moz-extension://38b0497f-37d9-49e7-9147-393888469493/build/main.js:37513:5
div
InspectedElementErrorBoundaryWrapper@moz-extension://38b0497f-37d9-49e7-9147-393888469493/build/main.js:38001:46
NativeStyleContextController@moz-extension://38b0497f-37d9-49e7-9147-393888469493/build/main.js:40650:38
div
div
OwnersListContextController@moz-extension://38b0497f-37d9-49e7-9147-393888469493/build/main.js:33491:37
SettingsModalContextController@moz-extension://38b0497f-37d9-49e7-9147-393888469493/build/main.js:36112:40
Components_Components@moz-extension://38b0497f-37d9-49e7-9147-393888469493/build/main.js:42701:52
ErrorBoundary_ErrorBoundary@moz-extension://38b0497f-37d9-49e7-9147-393888469493/build/main.js:37513:5
div
div
ThemeProvider@moz-extension://38b0497f-37d9-49e7-9147-393888469493/build/main.js:37655:23
PortaledContent@moz-extension://38b0497f-37d9-49e7-9147-393888469493/build/main.js:37685:34
div
div
div
ThemeProvider@moz-extension://38b0497f-37d9-49e7-9147-393888469493/build/main.js:37655:23
TimelineContextController@moz-extension://38b0497f-37d9-49e7-9147-393888469493/build/main.js:42881:35
ProfilerContextController@moz-extension://38b0497f-37d9-49e7-9147-393888469493/build/main.js:42326:35
TreeContextController@moz-extension://38b0497f-37d9-49e7-9147-393888469493/build/main.js:30393:31
SettingsContextController@moz-extension://38b0497f-37d9-49e7-9147-393888469493/build/main.js:31015:35
ModalDialogContextController@moz-extension://38b0497f-37d9-49e7-9147-393888469493/build/main.js:38064:38
DevTools_DevTools@moz-extension://38b0497f-37d9-49e7-9147-393888469493/build/main.js:54073:27
```

### GitHub query string (automated)

```text
https://api.github.com/search/issues?q=First is 3.14 when it should be 1.41 in:title is:issue is:open is:public label:"Component: Developer Tools" repo:facebook/react
```

### PR DESCRIPTION
**Pull request by mondaychen**
## Summary

resolves #24623

According to #24247 the original implementation only existed for a few days (18.0.0), so we'll stick to the new one

## How did you test this change?

Tested by adding `useDeferredValue('');` in List.js in react-devtools-shell

### CODE REVIEW

File: packages/react-debug-tools/src/ReactDebugHooks.js [hunk 1]
```diff
@@ -310,15 +310,11 @@ function useTransition(): [
...
-  // Advance the current hook index the same number of times
-  // so that subsequent hooks have the right memoized state.
-  nextHook(); // State
-  nextHook(); // Effect
+  const hook = nextHook();
   hookLog.push({
     primitive: 'DeferredValue',
     stackError: new Error(),
-    value,
+    value: hook !== null ? hook.memoizedState[0] : value,
```
Comment (lunaruan) [inline packages/react-debug-tools/src/ReactDebugHooks.js:317]: Should this just be `hook.memoizedState`?

**Comment by lunaruan** [comment]
@mondaychen Can you add a test to address Andrew's comments in this PR? 😊

**Comment by mondaychen** [comment]
OK I've updated a test, when running with the old code, you get the following error:
```
● ReactHooksInspectionIntegration › should support useDeferredValue hook

    expect(received).toEqual(expected) // deep equality

    - Expected  - 1
    + Received  + 1

    @@ -9,11 +9,11 @@
        Object {
          "id": 1,
          "isStateEditable": false,
          "name": "Memo",
          "subHooks": Array [],
    -     "value": 1,
    +     "value": 2,
        },
        Object {
          "id": 2,
          "isStateEditable": false,
          "name": "Memo",

      582 |     const childFiber = renderer.root.findByType(Foo)._currentFiber();
      583 |     const tree = ReactDebugTools.inspectHooksOfFiber(childFiber);
    > 584 |     expect(tree).toEqual([
          |                  ^
      585 |       {
      586 |         id: 0,
      587 |         isStateEditable: false,

      at Object.<anonymous> (packages/react-debug-tools/src/__tests__/ReactHooksInspectionIntegration-test.js:584:18)
```

This is because calling `nextHook` twice will cause the first `memo` to be reading second `memo`

With new code it should pass.

**Comment by mondaychen** [comment]
Another way to expose the issue more quickly, is that whenever we get a `null` from `nextHook()`, we just throw since it's not expected. Would that be too aggressive and might cause other issues?

**Review by lunaruan — APPROVED** [review]
