### PR TITLE
Extend input type check in selection capabilities (#12062)

### LINKED ISSUE #12062: Problem when input type changes from email to text
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When an input field changes from "email" to "text", an exception TypeError will be thrown from setSelection.
Screenshot

**Reproduction**
See here: https://github.com/adrianimboden/react-bug-reproduction

**What is the expected behavior?**
It should not crash because of an uncaught exception

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
master (https://github.com/facebook/react/commit/4ca7855ca062d5d7dfca83c86acf46731e1e57ef)
Firefox

This would be my proposed change to fix the issue: https://github.com/adrianimboden/react/commit/db923b8c3c1cb23ad9fb150c160ce56f39dd3cae

### PR DESCRIPTION
**Pull request by spirosikmd**
`restoreSelection` did not account for input elements that have changed
type after the commit phase. The new `text` input supported selection
but the old `email` did not and `setSelection` was incorrectly trying to
restore `null` selection state.

We also extend input type check in selection capabilities to cover cases
where input type is `search`, `tel`, `url`, or `password`.

Fix #12062

### CODE REVIEW

File: fixtures/dom/src/components/fixtures/text-inputs/index.js [hunk 1]
```diff
@@ -110,6 +114,37 @@ class TextInputFixtures extends React.Component {
           <InputTestCase type="url" defaultValue="" />
         </TestCase>
 
+        <TestCase
```
Comment (aweary) [inline fixtures/dom/src/components/fixtures/text-inputs/index.js]: For new test cases that are stateful, can you break it out into it's own component? See [NumberInputExtraZeroes.js](https://github.com/facebook/react/blob/master/fixtures/dom/src/components/fixtures/number-inputs/NumberInputExtraZeroes.js) as an example.

File: packages/react-dom/src/client/ReactInputSelection.js [hunk 2]
```diff
@@ -26,7 +26,8 @@ export function hasSelectionCapabilities(elem) {
   const nodeName = elem && elem.nodeName && elem.nodeName.toLowerCase();
   return (
     nodeName &&
-    ((nodeName === 'input' && elem.type === 'text') ||
+    ((nodeName === 'input' &&
+      ['text', 'email', 'tel'].indexOf(elem.type) >= 0) ||
```
Comment (aweary) [inline packages/react-dom/src/client/ReactInputSelection.js]: Instead of defining an inline array, let's just add some additional cases to the boolean expression. 

```js
(
nodeName === 'input' &&
(elem.type === 'text' || elem.type === 'email' || elem.type === 'tel')
)
```

File: fixtures/dom/src/components/fixtures/text-inputs/index.js (hunk 1 above)
Comment (spirosikmd) [reply fixtures/dom/src/components/fixtures/text-inputs/index.js]: I was in doubt about the implementation. Thanks for the guideline!

**Comment by spirosikmd** [comment]
Hi @aweary! It would be great if you can have another look at this one!

**Comment by spirosikmd** [comment]
Hey @aweary! 

Thank you for the tip! I added the `url` type as well. According to the HTML spec, `url` does have selection capabilities.

Regarding the `scripts/rollup/results.json`. Should I revert my changes to avoid conflicts? Or is it a requirement for each PR to update this file?

**Comment by aweary** [comment]
Thanks @spirosikmd, this looks good to me. I'd like to hear from @nhunzaker and/or @jquense on this as well before merging.

> Regarding the scripts/rollup/results.json. Should I revert my changes to avoid conflicts? Or is it a requirement for each PR to update this file?

You should try rebasing and running the `build` command again, to get an updated report without conflicts.

File: packages/react-dom/src/client/ReactInputSelection.js [hunk 3]
```diff
@@ -26,7 +26,12 @@ export function hasSelectionCapabilities(elem) {
   const nodeName = elem && elem.nodeName && elem.nodeName.toLowerCase();
   return (
     nodeName &&
-    ((nodeName === 'input' && elem.type === 'text') ||
+    ((nodeName === 'input' &&
+      (elem.type === 'text' ||
+        elem.type === 'search' ||
+        elem.type === 'tel' ||
+        elem.type === 'url' ||
+        elem.type === 'password')) ||
```
Comment (nhunzaker) [inline packages/react-dom/src/client/ReactInputSelection.js]: Why is email not in this list?

Comment (nhunzaker) [reply packages/react-dom/src/client/ReactInputSelection.js]: Sorry. That was very blunt! Should `email` be in here? I found a neat table from a spec:
https://html.spec.whatwg.org/multipage/input.html#concept-input-apply

So this matches up with the `setSelectionRange` column? Dang. I really want to know the reasoning behind not supporting this for all text based input. 

Would it be possible to add a comment at the top of this block that references this table for future contributors?

Comment (spirosikmd) [reply packages/react-dom/src/client/ReactInputSelection.js]: I will add a comment containing the link as well. As far as I can see we are only using the [`selectionStart`](https://github.com/facebook/react/blob/master/packages/react-dom/src/client/ReactInputSelection.js#L91) and [`selectionEnd`](https://github.com/facebook/react/blob/master/packages/react-dom/src/client/ReactInputSelection.js#L117) in the code. So I guess we match up with these two rows.

**Comment by react-linter** [comment]
ReactDOM: size: :small_red_triangle:+0.1%, gzip: :small_red_triangle:+0.1%


  <details>
  <summary>Details of bundled changes.</summary>

  <p>Comparing: 5dfbfe9da740398c0a2cf4d897a0085000d06b7b...8296f940705aba4aa0a0564ccb95c85c8461835f</p>


  
## react-dom
File | Filesize Diff | Gzip Diff | Prev Size | Current Size | Prev Gzip | Current Gzip | ENV
 ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  --- 
react-dom.development.js | +0.1% | +0.1% | 609.28 KB | 609.6 KB | 140.41 KB | 140.52 KB | UMD_DEV
**react-dom.production.min.js** | **:small_red_triangle:+0.1%** | **:small_red_triangle:+0.1%** | **100.18 KB** | **100.26 KB** | **31.97 KB** | **31.99 KB** | **UMD_PROD**
react-dom.development.js | +0.1% | +0.1% | 593.65 KB | 593.97 KB | 136.25 KB | 136.37 KB | NODE_DEV
**react-dom.production.min.js** | **:small_red_triangle:+0.1%** | **:small_red_triangle:+0.1%** | **98.64 KB** | **98.72 KB** | **31.11 KB** | **31.13 KB** | **NODE_PROD**
ReactDOM-dev.js | +0.1% | +0.1% | 618.04 KB | 618.42 KB | 139.01 KB | 139.12 KB | FB_DEV
**ReactDOM-prod.js** | **:small_red_triangle:+0.1%** | **:small_red_triangle:+0.1%** | **284.83 KB** | **285.02 KB** | **52.32 KB** | **52.35 KB** | **FB_PROD**

## create-component-with-subscriptions
File | Filesize Diff | Gzip Diff | Prev Size | Current Size | Prev Gzip | Current Gzip | ENV
 ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  --- 
create-component-with-subscriptions.development.js | n/a | n/a | 0 B | 9.7 KB | 0 B | 3 KB | NODE_DEV
**create-component-with-subscriptions.production.min.js** | **n/a** | **n/a** | **0 B** | **3.69 KB** | **0 B** | **1.6 KB** | **NODE_PROD**

  </details>
  
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

File: scripts/rollup/results.json [hunk 4]
```diff
@@ -221,141 +221,99 @@
...
       "packageName": "react-native-renderer",
-      "size": 467421,
-      "gzip": 99671
+      "size": 467747,
+      "gzip": 99762
     },
     {
       "filename": "ReactNativeRenderer-prod.js",
       "bundleType": "RN_PROD",
       "packageName": "react-native-renderer",
```
Comment (gaearon) [inline scripts/rollup/results.json]: Can you please revert this file?

**Comment by spirosikmd** [comment]
Hi @aweary! This should be ready to merge!

**Comment by nhunzaker** [comment]
The requested feedback checks out for me. @aweary what say you?

**Comment by nhunzaker** [comment]
@spirosikmd I'll check in to make sure this is still on the team's radar if we haven't come to consensus by next week.

Thanks for your contribution!

**Comment by nhunzaker** [comment]
This looks great to me. I pushed a commit that adds a reset button to the test fixture so that the test can be run multiple times without refreshing the page. That also covers the inverse case.

I'll wait for CI, then merge.

**Comment by spirosikmd** [comment]
Great! Thank you @nhunzaker!

**Comment by nhunzaker** [comment]
Thanks, @spirosikmd
