### PR TITLE
Ensure sync-xhr is allowed before reload and profile

### LINKED ISSUE #20806: Bug: devtools reload-and-profile feature is defeated by sync-xhr feature policy
React version: all

## Steps To Reproduce

1. Visit a site that uses `Feature-Policy: sync-xhr 'none'` and has the profiling build of react enabled
2. Attempt to use the "reload and start profiling" feature of devtools
3. The xhr request will fail on reload because it [attempts to make a synchronous XHR call](https://github.com/facebook/react/blob/9198a5cec0936a21a5ba194a22fcbac03eba5d1d/packages/react-devtools-extensions/src/injectGlobalHook.js#L84).  The profiling tab will be stuck in "press record to stop recording" state.  Devtools will now fail to load on all subsequent refreshes unless the developer clears session storage, because it keeps trying and failing to make that XHR request.

## The current behavior
see `3.` above

## The expected behavior
Ideally, this feature would not depend on synchronous XHR to function.  [Browsers are deprecating it](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Synchronous_and_Asynchronous_Requests#synchronous_request) and sites are blocking it via `Feature-Policy` due to third-party javascript abusing it.
In its current state, the feature should fail more gracefully when the XHR is blocked due to feature policy or in the future when browsers start blocking it by default.

### PR DESCRIPTION
**Pull request by ChrisDobby**
## Summary

Fixes #20806 
If `document.featurePolicy.allowsFeature('sync-xhr')` returns false a message is displayed when the user first clicks the 'reload and profile' button and the button is then disabled.

## Test Plan

https://user-images.githubusercontent.com/434389/109138228-0c297800-7752-11eb-8ec6-91ed4dc68343.mp4

### CODE REVIEW

File: packages/react-devtools-shared/src/devtools/views/Profiler/ReloadAndProfileButton.js [hunk 1]
```diff
@@ -43,8 +48,20 @@ export default function ReloadAndProfileButton() {
...
+  useEffect(() => {
+    if (!supportsSynchronousXHR) {
+      modalDialogDispatch({
+        type: 'SHOW',
+        content:
+          'Synchronous XHR is required for reload and profile but is disabled on this site.',
+      });
+    }
+  }, [supportsSynchronousXHR, modalDialogDispatch]);
+
```
Comment (bvaughn) [inline packages/react-devtools-shared/src/devtools/views/Profiler/ReloadAndProfileButton.js:64]: Something feels off about the button looking okay until you click it, then showing a "nope doesn't work" message and disabling itself.

I think it would better for us to just disable the button with a different `title` instead.

```js
  const buttonTitle = supportsSynchronousXHR
    ? "Reload and start profiling"
    : "Reload and start profiling has been disabled because synchronous XHR is not supported on this site"
```

What are your thoughts?

Comment (ChrisDobby) [reply packages/react-devtools-shared/src/devtools/views/Profiler/ReloadAndProfileButton.js:64]: I agree it doesn't feel quite right. I originally tried as you suggest but the title doesn't show as a tooltip when the button is disabled.

Comment (bvaughn) [reply packages/react-devtools-shared/src/devtools/views/Profiler/ReloadAndProfileButton.js:64]: Hmm...Could have sworn that titles/tooltips show up for disabled buttons. Oooh, they only show up if you click the disabled button. Maybe that's not the worst thing. Hmm...I think a disabled button is probably still better than a temporarily enabled one like this.

Comment (ChrisDobby) [reply packages/react-devtools-shared/src/devtools/views/Profiler/ReloadAndProfileButton.js]: Makes sense - have updated it to always have the button disabled with the title you suggested above

Comment (bvaughn) [reply packages/react-devtools-shared/src/devtools/views/Profiler/ReloadAndProfileButton.js]: K thanks! I'll likely review this on Friday. Pretty busy this week but I'm trying to sit aside time on Fridays to catch up with DevTools stuff.

File: packages/react-devtools-shared/src/backend/utils.js [hunk 2]
```diff
@@ -183,3 +183,10 @@ export function format(
 
   return '' + formatted;
 }
+
+export function isSynchronousXHRSupported() {
+  return (
+    window.document.featurePolicy &&
```
Comment (bvaughn) [inline packages/react-devtools-shared/src/backend/utils.js:189]: I think `window.document == null` for standalone DevTools, so this could cause an error if we were to ever try enabling reload-and-profile there (which I intend to do as soon as the backend supports it). Can we make this check safer?

Comment (ChrisDobby) [reply packages/react-devtools-shared/src/backend/utils.js:190]: Have added a check for `window.document` being truthy

Comment (bvaughn) [reply packages/react-devtools-shared/src/backend/utils.js:190]: Awesome!

Were you using a specific URL to test the disabled state? (I don't actually know of a website that uses this new header.)

Comment (bvaughn) [reply packages/react-devtools-shared/src/backend/utils.js:190]: Fair enough 😆 I guess I was being lazy. Thanks!

File: packages/react-devtools-shared/src/backend/utils.js [hunk 3]
```diff
@@ -183,3 +183,11 @@ export function format(
...
   return '' + formatted;
 }
+
+export function isSynchronousXHRSupported(): boolean {
+  return (
+    window.document &&
+    window.document.featurePolicy &&
+    window.document.featurePolicy.allowsFeature('sync-xhr')
+  );
+}
```
Comment (bvaughn) [inline packages/react-devtools-shared/src/backend/utils.js:193]: I'm a little surprised Flow didn't complain about this. If `window.document` or `window.document.featurePolicy` aren't defined, this function will return undefined rather than a boolean.

File: packages/react-devtools-shared/src/devtools/store.js [hunk 4]
```diff
@@ -141,6 +142,9 @@ export default class Store extends EventEmitter<{|
   _supportsReloadAndProfile: boolean = false;
   _supportsTraceUpdates: boolean = false;
 
+  // Needed for reload and profile
+  _supportsSynchronousXHR: boolean = false;
```
Comment (bvaughn) [inline packages/react-devtools-shared/src/devtools/store.js:146]: Slightly awkward conflict now with the `_supportsReloadAndProfile` variable above. So `_supportsReloadAndProfile` will be true even if `_supportsSynchronousXHR` is false.

Comment (bvaughn) [reply packages/react-devtools-shared/src/devtools/store.js:146]: Maybe the idea of disabling the button with a tooltip isn't worth it in retro and we should just hide it. Seems odd to return `true` for `supportsReloadAndProfile` even if we know the environment doesn't support it. Okay let me make that change.

**Comment by bvaughn** [comment]
Hm. Why is Flow upset...

**Review by bvaughn — APPROVED** [review]
Sorry for the noise. I should have just made my edits locally instead of using GH for it. Seemed easier at first but ended up being more work.

Thanks for doing this!
