### PR TITLE
Always toLowerCase when comparing nodeName or tagName

### LINKED ISSUE #3960: Controlled components don't work with xml
I have an app that's served as `xml`. Recent react version [supports xml](https://github.com/facebook/react/issues/2278). However, it looks like controlled components are broken. I created a demo 
https://github.com/neojski/random/tree/gh-pages/react-input-xml-error. These are two almost identical pages with one named `xhtml` and the other one `html`. The only difference is:

```diff
1c1
< <html>
---
> <html xmlns="http://www.w3.org/1999/xhtml">
```

On the `xhtml` one input's value may be changed. It's a controlled input that never changes the `state` property so its value shouldn't be mutable. It works as expected on the `html` page.

### PR DESCRIPTION
**Pull request by neojski**
In xml node name casing is exactly the same as the node was originally named.
Make sure to convert node name to upper case before making any node name checks.

Fixes #3960.

---

I searched for `.nodeName` pattern across the code base whilst fixing this. Please have a look at (possibly) similar issues as well before merging this.

In one place I've seen `nodeName.toLowerCase()`. Maybe we want to make that consistent with this change.

I'm not sure how to test this.

### CODE REVIEW

**Comment by neojski** [comment]
Oh, apparently `elem` in (shouldUseChangeEvent)[https://github.com/facebook/react/blob/54e3f12877d3fed985dfcafd4e7afc41211bca14/src/renderers/dom/client/eventPlugins/ChangeEventPlugin.js#L57] sometimes does not have `nodeName` attribute. It is sometimes `Window`. Should I rename `elem` argument to something better and check whether it has `nodeName` attribute?

And still, any ideas as how to test it?

**Comment by neojski** [comment]
I'm not thinking about creating a tiny module `getNodeName`:

```js
function getNodeName(node) {
  if (node && node.nodeName) {
    return node.nodeName.toUpperCase();
  }
  return null;
}
```

And using it instead of `.nodeName`. The only issue I see right now is `validateDOMNesting.js` that's using lower-cased stuff. Should I upper-case it?

File: src/renderers/dom/client/ReactInputSelection.js [hunk 1]
```diff
@@ -31,8 +31,8 @@ var ReactInputSelection = {
 
   hasSelectionCapabilities: function(elem) {
     return elem && (
-      (elem.nodeName === 'INPUT' && elem.type === 'text') ||
-      elem.nodeName === 'TEXTAREA' ||
+      (elem.nodeName.toUpperCase() === 'INPUT' && elem.type === 'text') ||
```
Comment (zpao) [inline src/renderers/dom/client/ReactInputSelection.js]: Might be worth just saving the value of `nodeName.toUpperCase()` so we only call it once (same in the last 2 case below)

**Comment by zpao** [comment]
Seems ok without a helper let's just fix up what I mentioned.

**Comment by spicyj** [comment]
Aesthetically I prefer `.toLowerCase()`… :) Fine either way I guess.

**Comment by neojski** [comment]
I prefer lower case as well. I used upper because right hand sides were already upper cased. I can change that if you wish @spicyj. 

I did the changes @zpao asked about. I also added checks that `nodeName` is truthy so we don't throw in case that method gets something strange (as mentioned in [my previous comment](https://github.com/facebook/react/pull/3984#issuecomment-106862032)).

**Comment by neojski** [comment]
Any news with this @spicyj? Do you want me to do the lower case stuff? Either way it's inconsistent since tests use upper case. Now I think that upper case makes more sense since that's the standard in html. So we can follow that.

**Comment by spicyj** [comment]
@neojski Let's do lower case. I was always bothered by the fact that it was uppercase in these tests. (Yes, `.nodeName` is uppercase, but conventional HTML markup (including XHTML) writes the tags in lowercase.)

**Comment by syranide** [comment]
@spicyj 

> In XML (and XML-based languages such as XHTML), tagName preserves case. On HTML elements in DOM trees flagged as HTML documents, tagName returns the element name in the uppercase form.

Since it's the standard and considering `nodeName` being an enum value of sorts (irrespective of input syntax), then uppercase seems like the correct case if we want to get technical. Also since we really only care about the tag names then perhaps `tagName` is the correct property, not that it really matters.

**Comment by neojski** [comment]
I changed this to lower case. Please have a look @spicyj

**Comment by spicyj** [comment]
Looks great. In src/renderers/dom/client/ReactMount.js we have a `.tagName` check – can you change that one too?

**Comment by neojski** [comment]
Done.

**Comment by spicyj** [comment]
Thank you!

**Comment by neojski** [comment]
Thanks!
