### PR TITLE
Fix autoFocus for hydration content when it is mismatched

### LINKED ISSUE #11726: client/server mismatch for text inside of an a/button causes the the a/button to focus on page load
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
If there is a client/server mismatch for text inside of an a or button element, it causes it to be automatically focused on page load.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template for React 16: https://jsfiddle.net/Luktwrdm/, template for React 15: https://jsfiddle.net/hmbg7e9w/).**
```
let text;
let URL = '/randomURL';
if (typeof window !== 'undefined') {
  text = 'CLIENT TEXT';
} else {
  text = 'TEXT';
}

return (
  <a href={URL}>
    {text}
  </a>
);
```

if the focus is not on the window (i.e. if a dom element is selected in the chrome inspector or react inspector widnow), then it doesn't add the focus.

**What is the expected behavior?**
The expected behavior is that it would either show CLIENT TEXT or TEXT (depending on how React16 resolves the diff), but for it not to be automatically highlighted 

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React16 / macosx / chrome + ff + safari

### PR DESCRIPTION
**Pull request by koba04**
This PR it to fix #11726.

In no hydration case, this validation is executed at here.

* https://github.com/facebook/react/blob/master/packages/react-dom/src/client/ReactDOM.js#L628  

But in hydration case, the validation doesn't pass through. So I've added the validation into before calling `focus()`. Is there any proper place to put the validation?

### CODE REVIEW

**Comment by gaearon** [comment]
Thanks! We'd need tests for this.

**Comment by gaearon** [comment]
Apparently it gets tagged with `Update` effect on mounting, which gets interpreted as a focus by DOM renderer. Can you figure out why hydration tags it with the `Update` effect in this case? (Oh I guess because we hydrate and try to update the text content? This is confusing.)

**Comment by brucewpaul** [comment]
thanks for fixing this!

**Comment by koba04** [comment]
Thanks! I've added a test for this. 

> I guess because we hydrate and try to update the text content

I agree with you. I'll figure out why `Update` effect is specified.

File: packages/react-dom/src/__tests__/ReactServerRendering-test.js [hunk 1]
```diff
@@ -372,6 +372,22 @@ describe('ReactDOMServer', () => {
       expect(element.firstChild.focus).not.toHaveBeenCalled();
     });
 
+    it('should not focus on either server or client with autofocus={false} even if the markup is mismatch', () => {
```
Comment (gaearon) [inline packages/react-dom/src/__tests__/ReactServerRendering-test.js]: Did you verify this test fails without your fix?

Comment (gaearon) [inline packages/react-dom/src/__tests__/ReactServerRendering-test.js]: "even if there is a markup mismatch"

File: packages/react-dom/src/__tests__/ReactServerRendering-test.js [hunk 2]
```diff
@@ -372,6 +372,22 @@ describe('ReactDOMServer', () => {
...
+      element.innerHTML = ReactDOMServer.renderToString(
+        <button autoFocus={false}>server</button>,
+      );
+      expect(element.firstChild.autofocus).toBe(false);
+
+      element.firstChild.focus = jest.fn();
+      ReactDOM.hydrate(<button autoFocus={false}>client</button>, element);
+
+      expect(element.firstChild.focus).not.toHaveBeenCalled();
+      expect(console.error.calls.count()).toBe(1);
```
Comment (gaearon) [inline packages/react-dom/src/__tests__/ReactServerRendering-test.js]: Let's assert on a specific warning here by checking `argsFor`.

File: packages/react-dom/src/__tests__/ReactServerRendering-test.js (hunk 1 above)
Comment (koba04) [reply packages/react-dom/src/__tests__/ReactServerRendering-test.js]: Yes.

**Comment by gaearon** [comment]
Looks like you need to run Prettier?

**Comment by gaearon** [comment]
The fix itself still feels a bit odd to me. Yes, it solves the problem for this particular case, but I still think it's unexpected that even though `finalizeInitialChildren` has returned `false`, we later get `commitMount`.

I would like to see an explanation for why this makes sense. Alternatively, maybe a different fix :-)

File: packages/react-dom/src/client/ReactDOM.js [hunk 3]
```diff
@@ -625,7 +625,7 @@ const DOMRenderer = ReactFiberReconciler({
     rootContainerInstance: Container,
   ): boolean {
     setInitialProperties(domElement, type, props, rootContainerInstance);
-    return shouldAutoFocusHostComponent(type, props);
+    return true;
```
Comment (gaearon) [inline packages/react-dom/src/client/ReactDOM.js]: This is not good because now every host Fiber gets scheduled for an effect during commit. The whole point of returning a boolean is to avoid this, as ideally this should be a rare case.

**Comment by koba04** [comment]
I'm still figuring out about the best way to fix this.
I guess there are different reasons to set `Update` effect on hydration mode or not.

* with hydration
    * Patch the diffs between server and client content
    * focus the DOM element.
* without hydration
    * focus the DOM element.

So we can return `true` from `finalizeInitialChildren` regardless the element type because no hydration mode doesn't have any diffs, so I guess it doesn't cause any operation.
But it will have some additional costs by passing through unnecessary flows.

To solve this, it might have to add a new effect for this?

**Comment by koba04** [comment]
I thoutht it is possible to patch the diffs at begin phase, but the DOM has already been mounted on hydration case so we should do this at commit phase.

**Comment by gaearon** [comment]
Let’s go back to your original solution where we do the check twice. It’s not ideal but if we leave a TODO there I think it’s okay. I don’t think this deserves its own effect but we can discuss this later with Sebastian.

**Comment by koba04** [comment]
I've added a TODO comment.

**Comment by gaearon** [comment]
Thanks! I tweaked the comment a little bit, but this is good to go.

**Comment by koba04** [comment]
Thanks!
