### PR TITLE
Fix forceUpdate in shallow test renderer

### LINKED ISSUE #11236: Shallow test renderer calls shouldComponentUpdate on forceUpdate
There is no extra guard or clause in `enqueueForceUpdate` when calling `render` which means the `render` always calls `shouldComponentUpdate` which can block even forced re-render during tests.

This for example [breaks shallow rendering in Enzyme when using MobX and observables](https://github.com/airbnb/enzyme/issues/1267).

Minimal test case:

```javascript
import React from 'react'
import ShallowRenderer from 'react-test-renderer/shallow';
const renderer = new ShallowRenderer();

class TestComponent extends React.Component {
  render() { return <span/> }
}

describe('forceUpdate', () => {
  it('does not call shouldComponentUpdate', () => {
    let called = 0
    TestComponent.prototype.shouldComponentUpdate = () => called += 1
    const component = renderer.render(<TestComponent/>);
    renderer._instance.forceUpdate()
    expect(called).toBe(0) // <- this throws because called === 1
  })
})
```

### PR DESCRIPTION
**Pull request by d4rky-pl**
Fixes #11236 by adding a flag during `enqueueForceUpdate` to make sure the `shouldComponentUpdate` is not being tested against.

### CODE REVIEW

File: src/renderers/testing/ReactShallowRendererEntry.js [hunk 1]
```diff
@@ -188,6 +190,7 @@ class Updater {
   }
 
   enqueueForceUpdate(publicInstance, callback, callerName) {
+    this._renderer._forcedUpdate = true;
```
Comment (gaearon) [inline src/renderers/testing/ReactShallowRendererEntry.js]: Since you're adding a new field can you also initialise it in the constructor please?

Comment (d4rky-pl) [reply src/renderers/testing/ReactShallowRendererEntry.js]: Done!

**Comment by gaearon** [comment]
I think this looks good. Thanks.
