### PR TITLE
fix: skip dangerouslySetInnerHtml hydration warning if it's undefined

### LINKED ISSUE #17170: dangerouslySetInnerHTML, children, and a bogus hydration warning
**Do you want to request a *feature* or report a *bug*?**

Bug (initially reported at https://github.com/zeit/next.js/issues/9173).

**What is the current behavior?**

If a component has both `dangerouslySetInnerHTML` and `children` props, and the component is used with just the `children` prop, on page load the client logs a warning beginning with ``Warning: Prop `dangerouslySetInnerHTML` did not match.``.

Interestingly:

- If just `dangerouslySetInnerHTML` is used there is no warning.
- Multiple instances with just a `children` prop results in only one warning, for the first occurance.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

Demo: https://codesandbox.io/s/react-hydration-warning-demo-3je59

In a Next.js project, create a page with the following content:

```jsx
const TestComponent = ({ dangerouslySetInnerHTML, children }) => (
  <div dangerouslySetInnerHTML={dangerouslySetInnerHTML} children={children} />
)

export default () => <TestComponent>a</TestComponent>
```

Loading the page in a browser will result in this warning logging to the console:

```
Warning: Prop `dangerouslySetInnerHTML` did not match. Server: "a" Client: ""
```

Note that the hydration warning is bogus; using view source and the inspector you can see the SSR and client rendered HTML is identical and correct.

This works just the same as before but without a hydration warning:

```jsx
const TestComponent = ({ dangerouslySetInnerHTML, children }) => {
  const divProps = {}
  if (dangerouslySetInnerHTML)
    divProps.dangerouslySetInnerHTML = dangerouslySetInnerHTML
  if (children) divProps.children = children

  return <div {...divProps} />
}
```

**What is the expected behavior?**

There should be no hydration warning at first client render.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Not sure if the bug is present in old versions of React, but it can be seen with v16.11.0.

### PR DESCRIPTION
**Pull request by eps1lon**
## Summary

Closes #17170

## Test Plan

Added tests to `ReactServerRenderingHydration-test.js` that make sure that
1. no warning is issued if `dangerouslySetInnerHTML` is `undefined` and the markup matches
2. warnings are issued if `dangerouslySetInnerHTML` is `undefined` and the markup does not match.

Verify fix with codesandboxes in #17170:
- Packages built from codesandbox CI are not working with `react-dom/server` /cc @CompuIves 
- Without `react-dom/server`: https://codesandbox.io/s/dangerouslysetinnerhtml-undefined-e14qg?file=/src/index.js logs no more warnings as expected.

### CODE REVIEW

File: packages/react-dom/src/__tests__/ReactServerRenderingHydration-test.js [hunk 1]
```diff
@@ -548,4 +548,41 @@ describe('ReactDOMServerHydration', () => {
...
+    );
+    const markup = ReactDOMServer.renderToStaticMarkup(reactElement);
+    domElement.innerHTML = markup;
+
+    ReactDOM.hydrate(reactElement, domElement);
+
+    expect(domElement.innerHTML).toEqual(markup);
+  });
+
+  it('should warns if innerHTML mismatches with dangerouslySetInnerHTML=undefined on the client', () => {
```
Comment (gaearon) [inline packages/react-dom/src/__tests__/ReactServerRenderingHydration-test.js:568]: should warn

File: packages/react-dom/src/client/ReactDOMComponent.js [hunk 2]
```diff
@@ -1110,12 +1110,11 @@ export function diffHydratedProperties(
       } else if (propKey === DANGEROUSLY_SET_INNER_HTML) {
         const serverHTML = domElement.innerHTML;
         const nextHtml = nextProp ? nextProp[HTML] : undefined;
-        const expectedHTML = normalizeHTML(
-          domElement,
-          nextHtml != null ? nextHtml : '',
-        );
-        if (expectedHTML !== serverHTML) {
-          warnForPropDifference(propKey, serverHTML, expectedHTML);
+        if (nextHtml != null) {
```
Comment (gaearon) [inline packages/react-dom/src/client/ReactDOMComponent.js:1113]: So.. what if `nextHtml` is `null` or `undefined`, but it was not `null` on the server? Wouldn't this miss a warning?

Comment (eps1lon) [reply packages/react-dom/src/client/ReactDOMComponent.js:1113]: I had the exact same question. This is pretty similar to the second test I added (https://github.com/facebook/react/pull/18676/files#diff-ab371863932cd2e8f0ba14ff2eaab380R568). I can change it not render anything on the client or add a new one that goes from `{ __html: "server" }` to `undefined`.

Comment (gaearon) [reply packages/react-dom/src/client/ReactDOMComponent.js:1113]: Adding new one sounds good.

Comment (gaearon) [reply packages/react-dom/src/client/ReactDOMComponent.js:1113]: I'm just asking how it works.

Comment (eps1lon) [reply packages/react-dom/src/client/ReactDOMComponent.js:1113]: I didn't read much of the surrounding code and relied on the tests doing what I expected so I can't tell you how it works.

Maybe I should convert it to a table and `it.each` so that it's more visible  how the props change between client and server? The tests are mostly setup.

Comment (gaearon) [reply packages/react-dom/src/client/ReactDOMComponent.js:1113]: We prefer explicitly written tests to `it.each`. Don't worry about duplication.

>I didn't read much of the surrounding code and relied on the tests doing what I expected so I can't tell you how it works.

I think we need to figure out how it works before we can be comfortable merging this. :-)

File: packages/react-dom/src/__tests__/ReactServerRenderingHydration-test.js (hunk 1 above)
Comment (eps1lon) [reply packages/react-dom/src/__tests__/ReactServerRenderingHydration-test.js]: fixed

File: packages/react-dom/src/client/ReactDOMComponent.js (hunk 2 above)
Comment (eps1lon) [reply packages/react-dom/src/client/ReactDOMComponent.js:1113]: > I think we need to figure out how it works before we can be comfortable merging this. :-)

Sure thing. Let me trace this for each test case. Maybe this clears this up.

**Comment by CompuIves** [comment]
> Packages built from codesandbox CI are not working with react-dom/server /cc @CompuIves

Could you shoot me a Twitter DM or email? I'm not sure what's broken, but want to look into it!

File: packages/react-dom/src/client/ReactDOMComponent.js (hunk 2 above)
Comment (eps1lon) [reply packages/react-dom/src/client/ReactDOMComponent.js:1113]: When tracing the code I wasn't sure if this might result in a loss of component stacks so I added these to the test to make sure.

It looks like the reconciler is going through all the instances that aren't hydrated and deletes them:
https://github.com/facebook/react/blob/dc630d3374e8b3d01cdf9e12a81eab9322ac6832/packages/react-reconciler/src/ReactFiberHydrationContext.old.js#L462

The host config is then responsible for warning about the deletion of hydrateable text/elements: https://github.com/facebook/react/blob/58c895e59cd2822a9a7a67606d5fe7da5e09ba2a/packages/react-dom/src/client/ReactDOMHostConfig.js#L957

So it's no longer warning about a mismatch in `dangerouslySetInnerHTML` but rather that the resulting html mismatches.

It seems like both approaches do not create a helpful error message. In the version on `master` it displays the wrong content of `dangerouslySetInnerHTML` thinking that it's `<p>server</p>` while this content came from the `children` prop. In the version on this PR we no longer see that `dangerouslySetInnerHTML` was part of the issue.
