### PR TITLE
Pre-release version fix

### LINKED ISSUE #12147: CI broken
Looks like commit 8a995f7 broke our CI. Not sure why. The release script passed all 4 test variants (dev+prod and bundle dev+prod). At first I was unable to reproduce the broken behavior, but after doing a fresh install (`rm -rf node_modules && yarn install`) I'm able.

I'm not sure yet what is causing this. Perhaps it has something to do with Yarn workspace and prerelease versions?

### PR DESCRIPTION
**Pull request by bvaughn**
Resolves #12147.

Release script properly updates peer deps for prerelease versions.

# Local release script test
## Fix previous release
`./scripts/release/build.js -v 16.3.0-alpha.0 --dry`
```diff
diff --git a/packages/react-art/package.json b/packages/react-art/package.json
index 7c12d814c..8dfd12640 100644
--- a/packages/react-art/package.json
+++ b/packages/react-art/package.json
@@ -26,7 +26,7 @@
     "prop-types": "^15.6.0"
   },
   "peerDependencies": {
-    "react": "^16.0.0"
+    "react": "^16.0.0 || 16.3.0-alpha.0"
   },
   "files": [
     "LICENSE",
diff --git a/packages/react-call-return/package.json b/packages/react-call-return/package.json
index 331b2f7d3..42840493a 100644
--- a/packages/react-call-return/package.json
+++ b/packages/react-call-return/package.json
@@ -14,6 +14,6 @@
     "object-assign": "^4.1.1"
   },
   "peerDependencies": {
-    "react": "^16.0.0"
+    "react": "^16.0.0 || 16.3.0-alpha.0"
   }
 }
diff --git a/packages/react-dom/package.json b/packages/react-dom/package.json
index 1b29ebdcd..379a754ac 100644
--- a/packages/react-dom/package.json
+++ b/packages/react-dom/package.json
@@ -19,7 +19,7 @@
     "prop-types": "^15.6.0"
   },
   "peerDependencies": {
-    "react": "^16.0.0"
+    "react": "^16.0.0 || 16.3.0-alpha.0"
   },
   "files": [
     "LICENSE",
diff --git a/packages/react-noop-renderer/package.json b/packages/react-noop-renderer/package.json
index afd4aaef7..0e32ea3f4 100644
--- a/packages/react-noop-renderer/package.json
+++ b/packages/react-noop-renderer/package.json
@@ -11,7 +11,7 @@
     "object-assign": "^4.1.1",
     "prop-types": "^15.6.0",
     "regenerator-runtime": "^0.11.0",
-    "react-reconciler": "*"
+    "react-reconciler": "* || 0.8.0-alpha.0"
   },
   "peerDependencies": {
     "react": "^16.0.0"
diff --git a/packages/react-reconciler/package.json b/packages/react-reconciler/package.json
index 1a3bc47ba..394d89a4f 100644
--- a/packages/react-reconciler/package.json
+++ b/packages/react-reconciler/package.json
@@ -21,7 +21,7 @@
     "node": ">=0.10.0"
   },
   "peerDependencies": {
-    "react": "^16.0.0"
+    "react": "^16.0.0 || 16.3.0-alpha.0"
   },
   "dependencies": {
     "fbjs": "^0.8.16",
diff --git a/packages/react-test-renderer/package.json b/packages/react-test-renderer/package.json
index 334ae31ef..7aaa839f3 100644
--- a/packages/react-test-renderer/package.json
+++ b/packages/react-test-renderer/package.json
@@ -20,7 +20,7 @@
     "prop-types": "^15.6.0"
   },
   "peerDependencies": {
-    "react": "^16.0.0"
+    "react": "^16.0.0 || 16.3.0-alpha.0"
   },
   "files": [
     "LICENSE",
```

## Simulate next prerelease
`./scripts/release/build.js -v 16.3.0-alpha.1 --dry`
```diff
diff --git a/package.json b/package.json
index 602cd80ad..caee1d1a2 100644
--- a/package.json
+++ b/package.json
@@ -1,6 +1,6 @@
 {
   "private": true,
-  "version": "16.3.0-alpha.0",
+  "version": "16.3.0-alpha.1",
   "workspaces": [
     "packages/*"
   ],
diff --git a/packages/react-art/package.json b/packages/react-art/package.json
index 8dfd12640..87c530c0a 100644
--- a/packages/react-art/package.json
+++ b/packages/react-art/package.json
@@ -1,7 +1,7 @@
 {
   "name": "react-art",
   "description": "React ART is a JavaScript library for drawing vector graphics using React. It provides declarative and reactive bindings to the ART library. Using the same declarative API you can render the output to either Canvas, SVG or VML (IE8).",
-  "version": "16.3.0-alpha.0",
+  "version": "16.3.0-alpha.1",
   "main": "index.js",
   "repository": "facebook/react",
   "keywords": [
@@ -26,7 +26,7 @@
     "prop-types": "^15.6.0"
   },
   "peerDependencies": {
-    "react": "^16.0.0 || 16.3.0-alpha.0"
+    "react": "^16.0.0 || 16.3.0-alpha.1"
   },
   "files": [
     "LICENSE",
diff --git a/packages/react-call-return/package.json b/packages/react-call-return/package.json
index 42840493a..722802842 100644
--- a/packages/react-call-return/package.json
+++ b/packages/react-call-return/package.json
@@ -1,7 +1,7 @@
 {
   "name": "react-call-return",
   "description": "Experimental APIs for multi-pass rendering in React.",
-  "version": "0.6.0-alpha.0",
+  "version": "0.6.0-alpha.1",
   "repository": "facebook/react",
   "files": [
     "LICENSE",
@@ -14,6 +14,6 @@
     "object-assign": "^4.1.1"
   },
   "peerDependencies": {
-    "react": "^16.0.0 || 16.3.0-alpha.0"
+    "react": "^16.0.0 || 16.3.0-alpha.1"
   }
 }
diff --git a/packages/react-dom/package.json b/packages/react-dom/package.json
index 379a754ac..beea3e497 100644
--- a/packages/react-dom/package.json
+++ b/packages/react-dom/package.json
@@ -1,6 +1,6 @@
 {
   "name": "react-dom",
-  "version": "16.3.0-alpha.0",
+  "version": "16.3.0-alpha.1",
   "description": "React package for working with the DOM.",
   "main": "index.js",
   "repository": "facebook/react",
@@ -19,7 +19,7 @@
     "prop-types": "^15.6.0"
   },
   "peerDependencies": {
-    "react": "^16.0.0 || 16.3.0-alpha.0"
+    "react": "^16.0.0 || 16.3.0-alpha.1"
   },
   "files": [
     "LICENSE",
diff --git a/packages/react-noop-renderer/package.json b/packages/react-noop-renderer/package.json
index 0e32ea3f4..b401ce96c 100644
--- a/packages/react-noop-renderer/package.json
+++ b/packages/react-noop-renderer/package.json
@@ -11,7 +11,7 @@
     "object-assign": "^4.1.1",
     "prop-types": "^15.6.0",
     "regenerator-runtime": "^0.11.0",
-    "react-reconciler": "* || 0.8.0-alpha.0"
+    "react-reconciler": "* || 0.8.0-alpha.1"
   },
   "peerDependencies": {
     "react": "^16.0.0"
diff --git a/packages/react-reconciler/package.json b/packages/react-reconciler/package.json
index 394d89a4f..d8bb6fd52 100644
--- a/packages/react-reconciler/package.json
+++ b/packages/react-reconciler/package.json
@@ -1,7 +1,7 @@
 {
   "name": "react-reconciler",
   "description": "React package for creating custom renderers.",
-  "version": "0.8.0-alpha.0",
+  "version": "0.8.0-alpha.1",
   "keywords": [
     "react"
   ],
@@ -21,7 +21,7 @@
     "node": ">=0.10.0"
   },
   "peerDependencies": {
-    "react": "^16.0.0 || 16.3.0-alpha.0"
+    "react": "^16.0.0 || 16.3.0-alpha.1"
   },
   "dependencies": {
     "fbjs": "^0.8.16",
diff --git a/packages/react-test-renderer/package.json b/packages/react-test-renderer/package.json
index 7aaa839f3..74bb83f43 100644
--- a/packages/react-test-renderer/package.json
+++ b/packages/react-test-renderer/package.json
@@ -1,6 +1,6 @@
 {
   "name": "react-test-renderer",
-  "version": "16.3.0-alpha.0",
+  "version": "16.3.0-alpha.1",
   "description": "React package for snapshot testing.",
   "main": "index.js",
   "repository": "facebook/react",
@@ -20,7 +20,7 @@
     "prop-types": "^15.6.0"
   },
   "peerDependencies": {
-    "react": "^16.0.0 || 16.3.0-alpha.0"
+    "react": "^16.0.0 || 16.3.0-alpha.1"
   },
   "files": [
     "LICENSE",
diff --git a/packages/react/package.json b/packages/react/package.json
index 1df29de8f..e02915d2a 100644
--- a/packages/react/package.json
+++ b/packages/react/package.json
@@ -4,7 +4,7 @@
   "keywords": [
     "react"
   ],
-  "version": "16.3.0-alpha.0",
+  "version": "16.3.0-alpha.1",
   "homepage": "https://reactjs.org/",
   "bugs": "https://github.com/facebook/react/issues",
   "license": "MIT",
diff --git a/packages/shared/ReactVersion.js b/packages/shared/ReactVersion.js
index 3781246bb..08787db3b 100644
--- a/packages/shared/ReactVersion.js
+++ b/packages/shared/ReactVersion.js
@@ -8,4 +8,4 @@
 'use strict';
 
 // TODO: this is special because it gets imported during build.
-module.exports = '16.3.0-alpha.0';
+module.exports = '16.3.0-alpha.1';
```

## Simulate next major
`./scripts/release/build.js -v 16.3.0 --dry`
```diff
diff --git a/package.json b/package.json
index caee1d1a2..9fbfe74d5 100644
--- a/package.json
+++ b/package.json
@@ -1,6 +1,6 @@
 {
   "private": true,
-  "version": "16.3.0-alpha.1",
+  "version": "16.3.0",
   "workspaces": [
     "packages/*"
   ],
diff --git a/packages/react-art/package.json b/packages/react-art/package.json
index 87c530c0a..57c1ff719 100644
--- a/packages/react-art/package.json
+++ b/packages/react-art/package.json
@@ -1,7 +1,7 @@
 {
   "name": "react-art",
   "description": "React ART is a JavaScript library for drawing vector graphics using React. It provides declarative and reactive bindings to the ART library. Using the same declarative API you can render the output to either Canvas, SVG or VML (IE8).",
-  "version": "16.3.0-alpha.1",
+  "version": "16.3.0",
   "main": "index.js",
   "repository": "facebook/react",
   "keywords": [
@@ -26,7 +26,7 @@
     "prop-types": "^15.6.0"
   },
   "peerDependencies": {
-    "react": "^16.0.0 || 16.3.0-alpha.1"
+    "react": "^16.0.0"
   },
   "files": [
     "LICENSE",
diff --git a/packages/react-call-return/package.json b/packages/react-call-return/package.json
index 722802842..afdfc6330 100644
--- a/packages/react-call-return/package.json
+++ b/packages/react-call-return/package.json
@@ -1,7 +1,7 @@
 {
   "name": "react-call-return",
   "description": "Experimental APIs for multi-pass rendering in React.",
-  "version": "0.6.0-alpha.1",
+  "version": "0.6.0",
   "repository": "facebook/react",
   "files": [
     "LICENSE",
@@ -14,6 +14,6 @@
     "object-assign": "^4.1.1"
   },
   "peerDependencies": {
-    "react": "^16.0.0 || 16.3.0-alpha.1"
+    "react": "^16.0.0"
   }
 }
diff --git a/packages/react-dom/package.json b/packages/react-dom/package.json
index beea3e497..1011ee25c 100644
--- a/packages/react-dom/package.json
+++ b/packages/react-dom/package.json
@@ -1,6 +1,6 @@
 {
   "name": "react-dom",
-  "version": "16.3.0-alpha.1",
+  "version": "16.3.0",
   "description": "React package for working with the DOM.",
   "main": "index.js",
   "repository": "facebook/react",
@@ -19,7 +19,7 @@
     "prop-types": "^15.6.0"
   },
   "peerDependencies": {
-    "react": "^16.0.0 || 16.3.0-alpha.1"
+    "react": "^16.0.0"
   },
   "files": [
     "LICENSE",
diff --git a/packages/react-noop-renderer/package.json b/packages/react-noop-renderer/package.json
index b401ce96c..afd4aaef7 100644
--- a/packages/react-noop-renderer/package.json
+++ b/packages/react-noop-renderer/package.json
@@ -11,7 +11,7 @@
     "object-assign": "^4.1.1",
     "prop-types": "^15.6.0",
     "regenerator-runtime": "^0.11.0",
-    "react-reconciler": "* || 0.8.0-alpha.1"
+    "react-reconciler": "*"
   },
   "peerDependencies": {
     "react": "^16.0.0"
diff --git a/packages/react-reconciler/package.json b/packages/react-reconciler/package.json
index d8bb6fd52..349bf5d99 100644
--- a/packages/react-reconciler/package.json
+++ b/packages/react-reconciler/package.json
@@ -1,7 +1,7 @@
 {
   "name": "react-reconciler",
   "description": "React package for creating custom renderers.",
-  "version": "0.8.0-alpha.1",
+  "version": "0.8.0",
   "keywords": [
     "react"
   ],
@@ -21,7 +21,7 @@
     "node": ">=0.10.0"
   },
   "peerDependencies": {
-    "react": "^16.0.0 || 16.3.0-alpha.1"
+    "react": "^16.0.0"
   },
   "dependencies": {
     "fbjs": "^0.8.16",
diff --git a/packages/react-test-renderer/package.json b/packages/react-test-renderer/package.json
index 74bb83f43..86656a54b 100644
--- a/packages/react-test-renderer/package.json
+++ b/packages/react-test-renderer/package.json
@@ -1,6 +1,6 @@
 {
   "name": "react-test-renderer",
-  "version": "16.3.0-alpha.1",
+  "version": "16.3.0",
   "description": "React package for snapshot testing.",
   "main": "index.js",
   "repository": "facebook/react",
@@ -20,7 +20,7 @@
     "prop-types": "^15.6.0"
   },
   "peerDependencies": {
-    "react": "^16.0.0 || 16.3.0-alpha.1"
+    "react": "^16.0.0"
   },
   "files": [
     "LICENSE",
diff --git a/packages/react/package.json b/packages/react/package.json
index e02915d2a..2fe8ee328 100644
--- a/packages/react/package.json
+++ b/packages/react/package.json
@@ -4,7 +4,7 @@
   "keywords": [
     "react"
   ],
-  "version": "16.3.0-alpha.1",
+  "version": "16.3.0",
   "homepage": "https://reactjs.org/",
   "bugs": "https://github.com/facebook/react/issues",
   "license": "MIT",
diff --git a/packages/shared/ReactVersion.js b/packages/shared/ReactVersion.js
index 08787db3b..53edb59dd 100644
--- a/packages/shared/ReactVersion.js
+++ b/packages/shared/ReactVersion.js
@@ -8,4 +8,4 @@
 'use strict';
 
 // TODO: this is special because it gets imported during build.
-module.exports = '16.3.0-alpha.1';
+module.exports = '16.3.0';
```

### CODE REVIEW

File: scripts/release/build-commands/update-package-versions.js [hunk 1]
```diff
@@ -30,30 +30,49 @@ const update = async ({cwd, dry, packages, version}) => {
...
+        json.version = `0.${minor}.0${suffix}`;
       } else {
         json.version = version;
       }
 
       if (project !== 'react') {
-        const peerVersion = json.peerDependencies.react.replace('^', '');
+        let peerVersion = json.peerDependencies.react.replace('^', '');
+        if (peerVersion.includes(' || ')) {
+          peerVersion = peerVersion.split(' || ')[0];
```
Comment (gaearon) [inline scripts/release/build-commands/update-package-versions.js]: This assumes no one manually edits them (e.g. to reorder). It's probably a fine assumption to make but would be nice to leave a comment with expected format. Or assert it.

**Comment by bvaughn** [comment]
I think everything should be sorted out now. 
Thanks for the weekend code review, Dan 😄
