### PR TITLE
Suspense component does not capture if `fallback` is not defined

### LINKED ISSUE #13864: Suspense component should only capture if fallback prop is defined
*[Edit by @acdlite: Decided in comments below that we will change the semantics so that a missing `fallback` prop means the exception should propagate to the next parent (like a rethrow). That way a Suspense component can specify other props like `maxDuration` without needing to provide a fallback, too.]*

---

**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
`<React.Suspense>` does not warn you if you omit a `fallback`). While redundant for TS/Flow usage,  I misspelled the `fallback` prop by accident in a playground and was tearing my hair out trying to figure out why things were not working as expected. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

Omit a `fallback`. 

**What is the expected behavior?**
React should warn during development if `fallback` is `undefined`.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Master

### PR DESCRIPTION
**Pull request by acdlite**
A missing fallback prop means the exception should propagate to the next
parent (like a rethrow). That way a Suspense component can specify other
props like maxDuration without needing to provide a fallback, too.

Closes #13864 

cc: @jaredpalmer

### CODE REVIEW

File: packages/react-reconciler/src/ReactFiberUnwindWork.js [hunk 1]
```diff
@@ -211,8 +211,9 @@ function throwException(
     workInProgress = returnFiber;
     do {
       if (workInProgress.tag === SuspenseComponent) {
+        const fallback = workInProgress.memoizedProps.fallback;
         const didTimeout = workInProgress.memoizedState;
-        if (!didTimeout) {
+        if (fallback !== undefined && !didTimeout) {
```
[the remark this answers is not in the document]
Comment (gaearon) [reply packages/react-reconciler/src/ReactFiberUnwindWork.js]: Also what happens if you sometimes specify it and sometimes don't? Is that a legit or broken pattern? Does it need a warning, like controlled<->uncontrolled "flapping" input?

[the remark this answers is not in the document]
Comment (sophiebits) [reply packages/react-reconciler/src/ReactFiberUnwindWork.js]: Prior art for our APIs (particularly defaultProps) is that undefined is treated as absent. Otherwise it is a pain to wrap Placeholder in your own component that passes a `fallback` through.

Comment (sebmarkbage) [inline packages/react-reconciler/src/ReactFiberUnwindWork.js]:
```suggestion
        if (!didTimeout && workInProgress.memoizedProps.fallback !== undefined) {
```

File: packages/react-reconciler/src/__tests__/ReactSuspense-test.internal.js [hunk 2]
```diff
@@ -271,4 +272,49 @@ describe('ReactSuspense', () => {
...
+    jest.advanceTimersByTime(1000);
+    expect(ReactTestRenderer).toHaveYielded([]);
+    expect(root).toFlushAndYield([]);
+    expect(root).toMatchRenderedOutput('Loading...');
+
+    jest.advanceTimersByTime(5000);
+    expect(ReactTestRenderer).toHaveYielded(['Promise resolved [Hi]']);
+    expect(root).toFlushAndYield(['Hi']);
+    expect(root).toMatchRenderedOutput('Hi');
+  });
```
Comment (NE-SmallTown) [inline packages/react-reconciler/src/__tests__/ReactSuspense-test.internal.js]: This test case is weird, I don't think we need provide this usage of Suspense(at lease for this case behavior). In this case, we set the `maxDuration` option  but it is useless, seems we use the `maxDuration` of the outer Suspense(default `0`?), this is not expected.

So just from my personal perspective, we have 2 ways:
1. Warn about this usage if we allow to do this

or 

2. Use the `maxDuration`(if provided) of inner and `fallback` of outer

File: packages/react-reconciler/src/ReactFiberUnwindWork.js [hunk 3]
```diff
@@ -205,9 +205,9 @@ function throwException(
     workInProgress = returnFiber;
     do {
       if (workInProgress.tag === SuspenseComponent) {
-        const state = workInProgress.memoizedState;
-        const didTimeout = state !== null && state.didTimeout;
-        if (!didTimeout) {
+        const fallback = workInProgress.memoizedProps.fallback;
+        const didTimeout = workInProgress.memoizedState;
+        if (!didTimeout && workInProgress.memoizedProps.fallback !== undefined) {
```
Comment (bvaughn) [inline packages/react-reconciler/src/ReactFiberUnwindWork.js]: Just noticed this. Looks like an oversight that you read from `workInProgress.memoizedProps.fallback` twice rather than use the `fallback` const.

Comment (gaearon) [reply packages/react-reconciler/src/ReactFiberUnwindWork.js]: Seems like this code already changed.
