### PR TITLE
[compiler] Fix bug w functions depending on hoisted primitives

### LINKED ISSUE #35122: [Compiler Bug]:  function are not memorized correctly.
### What kind of issue is this?

- [x] React Compiler core (the JS output is incorrect, or your app works incorrectly after optimization)
- [ ] babel-plugin-react-compiler (build issue installing or using the Babel plugin)
- [ ] eslint-plugin-react-hooks (build issue installing or using the eslint plugin)
- [ ] react-compiler-healthcheck (build issue installing or using the healthcheck script)

### Link to repro

https://playground.react.dev/#N4Igzg9grgTgxgUxALhAMygOzgFwJYSYAEAKgmDgIwAUAlEcADrFFyEVEDaCAHgA54YCADREwCHAFF+ghAF0iAXiJRxAZRwBDHAmoBWWsyIrxktGgS5qdJQD4GR463Y4i+ALYIYSsRICSmDowAG6aADbW9Ir2TCxOvlIyQtZ8QsFR9qkIwUQAtESUhnFEAL6ilAAMVUXxeGhE1LwCQkqKyhX0sfHGcGEImjABQaERHl41TiWOxkI4sMQ20ax9A0NeI9RjMBNlXE2ychNsmByEAMJheHAA1j6LMdPOJxB9AHRhEADm1ADkeGDSZoIAAmP1E-0BsmBO0cxw4EKSIJ8+xabXajlm8yIAB5gXgcudLjdFMBCVdriVlpowGAAHKaTyKRggHQ8HC5ITA3J6KrM2zAFEIErYgD0eOCtmYJRAwhAxzQeE+KBAeHcfAgMFcOAAnnwEAwiAAFMJQT54TAAeT4+HYpSIaBgEHcRB+ACNNK6EGFcnwTWbMBz+rhcmw1Xg+jAxf8cD8ANzMZjULpEEUi0MCMLaAiYACyEGBCGQRGZ4TCzKlYizYAV5CNfvNVptJ1osZl4AAFhAAO5rGCYcJgFBoAdCoA

### Link to the code that reproduces this issue

https://github.com/promer94/incorrect-memo-fn-nextjs

### To Reproduce

1. build the application with `next build`
2. start the application with `next start`
3. click the numbers to see the console log

```jsx
function Test1() {
    const [expire, setExpire] = useState(5)
    useEffect(() => {
        const timer = setInterval(() => {
            setExpire((prev) => prev - 1)
        }, 1000)
        if (expire === 0) {
            clearInterval(timer)
        }
        return () => clearInterval(timer)
    }, [expire])
    const onClick = () => {
        console.log('isExpired', isExpired)
    }
    const isExpired = expire === 0
    return <div onClick={onClick} className="text-red-500">{expire}</div>
}
```
The onclick function should be able to access the latest value of `isExpired` 

### How often does this bug happen?

Every time

### What version of React are you using?

19.2.0

### What version of React Compiler are you using?

`1.0.0` would cause this bug

But `^19.1.0-rc.3` works correctly

### PR DESCRIPTION
**Pull request by josephsavona**
Fixes an edge case where a function expression would fail to take a dependency if it referenced a hoisted `const` inferred as a primitive value. We were incorrectly skipping primitve-typed operands when determing scopes for merging in InferReactiveScopeVariables.

This was super tricky to debug, for posterity the trick is that Context variables (StoreContext etc) are modeled just like a mutable object, where assignment to the variable is equivalent to `object.value = ...` and reading the variable is equivalent to `object.value` property access. Comparing to an equivalent version of the repro case replaced with an object and property read/writes showed that everything was exactly right, except that InferReactiveScopeVariables wasn't merging the scopes of the function and the context variable, which led me right to the problematic line.

Closes #35122

### CODE REVIEW

**Comment by josephsavona** [comment]
Closes #35122

File: compiler/packages/babel-plugin-react-compiler/src/ReactiveScopes/InferReactiveScopeVariables.ts [hunk 1]
```diff
@@ -389,14 +389,6 @@ export function findDisjointMutableValues(
...
             operand.identifier.mutableRange.start > 0
           ) {
-            if (
-              instr.value.kind === 'FunctionExpression' ||
-              instr.value.kind === 'ObjectMethod'
-            ) {
-              if (operand.identifier.type.kind === 'Primitive') {
-                continue;
-              }
-            }
```
Comment (josephsavona) [inline compiler/packages/babel-plugin-react-compiler/src/ReactiveScopes/InferReactiveScopeVariables.ts:399]: intuitively this makes sense: we don't usually create scopes for primitives, but if we assigned a scope then it should follow all the regular merging logic of this pass
