### PR TITLE
Fix form status reset when component state is updated

### LINKED ISSUE #30368: Bug: useFormStatus pending state is reset when component state is updated
If you have a component that relies on the `pending` return value of `useFormStatus`, the `pending` state will incorrectly reset to `false` if the component is updated due to a `useState` update. This does not happen if the `useState` hook is placed in a child component. 

React version: 19.0.0-rc-512b09b2-20240718

## Steps To Reproduce

[codesandbox.io/p/sandbox/react-useformstatus-pending-reset-on-unrelated-state-update-m59zw8](https://codesandbox.io/p/sandbox/react-useformstatus-pending-reset-on-unrelated-state-update-m59zw8)

1. Create a react app that uses form actions (this uses NextJS starter code)
2. Have the form action delay for a set period of time before resolving
3. Create a child component that uses `useFormStatus().pending`. Have the component also use a `useState` hook that updates on an interval using `useEffect`. 
4. Place this child component as a child of the `<form />` element
5. Verify that `useFormStatus().pending` is reset to false as soon as a call to `setState` happns

Example component

```

export default function SubmissionState() {
  const formStatus = useFormStatus();
  const [counter, setCounter] = useState(0);
  useEffect(() => {
    const id = setTimeout(() => {
      if (!formStatus.pending) {
        setCounter(0);
        return;
      }
      setCounter(counter + 1);
    }, 1000);
    return () => clearTimeout(id);
  }, [counter, formStatus.pending]);
  return (
    <div>
      {formStatus.pending ? `Pending for ${counter} seconds` : "Not pending"}
    </div>
  );
}
```

this example works as expected, `useFormStatus().pending` state matches the server actions state

```
function SubmissionStateBody({ pending }: { pending: boolean }) {
  const [counter, setCounter] = useState(0);
  useEffect(() => {
    if (!pending) {
      setCounter(0);
      return;
    }
    const id = setTimeout(() => {
      setCounter(counter + 1);
    }, 1000);
    return () => clearTimeout(id);
  }, [counter, pending]);
  return (
    <div>{pending ? `Pending for ${counter} seconds` : "Not pending"}</div>
  );
}

export default function SubmissionStateCorrect() {
  const formStatus = useFormStatus();
  return <SubmissionStateBody pending={formStatus.pending} />;
}
``` 

Link to code example:

[Github repro using nextjs starter template](https://github.com/jatwood/repro-use-form-issue)

## The current behavior

The UI shows the submission as pending for the length of the server action.

## The expected behavior

The UI shows the submission as not-pending as soon as the counter is updated.

### PR DESCRIPTION
**Pull request by eps1lon**
Alternate to https://github.com/facebook/react/pull/33351 without the regression highlighted in https://github.com/facebook/react/pull/33351#discussion_r2247272687

Host context is now updated in `pushHostContext` (similar to normal React Context) in addition to during `updateHostComponent`.

Closes https://github.com/facebook/react/issues/30368
Closes https://github.com/facebook/react/pull/33351

### CODE REVIEW

File: packages/react-reconciler/src/ReactFiberBeginWork.js [hunk 1]
```diff
@@ -1928,31 +1926,15 @@ function updateHostComponent(
...
       workInProgress,
       renderLanes,
     );
-
-    // If the transition state changed, propagate the change to all the
-    // descendents. We use Context as an implementation detail for this.
-    //
-    // This is intentionally set here instead of pushHostContext because
-    // pushHostContext gets called before we process the state hook, to avoid
-    // a state mismatch in the event that something suspends.
```
Comment (eps1lon) [inline packages/react-reconciler/src/ReactFiberBeginWork.js:1979]: I'm not sure I fully understand this comment. If something suspends we pop back up. And the Component we're rendering (here: `TransitionAwareHostComponent`) should not be able to read the current Context just yet which is what pushing the context before the render would do, right? We can't nest Host Context anyway though. So this seems safe to move the push after the render.

Comment (sebmarkbage) [reply packages/react-reconciler/src/ReactFiberBeginWork.js:1979]: A common issue is that CompleteWork and UnwindWork unconditionally calls `popHostContext`. That's called even when something in the component suspends because it doesn't know if we suspended before or after the push. There's no state to indicate that.

That's why we always `pushHostContext` and other push things immediately when we enter the update before anything could error or suspend.

Since `renderTransitionAwareHostComponentWithHooks` might suspend, I don't think it's safe to move the `pushHostContext` after it. In fact I'm surprised we don't have a test that fails for that case. Maybe we're lacking coverage or there's some other thing that covers it but it shouldn't be safe in general.

Comment (eps1lon) [reply packages/react-reconciler/src/ReactFiberBeginWork.js:1979]: Makes sense. Moved the `pushContext` back to its original place. When the state changes, we update the context value which works because only a single transition provider is allowed.

Basically, we set the value on `pushHostContext` and when we update state.

**Comment by redbmk** [comment]
Would love to see this merged in soon. We're blocked from upgrading to Next 15 and React 19 until this issue is fixed - will also have to wait for Next to pull in a new canary release after this is merged.

@sebmarkbage any chance you could review the most recent changes?

File: packages/react-reconciler/src/ReactFiberBeginWork.js (hunk 1 above)
Comment (acdlite) [reply packages/react-reconciler/src/ReactFiberBeginWork.js:1979]: Can you revert this comment back to the original now too please?

**Review by acdlite — APPROVED** [review]

**Comment by devongovett** [comment]
Is there a release planned that might include this fix? This is still an issue in the latest stable version.

File: packages/react-reconciler/src/ReactFiberBeginWork.js (hunk 1 above)
Comment (syedarman7867867860-bit) [reply packages/react-reconciler/src/ReactFiberBeginWork.js:1979]: Sorry 😟

**Comment by redbmk** [comment]
@devongovett it looks like it's fixed in 19.2


https://github.com/user-attachments/assets/18c4352a-8c11-44ee-8c87-75fdd3a75405


Compare that with the behavior here: https://github.com/facebook/react/issues/31363#issuecomment-2704033890

how are you recreating it?

**Comment by RomkeSandwave** [comment]
I'm still noticing this issue on 19.2.5:

```tsx
type ButtonProps = DetailedHTMLProps<ButtonHTMLAttributes<HTMLButtonElement>, HTMLButtonElement>

function SubmitButton(props: PropsWithChildren<ButtonProps>): React.JSX.Element {
    const {pending} = useFormStatus()

    const [debouncedPending, setDebouncedPending] = useState(false)

    useEffect(() => {
        if (pending) {
            const handler = setTimeout(() => {
                setDebouncedPending(true)
            }, 400)

            return () => {
                clearTimeout(handler)
                setDebouncedPending(false)
            }
        } else {
            setDebouncedPending(false)
        }
    }, [pending])

    console.log({pending, debouncedPending});

    return <Button
        {...props}
        type="submit"
    >
        {props.children}
        {pending && debouncedPending && <Spinner />}
    </Button>
}
```

Without the effect the `pending` stays true until the form action completes. With the effect `pending` immediately resets back to `false`.

**Comment by redbmk** [comment]
> it looks like it's fixed in 19.2

OK I was wrong... the react.dev site SAYS 19.2, but the site itself is actually using a canary build of 19.3.

The problem is React rarely pushes new stable builds and when they do it's usually for major security bugs. [19.2.0](https://github.com/facebook/react/releases/tag/v19.2.0) was published back in October and there have only been [13 commits](https://github.com/facebook/react/compare/v19.2.0...v19.2.5) between then and [19.2.5](https://github.com/facebook/react/releases/tag/v19.2.5) which was just released a couple weeks ago. Meanwhile, there have been [492 commits](https://github.com/facebook/react/compare/v19.2.0...142cfde89edab3d4eabd6335458b4c8736cebfb6) between 19.2.0 and the latest commit in main, including this PR.

React seems to want you to use frameworks like nextjs that depend on canary builds rather than using stable versions. Compare these stackblitz's for example:

- [using 19.2.5](https://stackblitz.com/edit/react-ts-nbwu9y4a?file=package.json)
- [using 19.3.0-canary-142cfde8-20260422](https://stackblitz.com/edit/react-ts-8tqcnssf?file=package.json)


https://github.com/user-attachments/assets/96b36ef9-3982-43de-8dc8-8ddf39ce116f

So, it is fixed, but it won't be release until 19.3.0 comes out, which could be... who knows when. If you're OK with rolling a canary version you could use the latest. If you're not using NextJS you could at least use the version their latest version is pinned to in hopes that they've done enough vetting to say that version is stable enough for them.

**Comment by RomkeSandwave** [comment]
Thanks for finding out for us!
