### PR TITLE
Fix TestUtils crash with NODE_ENV=production

### LINKED ISSUE #7231: Unit test failures on React 15.2.1
Bug

Unit tests using shallow rendering fail on 'TypeError: Cannot read property 'onSetDisplayName' of null'.

I can't seem to get TestUtils into jsfiddle, but here is the build output and code snippet.
```
import expect from 'expect';
import TestUtils from 'react-addons-test-utils';
import React from 'react';
import BlurInput from '...';
...
    beforeEach(function () {
        props = {value: '1', onChange: function () {}};
        expect.spyOn(props, 'onChange');
        let renderer = TestUtils.createRenderer();
        renderer.render(<BlurInput {...props} />);
        instance = getInstance(renderer);
        componentTree = renderer.getRenderOutput();
    });
    it('reflects value to underlying input', function () {
        expect(componentTree.props.value).toBe('1');
        expect(instance.state.value).toBe('1');
    });


```
```
00:04:18.742   1) BlurInput "before each" hook for "reflects value to underlying input":
00:04:18.742      TypeError: Cannot read property 'onSetDisplayName' of null
00:04:18.742       at new ShallowComponentWrapper (node_modules/react/lib/ReactTestUtils.js:349:33)
00:04:18.742       at ReactShallowRenderer._render (node_modules/react/lib/ReactTestUtils.js:399:20)
00:04:18.742       at _batchedRender (node_modules/react/lib/ReactTestUtils.js:381:12)
00:04:18.742       at ReactDefaultBatchingStrategyTransaction.Mixin.perform (node_modules/react/lib/Transaction.js:138:20)
00:04:18.742       at Object.ReactDefaultBatchingStrategy.batchedUpdates (node_modules/react/lib/ReactDefaultBatchingStrategy.js:63:19)
00:04:18.742       at Object.batchedUpdates (node_modules/react/lib/ReactUpdates.js:98:20)
00:04:18.742       at ReactShallowRenderer.render (node_modules/react/lib/ReactTestUtils.js:374:16)
00:04:18.742       at Context.<anonymous> (BlurInput-test.js:19:18)
```
**What is the expected behavior?**
Unit test should run normally.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
15.2.1 has this issue.
15.2.0 does not.

### PR DESCRIPTION
**Pull request by gaearon**
I caused it with #7189.

We generally don’t recommend running TestUtils in production environment but this is technically a regression.

Fixes #7231.

### CODE REVIEW

File: src/test/ReactTestUtils.js [hunk 1]
```diff
@@ -410,9 +410,11 @@ NoopInternalComponent.prototype = {
 
 var ShallowComponentWrapper = function(element) {
   // TODO: Consolidate with instantiateReactComponent
-  this._debugID = nextDebugID++;
-  var displayName = element.type.displayName || element.type.name || 'Unknown';
-  ReactInstrumentation.debugTool.onSetDisplayName(this._debugID, displayName);
+  if (__DEV__) {
+    this._debugID = nextDebugID++;
+    var displayName = element.type.displayName || element.type.name || 'Unknown';
+    ReactInstrumentation.debugTool.onSetDisplayName(this._debugID, displayName);
```
Comment (gaearon) [inline src/test/ReactTestUtils.js]: I looked for it again, and this is the only unguarded `debugTool` call in the codebase. I missed it the last time because I didn’t realize TestUtils could be run in production mode.

**Comment by zpao** [comment]
👍

**Comment by EvNaverniouk** [comment]
Any chance we might see this in a 15.2.2 hot fix release?
