### PR TITLE
Fix uncontrolled radios

### LINKED ISSUE #9988: Regression: onChange doesn't fire with defaultChecked and radio inputs
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
In React 15.6.1, this behaviour is changed; In 15.5.4, it fires the change event reliably.

15.6.1 - https://codesandbox.io/embed/VPA42ZnRo
15.5.4 - https://codesandbox.io/embed/JZ0mnE5oy

You'll need to have the console open to get the debugger statement.

In 15.6.1, the first change fires, but all subsequent changes do not fire. In 15.5.4, all changes fire.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React 15.6.1 vs React 15.5.4; Chrome latest stable.

### PR DESCRIPTION
**Pull request by jquense**
Fixes #9988, this is against master but we should cherry-pick the change back to 15.6 for a patch release. 

I added a fixture instead of a test because, writing a unit test that reproduced the issue was confusingly hard actually.

Most of the extra bits here are to handle both fiber and stack, the content of the PR is really the one line in DOMComponent.

### CODE REVIEW

File: fixtures/dom/public/react-loader.js [hunk 1]
```diff
@@ -28,8 +28,8 @@ var query = parseQuery(window.location.search);
 var version = query.version || 'local';
 
 if (version !== 'local') {
-  REACT_PATH = 'https://unpkg.com/react@' + version + '/dist/react.min.js';
-  DOM_PATH = 'https://unpkg.com/react-dom@' + version + '/dist/react-dom.min.js';
+  REACT_PATH = 'https://unpkg.com/react@' + version + '/dist/react.js';
+  DOM_PATH = 'https://unpkg.com/react-dom@' + version + '/dist/react-dom.js';
```
Comment (jquense) [inline fixtures/dom/public/react-loader.js]: I switched to the unminified versions intentionally so was easier to step through stuff in devtools

File: src/renderers/dom/stack/client/ReactDOMComponent.js [hunk 2]
```diff
@@ -860,6 +860,9 @@ ReactDOMComponent.Mixin = {
         // happen after `_updateDOMProperties`. Otherwise HTML5 input validations
         // raise warnings and prevent the new value from being assigned.
         ReactDOMInput.updateWrapper(this);
+        // We also check that we haven't missed a value update, such as a
+        // Radio group shifting the checked value to another named radio input.
+        inputValueTracking.updateValueIfChanged(this);
```
Comment (jquense) [inline src/renderers/dom/stack/client/ReactDOMComponent.js]: This is the actual fix

File: src/renderers/dom/shared/inputValueTracking.js [hunk 3]
```diff
@@ -43,15 +46,11 @@ function getTracker(inst: any) {
   return inst._wrapperState.valueTracker;
 }
 
-function attachTracker(inst: InstanceWithWrapperState, tracker: ?ValueTracker) {
-  inst._wrapperState.valueTracker = tracker;
+function detachTracker(subject: SubjectWithWrapperState) {
+  delete subject._wrapperState.valueTracker;
```
Comment (gaearon) [inline src/renderers/dom/shared/inputValueTracking.js]: Can we use `= null` instead? `delete` causes deopts in my experience.

File: src/renderers/dom/shared/inputValueTracking.js [hunk 4]
```diff
@@ -144,9 +143,13 @@ var inputValueTracking = {
     }
 
     var lastValue = tracker.getValue();
-    var nextValue = getValueFromNode(
-      ReactDOMComponentTree.getNodeFromInstance(inst),
-    );
+
+    var node = inst;
+    if (!(inst: any).nodeName) {
```
Comment (gaearon) [inline src/renderers/dom/shared/inputValueTracking.js]: Can you comment on this part? What are you trying to detect?

File: src/renderers/dom/shared/inputValueTracking.js (hunk 3 above)
Comment (jquense) [inline src/renderers/dom/shared/inputValueTracking.js]: I think so. I think originally I was being overly cautious about expected properties sticking around.

File: src/renderers/dom/shared/inputValueTracking.js (hunk 4 above)
Comment (jquense) [inline src/renderers/dom/shared/inputValueTracking.js]: yeah its not great, I'm trying to detect if `inst` is a component instance, like it is in stack, or a DOM node as in fiber. This is the most minimal DRY change I could think of. Alternatively we could split this method into two, but its a bunch of duplication.

Comment (gaearon) [inline src/renderers/dom/shared/inputValueTracking.js]: Let's use same check as in [here](https://github.com/facebook/react/blob/cff012fc16ea6e7f40398410aacc3be20dc39804/src/renderers/dom/shared/findDOMNode.js#L57) and leave a TODO to remove it when Stack is removed.

Comment (jquense) [inline src/renderers/dom/shared/inputValueTracking.js]: perfect 👍

**Comment by gaearon** [comment]
Looks like Stack tests are failing

```
 FAIL  src/renderers/dom/shared/__tests__/inputValueTracking-test.js
  ● inputValueTracking › should stop tracking

    expect(received).toBe(expected)
    
    Expected value to be (using ===):
      false
    Received:
      true
```

Also prettier is unhappy.

**Comment by jquense** [comment]
not sure what the deal with prettier is, i ran it locally. lemme mess around with it. Do I have to do something special to run tests against the stack renderer?

**Comment by jquense** [comment]
o nvm on the failing test, that's my bad. sorry

**Comment by nhunzaker** [comment]
@jquense This looks great from my end. I'd be happy to take on some manual browser testing. What should I test for?

**Comment by nhunzaker** [comment]
Here's a test build with the lint fix:
http://react-fix-uncontrolled-radios.surge.sh/

File: fixtures/dom/src/components/TestCase.js [hunk 5]
```diff
@@ -40,10 +42,10 @@ class TestCase extends React.Component {
     let {complete} = this.state;
 
     const {version} = parse(window.location.search);
-    const isTestRelevant =
+    const isTestFixed =
       !version || !resolvedIn || semver.gte(version, resolvedIn);
 
-    complete = !isTestRelevant || complete;
+    complete = !isTestFixed || complete;
```
Comment (jquense) [inline fixtures/dom/src/components/TestCase.js]: Last time I do merge conflict resolve on github :P man.

**Comment by jquense** [comment]
I don't think this change could change behavior for controlled inputs but technically it's doing slightly more work on every input update. I did run the various fixtures for input changes and didn't see anything but just noting it for posterity.

**Comment by nhunzaker** [comment]
Checks out for me. @jquense Could you handle bringing this over to 15.x?

**Comment by gaearon** [comment]
AFAIK @flarnie's not working on 15.6.x right now. Do you want to handle this release? Would be your first release :-)

**Comment by nhunzaker** [comment]
Well if you put it that way.

Sure

**Comment by gaearon** [comment]
It's yours! Look at what we did for previous releases: merge things to a branch freshly based of 15-stable, let me know when it's ready and we can get it out.

**Comment by EastHJ** [comment]
发送自我的 BlackBerry 10 智能手机。                                                                                                                                                                                                                发件人： Dan Abramov已发送： 2017年7月14日星期五 下午6:54收件人： facebook/react答复： facebook/react抄送： Subscribed主题： Re: [facebook/react] Fix uncontrolled radios (#10156)It's yours! Look at what we did for previous releases: merge things to a branch freshly based of 15-stable, let me know when it's ready and we can get it out.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/facebook/react","title":"facebook/react","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/facebook/react"}},"updates":{"snippets":[{"icon":"PERSON","message":"@gaearon in #10156: It's yours! Look at what we did for previous releases: merge things to a branch freshly based of 15-stable, let me know when it's ready and we can get it out. "}],"action":{"name":"View Pull Request","url":"https://github.com/facebook/react/pull/10156#issuecomment-315331842"}}}

File: src/renderers/dom/shared/inputValueTracking.js [hunk 6]
```diff
@@ -43,15 +47,11 @@ function getTracker(inst: any) {
...
+function detachTracker(subject: SubjectWithWrapperState) {
+  subject._wrapperState.valueTracker = null;
 }
 
-function detachTracker(inst: InstanceWithWrapperState) {
-  delete inst._wrapperState.valueTracker;
-}
-
-function getValueFromNode(node) {
+function getValueFromNode(node: any) {
```
Comment (gaearon) [inline src/renderers/dom/shared/inputValueTracking.js]: In general we should avoid adding `any` wherever possible. It very often leads to bugs. I know we used it sometimes, but I just want to point out for future reviews that it should be used only as last measure.

(I don’t mean this particular case is problematic, but this is something to always keep in mind.)

File: src/renderers/dom/shared/inputValueTracking.js [hunk 7]
```diff
@@ -113,40 +113,46 @@ var inputValueTracking = {
...
       return;
     }
     var node = ReactDOMComponentTree.getNodeFromInstance(inst);
-    attachTracker(inst, trackValueOnNode(node, inst));
+    inst._wrapperState.valueTracker = trackValueOnNode(node, inst);
   },
 
-  updateValueIfChanged(inst: InstanceWithWrapperState | Fiber) {
-    if (!inst) {
+  updateValueIfChanged(subject: SubjectWithWrapperState | Fiber) {
```
Comment (gaearon) [inline src/renderers/dom/shared/inputValueTracking.js]: Was there any specific reason for changing terminology here? Did inputs change? Or was existing terminology inconsistent? In Stack, we used `instance` for internal instance, but in Fiber we use it for abstract renderer-specific instance (such as DOM node in case of ReactDOM). So both seemed fitting to me.

File: src/renderers/dom/shared/inputValueTracking.js [hunk 8]
```diff
@@ -113,40 +113,46 @@ var inputValueTracking = {
...
     var lastValue = tracker.getValue();
-    var nextValue = getValueFromNode(
-      ReactDOMComponentTree.getNodeFromInstance(inst),
-    );
+
+    var node = subject;
+
+    // TODO: remove check when the Stack renderer is retired
+    if ((subject: any).nodeType !== ELEMENT_NODE) {
+      node = ReactDOMComponentTree.getNodeFromInstance(subject);
```
Comment (gaearon) [inline src/renderers/dom/shared/inputValueTracking.js]: Could you explain more about why this change is necessary? I still don’t quite get why it was called unconditionally, but now is called conditionally, even though `subject` (aka `inst`) type has not changed (or has it?)

Comment (gaearon) [inline src/renderers/dom/shared/inputValueTracking.js]: Oops, I misread. I now see that previous code also had (a different) check. I wonder if changing that check is what caused the issue. I'm still not sure why though.

Comment (gaearon) [inline src/renderers/dom/shared/inputValueTracking.js]: Hmm no I didn’t misread 😛 

This does look like a new check. So my previous comment still stands.

File: src/renderers/dom/shared/inputValueTracking.js (hunk 7 above)
Comment (jquense) [inline src/renderers/dom/shared/inputValueTracking.js]: The inputs changed as far as I can know. The only place this was called otherwise was in the ChangeEventPlugin where it's just called an "instance" It may very well be a DOM node there in Fiber (now that I think of it). The need for the logic branch here is that we need the actual DOM node, and to handle both renderers that means calling `getNodeFromInstance` which seems to be fairly unforgiving of you passing in a node already, which I think is somerhow what's happening

As for the terminology it was more to save line space instead of writing `InstanceWithWrapperState | ElementWithWrapperState` in a few places.

File: src/renderers/dom/shared/inputValueTracking.js (hunk 8 above)
Comment (jquense) [inline src/renderers/dom/shared/inputValueTracking.js]: more in the comment above, but the check is purely to avoid calling `getNodeFromInstance` when `inst` is already a Node, as in the Fiber case. The only reason it was added was to handle both renderers, You can see in backport PR that this file isn't even touched (i'm guessing that one probably doesn't suffer this bug btw)

File: src/renderers/dom/shared/inputValueTracking.js (hunk 7 above)
Comment (gaearon) [inline src/renderers/dom/shared/inputValueTracking.js]: Do I understand correctly that now the code supports passing three different types? Stack instance, Fiber, and a DOM node.

File: src/renderers/dom/shared/inputValueTracking.js [hunk 9]
```diff
@@ -113,40 +113,46 @@ var inputValueTracking = {
...
     }
     node._wrapperState.valueTracker = trackValueOnNode(node, node);
   },
 
-  track: function(inst: InstanceWithWrapperState) {
+  track(inst: InstanceWithWrapperState) {
     if (getTracker(inst)) {
       return;
     }
     var node = ReactDOMComponentTree.getNodeFromInstance(inst);
```
Comment (gaearon) [inline src/renderers/dom/shared/inputValueTracking.js]: I looked at the stacktrace and it's crashing here (rather than in the other place I expected).

File: src/renderers/dom/shared/inputValueTracking.js [hunk 10]
```diff
@@ -113,40 +113,46 @@ var inputValueTracking = {
...
+    var tracker = getTracker(subject);
 
     if (!tracker) {
-      if (typeof (inst: any).tag === 'number') {
-        inputValueTracking.trackNode((inst: any).stateNode);
+      if (typeof (subject: any).tag === 'number') {
+        inputValueTracking.trackNode((subject: any).stateNode);
       } else {
-        inputValueTracking.track((inst: any));
+        inputValueTracking.track((subject: any));
```
Comment (gaearon) [inline src/renderers/dom/shared/inputValueTracking.js]: This branching looks odd to me. It seems like it tries to branch on Fiber and Stack code. However now `subject` could be a DOM node itself. In this case it will go to `track()` rather than `trackNode()` which is why it breaks.

I think this shows why it might be better to reduce the polymorphism here and maybe change this to only accept DOM nodes. But I'd also like to understand why tests (including fixtures) didn't catch this. It is not quite obvious to me.

File: src/renderers/dom/shared/inputValueTracking.js (hunk 7 above)
Comment (jquense) [inline src/renderers/dom/shared/inputValueTracking.js]: TBH I don't know what the `Fiber` type is/does here. I didn't add the types originallym and AFAICT its never passed a Fiber, only and instance or Dom node

File: src/renderers/dom/shared/inputValueTracking.js (hunk 9 above)
Comment (jquense) [inline src/renderers/dom/shared/inputValueTracking.js]: ooo I think I understand where the bug is

File: src/renderers/dom/shared/inputValueTracking.js (hunk 7 above)
Comment (gaearon) [inline src/renderers/dom/shared/inputValueTracking.js]: Hmm. I was under impression it was always passed a Fiber or a Stack instance before this change. Since `.tag` check is for detecting Fibers.

Comment (jquense) [inline src/renderers/dom/shared/inputValueTracking.js]: That may be! I still unfamiliar with the Fiber data types but the only place this is called is is ChangeEventPlugin with the `targetInst` parameter and DOMComponent. I'm unsure what the case is in the changeEventPlugin. 

Is the Fiber situation that sometimes it may be an "instance" (DOM Node) and sometimes it may be a "Fiber". In the Stack case it's always an internal Instance

Comment (gaearon) [inline src/renderers/dom/shared/inputValueTracking.js]: I'll check that, thanks.

File: src/renderers/dom/shared/inputValueTracking.js [hunk 11]
```diff
@@ -113,40 +113,46 @@ var inputValueTracking = {
...
-  updateValueIfChanged(inst: InstanceWithWrapperState | Fiber) {
-    if (!inst) {
+  updateValueIfChanged(subject: SubjectWithWrapperState | Fiber) {
+    if (!subject) {
       return false;
     }
-    var tracker = getTracker(inst);
+    var tracker = getTracker(subject);
 
     if (!tracker) {
```
Comment (gaearon) [inline src/renderers/dom/shared/inputValueTracking.js]: I'm having trouble understanding how to hit this code path. In which case do we not have a tracker already? I assumed we always have it since we create it during mount.

**Comment by gaearon** [comment]
https://github.com/facebook/react/pull/10207
