### PR TITLE
fix: select console error to not suggest to set readonly to true

### LINKED ISSUE #27657: Bug: Select when passed a value as Prop errors with a suggestion to pass readOnly
Seems weird when we try to use a `select` component, and pass a value as a prop, it prompts with the error to either set `onChange` or `readOnly`.
the `readOnly` at the last seems misleading since the `select` component does not have a `readOnly` prop, unlike inputs which do  have a `readOnly` attribute.

**SELECT PROPS**
https://react.dev/reference/react-dom/components/select

seems an easy fix would be to check if the mounted component is a `select` component and then conditionally just change the error message, though would need to add tests to support the same.

https://github.com/facebook/react/assets/72331432/12674152-7d57-4d98-99e6-635577b31bfe

cc @sophiebits 

codesandbox link to tinker:- https://codesandbox.io/s/admiring-wright-9sctsn?file=/src/App.js

### PR DESCRIPTION
**Pull request by Biki-das**
fix #27657 

added test in the `ReactDOMSELECT-test.js` to not allow regession to happen in future.

After changes this is what the error message looks like

https://github.com/facebook/react/assets/72331432/53dcbe2a-70d2-43d2-a52d-a4fc389fdfbf

### CODE REVIEW

**Comment by Biki-das** [comment]
cc @hoxyq @sophiebits

File: packages/react-dom/src/__tests__/ReactDOMSelect-test.js [hunk 1]
```diff
@@ -1289,5 +1289,115 @@ describe('ReactDOMSelect', () => {
...
+            <option value="gorilla">A gorilla!</option>
+          </select>,
+        ),
+      ).toErrorDev(
+        'Warning: You provided a `value` prop to a form ' +
+          'field without an `onChange` handler. This will render a read-only ' +
+          'field. If the field should be mutable use `defaultValue`. ' +
+          'Otherwise, set `onChange`.',
+      );
+    });
```
Comment (weikhor) [inline packages/react-dom/src/__tests__/ReactDOMSelect-test.js:1401]: I think we can simplify repetitive test codes using for loop. Example code snippet,.
```
const testCases = [
  { value: false },
  { value: 0 },
  { value: "0" },
  { value: "" },
];

test.each(testCases)(
    "should warn about missing onChange if value is %p",
    ({ value }) => {
      it(`given value ${value}`, () => {
        expect(() =>
          ReactTestUtils.renderIntoDocument(
            <select value={value}>
              <option value="monkey">A monkey!</option>
              <option value="giraffe">A giraffe!</option>
              <option value="gorilla">A gorilla!</option>
            </select>,
          ),
        ).toErrorDev(
          'Warning: You provided a `value` prop to a form ' +
            'field without an `onChange` handler. This will render a read-only ' +
            'field. If the field should be mutable use `defaultValue`. ' +
            'Otherwise, set `onChange`.',
        );
      });
    }
  );
```

Comment (weikhor) [inline packages/react-dom/src/__tests__/ReactDOMSelect-test.js:1401]: I think we can simplify repetitive test codes using for loop . Example code snippet,.
```
const testCases = [
  { value: false },
  { value: 0 },
  { value: "0" },
  { value: "" },
];

test.each(testCases)(
    "should warn about missing onChange if value is %p",
    ({ value }) => {
      it(`given value ${value}`, () => {
        expect(() =>
          ReactTestUtils.renderIntoDocument(
            <select value={value}>
              <option value="monkey">A monkey!</option>
              <option value="giraffe">A giraffe!</option>
              <option value="gorilla">A gorilla!</option>
            </select>,
          ),
        ).toErrorDev(
          'Warning: You provided a `value` prop to a form ' +
            'field without an `onChange` handler. This will render a read-only ' +
            'field. If the field should be mutable use `defaultValue`. ' +
            'Otherwise, set `onChange`.',
        );
      });
    }
  );
```

**Comment by Biki-das** [comment]
@hoxyq friendly ping :-)

File: packages/react-dom/src/__tests__/ReactDOMSelect-test.js [hunk 2]
```diff
@@ -1289,5 +1289,115 @@ describe('ReactDOMSelect', () => {
...
+
+    it('should not warn about missing onChange if disabled is true', () => {
+      ReactTestUtils.renderIntoDocument(
+        <select value="monkey" disabled={true}>
+          <option value="monkey">A monkey!</option>
+          <option value="giraffe">A giraffe!</option>
+          <option value="gorilla">A gorilla!</option>
+        </select>,
+      );
+    });
```
Comment (hoxyq) [inline packages/react-dom/src/__tests__/ReactDOMSelect-test.js:1333]: Why is there no `expect` statement? If these blocks will be executed and print the error, would all of these tests fail?

**Comment by Biki-das** [comment]
@hoxyq pushed a new commit, added an expect statement to check to `.not.toThrow()`, tests are passing as of now.

**Comment by hoxyq** [comment]
> @hoxyq pushed a new commit, added an expect statement to check to `.not.toThrow()`, tests are passing as of now.

Thanks, I think you've missed the first case.

**Comment by Biki-das** [comment]
@hoxyq thanks for catching that and assisting in this one :-) , added the same.

File: packages/react-dom-bindings/src/shared/ReactControlledValuePropTypes.js [hunk 3]
```diff
@@ -35,8 +35,8 @@ export function checkControlledValueProps(
       console.error(
         'You provided a `value` prop to a form field without an ' +
           '`onChange` handler. This will render a read-only field. If ' +
-          'the field should be mutable use `defaultValue`. Otherwise, ' +
-          'set either `onChange` or `readOnly`.',
+          'the field should be mutable use `defaultValue`. Otherwise, set %s.',
+        tagName === 'select' ? '`onChange`' : 'either `onChange` or `readOnly`',
       );
```
Comment (hoxyq) [inline packages/react-dom-bindings/src/shared/ReactControlledValuePropTypes.js:40]: nit:

Can you please split it into `if / else` statement?
```
if (tagName === 'select') {
  console.error('...');
} else {
  console.error('...');
}
```

I think this is much more readable

**Review by hoxyq — APPROVED** [review]

**Comment by Biki-das** [comment]
@hoxyq done ✅.
