### PR TITLE
[DevTools] Fix null ref crash in ContextMenu when items list is empty

### LINKED ISSUE #35923: [DevTools Bug] Cannot read properties of null (reading 'ownerDocument')
### Website or app

material-library.com

### Repro steps

1. open the site
2. clicked on the view all button for categories
3. scrolled the page and stopped recording
4. clicked timeline option

### How often does this bug happen?

Only once

### DevTools package (automated)

react-devtools-extensions

### DevTools version (automated)

7.0.1-3cde211b0c

### Error message (automated)

Cannot read properties of null (reading 'ownerDocument')

### Error call stack (automated)

```text
at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:919551
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:919824
    at commitHookEffectListMount (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:129924)
    at commitLayoutEffectOnFiber (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:142040)
    at recursivelyTraverseLayoutEffects (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:157699)
    at commitLayoutEffectOnFiber (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:141997)
    at recursivelyTraverseLayoutEffects (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:157699)
    at commitLayoutEffectOnFiber (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:141997)
    at recursivelyTraverseLayoutEffects (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:157699)
    at commitLayoutEffectOnFiber (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:141997)
```

### Error component stack (automated)

```text
at ContextMenu_ContextMenu (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:918953)
    at ContextMenuContainer (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:920310)
    at CanvasPageContextMenu (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:1089461)
    at AutoSizedCanvas (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:1091403)
    at div (<anonymous>)
    at _t (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:754231)
    at div (<anonymous>)
    at src_CanvasPage (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:1096981)
    at TimelineSearchContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:1089153)
    at div (<anonymous>)
    at Timeline_Timeline (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:1116965)
    at div (<anonymous>)
    at div (<anonymous>)
    at div (<anonymous>)
    at SettingsModalContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:879909)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:1144384
    at ao (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:898411)
    at div (<anonymous>)
    at div (<anonymous>)
    at ThemeProvider (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:901116)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:901313
    at div (<anonymous>)
    at div (<anonymous>)
    at div (<anonymous>)
    at ThemeProvider (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:901116)
    at SuspenseTreeContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:1147064)
    at InspectedElementContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:915935)
    at TimelineContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:994422)
    at ProfilerContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:986233)
    at TreeContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:786019)
    at SettingsContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:815755)
    at ModalDialogContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:972480)
    at DevTools_DevTools (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:1175879)
```

### GitHub query string (automated)

```text
https://api.github.com/search/issues?q=Cannot read properties of null (reading 'ownerDocument') in:title is:issue is:open is:public label:"Component: Developer Tools" repo:facebook/react
```

### PR DESCRIPTION
**Pull request by fresh3nough**
## Summary

Fixes #35923

When the `ContextMenu` component renders with an empty `items` list (or when the portal container is missing), the component returns `null` and the portal `<div ref={ref}>` is never mounted. However, the `useLayoutEffect` still fires and calls `repositionToFit(ref.current, ...)` where `ref.current` is `null`, causing:

```
TypeError: Cannot read properties of null (reading 'ownerDocument')
```

This happens in the Timeline profiler view when the user right-clicks on the canvas before hovering over any specific event, resulting in an empty context menu items list being passed to the `ContextMenu` component.

## How did you test this change?

Added `contextMenu-test.js` with two test cases:
1. Verifies the component does not crash when `items` is empty (reproduces the exact error from the issue)
2. Verifies the component renders correctly when items are provided

Steps to reproduce the original bug:
1. Open React DevTools
2. Record a profiling session
3. Switch to the Timeline tab
4. Right-click on the canvas area (not on a specific event)

With this fix, the right-click on an empty area no longer crashes.

### CODE REVIEW

File: packages/react-devtools-shared/src/devtools/ContextMenu/ContextMenu.js [hunk 1]
```diff
@@ -74,7 +74,13 @@ export default function ContextMenu({
   );
 
   useLayoutEffect(() => {
-    const menu = ((ref.current: any): HTMLElement);
+    const menu = ref.current;
+
+    // The portal may not be rendered if items is empty or the portal
+    // container is missing, in which case the ref will be null.
+    if (menu == null) {
```
Comment (eps1lon) [inline packages/react-devtools-shared/src/devtools/ContextMenu/ContextMenu.js]: Let's break on the same early return condition. Otherwise `menu` being null would be a bug we should report instead of silently exiting.
```suggestion
    if (portalContainer == null || items.length === 0) {
```

File: packages/react-devtools-shared/src/__tests__/contextMenu-test.js
Comment (eps1lon) [inline packages/react-devtools-shared/src/__tests__/contextMenu-test.js:1]: We generally don't write unit test since they tend to break too often without actually showing real user facing breakage. This change can live without any test.

File: packages/react-devtools-shared/src/devtools/ContextMenu/ContextMenu.js (hunk 1 above)
Comment (fresh3nough) [reply packages/react-devtools-shared/src/devtools/ContextMenu/ContextMenu.js]: Will do

File: packages/react-devtools-shared/src/__tests__/contextMenu-test.js
Comment (fresh3nough) [reply packages/react-devtools-shared/src/__tests__/contextMenu-test.js:1]: Ak

File: packages/react-devtools-shared/src/devtools/ContextMenu/ContextMenu.js [hunk 2]
```diff
@@ -73,8 +70,21 @@ export default function ContextMenu({
     '[data-react-devtools-portal-root]',
   );
 
+  const hideMenu = portalContainer == null || items.length === 0;
+  const menuRef = React.useRef<HTMLDivElement | null>(null);
+
   useLayoutEffect(() => {
-    const menu = ((ref.current: any): HTMLElement);
```
Comment (eps1lon) [inline packages/react-devtools-shared/src/devtools/ContextMenu/ContextMenu.js:77]: This cast was unsound. `ref` was passed from https://github.com/facebook/react/blob/e0cc7202e14418b453c69c4f06dc00c64151f202/packages/react-devtools-shared/src/devtools/ContextMenu/ContextMenuContainer.js#L35-L57

i.e. the owner both set the ref and let the child override the ref again. It seems to me we just don't need to pass along the ref and let `ContextMenu` fully own the ref on the `div`

Comment (fresh3nough) [reply packages/react-devtools-shared/src/devtools/ContextMenu/ContextMenu.js:77]: gotcha
