### PR TITLE
Fix #21972: Add `onResize` event to video elements

### LINKED ISSUE #21972: Bug: `onResize` media event is missing
Note: I’m happy to make a pull request to fix this, I just wanted to log it first to ensure there’s interest.

---

React’s [synthetic media events](https://reactjs.org/docs/events.html#media-events) contain several [existing media events](https://html.spec.whatwg.org/multipage/media.html#mediaevents), for instance `onLoadedMetadata` and `onVolumeChange`. But there is no `onResize` handler.

[`resize` is a standard media event](https://html.spec.whatwg.org/multipage/media.html#event-media-resize) that triggers when one or both of the `videoWidth` and `videoHeight` attributes have just been updated. It’s useful for responding to resolution changes in video players.

React version: 17.0.2 (latest release as of initial issue report)

## Steps To Reproduce

1. Create a `<video>` element with an `onResize` prop.
2. Check the console for the following warning:

```
 Warning: Unknown event handler property `onResize`. It will be ignored.
```

Link to code example: https://codesandbox.io/s/musing-snowflake-zb0qh?file=/src/App.js

## The current behavior

`onResize` handlers are ignored on `<video>` elements.

## The expected behavior

`onResize` handlers are valid on `<video>` elements.

### PR DESCRIPTION
**Pull request by rileyjshaw**
## Summary

This is a simple fix for #21972 that adds support for the `onResize` media event. See #21972 for a detailed description of the problem.

## Test Plan

- Run https://codesandbox.io/s/musing-snowflake-zb0qh?file=/src/App.js with the new additions.
  - `onResize` handler should not throw a warning

## Pre-commit checklist ([source](https://reactjs.org/docs/how-to-contribute.html#sending-a-pull-request))

✅ Fork the repository and create your branch from `main`.
✅ Run `yarn` in the repository root.
✅ If you’ve fixed a bug or added code that should be tested, add tests!
✅ Ensure the test suite passes (`yarn test`). Tip: `yarn test --watch TestName` is helpful in development.
✅ Run `yarn test --prod` to test in the production environment.
✅ If you need a debugger, run `yarn debug-test --watch TestName`, open chrome://inspect, and press “Inspect”.
✅ Format your code with prettier (`yarn prettier`).
✅ Make sure your code lints (`yarn lint`). Tip: `yarn linc` to only check changed files.
✅ Run the Flow typechecks (`yarn flow`).
✅ If you haven’t already, complete the CLA.

## Post-commit checklist

The [synthetic event reference docs](https://github.com/reactjs/reactjs.org/blob/main/content/docs/reference-events.md) will need to be updated.

### CODE REVIEW

File: packages/react-dom/src/events/DOMPluginEventSystem.js [hunk 1]
```diff
@@ -201,6 +201,9 @@ export const mediaEventTypes: Array<DOMEventName> = [
   'waiting',
 ];
 
+// List of events that need to be individually attached to video elements.
+export const videoEventTypes: Array<DOMEventName> = ['resize'];
```
Comment (rileyjshaw) [inline packages/react-dom/src/events/DOMPluginEventSystem.js:205]: Note: I created a separate `videoEventTypes` array, since I doubt anyone will want to add `onResize` to an audio event. It would simplify the code a bit to just add `resize` to the `mediaEventTypes` array, if that’s preferred.

**Review by crypt096 — APPROVED** [review]

**Comment by rileyjshaw** [comment]
Bumping this in case nobody has seen it yet 👀

File: packages/react-dom/src/events/DOMPluginEventSystem.js (hunk 1 above)
Comment (gaearon) [reply packages/react-dom/src/events/DOMPluginEventSystem.js:205]: A one-item array seems like overkill to me. Are there any downsides to adding it to `mediaEventTypes`? I'd suggest that.

File: packages/react-dom/src/events/DOMPluginEventSystem.js [hunk 2]
```diff
@@ -216,6 +219,7 @@ export const nonDelegatedEvents: Set<DOMEventName> = new Set([
   // and can occur on other elements too. Rather than duplicate that event,
   // we just take it from the media events array.
   ...mediaEventTypes,
```
Comment (gaearon) [inline packages/react-dom/src/events/DOMPluginEventSystem.js:221]: Note that adding `resize` here would disable delegation for it. Are there _any_ existing cases where we relied on delegation for it? I suppose not because we used to warn, so it was definitely unused.

**Review by gaearon — CHANGES_REQUESTED** [review]
Thanks for a detailed PR. Unless there are good reasons, let's remove the second array and keep them unified.

File: packages/react-dom/src/events/DOMPluginEventSystem.js (hunk 1 above)
Comment (rileyjshaw) [reply packages/react-dom/src/events/DOMPluginEventSystem.js:205]: Happy to make the change! The only “downside” is that since [the `resize` event spec](https://html.spec.whatwg.org/multipage/media.html#event-media-resize) lists:

> Media element is a `video` element

in its preconditions, we _might_ want to log a warning if someone attaches `onResize` to an `audio` element. But I agree, I think the simplification is worth it. I’ll make the change now.

File: packages/react-dom/src/events/DOMPluginEventSystem.js (hunk 2 above)
Comment (rileyjshaw) [reply packages/react-dom/src/events/DOMPluginEventSystem.js:221]: As far as I can tell it was unused. Perhaps there could be a future conflict if a Synthetic Event was created for the [Window:resize event](https://developer.mozilla.org/en-US/docs/Web/API/Window/resize_event)?

It seems safe to me for now, but let me know if there are any further tests you’d like me to run.

File: packages/react-dom/src/events/DOMPluginEventSystem.js (hunk 1 above)
Comment (rileyjshaw) [reply packages/react-dom/src/events/DOMPluginEventSystem.js]: Done ✨

**Comment by rileyjshaw** [comment]
Thanks for the review, @gaearon! I consolidated the arrays as requested.

**Review by gaearon — APPROVED** [review]

**Comment by gaearon** [comment]
Thanks!
