### PR TITLE
Fix checksum hash attribute insertion for self-closing root tags.  Fixes #4323


### LINKED ISSUE #4323: Checksum inserted incorrectly for self-closing root tags
This came up while diagnosing #4321 - https://github.com/facebook/react/issues/4321#issuecomment-120064258

This is because we just look for the closing `>` when adding the checksum.

```
> ReactDOM.renderToString(React.createElement('img'))
'<img data-reactid=".yxoueqje2o"/ data-react-checksum="-951841932">'
> ReactDOM.renderToString(React.createElement('div', null, React.createElement('img')))
'<div data-reactid=".2d7dcluvuv4" data-react-checksum="-890562330"><img data-reactid=".2d7dcluvuv4.0"/></div>'
```

### PR DESCRIPTION
**Pull request by jimfb**
Fix checksum hash attribute insertion for self-closing root tags.  Fixes #4323

### CODE REVIEW

File: src/renderers/dom/server/ReactMarkupChecksum.js [hunk 1]
```diff
@@ -22,6 +22,13 @@ var ReactMarkupChecksum = {
    */
   addChecksumToMarkup: function(markup) {
     var checksum = adler32(markup);
+
+    // If root tag is a self-closing tag
+    if (markup.charAt(markup.length-2) === '/') {
+      return markup.substring(0, markup.length-2) + ' ' +
+        ReactMarkupChecksum.CHECKSUM_ATTR_NAME + '="' + checksum + '" />';
+    }
+
```
Comment (zpao) [inline src/renderers/dom/server/ReactMarkupChecksum.js]: Instead of special casing the `/`, we can just take advantage of regular expression matches in `replace` (also I don't think we want to add the space before `/>` anyway)

```js
    return markup.replace(
      /\/?>/,
      ' ' + ReactMarkupChecksum.CHECKSUM_ATTR_NAME + '="' + checksum + '"$&'
    );
```

**Comment by jimfb** [comment]
Better?

File: src/renderers/dom/server/ReactMarkupChecksum.js [hunk 2]
```diff
@@ -22,9 +22,11 @@ var ReactMarkupChecksum = {
    */
   addChecksumToMarkup: function(markup) {
     var checksum = adler32(markup);
+
+    // If root tag is a self-closing tag
```
Comment (zpao) [inline src/renderers/dom/server/ReactMarkupChecksum.js]: Better, but can you turn this comment into a complete thought.

**Comment by spicyj** [comment]
Normally we pull out all regexes to the top level in case browsers optimize it only when it's the same object.
