### PR TITLE
[DevTools] find best renderer when inspecting

### LINKED ISSUE #24539: [DevTools Bug]: When inspecting with DevTools, it fails to select correct react component when there are multiple react-dom instances in the application
### Website or app

https://codesandbox.io/s/jtiw8m

### Repro steps

When using devtools in the linked codesandbox, I am not able to select react components that are rendered by the micro-fe using the inspect tool.

Steps to reproduce:
1. Go to https://jtiw8m.csb.app/ 
2. Open React DevTools and click on Inspect icon with the "Select an element on the page to inspect it"  tooltip
3. Inspect the component with the pink background and text "micro-fe example heading"
4. Devtools selects `App` as the component (or if the component type filter is disabled, it selects the `div` where the micro-fe is mounted)

Ideally it would actually select either the `MicroFeRoot` component (or the corresponding html node if the filter is disabled).

I was able to get it working by doing [the following change](https://github.com/facebook/react/compare/main...danielkutt:devtools-microfe-bug) in the `react-devtools-backend/src/backend/agent.js`

### How often does this bug happen?

Every time

### DevTools package (automated)

_No response_

### DevTools version (automated)

_No response_

### Error message (automated)

_No response_

### Error call stack (automated)

_No response_

### Error component stack (automated)

_No response_

### GitHub query string (automated)

_No response_

### PR DESCRIPTION
**Pull request by mondaychen**
## Summary

resolves #24539

When inspecting with DevTools, originally we use the first renderer where we can found a fiber with inspected element. However, if two or more renderers are nested (see the example in the issue #24539), this might cause a mismatch. 
In this PR, we now always go through all renderers until we find an exact match (where the inspected element is exactly the same `stateNode` linked to the fiber). If we cannot find an exact match, we fallback to the original logic and return a renderer where we find a non-exact matching fiber.

## How did you test this change?

I built the extension and tested with the same URL the issue author provided. You can see the inspecting tool can now correctly select the "MicroFeRoot" node (and the element inside)

https://user-images.githubusercontent.com/1001890/171740973-c1b546b0-5269-40fa-b0b9-bf04dd7ddd52.mov

### CODE REVIEW

File: packages/react-devtools-shared/src/backend/agent.js [hunk 1]
```diff
@@ -310,20 +313,16 @@ export default class Agent extends EventEmitter<{|
...
-        if (id !== null) {
-          return id;
-        }
-      } catch (error) {
-        // Some old React versions might throw if they can't find a match.
-        // If so we should ignore it...
-      }
+      renderers.push(renderer);
+    }
+    const rendererInterface = getBestMatchingRendererInterface(renderers, node);
```
Comment (lunaruan) [inline packages/react-devtools-shared/src/backend/agent.js:323]: This probably should be in the `backend/agent` file instead of the utils because you're using two for loops right now and if you put the code from `getBestMatchingRendererInterface` into the agent you would only need one

ex. 

```js
let renderer = this._rendererInterfaces[0];
for (const rendererID in this._rendererInterfaces) {
  const currentRenderer = ...;
  const fiber = currentRenderer.getFiberForNative(node, false);
  if (fiber !== null && fiber.stateNode === node) {
   renderer = currentRenderer;
    break;
  }
  ...
}
...
```

**Comment by lunaruan** [comment]
I think this PR might break the legacy renderer. Could you take a look? 😊

File: packages/react-devtools-shared/src/backend/agent.js (hunk 1 above)
Comment (mondaychen) [reply packages/react-devtools-shared/src/backend/agent.js:323]: The first for-loop is only there for proper typing. Maybe I should refactor the types of `this._rendererInterfaces`?
It's indeed easier to do everything `agent`, but how about the use of the util function in `Overlay`?

Comment (mondaychen) [reply packages/react-devtools-shared/src/backend/agent.js]: I updated the file with better typing https://github.com/facebook/react/pull/24665/commits/d0346ff11517296b2e0f95d8a64e1802d3fbfc13 so that I can use `values()` instead of for-loop https://github.com/facebook/react/pull/24665/commits/9a7e0beb41f6cec0a85634a23bd92efc2084293b

Does it make sense?

File: packages/react-devtools-shared/src/backend/agent.js [hunk 2]
```diff
@@ -309,22 +309,39 @@ export default class Agent extends EventEmitter<{|
...
+    if (rendererInterface != null) {
+      return rendererInterface.getFiberIDForNative(node, true);
+    }
+    return null;
+  }
+
+  getDisplayNameForNode(node: Object): string | null {
+    const rendererInterface = this.getBestMatchingRendererInterface(node);
+    if (rendererInterface != null) {
+      return rendererInterface.getDisplayNameForFiberID(node, true);
```
Comment (lunaruan) [inline packages/react-devtools-shared/src/backend/agent.js:343]: Does this not require an ID?

File: packages/react-devtools-shared/src/backend/views/Highlighter/Overlay.js [hunk 3]
```diff
@@ -230,22 +233,10 @@ export default class Overlay {
...
-          if (id !== null) {
-            ownerName = rendererInterface.getDisplayNameForFiberID(id, true);
-            break;
-          }
-        }
-
-        if (ownerName) {
-          name += ' (in ' + ownerName + ')';
-        }
+      const ownerName = this.agent.getDisplayNameForNode(node);
```
Comment (lunaruan) [inline packages/react-devtools-shared/src/backend/views/Highlighter/Overlay.js:236]: Maybe instead of making `getDisplayNameForNode` you can use `getBestMatchingRendererInterface`, `getFiberIDForNative`, and `gwetDisplayNameForFiberID`?

**Comment by mondaychen** [comment]
@lunaruan updated 😃

File: packages/react-devtools-shared/src/backend/agent.js [hunk 4]
```diff
@@ -309,22 +309,31 @@ export default class Agent extends EventEmitter<{|
...
       }
     }
+    // if an exact match is not found, return the first valid renderer as fallback
+    return bestMatch;
+  }
+
+  getIDForNode(node: Object): number | null {
+    const rendererInterface = this.getBestMatchingRendererInterface(node);
+    if (rendererInterface != null) {
+      return rendererInterface.getFiberIDForNative(node, true);
```
Comment (lunaruan) [inline packages/react-devtools-shared/src/backend/agent.js:335]: Should we wrap this around a `try/catch` like before?

Comment (mondaychen) [reply packages/react-devtools-shared/src/backend/agent.js:335]: I'll add it back for safety, but it looks pretty vague what exactly it's trying to catch. The comment says it's for old react, and commit itself is pretty old too. Do we know in which version this might cause an error, so we can get rid of it one day?

Comment (lunaruan) [reply packages/react-devtools-shared/src/backend/agent.js]: That's a good question. I'm not sure. We're currently supporting React 16, which was released 5 years ago, so we're supporting pretty far back. I'm not sure exactly which version causes an error, but if you want to find out and add a comment that'd be great 😊

**Review by lunaruan — APPROVED** [review]
LGTM!

File: packages/react-devtools-shared/src/backend/agent.js [hunk 5]
```diff
@@ -309,22 +309,39 @@ export default class Agent extends EventEmitter<{|
...
-        const id = renderer.getFiberIDForNative(node, true);
-        if (id !== null) {
-          return id;
+      const fiber = renderer.getFiberForNative(node);
+      if (fiber != null) {
+        // check if fiber.stateNode is matching the original hostInstance
+        if (fiber.stateNode === node) {
+          return renderer;
+        } else {
+          bestMatch = renderer;
```
[the remark this answers is not in the document]
Comment (Gam3356) [reply packages/react-devtools-shared/src/backend/agent.js:324]: I'm real humble also have a lot of patient which a lot people don't have in live. Patient is the key

File: packages/react-devtools-shared/src/backend/views/Highlighter/Overlay.js (hunk 3 above)
Comment (Gam3356) [reply packages/react-devtools-shared/src/backend/views/Highlighter/Overlay.js]: Thank you guys! The company have a phone number?

**Review by ihsanali01 — COMMENTED** [review]
Thanks
