### PR TITLE
Warn when multiple instances of React are loaded on the same page

### LINKED ISSUE #2402: Warn when two versions of React are used alongside
People lose hours of work debugging a simple issue: two versions of React being loaded at the same time.

https://github.com/gaearon/react-hot-loader/issues/32#issuecomment-60043061
https://github.com/KyleAMathews/coffee-react-quickstart/issues/10#issuecomment-50655116
https://github.com/gaearon/react-document-title/issues/1#issuecomment-60241045
https://github.com/clayallsopp/react.backbone/issues/26

Because there is no warning right away when this happens, they usually discover the problem through invariant violations. Some of them are descriptive (e.g. `Uncaught Error: Invariant Violation: The handler for Route "hello" must be a valid React component`) and I think I even saw warning that said something like "check if two copies of React are loaded", but some are really cryptic: `Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs...`.

Is there a reason why we don't want to warn *right away* when two copies of React are loaded?

### PR DESCRIPTION
**Pull request by robertknight**
This causes a variety of hard-to-debug issues. This implements the proposed warning from the comments in #2402.

There are already a number of specific places in the code which warn about using multiple copies of React but those don't always get triggered. This adds a check at the top of the main module which spits out a warning before any of the initialization runs.

Fixes #2402

(Apologies, I closed the previous PR due to a force push in my branch)

### CODE REVIEW

File: src/browser/ui/React.js [hunk 1]
```diff
@@ -13,6 +13,30 @@
...
+  // Using multiple instances cause a variety of problems if elements
+  // from different versions are mixed on the same page.
+  //
+  // See issue #2402
+  if (ExecutionEnvironment.canUseDOM) {
+    warning(
+      typeof window.__REACT_VERSION__ === 'undefined',
+      'Multiple instances of React have been initialized on the same page. ' +
+      'Currently initializing React v' + REACT_VERSION + ' but another instance of React v' +
+      window.__REACT_VERSION__ + ' was already initialized'
```
Comment (gaearon) [inline src/browser/ui/React.js]: I don't think versions matter that much. The real issue is, they won't work together well, IMO it's worth explicitly stating that. Also a link to an official `fb.me` gist would be nice but that's up to maintainers.

**Comment by ivan-kleshnin** [comment]
:thumbsup: I was beaten by that not once

**Comment by four43** [comment]
+1, Thanks for this. Indicating there is a problem is the first step, then we can work on solving the problem. This seems like a quick indication that would save a lot of hassle of not knowing what the problem.

**Comment by jsfb** [comment]
It has been long enough, I think everyone has had a chance to see this.  Looks good to me, merging.

**Comment by JedWatson** [comment]
:+1: brilliant, thanks for this.

**Comment by gaearon** [comment]
:+1:

**Comment by robertknight** [comment]
An issue with this at the moment is that it won't produce a warning if mixing React < 0.14 with React >= 0.14. Are there any other global properties on window or document that this warning could check for to detect earlier versions of React?

**Comment by spicyj** [comment]
I don't think this PR is the best solution here. It's legitimate to load two copies of React if you keep them separate – for example, you might want to embed a third-party script which bundles its own copy of React and only renders into its own subtree. As long as you create and render elements with the same copy of React, you won't run into problems (as far as I know of).

I'd prefer something more like #3332 where we warn in problematic cases and leave people alone if they're not mixing things in a problematic way. This PR also doesn't catch cases where you use multiple copies of React on the server in a bad way (since it guards its global assignment in a `canUseDOM`), which is another reason I don't like tacking on a global.

In any event, this adds a *lot* of log spew to the tests and that needs to be fixed.

**Comment by robertknight** [comment]
@spicyj - Apologies about the log spam in the tests, I hadn't noticed as the tests that produce the warnings run early on and I'd only seen the all-green output at the end. I agree that tacking on a global is not particularly pretty, but the solution in #3332 wouldn't have caught the issue I ran into. See https://github.com/facebook/react/issues/2402#issuecomment-89234482 .

Looking at the various posts that @gaearon linked to in the description of 2402 the problem in many of those cases was when using Browserify or Webpack to create an app bundle and inadvertently ending up with dependencies and the main app code pulling in different versions of React. The second time this happened to me the result was actually that only parts of React were duplicated because of Browserify's deduplication of modules that didn't change between the two versions. 

@gaearon - Do you know if there is a way to prevent Webpack from including multiple versions of a dependency in the same bundle, or a way that React could detect if this happens?

**Comment by robertknight** [comment]
Here is a possible alternative which would only handle the case where multiple copies of React are bundled into the same Browserify/Webpack bundle or set of bundles that are part of the same app.

This relies on the 'process' object being available in both Browserify/Webpack and being shared across all modules in the app. This could also (optionally - by testing process.browser) be used server-side in Node. It should also fix the spam in the tests.

````
// warnIfModuleIsDuplicated.js

// check for duplicated modules in the same Node app or Webpack/Browserify bundle.
// This relies on the 'process' module being shared by all modules in the same bundle
// but not between bundles from different vendors.
//
// - This could check process.browser to only warn in Webpack/Browserify bundles.

function warnIfModuleIsDuplicated(name, version) {
	if (typeof process === 'undefined' || typeof process.env !== 'object') {
		return;
	}
        var versionKey = name + '_VERSION';
	var existingVersion = process.env[versionKey];
	if (existingVersion) {
		console.warn('Multiple copies of ' + name + ' were loaded. Found existing version ' + existingVersion +
		  ' while loading version ' + version);
	}
	process.env[versionKey] = version;
}

module.exports = warnIfModuleIsDuplicated;

// in React.js
require('warnIfModuleIsDuplicated')('React', module.exports.version);
````

Does this seem like a better approach? If so I'll submit a PR along these lines.

**Comment by zpao** [comment]
@spicyj should we revert this while we sort it out?

**Comment by syranide** [comment]
@zpao Off-topic, but fixing the tests would be awesome, many currently use multiple (partial?) React instances simultaneously and just happens to work at current. It is a blocker for a PR I had to keep the concatenated IDs stored internally, leaving only minimal sequential IDs in the DOM, say what you want about that PR but it is something we'll want to fix eventually at least :)

**Comment by spicyj** [comment]
@zpao Yeah, let's for now. #3646.
