### PR TITLE
Clear previous children when SVG node doesn't have innerHTML

### LINKED ISSUE #10013: dangerouslySetInnerHTML in IE11 for svg elements
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When using `dangerouslySetInnerHtml` of svg elements, the DOM nodes from the previous render aren't being removed.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/84v837e9/).**

See this [fiddle](https://jsfiddle.net/csmrvzsb/1/)

**What is the expected behavior?**
The DOM should only contain the last rendered value for `dangerouslySetInnerHTML`.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React - 15.5.4+
Browser - IE11
Did this work in previous versions of React? Not sure

After digging around I found #6982 . Which made me think this is happening because of [this line](https://github.com/facebook/react/blob/master/src/renderers/dom/shared/setInnerHTML.js#L37) in `setInnerHTML.js` where it looks like this
```js
  // IE does not have innerHTML for SVG nodes, so instead we inject the
  // new markup in a temp node and then move the child nodes across into
  // the target node
  if (node.namespaceURI === DOMNamespaces.svg && !('innerHTML' in node)) {
    reusableSVGContainer =
      reusableSVGContainer || document.createElement('div');
    reusableSVGContainer.innerHTML = '<svg>' + html + '</svg>';
    var svgNode = reusableSVGContainer.firstChild;
    while (svgNode.firstChild) {
      node.appendChild(svgNode.firstChild);
    }
  }
```

Because there's a call to `node.appendChild(svgNode.firstChild);` it will never remove all of the previous nodes but only add the new ones.
But that's just a guess...

### PR DESCRIPTION
**Pull request by OriR**
Fixes #10013 

I also fixed the UT, but they only work in node 6+ (using Proxy).
I saw that node 4-5 are still supported as development environments, so if this upgrade is not possible right now I'll revert them.
Couldn't get the tests to work otherwise 😞

### CODE REVIEW

**Comment by gaearon** [comment]
Have you tested it in IE?

**Comment by OriR** [comment]
The only IE environment I have is IE11 Windows 10 on Parallels and it's now working there (that's the environment I originally encountered this issue)

**Comment by nhunzaker** [comment]
@gaearon @OriR I can test against IE9 and IE10 in a bit.

**Comment by nhunzaker** [comment]
@gaearon @OriR I have confirmed this works in IE9 and IE10! I made an SVG test fixture for it here:

http://react-svg-innerhtml.surge.sh/svg

We can decide if we want to merge this test fixture later. I can send out a PR for that later.

File: src/renderers/dom/shared/utils/__tests__/setInnerHTML-test.js [hunk 1]
```diff
@@ -24,17 +24,35 @@ describe('setInnerHTML', () => {
...
-        appendChild: jasmine.createSpy(),
-      };
+      node = document.createElementNS(Namespaces.svg, 'svg');
 
+      nodeProxy = new Proxy(node, {
+        has: (target, prop) => {
+          return prop === 'innerHTML' ? false : prop in target;
+        },
+        get: (target, prop) => {
+          if (prop === 'appendChild') {
```
Comment (gaearon) [inline src/renderers/dom/shared/utils/__tests__/setInnerHTML-test.js]: Why do we need this? If you append a child to another parent, it will be removed from the current parent.

Isn't just 

```js
        get: (target, prop) => {
          return target[prop];
        },
```

enough?

Comment (OriR) [reply src/renderers/dom/shared/utils/__tests__/setInnerHTML-test.js]: In the comment [here](https://github.com/facebook/react/pull/11108/files#diff-58de46abac1f1a2608d82f6fb7b1d2b4L27) it says that JSDOM doesn't remove the node from the current parent when moving nodes using `appendChild`, though I didn't verify this myself.

I could check and see if that's still relevant, if not then I can remove the `get` handler altogether.

Comment (gaearon) [reply src/renderers/dom/shared/utils/__tests__/setInnerHTML-test.js]: Please check this, yes. The comments might be very outdated.

Comment (OriR) [reply src/renderers/dom/shared/utils/__tests__/setInnerHTML-test.js]: You were right, this was no longer necessary 🎉 
Removed the `get` handler altogether!

**Comment by gaearon** [comment]
Thanks.
