### PR TITLE
Fire unknown prop warning when rendering client side.

### LINKED ISSUE #6676: DOM property case warning is broken for non-SSR
#6585

### PR DESCRIPTION
**Pull request by jimfb**
Fire unknown prop warning when rendering client side.

Fixes #6676.

### CODE REVIEW

**Comment by jimfb** [comment]
cc @spicyj

File: src/renderers/dom/shared/devtools/ReactDOMUnknownPropertyDevtool.js [hunk 1]
```diff
@@ -26,15 +25,17 @@ if (__DEV__) {
...
+  var warnUnknownProperty = function(name, source) {
     if (DOMProperty.properties.hasOwnProperty(name) || DOMProperty.isCustomAttribute(name)) {
       return;
     }
     if (reactProps.hasOwnProperty(name) && reactProps[name] ||
         warnedProperties.hasOwnProperty(name) && warnedProperties[name]) {
       return;
     }
-
+    if (EventPluginRegistry.registrationNameModules.hasOwnProperty(name)) {
```
Comment (spicyj) [inline src/renderers/dom/shared/devtools/ReactDOMUnknownPropertyDevtool.js]: Why was this necessary?

File: src/renderers/dom/shared/devtools/ReactDOMUnknownPropertyDevtool.js [hunk 2]
```diff
@@ -80,21 +81,21 @@ if (__DEV__) {
...
+    warnUnknownProperty(key, element._source);
+  }
+}
+
 var ReactDOMUnknownPropertyDevtool = {
-  onCreateMarkupForProperty(name, value) {
-    warnUnknownProperty(name);
-  },
-  onSetValueForProperty(node, name, value) {
-    warnUnknownProperty(name);
```
Comment (spicyj) [inline src/renderers/dom/shared/devtools/ReactDOMUnknownPropertyDevtool.js]: Wait, did this change make it so it does warn on non-SSR?

Comment (spicyj) [inline src/renderers/dom/shared/devtools/ReactDOMUnknownPropertyDevtool.js]: Adding this devtool I mean.

File: src/renderers/dom/shared/devtools/ReactDOMUnknownPropertyDevtool.js (hunk 1 above)
Comment (jimfb) [inline src/renderers/dom/shared/devtools/ReactDOMUnknownPropertyDevtool.js]: Because previously we were processing only non-event properties because we were listening in setValueForProperty or whatever, but now we are just reading off the element so we need to filter out the events ourselves.

File: src/renderers/dom/shared/devtools/ReactDOMUnknownPropertyDevtool.js (hunk 2 above)
Comment (jimfb) [inline src/renderers/dom/shared/devtools/ReactDOMUnknownPropertyDevtool.js]: I believe this fixed the issue because the prop names were being filtered prior to this event firing, which means we only fire this event on props that are "correct".  This is a reasonable behavior, because some devtools (eg. perf) might want to know about the DOM operations that are actually being performed, rather than every prop that was specified.  We can re-think how/when those events fire, but that's a much longer discussion.

**Comment by zpao** [comment]
It would be great to get a fix for this out soon. Can we wrap this up?

**Comment by jimfb** [comment]
AFAIK, this is blocked in review.  Ball is in @spicyj's court?  Or if you think it's fine we can just rebase&merge.

**Comment by spicyj** [comment]
We should unify so that onCreateMarkupForProperty and onSetValueForProperty are either both called on unrecognized names or neither. Similarly, both should include events or neither should. It does not make sense that you had to delete some of the listeners and add the event registration check given that the markup warning already worked correctly (as I understand it).

(It almost seems like it would make sense to only have one event here, not sure though.)

**Comment by jimfb** [comment]
A correct solution to the `on...Property` events will likely require a bit of thinking, as per "We can re-think how/when those events fire, but that's a much longer discussion."  We need to better understand what those events are likely to be used for, and that's out of scope for this diff.  It doesn't make sense to unify those functions because the things they would want to expose are different (for instance, setting a property should probably expose the node that is being modified, whereas markup doesn't have a node yet and so it couldn't possibly reference it in the event).  I could delete those events entirely, but that would just create some churn since we're almost certainly going to add something like them back again in the future.  Unless you want me to just delete them, it's a much longer discussion and shouldn't hold up this diff.

For this diff, neither `onCreateMarkupForProperty` nor `onSetValueForProperty` are being used.  The question of what to do with those events is completely orthoginal, and this diff can be merged independent of that discussion.

**Comment by spicyj** [comment]
Okay, I didn't read this carefully enough and didn't realize it doesn't use either of those any more. I'm okay with this. Sorry for the back and forth.

**Comment by facebook-github-bot-0** [comment]
@jimfb updated the pull request.

**Comment by facebook-github-bot-5** [comment]
@jimfb updated the pull request.

**Comment by zpao** [comment]
Going to say this is semver-patch since it fixes a regression, though it could potentially be a noisy change. In reality it probably won't matter too much since the next version will like another minor based on the backlog.
