### PR TITLE
Fix bug with double updates in a single batch

### LINKED ISSUE #2410: Batching can update one component twice, causing unpredictable lifecycle
This one is hard to explain or reproduce but I'll try...

I'm using the following mixin which has changed slightly from the original I found in a gist a while back:

```js

var React = require('react');

var LayeredComponentMixin = {

  componentDidMount: function() {
    this._layer = document.createElement('div');
    document.body.appendChild(this._layer);
    this._renderLayer();
  },

  componentDidUpdate: function() {
    this._renderLayer();
  },

  componentWillUnmount: function() {
    this._unrenderLayer();
    document.body.removeChild(this._layer);
  },

  _renderLayer: function() {
    var layer = this.renderLayer();

    if (null === layer) {
      layer = <noscript />;
    }

    React.render(layer, this._layer);

    if (this.layerDidMount) {
      this.layerDidMount(this._layer);
    }
  },

  _unrenderLayer: function() {
    if (this.layerWillUnmount) {
      this.layerWillUnmount(this._layer);
    }

    React.unmountComponentAtNode(this._layer);
  }

};

module.exports = LayeredComponentMixin;
```

This allows me to create layered components, in my case a modal dialog. I use the following component to build my modals:

```js

var React = require('react');

var ToolboxUserActionCreators = require('../../actions/ToolboxUserActionCreators');

var ModalStore = require('../../stores/ModalStore');

function getStateFromStore() {
  return {
    modalCount: ModalStore.getModalCount()
  };
}

var Modal = React.createClass({

  componentWillMount: function() {
    this.setState({
      modalLevel: ModalStore.getModalCount()
    });
  },

  componentDidMount: function() {
    ModalStore.addChangeListener(this.onChange);
    document.addEventListener('keydown', this.handleKeyDown);
  },

  componentWillUnmount: function() {
    ModalStore.removeChangeListener(this.onChange);
    document.removeEventListener('keydown', this.handleKeyDown);
  },

  getInitialState: function() {
    return getStateFromStore();
  },

  getDefaultProps: function() {
    return {
      className: 'feature'
    }
  },

  render: function() {
    var className               = 'toolbox2-modal-content toolbox2-modal-' + this.props.className;
    var modalBackdropClassName  = 'toolbox2-modal-backdrop';
    var handleBackdropClick     = this.handleBackdropClick;
    var killClick               = this.killClick;
    var modalLevel              = this.state.modalLevel;
    var totalModals             = this.state.modalCount;

    if (modalLevel < totalModals) {
      modalBackdropClassName += ' toolbox2-modal-backdrop-secondary';
    }

    return (
      <div className={modalBackdropClassName} onClick={handleBackdropClick}>
        <div className={className} onClick={killClick}>
          {this.props.children}
        </div>
      </div>
    );
  },

  killClick: function(e) {    
    e.stopPropagation();
  },

  handleBackdropClick: function() {
    this.props.onRequestClose();
  },

  handleKeyDown: function(e) {
    if (e.keyCode === 27) {
      this.handleBackdropClick();
    }
  },

  onChange: function() {
    this.setState(getStateFromStore());
  }

});

module.exports = Modal;
```

This combination works perfectly. That is until I close the highest modal. If an `<input />` component is used inside of the `<Modal>` render method, ie `this.props.children`, the following error is thrown. All other element types (that I've tried including `textarea` and `select` work fine, but `input` throws the following: 

`Uncaught Error: Invariant Violation: getDOMNode(): A component must be mounted to have a DOM node`

The trace is as follows:

```
Uncaught Error: Invariant Violation: getDOMNode(): A component must be mounted to have a DOM node. bundle.js:60783
invariant bundle.js:60783
ReactBrowserComponentMixin.getDOMNode bundle.js:62069
ReactCompositeComponent.createClass.componentDidUpdate bundle.js:64334
assign.notifyAll bundle.js:68718
ON_DOM_READY_QUEUEING.close bundle.js:72258
Mixin.closeAll bundle.js:68960
Mixin.perform bundle.js:68901
Mixin.perform bundle.js:68887
assign.perform bundle.js:56107
(anonymous function) bundle.js:56186
wrapper bundle.js:53734
Mixin.closeAll bundle.js:68960
Mixin.perform bundle.js:68901
ReactDefaultBatchingStrategy.batchedUpdates bundle.js:64050
batchedUpdates bundle.js:56122
ReactEventListener.dispatchEvent bundle.js:64980
```

`ReactCompositeComponent.createClass.componentDidUpdate bundle.js:64334` is [here](https://github.com/facebook/react/blob/b7cd3e7d1de31108594a6698215bfa7bf8619b34/src/browser/ui/dom/components/ReactDOMInput.js#L98).

This only happens when there are several modals on top of each other; one dialog with an `<input />` runs fine with no error.

The weird thing is that the app still runs fine, the error thrown has no impact (apart from being thrown) on how my app performs....

This is on 0.12RC1 using webpack to build.

### LINKED ISSUE #6371: Uncaught Invariant Violation: Must be mounted to trap events when replacing an image with a link to an image
I'm having a hard time narrowing a repro down for this and there seem to be a lot of required moving parts, so I'll try to give as much information as I can.

Relevant snippet of package.json:

```
    "react": "15.0.0-rc.2", // repros w/ 0.14.7 as well
    "react-dom": "15.0.0-rc.2",
    "react-redux": "4.0.6",
    "react-router": "2.0.0-rc5",
    "react-router-redux": "4.0.0-rc.1",
    "redux": "3.2.1",
```

Our routes look something like this:

```
      <Route component={App}>
        <Route component={LayoutNoFooter}>
          <Route component={Page2} />
        </Route>
        <Route component={Layout}>
          <Route component={Page1} />
        </Route>
      </Route>
```

`LayoutNoFooter` simply wraps `Layout` and passes an additional prop in.

I have this component in the `Header`, which is rendered by `Layout`: https://gist.github.com/aaronjensen/86c9643ecc53ad4e9006

`Header` is a react-redux connected component.

`Page1` has a `componentWillUnmount` that dispatches an action that ultimately toggles `searchMode` in `HeaderLogo`. 

When I go from `Page1` to `Page2` the invariant violation fires.

If I `setTimeout` the action dispatch in `componentWillUnmount` it appears to work fine. If I replace `LayoutNoFooter` with `Layout` it appears to work fine.

The invariant violation is on the `img` tag of the `HeaderLogo`

stack

I've tried building a repro in codepen, with a similar structure `setState` calls to simulate react-router and redux, but I suspect they are doing more that would require me to actually build a repro w/ those technologies. If that would be helpful, I can work on it over time and hopefully repro it. Maybe there's enough info here, however. Thanks!

### LINKED ISSUE #6538: React 15 update: Uncaught TypeError: Cannot read property 'addEventListener' of null
Hello,

After updating to React 15.0.1, we are getting the following error:
```
Uncaught TypeError: Cannot read property 'addEventListener' of null
```
image

### PR DESCRIPTION
**Pull request by spicyj**
The code here feels a little convoluted but I don't know how to make it clearer. Suggestions welcome.

cc @facebook/react-core

Fixes #2410. Fixes #6371. Fixes #6538.

I also manually tested the codepen in #3762 and verified it now works.

### CODE REVIEW

File: src/renderers/shared/reconciler/ReactCompositeComponent.js [hunk 1]
```diff
@@ -659,16 +660,16 @@ var ReactCompositeComponentMixin = {
...
+    } else if (this._pendingStateQueue !== null || this._pendingForceUpdate) {
       this.updateComponent(
         transaction,
         this._currentElement,
         this._currentElement,
         this._context,
         this._context
       );
+    } else {
+      this._updateBatchNumber = null;
```
Comment (jimfb) [inline src/renderers/shared/reconciler/ReactCompositeComponent.js]: This line seems to imply that `enqueueUpdate` is getting called on a component that does not need to be updated (meets neither of the two conditions above) - which seems bad/wrong.  What am I missing here?

**Comment by jimfb** [comment]
Looks good to me.  I'm a little confused about why `_updateBatchNumber` would be set (implying `enqueueUpdate` was called) if none of the update conditions are true, but that's not a regression from this PR so I'm happy to take this as-is.

👍

File: src/renderers/shared/reconciler/ReactCompositeComponent.js (hunk 1 above)
Comment (spicyj) [inline src/renderers/shared/reconciler/ReactCompositeComponent.js]: Yeah. :( setState calls enqueueSetState and enqueueCallback which each create a separate batch. That is almost certainly unintended but I left it as-is for now.

Comment (spicyj) [inline src/renderers/shared/reconciler/ReactCompositeComponent.js]: That is, enqueueCallback marks the component dirty which is harmless when done in conjunction with enqueueSetState but kinda silly when it can get split into a separate batch.

Comment (jimfb) [inline src/renderers/shared/reconciler/ReactCompositeComponent.js]: 👍

**Comment by gaearon** [comment]
:+1:

**Comment by facebook-github-bot-7** [comment]
@spicyj updated the pull request.

**Comment by sebmarkbage** [comment]
As discussed in person: If componentWillUnmount is allowed to have side-effects (which I think it needs to because unsubscribing is a side-effect) which includes setState on another component, then it should be outside of the reconciliation pass which is supposed to be side-effect free. Maybe we should queue/defer unmounts?

**Comment by zpao** [comment]
Going to bump this to 15.x since it doesn't apply cleanly without some of the things we're taking there. Shouldn't matter too much in terms of timing.
