### PR TITLE
fix(devtools): expose css vars to reach-ui portal components

### LINKED ISSUE #22678: Improve DevTools CSS variables situation
Related to this comment: https://github.com/facebook/react/pull/22660#pullrequestreview-795368779

The majority of DevTools theme colors are stored in `packages/react-devtools-shared/src/constants`:
https://github.com/facebook/react/blob/5cccacd131242bdea2c2fe4b33fac50d2e3132b4/packages/react-devtools-shared/src/constants.js#L75-L383

But some of them are also stored in `packages/react-devtools-shared/src/devtools/views/root.css`:
https://github.com/facebook/react/blob/5cccacd131242bdea2c2fe4b33fac50d2e3132b4/packages/react-devtools-shared/src/devtools/views/root.css#L2-L18

This is because of how they are referenced in a theme-agnostic way by Reach UI style overrides (for things like tooltips and context menus).

Can we do better here, at least to ensure they stay in sync? For example, can the `ThemeProvider` set the redundant values at the root level when the `SettingsContext` theme changes?

The primary goals of the current architecture are:
1. Don't bleed styles into the global namespace (for our inline package users like Code Sandbox or Replay IO).
2. Don't require awkward forced layout or re-renders for components that read style values programatically.

### PR DESCRIPTION
**Pull request by jyash97**
## Summary
Expose CSS vars to reach UI portal rendered components. 

Closes #22678 

## How did you test this change?
Tested locally with react-devtools-inline app.

Devtools_CSS_Variables

### CODE REVIEW

File: packages/react-devtools-shared/src/devtools/views/Components/reach-ui/tooltip.js [hunk 1]
```diff
@@ -0,0 +1,23 @@
...
+ */
+
+import * as React from 'react';
+import ReachTooltip from '@reach/tooltip';
+import useThemeStyles from '../../useThemeStyles';
+
+const Tooltip = ({children, ...props}) => {
+  const style = useThemeStyles();
+  return (
+    <ReachTooltip style={style} {...props}>
```
Comment (jyash97) [inline packages/react-devtools-shared/src/devtools/views/Components/reach-ui/tooltip.js:17]: Should we add the below class here ? as it is explicitly passed everywhere https://github.com/facebook/react/blob/327d5c48454aaee0d78fa69b7ef96a14605bf93b/packages/react-devtools-shared/src/devtools/views/Tooltip.css#L1-L13

File: packages/react-devtools-shared/src/devtools/views/Settings/SettingsContext.js [hunk 2]
```diff
@@ -296,12 +296,6 @@ export function updateThemeVariables(
     // $FlowFixMe scrollbarColor is missing in CSSStyleDeclaration
     documentElement.style.scrollbarColor = `var(${`--${theme}-color-scroll-thumb`}) var(${`--${theme}-color-scroll-track`})`;
   });
-
-  // The ThemeProvider works by writing DOM style variables to an HTMLDivElement.
-  // Because Portals render in a different DOM subtree, these variables don't propagate.
-  // So we need to also set @reach/tooltip specific styles on the root.
-  updateStyleHelper(theme, 'color-tooltip-background', documentElements);
-  updateStyleHelper(theme, 'color-tooltip-text', documentElements);
```
Comment (jyash97) [inline packages/react-devtools-shared/src/devtools/views/Settings/SettingsContext.js:304]: I dont think we need this know, since we are already updating var based on the context.

File: packages/react-devtools-shared/src/devtools/views/useThemeStyles.js [hunk 3]
```diff
@@ -0,0 +1,28 @@
...
+
+const useThemeStyles = () => {
+  const {theme, displayDensity, browserTheme} = useContext(SettingsContext);
+
+  const style = useMemo(
+    () => ({
+      ...THEME_STYLES[displayDensity],
+      ...THEME_STYLES[theme === 'auto' ? browserTheme : theme],
+    }),
+    [theme, browserTheme, displayDensity],
```
Comment (jyash97) [inline packages/react-devtools-shared/src/devtools/views/useThemeStyles.js:22]: This style just focuses on theme-based vars

**Comment by jyash97** [comment]
Might need help with Flow types here.

File: packages/react-devtools-shared/src/devtools/views/Components/reach-ui/menu-button.js [hunk 4]
```diff
@@ -0,0 +1,28 @@
+/**
+ * Copyright (c) Facebook, Inc. and its affiliates.
+ *
+ * This source code is licensed under the MIT license found in the
+ * LICENSE file in the root directory of this source tree.
+ *
+ * @flow
+ */
```
Comment (jyash97) [inline packages/react-devtools-shared/src/devtools/views/Components/reach-ui/menu-button.js:8]: Note: I have added this by just copying pasting it from other files. Let me know if any change is required here.

**Comment by bvaughn** [comment]
CI's pointing out a couple of minor erros:

### Lint
```
/home/circleci/project/packages/react-devtools-shared/src/devtools/views/Settings/SettingsContext.js
  261:10  error  'updateStyleHelper' is defined but never used  no-unused-vars
```

### Flow
```
Error ----------------------- packages/react-devtools-shared/src/devtools/views/Components/reach-ui/menu-button.js:19:19

Missing type annotation for destructuring.

   19| const MenuList = ({children, ...props}) => {
                         ^^^^^^^^^^^^^^^^^^^^


Error --------------------------- packages/react-devtools-shared/src/devtools/views/Components/reach-ui/tooltip.js:14:18

Missing type annotation for destructuring.

   14| const Tooltip = ({children, ...props}) => {
                        ^^^^^^^^^^^^^^^^^^^^
```

**Comment by jyash97** [comment]
> /home/circleci/project/packages/react-devtools-shared/src/devtools/views/Settings/SettingsContext.js
  261:10  error  'updateStyleHelper' is defined but never used  no-unused-vars
  
  I kept this considering that we might need it in the future. Have removed this in the latest commit.
  
  
  > Flow errors
  
  It would be great if you could guide me in fixing flow related issues

**Comment by bvaughn** [comment]
> It would be great if you could guide me in fixing flow related issues

Flow error is indicating that component props need to be typed. You can find other examples of this within these source, e.g.
https://github.com/facebook/react/blob/99a73ac670ce8d71ae8a690e9795d35cbdfa20b6/packages/react-devtools-timeline/src/EventTooltip.js#L73-L85

**Comment by jyash97** [comment]
I got for the children, its the props destructuring thats confusing me, should I add all props from reach-ui?

**Comment by bvaughn** [comment]
Just add `: any` type for now.

**Comment by jyash97** [comment]
All checks are passing ✅

File: packages/react-devtools-shared/src/devtools/views/Components/reach-ui/tooltip.js (hunk 1 above)
Comment (bvaughn) [reply packages/react-devtools-shared/src/devtools/views/Components/reach-ui/tooltip.js:17]: Would be a nice default then, yes.

File: packages/react-devtools-shared/src/devtools/views/useThemeStyles.js (hunk 3 above)
Comment (bvaughn) [reply packages/react-devtools-shared/src/devtools/views/useThemeStyles.js:22]: I dig this change.

**Review by bvaughn — APPROVED** [review]
I dig it. Approved, but I'll hold off merging for now in case you'd like to make the default Tooltip className chagne.

**Review by bvaughn — APPROVED** [review]
