### PR TITLE
DevTools bugfix: Ignore duplicate welcome "message" events

### LINKED ISSUE #24162: [DevTools Bug] Cannot add node "1" because a node with that id is already in the Store.
### Website or app

http://bestellen-a.cito.nl

### Repro steps

Just opening the console and going to Components or Profiler shows this error.

I noticed that in the console there are two warnings for contentScript.js (I am assuming this file is part of this extension):
﻿
contentScript.js:113 [Violation] 'message' handler took 210ms
contentScript.js:113 [Violation] 'message' handler took 891ms

### How often does this bug happen?

Sometimes

### DevTools package (automated)

react-devtools-extensions

### DevTools version (automated)

4.24.0-82762bea5

### Error message (automated)

Cannot add node "1" because a node with that id is already in the Store.

### Error call stack (automated)

```text
at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:26326:41
    at bridge_Bridge.emit (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:24400:22)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:24566:14
    at listener (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:54300:39)
```

### Error component stack (automated)

_No response_

### GitHub query string (automated)

```text
https://api.github.com/search/issues?q=Cannot add node  because a node with that id is already in the Store. in:title is:issue is:open is:public label:"Component: Developer Tools" repo:facebook/react
```

### PR DESCRIPTION
**Pull request by bvaughn**
Resolves #24162

### CODE REVIEW

File: packages/react-devtools-extensions/src/contentScript.js [hunk 1]
```diff
@@ -25,15 +25,15 @@ function handleMessageFromDevtools(message) {
...
-    evt.data &&
-    evt.data.source === 'react-devtools-bridge'
+    event.source === window &&
+    event.data &&
+    event.data.source === 'react-devtools-bridge'
   ) {
     backendInitialized = true;
 
-    port.postMessage(evt.data.payload);
+    port.postMessage(event.data.payload);
```
Comment (bvaughn) [inline packages/react-devtools-extensions/src/contentScript.js:36]: This change wasn't necessary, the name `evt` just irked me.

File: packages/react-devtools-extensions/src/backend.js [hunk 2]
```diff
@@ -14,6 +16,21 @@ function welcome(event) {
...
+  if (welcomeHasInitialized) {
+    console.warn(
+      'React DevTools detected duplicate welcome "message" events from the content script.',
+    );
+    return;
+  }
+
+  welcomeHasInitialized = true;
+
   window.removeEventListener('message', welcome);
```
Comment (bvaughn) [inline packages/react-devtools-extensions/src/backend.js:34]: The above change seems kind of silly, since we're removing the event handler here– but it seems like the batching (mentioned in the comment above) prevents the event handler from being removed properly.

Comment (bvaughn) [reply packages/react-devtools-extensions/src/backend.js:38]: It looks like maybe the `removeEventHandler` part of the event handler API is being broken– such that we can _register_ an event handler on the `window` but then never remove it. This is a pretty serious bug that should be fixed (somewhere in react-easy-state maybe?)

File: packages/react-devtools-extensions/src/contentScript.js (hunk 1 above)
Comment (lunaruan) [reply packages/react-devtools-extensions/src/contentScript.js:36]: 😂

**Comment by lunaruan** [comment]
I get this change, but it makes me sad 😭

**Review by lunaruan — APPROVED** [review]

**Comment by jimmytheguitarman** [comment]
I had this issue myself, and then i noticed two react icons in the top left part of my browser. 
Appears that i had the react dev tools extension in the browser installed, and i npm installed it in my project.

After removing the browser version, everything was fine.
