### PR TITLE
DevTools Profiler: Improve how empty commits are filtered

### LINKED ISSUE #16446: Error: "Could not find node with id "266" in commit tree"
PLEASE INCLUDE REPRO INSTRUCTIONS AND EXAMPLE CODE

I got this error when I click 'Ranked'.

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.0.4-3c6a219

Call stack: at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:11:11441
    at Map.forEach (<anonymous>)
    at commitIndex (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:11:11387)
    at e.getRankedChartData (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:11:11920)
    at _i (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:56:277123)
    at Ha (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:55890)
    at Xl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:98280)
    at Hl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:84255)
    at Fl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:81285)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:25363

Component stack: in _i
    in div
    in div
    in div
    in Or
    in Unknown
    in n
    in Unknown
    in div
    in div
    in Ha
    in le
    in ve
    in ko
    in Ul

### PR DESCRIPTION
**Pull request by bvaughn**
DevTools Profiler: Improve how empty commits are filtered

Previously, DevTools filtered empty commits on the backend, while profiling, through the use of a bailout heuristic that React currently happens to use. This approach was brittle and may have exacerbated the long-standing Profiler bug #16446.

This PR removes that heuristic and adds as a post-processing filtering pass instead. This removes the coupling between DevTools and a React internal implementation detail that may change.

I believe DevTools has two choices of criteria for this filtering:
* Filter commits that have no actual duration metadata.
* Filter commits that have no recorded operations (no mutations to the tree, no changed tree base durations).

I chose the first option, filtering by commits that have no reported metadata. It will miss an edge case, `unmountComponentAtNode`, but we would have nothing meaningful to show in the Profiler for that case anyway. (This particular case is why one of the snapshots changed with this commit.)

The second option, filtering by recorded operations, could potentially miss a more important edge case: where a component *did* render, but its `treeBaseDuration` didn't change. (In that event, there would be no tree `operations` sent.)

I believe this PR might resolve the longstanding issue #16446 but since it's very hard to reproduce, I'm not sure.

### CODE REVIEW

File: packages/react-devtools-shared/src/__tests__/__snapshots__/profilingCache-test.js.snap [hunk 1]
```diff
@@ -1520,19 +1510,7 @@ Object {
...
-    Array [
-      1,
-      6,
-      0,
-      2,
-      4,
-      9,
-      8,
-      7,
-      6,
```
Comment (bvaughn) [inline packages/react-devtools-shared/src/__tests__/__snapshots__/profilingCache-test.js.snap]: Just to better annotate this change:
```sh
  1,  # rendered ID
  6,  # root ID
  0,  # string table isze
  2,  # TREE_OPERATION_REMOVE operation
  4,  # number of Fibers removed
  9,  # ids...
  8,  
  7,  
  6,
```

As explained in the PR description, it was expected.
