### PR TITLE
Make ReactTestUtils.scryRenderedComponentWithClass find multiple classes

### LINKED ISSUE #4952: scryRenderedDOMComponentsWithClass for multiple class names in 0.14-rc1
Some of my tests are failing in 0.14-rc1 because `scryRenderedDOMComponentsWithClass` does not accept multiple class names [anymore](https://github.com/facebook/react/commit/e704503dc78476076c9f12e5147f26b0725c1e35#commitcomment-13362637). E.g. [testing a node](https://github.com/gpbl/react-day-picker/blob/master/test/DayPicker.js#L137-L139) that does have multiple classes:

```js
const nextButton = TestUtils.findRenderedDOMComponentWithClass(dayPickerEl,
      "DayPicker-NavButton DayPicker-NavButton--next");
expect(nextButton).to.not.be.undefined;
```

giving the result:

```
$ Error: Did not find exactly one match (found: 0) for class:DayPicker-NavButton DayPicker-NavButton--next
```

Is this change in the API necessary? Or: how should I test this kind of nodes?

### PR DESCRIPTION
**Pull request by zpao**
Fixes #4952

This now allows an array of classnames which is a better API to use but it also allows the whitespace separated API from before work (better than it used to but also technically different behavior).

### CODE REVIEW

File: src/test/ReactTestUtils.js [hunk 1]
```diff
@@ -174,14 +174,16 @@ var ReactTestUtils = {
...
+    }
     return ReactTestUtils.findAllInRenderedTree(root, function(inst) {
       if (ReactTestUtils.isDOMComponent(inst)) {
-        var instClassName = ReactDOM.findDOMNode(inst).className;
-        return (
-          instClassName &&
-          (('' + instClassName).split(/\s+/)).indexOf(className) !== -1
-        );
+        var classList = ReactDOM.findDOMNode(inst).className.split(/\s+/);
+        return classNames.reduce(function(accum, className) {
```
Comment (spicyj) [inline src/test/ReactTestUtils.js]: .every?

Comment (zpao) [inline src/test/ReactTestUtils.js]: Uh yea, that would be a bit clearer
