### PR TITLE
Fix browser bundle for AMD

### LINKED ISSUE #8301: react-dom 15.4.0 does not work in AMD enviroment
If I try to load react-dom with RequireJS, I get an error: "Mismatched anonymous define()".
Looking at the react-dom from the 15.4.0 distribution (https://cdnjs.cloudflare.com/ajax/libs/react/15.4.0/react-dom.js), I notice that there seem to be two UMD wrappers at the top.
This is probably related to the change in the packaging structure (#7164 and #7168).

### PR DESCRIPTION
**Pull request by zpao**
Fixes #8301

I confirmed that the webpack bundling that got us into this situation is still ok so I think this should be safe. I didn't explicitly check SystemJS but I think it should be in the same boat.

cc @gaearon

### CODE REVIEW

**Comment by zpao** [comment]
For anybody following along at home, this doesn't fix SystemJS. I was definitely wrong to assume that. It gets detected as AMD in the outer wrapper but it's `define` resets and the inner wrapper doesn't detect as AMD, falling back to the global.

File: grunt/config/browserify.js [hunk 1]
```diff
@@ -63,28 +63,37 @@ function simpleBannerify(src) {
...
+// call that function and return it.
+// 2. We put our own UMD wrapper around that fixed internal function, ensuring
+// React is in scope. This outer wrapper is essentially the same UMD wrapper
+// browserify would create, just handling the scope issue.
+// Is this insane? Yes.
+// Does it work? Yes.
+// Should it go away ASAP? Yes.
 function wrapperify(src) {
-  src = src.replace('define([],f)', 'return f()');
+  src = src.replace(
```
Comment (gaearon) [inline grunt/config/browserify.js]: Let's throw if there are no matches.

Comment (zpao) [inline grunt/config/browserify.js]: 👍 done.
