### PR TITLE
Fail tests on any un-spied warnings

### LINKED ISSUE #3890: Get to 0 warnings in tests
We have some unhandled warnings in our tests, which isn't great. We should clean those up and then we can make it so that any unhandled warnings are test failures.

### PR DESCRIPTION
**Pull request by spicyj**
Fixes #3890. Fixed existing tests to all set `console.error` back to its original value when they're done by making them use spyOn.

### CODE REVIEW

File: src/isomorphic/modern/class/__tests__/ReactTypeScriptClass-test.ts [hunk 1]
```diff
@@ -311,13 +311,12 @@ describe('ReactTypeScriptClass', function() {
...
   it('throws if no render function is defined', function() {
-    var warn = jest.genMockFn();
-    console.error = warn;
+    spyOn(console, 'error');
 
     expect(() => React.render(React.createElement(Empty), container)).toThrow();
 
-    expect(warn.mock.calls.length).toBe(1);
-    expect(warn.mock.calls[0][0]).toBe(
+    expect((<any>console.error).argsForCall.length).toBe(1);
```
Comment (zpao) [inline src/isomorphic/modern/class/__tests__/ReactTypeScriptClass-test.ts]: Do we need to typecast this to make TypeScript happy?

File: test/lib/jasmine-execute.js [hunk 2]
```diff
@@ -16,4 +16,31 @@ document.write('<style> @import \'../vendor/jasmine/jasmine.css?_=' + (+new Date
...
+  var oldError = console.error;
+  var newError = function() {
+    oldError.apply(this, arguments);
+    var spec = env.currentSpec;
+    if (spec) {
+      var expectationResult = new jasmine.ExpectationResult({
+        passed: false,
+        message:
+          'Expected test not to warn. If the warning is expected, mock it ' +
+          'out and test that the warning occurs.',
```
Comment (zpao) [inline test/lib/jasmine-execute.js]: Perhaps mention using `spyOn` explicitly?

Also, this isn't getting used by jest. That's not ideal but it's fine for now.

Comment (spicyj) [inline test/lib/jasmine-execute.js]: I know. It's easy to copy/paste this to the jest config but I figured it's better to just have it in one place for now, so I opted for here so Travis gets it.

File: src/isomorphic/modern/class/__tests__/ReactTypeScriptClass-test.ts (hunk 1 above)
Comment (spicyj) [inline src/isomorphic/modern/class/__tests__/ReactTypeScriptClass-test.ts]: Yeah.
