### PR TITLE
Fix shallow renderer callbacks

### LINKED ISSUE #10089: react-test-renderer/shallow setState callback is never called
**Do you want to request a *feature* or report a *bug*?**

Bug, following on from https://github.com/airbnb/enzyme/issues/953

**What is the current behavior?**

In `node_modules/react-test-renderer/cjs/react-test-renderer-shallow.development.js`, the callback second argument to `setState` is never called.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/84v837e9/).**

```js
import ShallowRenderer from 'react-test-renderer/shallow'

const renderer = new ShallowRenderer()
renderer.render(<YourComponent />)
const instance = renderer.getMountedInstance()
instance.methodThatCallsSetState()
// => callback passed into setState as the second argument within methodThatCallsSetState is never called
```

The shallow renderer code is as follows:

```js
Updater.prototype.enqueueSetState = function enqueueSetState(publicInstance, partialState, callback, callerName) {
  if (typeof partialState === 'function') {
    partialState = partialState(publicInstance.state, publicInstance.props);
  }

  this._renderer._newState = _extends({}, publicInstance.state, partialState);

  this._renderer.render(this._renderer._element, this._renderer._context);
};
```

As you can see, the callback is ignored. In the deep renderer (`node_modules/react-test-renderer/cjs/react-test-renderer.development.js`), the callback _is_ used:
```js
enqueueSetState: function (instance, partialState, callback) {
  var fiber = ReactInstanceMap_1.get(instance);
  var priorityLevel = getPriorityContext(fiber, false);
  callback = callback === undefined ? null : callback;
  {
    warnOnInvalidCallback(callback, 'setState');
  }
  addUpdate$1(fiber, partialState, callback, priorityLevel);
  scheduleUpdate(fiber, priorityLevel);
}
```

**What is the expected behavior?**

The callback is called.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React v16, `react-test-renderer` v16. I don't know if this worked before.

### PR DESCRIPTION
**Pull request by codepodu**
Shallow renderer now executes any callbacks passed to setState/replaceState/forceUpdate.

Fixes #10089 
I've incorporated failing tests provided in #10092 by @Leeds-eBooks.

### CODE REVIEW

File: src/renderers/dom/test/__tests__/ReactTestUtils-test.js [hunk 1]
```diff
@@ -405,6 +405,108 @@ describe('ReactTestUtils', () => {
...
+    const result = shallowRenderer.render(<SimpleComponent />);
+    expect(result.props.children).toBe(0);
+
+    const callback = jest.fn(function() {
+      expect(this).toBe(instance);
+    });
+
+    // No longer a public API, but we can test that it works internally by
+    // reaching into the updater.
+    shallowRenderer._updater.enqueueReplaceState(
```
Comment (bvaughn) [inline src/renderers/dom/test/__tests__/ReactTestUtils-test.js]: Wish we had a better way to test this~ but there's precedent in at least a half dozen other tests so it's probably okay. 😁

**Comment by mabounassif** [comment]
Which version was this release in?

**Comment by bvaughn** [comment]
It was merged on July 10th, which was in between the last 16 alpha release and the first beta release I think. Not that you'd be interested in installing either. This fix is in all of the 16.x final releases though.

**Comment by mabounassif** [comment]
It's not working for me - `setState` callback is not being called. Very similar to the following issue: https://github.com/airbnb/enzyme/issues/953.

Using
```
"react": "^16.1.1"
"enzyme": "^3.1.1"
```

Will investigate more and try to pinpoint the issue

**Comment by bvaughn** [comment]
Open a new issue with repro steps if you're convinced it's still an issue. 😄 

PR #10106 did add tests for this though, FWIW.

**Comment by mabounassif** [comment]
The library I'm depending on is still pointing to the older version of `react-test-renderer`.
https://github.com/airbnb/enzyme/blob/master/packages/enzyme-adapter-react-16/package.json#L42

All is good. Sorry about the false alarm.
