### PR TITLE
Use defaultValue instead of setAttribute('value')

### LINKED ISSUE #7328: IE 11 and Edge no longer prompt to remember password on controlled form
**Do you want to request a _feature_ or report a _bug_?**
Bug (regression) IE/Edge

**What is the current behavior?**
On React > v15.2.0, Edge and IE11 do not prompt the user to save the password for the form

**Steps to reproduce**
With react 15.1.0:
https://jsfiddle.net/69z2wepo/49876/
With React 15.2.0:
https://jsfiddle.net/69z2wepo/49877/

**What is the expected behavior?**
The browser prompts the user to save their password for the form

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React > 15.2.0. It worked in React 15.2.0
IE 11, Edge

### PR DESCRIPTION
**Pull request by nhunzaker**
This commit replaces the method of synchronizing an input's value
attribute from using setAttribute to assigning defaultValue. This has
several benefits:

- Fixes issue where IE10+ and Edge password icon disappears (#7328)
- Fixes issue where toggling input types hides display value on dates
  in Safari (unreported). See [a gif](https://user-images.githubusercontent.com/590904/32701917-13b2911e-c7ac-11e7-8d82-9b777dc61a0f.gif).
- Removes mutationMethod behaviors from DOMPropertyOperations
- Removes the need to re-assign `min`, `max`, and other input props to ensure execution order. value and defaultValue always assign later.

This should replace https://github.com/facebook/react/pull/8266, which is out of date and the fork has been removed :(.

### Test Plan

Visit the fixtures here: http://react-value-attribute-change.surge.sh/

1. Test [text inputs](http://react-value-attribute-change.surge.sh/text-inputs)
2. Test [number inputs](http://react-value-attribute-change.surge.sh/number-inputs)
3. Test [password inputs](http://react-value-attribute-change.surge.sh/password-inputs) in IE10+ and Edge
4. Test [input change events](http://react-value-attribute-change.surge.sh/input-change-events)

I've tested these in the following browsers (oof):

- [x] Chrome 42
- [x] Chrome 61
- [x] IE 9
- [x] IE 10
- [x] IE 11
- [x] Edge 15
- [x] Edge 16
- [x] Firefox 56
- [x] Firefox ESR (47)
- [x] iOS Safari 6
- [x] iOS Safari 10
- [x] iOS Safari 11
- [x] Desktop Safari 11
- [x] Desktop Safari 10
- [x] Desktop Safari 7
- [x] Desktop Safari 6  
- [x] Chrome for Android (latest)

---

This should fix #7328 (https://github.com/facebook/react/pull/8266)

### CODE REVIEW

File: fixtures/dom/src/components/fixtures/number-inputs/index.js [hunk 1]
```diff
@@ -27,7 +27,7 @@ function NumberInputs() {
         <NumberTestCase />
 
         <p className="footnote">
-          <b>Notes:</b> Chrome and Safari clear trailing decimals on blur. React
+          <b>Notes:</b> Modern Chrome and Safari {'<='} 6 clear trailing decimals on blur. React
```
Comment (nhunzaker) [inline fixtures/dom/src/components/fixtures/number-inputs/index.js]: Dropping decimal places on blur seems to no longer be an issue in modern safari 🎉 .

File: packages/react-dom/src/__tests__/ReactDOMInput-test.js [hunk 2]
```diff
@@ -1270,6 +1279,36 @@ describe('ReactDOMInput', () => {
       expect(node.getAttribute('value')).toBe('2');
     });
```
Comment (nhunzaker) [inline packages/react-dom/src/__tests__/ReactDOMInput-test.js]: I had to update these two tests because overriding the `value` property was done such that you couldn't check the current value.

**Comment by jquense** [comment]
🎉🎉

File: packages/react-dom/src/client/ReactDOMFiberInput.js [hunk 3]
```diff
@@ -57,30 +57,14 @@ function isControlled(props) {
...
-  );
+  var hostProps = Object.assign({}, props, {
+    defaultChecked: undefined,
+    defaultValue: undefined,
+    value: undefined,
+    checked: checked != null ? checked : node._wrapperState.initialChecked,
+  });
 
   return hostProps;
 }
```
Comment (nhunzaker) [inline packages/react-dom/src/client/ReactDOMFiberInput.js]: `value` no longer gets assigned to inputs using `DOMPropertyOperations`. This means that `value` _always_ gets set after every normal property is set. We don't have to mess with property assignment order here anymore.

File: packages/react-dom/src/client/ReactDOMFiberInput.js [hunk 4]
```diff
@@ -235,32 +211,20 @@ export function updateWrapper(element: Element, props: Object) {
...
-      node.value = node.defaultValue;
-      break;
-    default:
-      node.value = node.value;
-      break;
+    // value must be assigned before defaultValue. This fixes an issue where the
+    // visually displayed value of date inputs disappears on mobile Safari and Chrome:
+    // https://github.com/facebook/react/issues/7233
+    node.defaultValue = value;
   }
```
Comment (nhunzaker) [inline packages/react-dom/src/client/ReactDOMFiberInput.js]: This _might_ fix #8395 and invalidate https://github.com/facebook/react/pull/11202. I need to verify.

Comment (nhunzaker) [reply packages/react-dom/src/client/ReactDOMFiberInput.js]: Basically we just need defaultValue to always get set after value. This won't happen if an empty value is provided. That might avoid initial validation issues in Firefox.

**Comment by nhunzaker** [comment]
Fixed lint and formatting. Now I just need to figure out how to get Flow to think HTMLInputElement has a `defaultValue` property.

File: packages/react-dom/src/client/ReactDOMFiberInput.js [hunk 5]
```diff
@@ -327,3 +291,21 @@ function updateNamedCousins(rootNode, props) {
...
+//
+// https://github.com/facebook/react/issues/7253
+function synchronizeDefaultValue(node: Element, type: ?string, value: string) {
+  if (
+    // Focused number inputs synchronize on blur. See ChangeEventPlugin.js
+    (type !== 'number' || node.ownerDocument.activeElement !== node) &&
+    node.defaultValue !== value
+  ) {
+    node.defaultValue = value;
+  }
```
Comment (nhunzaker) [inline packages/react-dom/src/client/ReactDOMFiberInput.js]: Assigning `defaultValue` sets the `value` attribute, but doesn't have the side-effect of removing the password icon in IE. I'm not sure how I discovered this. I wish I had that kind of intuition for more useful things 😸.

screen shot 2017-11-12 at 12 40 05 pm

**Comment by nhunzaker** [comment]
K. I think flow is happy. Hopefully the changes are reasonable.

**Comment by gaearon** [comment]
What is blocking this from merge?

**Comment by nhunzaker** [comment]
Nothing. Just approval. @jquense does 🎉 🎉 mean i pass? 😛

**Comment by gaearon** [comment]
I can try running our internal WebDriver tests on this.

**Comment by gaearon** [comment]
Internal diff https://fburl.com/h09o8qip
Test run (if I correctly scheduled it) https://fburl.com/y6hz1zwc

**Comment by nhunzaker** [comment]
I can't view those pages, but 🤞🤞🤞

**Comment by gaearon** [comment]
Passed on our end. I don't know if they test this code path but if somebody on the DOM team stamps it let's go!

**Comment by jquense** [comment]
i'll take a look this weekend :)

**Comment by nhunzaker** [comment]
No rush! 🦃🦃🍰🍰🍗🍗

File: packages/react-dom/src/__tests__/ReactDOMInput-test.js [hunk 6]
```diff
@@ -1270,6 +1279,36 @@ describe('ReactDOMInput', () => {
...
 
+    it('initially sets the value attribute on mount', () => {
```
Comment (gaearon) [inline packages/react-dom/src/__tests__/ReactDOMInput-test.js]: Can you explain why these tests were added, and why they are important?

File: packages/react-dom/src/client/ReactDOMFiberInput.js [hunk 7]
```diff
@@ -190,6 +176,7 @@ export function updateWrapper(element: Element, props: Object) {
   }
 
   var value = props.value;
+  var valueAsString = '' + props.value;
```
Comment (gaearon) [inline packages/react-dom/src/client/ReactDOMFiberInput.js]: Nit: we might need it. So maybe we should only calculate it when necessary? Also this is a second `props.value` access but we've already just read it.

I would just leave inline conversions.

File: packages/react-dom/src/client/ReactDOMFiberInput.js [hunk 8]
```diff
@@ -235,32 +213,20 @@ export function updateWrapper(element: Element, props: Object) {
...
   var node = ((element: any): InputWithWrapperState);
+  var hasUserInput = node.value !== '';
+  var value = node._wrapperState.initialValue;
 
-  // Detach value from defaultValue. We won't do anything if we're working on
-  // submit or reset inputs as those values & defaultValues are linked. They
-  // are not resetable nodes so this operation doesn't matter and actually
-  // removes browser-default values (eg "Submit Query") when no value is
-  // provided.
+  if (value !== '' || props.hasOwnProperty('value')) {
```
Comment (jquense) [inline packages/react-dom/src/client/ReactDOMFiberInput.js]: `hasUserInput`?

File: packages/react-dom/src/__tests__/ReactDOMInput-test.js (hunk 6 above)
Comment (nhunzaker) [reply packages/react-dom/src/__tests__/ReactDOMInput-test.js]: Good catch. These aren't necessary, but I needed them mid-way through making the change. I'll remove these.

I added these tests when I removed the `value` mutation method and [removed `value` from the property object in `getHostProps`](https://github.com/facebook/react/pull/11534/files#diff-2364bccf91025269af6a1cc9483ffdb3R67). Without the addition of [assigning `value` in the post mount hook](https://github.com/facebook/react/pull/11534/files#diff-2364bccf91025269af6a1cc9483ffdb3R223), inputs never received an initial value.

But it looks like these aren't necessary any more. I've also since removed specific checks for `reset` and `submit` input types too. Checking again, half the ReactDOMInput test suite fails when the value assignment code in `postMountWrapper` goes away.

Comment (nhunzaker) [reply packages/react-dom/src/__tests__/ReactDOMInput-test.js]: Removed in fde83b2

File: packages/react-dom/src/client/ReactDOMFiberInput.js (hunk 8 above)
Comment (nhunzaker) [reply packages/react-dom/src/client/ReactDOMFiberInput.js]: Ah this is confusing. `node.value` is different from `node._wrapperState.initialValue`.`hasUserInput` tracks if a user has started typing into an input before JS evaluates (in the case of server-side rendering).

When a component mounts, we don't want to initial set `value` or `defaultValue` if they aren't provided in props, and we don't want to set `value` to the initial React-provide value if a user has already entered text.

I'm going to rename the `value` variable to `initialValue`. I think I can also change this check to avoid type comparison and just check for presence of the `value` or `defaultValue` in `props`.

File: packages/react-dom/src/client/ReactDOMFiberInput.js [hunk 9]
```diff
@@ -18,8 +18,10 @@ import ReactControlledValuePropTypes from '../shared/ReactControlledValuePropTyp
 import * as inputValueTracking from './inputValueTracking';
 
 type InputWithWrapperState = HTMLInputElement & {
+  value: string,
+  defaultValue: string,
```
Comment (jquense) [inline packages/react-dom/src/client/ReactDOMFiberInput.js]: are these needed, HTMLInputElement should already contain these properties i think yeah?

File: packages/react-dom/src/client/ReactDOMFiberInput.js (hunk 8 above)
Comment (nhunzaker) [reply packages/react-dom/src/client/ReactDOMFiberInput.js]: Done in 90ed488

File: packages/react-dom/src/client/ReactDOMFiberInput.js (hunk 9 above)
Comment (nhunzaker) [reply packages/react-dom/src/client/ReactDOMFiberInput.js]: Huh. Flow was yelling at me, but not anymore. Thanks!

d8925a2

File: packages/react-dom/src/client/ReactDOMFiberInput.js (hunk 7 above)
Comment (nhunzaker) [reply packages/react-dom/src/client/ReactDOMFiberInput.js]: Done in 5e194d1

File: packages/react-dom/src/shared/HTMLDOMPropertyConfig.js [hunk 10]
```diff
@@ -83,34 +83,6 @@ var HTMLDOMPropertyConfig = {
     htmlFor: 'for',
     httpEquiv: 'http-equiv',
   },
-  DOMMutationMethods: {
-    value: function(node, value) {
-      if (value == null) {
-        return node.removeAttribute('value');
```
Comment (aweary) [inline packages/react-dom/src/shared/HTMLDOMPropertyConfig.js]: This would only happen when switching from a controlled to uncontrolled component right? Since we're not removing the attribute anymore could this break anybody?

**Comment by gaearon** [comment]
Note: let's hold off merging. We're doing a release tomorrow. Then can merge.

File: packages/react-dom/src/shared/HTMLDOMPropertyConfig.js (hunk 10 above)
Comment (nhunzaker) [reply packages/react-dom/src/shared/HTMLDOMPropertyConfig.js]: This is for elements that use the `value` attribute, like `<progress />` and `<meter />`. I am not sure inputs can actually ever have a null `value` prop because:

1. [An input sets an "initial value" on creation](https://github.com/facebook/react/blob/master/packages/react-dom/src/client/ReactDOMFiberInput.js#L81)
2. If that value is null, it falls back to `defaultValue`
3. [If defaultValue is null, it falls back to an empty string](https://github.com/facebook/react/blob/master/packages/react-dom/src/client/ReactDOMFiberInput.js#L140)

Additionally, React yells at you for switching between a controlled and uncontrolled input, and if the value is ever null.

Comment (jquense) [reply packages/react-dom/src/shared/HTMLDOMPropertyConfig.js]: Doesn't react yell if you switch to undefined? Null gets a different warning about using an empty string

Comment (nhunzaker) [reply packages/react-dom/src/shared/HTMLDOMPropertyConfig.js]: Yes. You get the following warnings when switching to and from `undefined`:

> Warning: A component is changing an uncontrolled input of type undefined to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-components

**Comment by nhunzaker** [comment]
Conflicts resolved and 16.2.0 is a thing. @gaearon Safe to merge?

File: packages/react-dom/src/shared/HTMLDOMPropertyConfig.js (hunk 10 above)
Comment (aweary) [reply packages/react-dom/src/shared/HTMLDOMPropertyConfig.js]: Right, it warns and it will also remove the attribute. With this change, I believe it will warn but the attribute will not be removed.

**Comment by gaearon** [comment]
Let's give 16.2.0 a few days to breathe? Might need to cut some hotfixes.

**Comment by nhunzaker** [comment]
Sure thing, 👍

File: packages/react-dom/src/shared/HTMLDOMPropertyConfig.js (hunk 10 above)
Comment (nhunzaker) [reply packages/react-dom/src/shared/HTMLDOMPropertyConfig.js]: Good catch. It does not remove the attribute, but the behavior is inconsistent with master. In the absence of a `value` attribute, an input reverts back to the initial value it was created with. For example:

**React 16.2.0:**

value

**However, with this change, the attribute is never reverted to that initial value:**

value-local

I'll add test coverage for this case. Sorry to neglect the distinction between `null` and `undefined` 😦

**Comment by nhunzaker** [comment]
In 5f9b50f925089213fe203f66a9f12607ded01fb4 I made it so the `value` attribute reverts back to the initial state of the controlled input when given null/undefined. This is consistent with the original behavior. I've also added test coverage for those cases.

**Comment by gaearon** [comment]
Do changes need another round of browser testing?

**Comment by nhunzaker** [comment]
I don't think so. The DOM mechanics have not changed. I can do another round if you'd like though.

**Comment by nhunzaker** [comment]
I'll take a pass tomorrow morning. It should not take long with the existing tmp fixture I have.

**Comment by gaearon** [comment]
Cool, thanks!

**Comment by gaearon** [comment]
I decided to get this in for now, and if you discover something that's off, please send another PR.
