### PR TITLE
Fix <input> with type date/time/etc. issue on mobile browsers

### LINKED ISSUE #7233: Date input with defaultValue regression in 15.2
On Chrome browser or webview on Android, an `<input type="date">` with a defaultValue specified does not show the defaultValue with react 15.2, but it works in 15.1.

I've tested on multiple devices, including tablets and phones. My phone has chrome/51.0.2704.81.

It works ok on Chrome desktop browser.

With React 15.1:
screenshot_20160708-194606

With React 15.2
screenshot_20160708-194726

Additionally, if you tap the blank date field, and select the date which is what the defaultValue was set to, it leaves the field blank and no onChange event is triggered.

Test case:
      ` <input type="date" defaultValue='2016-07-08'/>`

https://jsfiddle.net/kellycampbell/69z2wepo/48384/

Inspecting the elements rendered on the Android device via chrome devtools, the 15.1 version renders as:
`<input type="date">
`

The 15.2 version renders with the value in the element:
`<input type="date" value="2016-07-08">
`

This also affects `<input type="time">`, and possibly other types, but I've only tested date and time.

### PR DESCRIPTION
**Pull request by keyanzhang**
Fixes #7233. 

In short, iOS Safari acts weird when dealing with HTML5 input types: assigning `node.defaultValue` doesn't let the browser update the UI, so we'll need to set `node.value` to a dummy value then reset it. 

Reviewers: @spicyj @jimfb 

Test Plan:
https://jsbin.com/sefihic/edit?js,output should work on iOS Safari and other mobile browsers (I tested with iOS Safari, iOS Chrome, and Android Browser)

### CODE REVIEW

**Comment by dozoisch** [comment]
Tested in my product! Works perfectly :)!  :shipit:

File: src/renderers/dom/client/wrappers/ReactDOMInput.js [hunk 1]
```diff
@@ -230,8 +230,24 @@ var ReactDOMInput = {
...
+      case 'submit':
+      case 'reset':
+        break;
+      case 'date':
+      case 'datetime':
+      case 'datetime-local':
+      case 'month':
+      case 'time':
+      case 'week':
+        // this fixes the no-show issue on iOS Safari: https://github.com/facebook/react/issues/7233
```
Comment (spicyj) [inline src/renderers/dom/client/wrappers/ReactDOMInput.js]: Can you say "iOS Safari and Android Chrome" and capitalize the sentence?

File: src/renderers/dom/client/wrappers/ReactDOMInput.js [hunk 2]
```diff
@@ -230,8 +230,24 @@ var ReactDOMInput = {
...
     // removes browser-default values (eg "Submit Query") when no value is
     // provided.
-    if (props.type !== 'submit' && props.type !== 'reset') {
-      node.value = node.value;
+
+    switch (props.type) {
+      case 'submit':
+      case 'reset':
+        break;
+      case 'date':
```
Comment (spicyj) [inline src/renderers/dom/client/wrappers/ReactDOMInput.js]: Can you add 'color'?

File: src/renderers/dom/client/wrappers/ReactDOMInput.js [hunk 3]
```diff
@@ -230,8 +230,24 @@ var ReactDOMInput = {
...
+      case 'datetime':
+      case 'datetime-local':
+      case 'month':
+      case 'time':
+      case 'week':
+        // this fixes the no-show issue on iOS Safari: https://github.com/facebook/react/issues/7233
+        node.value = '';
```
Comment (kellycampbell) [inline src/renderers/dom/client/wrappers/ReactDOMInput.js]: What's the reason for this assignment since the next line reassigns it to defaultValue? Also, line 249 looks like a no-op as well.

Comment (spicyj) [inline src/renderers/dom/client/wrappers/ReactDOMInput.js]: It fixes a bug where iOS Safari and Android Chrome do not show the value. The one on line 249 detaches .value from .defaultValue (by default, changing .defaultValue affects .value but they work independently as soon as .value is ever set, including to its existing value).

Comment (nhunzaker) [inline src/renderers/dom/client/wrappers/ReactDOMInput.js]: Hmm. Neat. I need to check to see if this influences my Chrome backspace issue PR (#7359)

Comment (nhunzaker) [inline src/renderers/dom/client/wrappers/ReactDOMInput.js]: Looks like no. At least from my test case:

https://gist.github.com/nhunzaker/d31817ffd48279b4bf1f7513dd84f400

I don't want to make you all linger too much on this. I wish I understood how the detachment works better. Is it possible that this case is display-only?

Comment (spicyj) [inline src/renderers/dom/client/wrappers/ReactDOMInput.js]: Sorry, do you have a specific question? The correct browser behavior is:

.value always reflects the current displayed value of a field and what would be used if the form is submitted.

.defaultValue is always the same as the HTML value attribute (and get/setAttribute 'value'). When a form "reset" button is clicked, .value reverts to .defaultValue.

Initially, they are linked so that changing the value attribute or setting .defaultValue also changes value. Once value changes (either due to `.value =` or the user interacting), they function independently.

Comment (nhunzaker) [inline src/renderers/dom/client/wrappers/ReactDOMInput.js]: Yes, though you've just now answered it. I am sorry to have forced a quick lecture on the DOM :).

I wanted to figure out if the delinking here eliminated the need for [the fix I added](https://github.com/facebook/react/pull/7359/files#diff-1b0e3b280991cd0b7cde194b30353b3eR211) to #7359 where `defaultValue` is only reassigned if it is different. 

[From a quick test outside of React](http://codepen.io/nhunzaker/pen/jAvxvQ), I thought this PR would make it unnecessary. However it isn't, and I became confused. It looks like, [no matter what, `value` and `checked` get assigned in `ReactDOMInput.getHostProps`](https://github.com/facebook/react/blob/master/src/renderers/dom/client/wrappers/ReactDOMInput.js#L73-L74), and subsequently get sent out as DOM mutations. Even for uncontrolled inputs.

So that's what I'm working through now. No need to continue talking about it here, but I'd like to avoid being able to do the comparison check  and wanted to better understand the solution in this PR.

**Comment by iammerrick** [comment]
Getting peer dependency issues trying to install the release candidate. Any ideas about when 15.3.1 will land so we can plan accordingly?
