### PR TITLE
Properly set value and defaultValue for input and textarea

### LINKED ISSUE #4618: Can't update defaultChecked/defaultValue.
When I rerender a component with "defaultChecked" or "defaultValue" react fails to update the "value" and "checked" attribute accordingly.

Before you say "use a controlled input" I would argue that this is a bug as it basically disallows uncontrolled forms with "reset" buttons. (It will always reset to whatever the initial default value was).

### PR DESCRIPTION
**Pull request by jimfb**
Spiritual successor to https://github.com/facebook/react/pull/5680.  This is a fix for #6119 and #6219, both of which are blocking v15. As an added bonus, it happens to also fix #4618 :P.  It works by setting/removing both the attribute and property for `value` on inputs, and setting the property for `defaultValue`.

I fixed the tests to be more reasonable (inputs retain their initial value, rather than having the value potentially change when defaultValue changes). I also fixed the browser inconsistencies.

### CODE REVIEW

**Comment by jimfb** [comment]
@zpao @spicyj Ok, the tests are all passing now.  I fixed the tests to be more reasonable (inputs retain their initial value, rather than having the value potentially change when defaultValue changes).  I also fixed the browser inconsistencies (I think, still testing).

I don't think I'm quite ready to merge (a little more testing is still required), but I think it's in an ok state now, if people want to take a peak at it.

**Comment by jimfb** [comment]
@zpao @spicyj Ok, take a look now?

**Comment by spicyj** [comment]
This is not for 15.0, right?

**Comment by jimfb** [comment]
Paul Sebastian and I were at the PR review.  We weren't 100% decided, but Paul said to fix up #5680 to potentially land for v15.0

**Comment by jimfb** [comment]
Ok, I think this is good to go now.  Here are some fiddles that demonstrate everything working:
 > http://jsfiddle.net/3r0krefu/ (fixes Ben's concerns from https://github.com/facebook/react/pull/5680)
 > http://jsfiddle.net/ub6ec5rt/ (fixes Ben's concerns from https://github.com/facebook/react/pull/5680)
 > http://jsfiddle.net/v6fz2ct1/ (fixes https://github.com/facebook/react/issues/6119)
 > http://jsfiddle.net/wavkdt6b/ (fixes https://github.com/facebook/react/issues/6219)

File: src/renderers/dom/client/wrappers/ReactDOMInput.js [hunk 1]
```diff
@@ -207,13 +207,31 @@ var ReactDOMInput = {
...
+  },
+
+  postUpdateWrapper: function(inst) {
+    var props = inst._currentElement.props;
+    if (!props.value && props.defaultValue) {
+      invariant(inst._rootNodeID, 'Must be mounted to initialize initial input value');
+      var node = ReactDOMComponentTree.getNodeFromInstance(inst);
+      if (node.defaultValue !== props.defaultValue) {
+        var tmp = node.value;
+        node.defaultValue = ''+props.defaultValue;
```
Comment (gaearon) [inline src/renderers/dom/client/wrappers/ReactDOMInput.js]: Nit: missing spaces before and after *

**Comment by zpao** [comment]
Can you refresh me and explain why we need to change `defaultValue` behavior here?

**Comment by jimfb** [comment]
@zpao https://github.com/facebook/react/issues/4618 - In case someone has an uncontrolled component and then clicks the reset button, which was the genesis of this PR.  I used it (`defaultValue`) to solve browser inconsistencies; it might be sufficient to do it with just attributes (I could look into backing out `defaultValue` and using only the attribute if you think that's worthwhile, but Sebastian likes properties so I figured I'd throw him a bone and just use the property there :P).

**Comment by jimfb** [comment]
Rebased, in case we decide to take this as an alternative to https://github.com/facebook/react/pull/6406

**Comment by STRML** [comment]
What's the status on this? This bug effectively makes v15 a broken release, as it makes text inputs nearly unusable in many cases. Anything I can help with to get it in for v15.0.1?

**Comment by spicyj** [comment]
(@STRML We merged https://github.com/facebook/react/pull/6449 instead and released already.)

**Comment by facebook-github-bot-1** [comment]
@jimfb updated the pull request.

File: src/renderers/dom/client/wrappers/ReactDOMInput.js [hunk 2]
```diff
@@ -216,13 +215,42 @@ var ReactDOMInput = {
...
+  },
+
+  postUpdateWrapper: function(inst) {
+    var props = inst._currentElement.props;
+    var node = null;
+    var tmp = null;
+    if (!props.value && props.defaultValue) {
+      invariant(inst._rootNodeID, 'Must be mounted to initialize initial input value');
+      node = ReactDOMComponentTree.getNodeFromInstance(inst);
+      if (node.defaultValue !== props.defaultValue) {
```
Comment (spicyj) [inline src/renderers/dom/client/wrappers/ReactDOMInput.js]: We should cast to string here before comparing like we do for value.

File: src/renderers/dom/client/wrappers/ReactDOMInput.js [hunk 3]
```diff
@@ -216,13 +215,42 @@ var ReactDOMInput = {
...
+    } else {
+      ReactDOMInput.postUpdateWrapper(inst);
+    }
+  },
+
+  postUpdateWrapper: function(inst) {
+    var props = inst._currentElement.props;
+    var node = null;
+    var tmp = null;
+    if (!props.value && props.defaultValue) {
```
Comment (spicyj) [inline src/renderers/dom/client/wrappers/ReactDOMInput.js]: `!= null` I think; empty string is significant.

File: src/renderers/dom/client/wrappers/ReactDOMInput.js [hunk 4]
```diff
@@ -216,13 +215,42 @@ var ReactDOMInput = {
...
+      invariant(inst._rootNodeID, 'Must be mounted to initialize initial input value');
+      node = ReactDOMComponentTree.getNodeFromInstance(inst);
+      if (node.defaultValue !== props.defaultValue) {
+        tmp = node.value;
+        node.defaultValue = '' + props.defaultValue;
+        node.value = tmp;
```
Comment (spicyj) [inline src/renderers/dom/client/wrappers/ReactDOMInput.js]: This loses selection state.

**Comment by spicyj** [comment]
@sebmarkbage says that when you change defaultValue it *should* change the visible value (but we can't take that for 15).

@zpao wants a more detailed test plan.

File: src/renderers/dom/client/wrappers/ReactDOMTextarea.js [hunk 5]
```diff
@@ -159,13 +162,30 @@ var ReactDOMTextarea = {
...
+    }
+  },
+
+  postUpdateWrapper: function(inst) {
+    var props = inst._currentElement.props;
+    if (props.value == null && props.defaultValue) {
+      invariant(inst._rootNodeID, 'Must be mounted to initialize defaultValue');
+      var node = ReactDOMComponentTree.getNodeFromInstance(inst);
+      if (node.defaultValue !== props.defaultValue) {
+        node.value = node.value; // Hack to detach value and defaultValue
```
Comment (jimfb) [inline src/renderers/dom/client/wrappers/ReactDOMTextarea.js]: Sebastian (ideally) wants us to detach at initial mount.

**Comment by jimfb** [comment]
As per PR review... Ben had some nitpicks to fix, sebastian had the detach on initial mount request, and Paul wanted a full browser test matrix to show that the behaviors demonstrated in the fiddles work on all the browsers we care about.  Given that those things are done, everyone is happy this and we can merge.

**Comment by facebook-github-bot-1** [comment]
@jimfb updated the pull request.

**Comment by facebook-github-bot-6** [comment]
@jimfb updated the pull request.

**Comment by jimfb** [comment]
Ok, updated to fix Ben's nits, Sebastian's request to disconnect at initial mount, and Paul's request that I re-test in the various browsers after fixing the nits.

My test routine:
 * verify that modifying default value does not modify text input value
 * verify that modifying default value does not modify checkbox value
 * verify that modifying default value does not modify textarea value
 * verify that the reset button will reset text inputs to the specified default value
 * verify that the reset button will reset checkboxes to the specified default value
 * verify that the reset button will reset textareas to the specified default value
 * verify that progress element can be set to an indeterminate state
 * verify that we render a select box with `value=""` as the empty string
 * verify that controlled inputs work, curser does not jump to the end of the text input

My browsers:
Chrome (Version 50.0.2661.86)
Firefox 46 (Version 46.0)
Safari 9.1 (Version 10601.5.17.4)
Opera 36 (Version 36.0.2130.65)
Internet Explorer 11 (Version 11.103.10586.0)
Internet Explorer 10 (Version 10.0.9200.17519)
Internet Explorer 8 (via compatibility mode on a IE10 browser)

Everything worked beautifully in all the browsers :).

File: src/renderers/dom/client/wrappers/ReactDOMInput.js [hunk 6]
```diff
@@ -216,13 +215,45 @@ var ReactDOMInput = {
...
+    if (props.value == null && props.defaultValue != null) {
+      invariant(inst._rootNodeID, 'Must be mounted to initialize initial input value');
+      node = ReactDOMComponentTree.getNodeFromInstance(inst);
+      node.defaultValue = '' + props.defaultValue;
+    }
+    if (props.checked == null && props.defaultChecked != null) {
+      invariant(inst._rootNodeID, 'Must be mounted to initialize initial input value');
+      node = ReactDOMComponentTree.getNodeFromInstance(inst);
+
+      // tmp is needed to work around a chrome bug: https://jsfiddle.net/wsa679ht/
```
Comment (spicyj) [inline src/renderers/dom/client/wrappers/ReactDOMInput.js]: Can you explain the bug in words in case jsfiddle disappears?

Comment (spicyj) [inline src/renderers/dom/client/wrappers/ReactDOMInput.js]: Also link to a Chrome bug report.

File: src/renderers/dom/client/wrappers/ReactDOMInput.js [hunk 7]
```diff
@@ -216,13 +215,45 @@ var ReactDOMInput = {
...
+    }
+  },
+
+  postMountWrapper: function(inst) {
+    var node = ReactDOMComponentTree.getNodeFromInstance(inst);
+    node.value = node.value; // Detach value from and defaultValue
+    node.checked = node.checked; // Detach checked from and defaultChecked
+  },
+
+  postUpdateWrapper: function(inst) {
```
Comment (spicyj) [inline src/renderers/dom/client/wrappers/ReactDOMInput.js]: Is there a reason this needs to go in a separate function rather than just in updateWrapper? (Not actually sure offhand which is preferable, but this seems to be a change.)

Comment (spicyj) [inline src/renderers/dom/client/wrappers/ReactDOMInput.js]: select needs it in post because it relies on children having reconciled.

Comment (spicyj) [inline src/renderers/dom/client/wrappers/ReactDOMInput.js]: Although I'm not sure why it can't just happen after recursing and needs to be queued.

File: src/renderers/dom/client/wrappers/ReactDOMInput.js (hunk 6 above)
Comment (jimfb) [inline src/renderers/dom/client/wrappers/ReactDOMInput.js]: Ok, I filed https://bugs.chromium.org/p/chromium/issues/detail?id=608416

Comment (jimfb) [inline src/renderers/dom/client/wrappers/ReactDOMInput.js]: Updating comment in code.

**Comment by facebook-github-bot-5** [comment]
@jimfb updated the pull request.

File: src/renderers/dom/client/wrappers/ReactDOMInput.js (hunk 7 above)
Comment (jimfb) [inline src/renderers/dom/client/wrappers/ReactDOMInput.js]: Ok, I got rid of postUpdateWrapper.  Ran through the tests on Chrome and Firefox again, looks good.

**Comment by facebook-github-bot-2** [comment]
@jimfb updated the pull request.

**Comment by facebook-github-bot-8** [comment]
@jimfb updated the pull request.

File: src/renderers/dom/client/wrappers/ReactDOMInput.js (hunk 6 above)
Comment (spicyj) [inline src/renderers/dom/client/wrappers/ReactDOMInput.js]: Can you give them a repro case that doesn't use React?

Comment (jimfb) [inline src/renderers/dom/client/wrappers/ReactDOMInput.js]: Ok, submitted another fiddle that doesn't use React.

Comment (spicyj) [inline src/renderers/dom/client/wrappers/ReactDOMInput.js]: Thanks.

File: src/renderers/dom/client/wrappers/ReactDOMTextarea.js [hunk 8]
```diff
@@ -66,12 +65,14 @@ var ReactDOMTextarea = {
       '`dangerouslySetInnerHTML` does not make sense on <textarea>.'
     );
 
-    // Always set children to the same thing. In IE9, the selection range will
-    // get reset if `textContent` is mutated.
```
Comment (zpao) [inline src/renderers/dom/client/wrappers/ReactDOMTextarea.js]: Is this still applicable?

File: src/renderers/dom/client/wrappers/ReactDOMInput.js [hunk 9]
```diff
@@ -214,17 +213,43 @@ var ReactDOMInput = {
...
+          node.defaultChecked = !!props.defaultChecked;
+          node.checked = tmp;
+        }
+      }
     }
   },
+
+  postMountWrapper: function(inst) {
+    var node = ReactDOMComponentTree.getNodeFromInstance(inst);
+    node.value = node.value; // Detach value from and defaultValue
```
Comment (zpao) [inline src/renderers/dom/client/wrappers/ReactDOMInput.js]: What does this comment mean? Maybe just do a single comment on its own line above both of these lines that's clearer (probably don't need the same comment for both)

File: src/renderers/dom/shared/HTMLDOMPropertyConfig.js [hunk 10]
```diff
@@ -15,7 +15,6 @@ var DOMProperty = require('DOMProperty');
 
 var MUST_USE_PROPERTY = DOMProperty.injection.MUST_USE_PROPERTY;
 var HAS_BOOLEAN_VALUE = DOMProperty.injection.HAS_BOOLEAN_VALUE;
-var HAS_SIDE_EFFECTS = DOMProperty.injection.HAS_SIDE_EFFECTS;
```
Comment (zpao) [inline src/renderers/dom/shared/HTMLDOMPropertyConfig.js]: Want to prep the followup PR to remove the `HAS_SIDE_EFFECTS` logic? Or just do it here as a 2nd commit (I think the reasoning for a followup in the other PR was that it was a non-core contributor).

Comment (jimfb) [inline src/renderers/dom/shared/HTMLDOMPropertyConfig.js]: Yeah, I will follow up once this has merged.  But I don't want to make this diff any more complicated (it's taking long enough for people to review already), and git seems to make my life pretty miserable if I try to stack diffs and then changes are requested to the base diff, so I'll wait until after this has merged.

File: src/renderers/dom/client/wrappers/ReactDOMTextarea.js (hunk 8 above)
Comment (jimfb) [inline src/renderers/dom/client/wrappers/ReactDOMTextarea.js]: Looking into it now.  If not, I'll remove the comment as part of my rebase.

File: src/renderers/dom/client/wrappers/ReactDOMInput.js (hunk 9 above)
Comment (jimfb) [inline src/renderers/dom/client/wrappers/ReactDOMInput.js]: When a text input is created, value and defaultValue are attached to each other.  Changing defaultValue results in value being changed.  This line detaches them by setting value.  I think I like both comments, because it makes it abundantly clear that both of these apparent no-ops are intentional.

Comment (spicyj) [inline src/renderers/dom/client/wrappers/ReactDOMInput.js]: Your grammar here is also a bit off, maybe missing a word?

Comment (jimfb) [inline src/renderers/dom/client/wrappers/ReactDOMInput.js]: Ah, good call, I read right over that.  Probably an extra 'and'.  👍 

Will fix during rebase.

**Comment by facebook-github-bot-9** [comment]
@jimfb updated the pull request.

File: src/renderers/dom/client/wrappers/ReactDOMTextarea.js (hunk 8 above)
Comment (jimfb) [inline src/renderers/dom/client/wrappers/ReactDOMTextarea.js]: Looked into it.  Appears that IE9 does indeed get upset if you set textContent to the same value it already had.  But this was totally the wrong place for a comment to be talking about that; applied a hack in `setTextContent.js` which is a much more appropriate place to deal with this.

Comment (spicyj) [inline src/renderers/dom/client/wrappers/ReactDOMTextarea.js]: It's only relevant for textareas, isn't it?

**Comment by facebook-github-bot-5** [comment]
@jimfb updated the pull request.

File: src/renderers/dom/client/wrappers/ReactDOMTextarea.js (hunk 8 above)
Comment (jimfb) [inline src/renderers/dom/client/wrappers/ReactDOMTextarea.js]: Not sure, what happens if you have a contenteditable div with text in it?  I wouldn't be surprised if there were another edge condition where this applied for React reconciliation, independent of text areas.

But regardless, it's feels very wrong for getNativeProps to always return the initialValue BECAUSE it knows that the reconciler will use the `textContent` property (as oppose to any other perfectly-valid method) to set the `children` of the textarea.  Correct solution is for the reconciler to properly handle this edge case by virtue of the fact that `setTextContent` properly handles this edge case.

File: src/renderers/dom/client/wrappers/ReactDOMInput.js [hunk 11]
```diff
@@ -214,17 +213,43 @@ var ReactDOMInput = {
...
+      if (props.value == null && props.defaultValue != null) {
+        invariant(inst._rootNodeID, 'Must be mounted to initialize initial input value');
+        node.defaultValue = '' + props.defaultValue;
+      }
+      if (props.checked == null && props.defaultChecked != null) {
+        invariant(inst._rootNodeID, 'Must be mounted to initialize initial input value');
+
+        // tmp is needed to work around a chrome bug where setting defaultChecked
+        // will sometimes influence the value of checked (even after detachment).
+        // Reference: https://bugs.chromium.org/p/chromium/issues/detail?id=608416
```
Comment (spicyj) [inline src/renderers/dom/client/wrappers/ReactDOMInput.js]: Based on the patch that fixes it, it sounds like the issue is that setting .checked to its current value doesn't detach it. Maybe we can just do

```
node.checked = !node.checked;
node.checked = !node.checked;
```

in postMountWrapper with a link to the bug and/or commit?

Comment (jimfb) [inline src/renderers/dom/client/wrappers/ReactDOMInput.js]: Yep, sounds like that would work too.  Updated PR.

**Comment by facebook-github-bot-4** [comment]
@jimfb updated the pull request.

File: src/renderers/dom/client/wrappers/ReactDOMInput.js [hunk 12]
```diff
@@ -214,17 +213,44 @@ var ReactDOMInput = {
...
   },
+
+  postMountWrapper: function(inst) {
+    // This is in postMount because we need access to the DOM node, which is not
+    // available until after the component has mounted.
+    var node = ReactDOMComponentTree.getNodeFromInstance(inst);
+    node.value = node.value; // Detach value from defaultValue
+
+    // In addition to detaching value, we also need to detach checked.
+    // Normally, we'd just do node.`checked = node.checked` like above...
```
Comment (spicyj) [inline src/renderers/dom/client/wrappers/ReactDOMInput.js]: backtick in the wrong place

File: src/renderers/dom/client/wrappers/ReactDOMInput.js [hunk 13]
```diff
@@ -166,13 +166,12 @@ var ReactDOMInput = {
...
       warnIfValueIsNull(props);
 
-      var initialValue = inst._wrapperState.initialChecked || inst._wrapperState.initialValue;
       var defaultValue = props.defaultChecked || props.defaultValue;
       var controlled = props.checked !== undefined || props.value !== undefined;
       var owner = inst._currentElement._owner;
 
       if (
-        (initialValue || !inst._wrapperState.controlled) &&
+        (!inst._wrapperState.controlled) &&
```
Comment (spicyj) [inline src/renderers/dom/client/wrappers/ReactDOMInput.js]: unnecessary parens

File: src/renderers/dom/client/wrappers/ReactDOMTextarea.js (hunk 8 above)
Comment (spicyj) [inline src/renderers/dom/client/wrappers/ReactDOMTextarea.js]: The issue is that no matter how you might update the children, IE loses cursor position in textareas only. Elements with contenteditable should be handled by our ReactInputSelection wrapper on the transaction. I'd like this logic to be maintained as it was, where the children are always passed down the same way.

File: src/renderers/dom/client/wrappers/ReactDOMTextarea.js [hunk 14]
```diff
@@ -110,40 +111,42 @@ var ReactDOMTextarea = {
...
-      }
-      invariant(
-        defaultValue == null,
-        'If you supply `defaultValue` on a <textarea>, do not pass children.'
-      );
-      if (Array.isArray(children)) {
+
+    var value = LinkedValueUtils.getValue(props);
+
+    // only bother fetching default value if we're going to use it
```
Comment (spicyj) [inline src/renderers/dom/client/wrappers/ReactDOMTextarea.js]: Capitalize please.

Comment (spicyj) [inline src/renderers/dom/client/wrappers/ReactDOMTextarea.js]: To make this clearer, can you do

```
var value = ...;
var initialValue = value;
if (initialValue == null) {
  var defaultValue = ...;
  ...
  initialValue = defaultValue;
}
```

and then use `'' + initialValue` below?

File: src/renderers/dom/client/wrappers/ReactDOMTextarea.js [hunk 15]
```diff
@@ -157,17 +160,29 @@ var ReactDOMTextarea = {
       warnIfValueIsNull(props);
     }
 
+    var node = ReactDOMComponentTree.getNodeFromInstance(inst);
     var value = LinkedValueUtils.getValue(props);
     if (value != null) {
+
```
Comment (spicyj) [inline src/renderers/dom/client/wrappers/ReactDOMTextarea.js]: rm

File: src/renderers/dom/client/wrappers/__tests__/ReactDOMInput-test.js [hunk 16]
```diff
@@ -66,6 +69,38 @@ describe('ReactDOMInput', function() {
...
+  it('should update `defaultValue` for uncontrolled input', function() {
+    var container = document.createElement('div');
+
+    var node = ReactDOM.render(<input type="text" defaultValue="0" />, container);
+
+    expect(node.value).toBe('0');
+
+    ReactDOM.render(<input type="text" defaultValue="1" />, container);
+
+    expect(node.value).toBe('0');
```
Comment (spicyj) [inline src/renderers/dom/client/wrappers/__tests__/ReactDOMInput-test.js]: Do you want to assert that `node.defaultValue` is 1 here too?

File: src/renderers/dom/client/wrappers/__tests__/ReactDOMInput-test.js [hunk 17]
```diff
@@ -66,6 +69,38 @@ describe('ReactDOMInput', function() {
...
+  });
+
+  it('should render value for SSR', function() {
+    var image = ReactDOMServer.renderToString(<input type="text" defaultValue="1" />);
```
Comment (spicyj) [inline src/renderers/dom/client/wrappers/__tests__/ReactDOMInput-test.js]: `markup` would be clearer than `image`.

File: src/renderers/dom/client/wrappers/__tests__/ReactDOMInput-test.js [hunk 18]
```diff
@@ -138,6 +170,29 @@ describe('ReactDOMInput', function() {
     expect(node.value).toEqual('foobar');
   });
 
+  it('should not incur unnecessary DOM mutations', function() {
+    var container = document.createElement('div');
+    ReactDOM.render(<input value="a" />, container);
+
+    var node = container.firstChild;
+    var nodeValue = 'a'; // node.value always returns undefined
```
Comment (spicyj) [inline src/renderers/dom/client/wrappers/__tests__/ReactDOMInput-test.js]: wrong comment?

File: src/renderers/dom/client/wrappers/__tests__/ReactDOMTextarea-test.js [hunk 19]
```diff
@@ -24,46 +25,51 @@ describe('ReactDOMTextarea', function() {
...
       }
-      var stub = ReactDOM.render(component, container);
-      var node = ReactDOM.findDOMNode(stub);
-      // Fixing jsdom's quirky behavior -- in reality, the parser should strip
-      // off the leading newline but we need to do it by hand here.
-      node.value = node.innerHTML.replace(/^\n/, '');
-      return stub;
+      var node = ReactDOM.render(component, container);
+
+      if (!skipReplace) {
```
Comment (spicyj) [inline src/renderers/dom/client/wrappers/__tests__/ReactDOMTextarea-test.js]: Why is this necessary?

File: src/renderers/dom/client/wrappers/__tests__/ReactDOMTextarea-test.js [hunk 20]
```diff
@@ -189,16 +251,44 @@ describe('ReactDOMTextarea', function() {
     expect(node.value).toEqual('giraffe');
   });
 
+  it('should not keep value when switching to uncontrolled element if not changed', function() {
```
Comment (spicyj) [inline src/renderers/dom/client/wrappers/__tests__/ReactDOMTextarea-test.js]: _should_ keep value, right?

File: src/renderers/dom/client/wrappers/__tests__/ReactDOMInput-test.js [hunk 21]
```diff
@@ -66,6 +69,38 @@ describe('ReactDOMInput', function() {
...
+    var node = ReactDOM.render(<input type="text" value="0" readOnly="true" />, container);
+
+    expect(node.value).toBe('0');
+
+    ReactDOM.render(<input type="text" defaultValue="1" />, container);
+
+    expect(node.value).toBe('0');
+  });
+
+  it('should render value for SSR', function() {
```
Comment (spicyj) [inline src/renderers/dom/client/wrappers/__tests__/ReactDOMInput-test.js]: Do we have a SSR test where we render with `value` (not `defaultValue`)? If not, can you add one?

**Comment by spicyj** [comment]
Accepted with inline comments. Also Travis is failing.

File: src/renderers/dom/client/utils/setTextContent.js [hunk 22]
```diff
@@ -26,7 +26,11 @@ var setInnerHTML = require('setInnerHTML');
  * @internal
  */
 var setTextContent = function(node, text) {
-  node.textContent = text;
+  // IE9 sets the value even if it is unchanged, which results in artifacts
+  // like cursor/select position getting lost.  So we check in userland.
+  if (node.textContent !== text) { // Hack for IE9 and below
+    node.textContent = text;
+  }
```
Comment (sebmarkbage) [inline src/renderers/dom/client/utils/setTextContent.js]: This is in the wrong place. It should just avoid updating textContent.

File: src/renderers/dom/client/wrappers/ReactDOMInput.js (hunk 11 above)
Comment (jimfb) [inline src/renderers/dom/client/wrappers/ReactDOMInput.js]: Actually, no.  Issue is that setting the checked state (even just temporarily) will wipe out the radio button selections.  We would need to do a post-post-mount.

Sebastian implied that he liked the `tmp` variable solution better anyway (read, update, restore).

File: src/renderers/dom/client/wrappers/__tests__/ReactDOMTextarea-test.js (hunk 19 above)
Comment (jimfb) [inline src/renderers/dom/client/wrappers/__tests__/ReactDOMTextarea-test.js]: cc @hayesgm You wrote this line, why is this necessary?

**Comment by facebook-github-bot-2** [comment]
@jimfb updated the pull request.

File: src/renderers/dom/client/wrappers/ReactDOMInput.js (hunk 11 above)
Comment (spicyj) [inline src/renderers/dom/client/wrappers/ReactDOMInput.js]: I thought the whole point was that we wanted to detach on mount? We originally did the tmp thing and @sebmarkbage said detaching on mount was preferable. This is gross though. We could… unset name so radio buttons don't get screwed up and then set it back?

Comment (jimfb) [inline src/renderers/dom/client/wrappers/ReactDOMInput.js]: Ok, I don't see how using tmp on update is any grosser/dirtier than using it on initial mount.  Especially since this means we incur unnecessary dom operations for every input instead of just updates to radio buttons.  But if you really like it better, I'll do it your way (unset name, set checked twice, set name) - updating diff now.

File: src/renderers/dom/client/wrappers/__tests__/ReactDOMTextarea-test.js (hunk 19 above)
Comment (jimfb) [inline src/renderers/dom/client/wrappers/__tests__/ReactDOMTextarea-test.js]: Ping @hayesgm

File: src/renderers/dom/client/wrappers/__tests__/ReactDOMInput-test.js (hunk 16 above)
Comment (jimfb) [inline src/renderers/dom/client/wrappers/__tests__/ReactDOMInput-test.js]: Done.

**Comment by facebook-github-bot-7** [comment]
@jimfb updated the pull request.

File: src/renderers/dom/client/wrappers/__tests__/ReactDOMTextarea-test.js (hunk 19 above)
Comment (hayesgm) [inline src/renderers/dom/client/wrappers/__tests__/ReactDOMTextarea-test.js]: Sorry, been MIA, taking a look now.

Comment (hayesgm) [inline src/renderers/dom/client/wrappers/__tests__/ReactDOMTextarea-test.js]: I believe this was causing a quirk with one of the test cases, as setting `innerHTML` changed the behavior of my test. Also, I think it's a strange hack that should be opt-in instead of opt-out for test cases which call into `renderTextarea`. That said, if it's no longer applicable, you can surely remove the flag.

**Comment by facebook-github-bot-5** [comment]
@jimfb updated the pull request.

**Comment by jimfb** [comment]
Ok, I think this is mostly ready-to-go.  A couple of last todo items for me are:
 * Look into `skipReplace` and remove if unnecessary.  Add comment if necessary.
 * Re-run the full test plan above on all the browsers above, verify things didn't break.

If people have other last comments, I think now is the time.

File: src/renderers/dom/client/wrappers/__tests__/ReactDOMTextarea-test.js (hunk 19 above)
Comment (spicyj) [inline src/renderers/dom/client/wrappers/__tests__/ReactDOMTextarea-test.js]: We should do this unconditionally but set node.defaultValue not node.value. Then the tests pass.

**Comment by spicyj** [comment]
Yeah, let's get this in after you fix the skipReplace thing.

File: src/renderers/dom/client/wrappers/__tests__/ReactDOMTextarea-test.js (hunk 19 above)
Comment (hayesgm) [inline src/renderers/dom/client/wrappers/__tests__/ReactDOMTextarea-test.js]: Sounds right to me.

**Comment by facebook-github-bot-0** [comment]
@jimfb updated the pull request.

**Comment by jimfb** [comment]
Ok, just got done with my test suite, things are looking good.  Since we no longer set the textContent of controlled textareas during reconciliation (due to changes requested by @spicyj and @sebmarkbage), I needed to apply a minor patch for correctness:

```
diff --git a/src/renderers/dom/client/wrappers/ReactDOMTextarea.js b/src/renderers/dom/client/wrappers/ReactDOMTextarea.js
index fd18c1d..74d62ff 100644
--- a/src/renderers/dom/client/wrappers/ReactDOMTextarea.js
+++ b/src/renderers/dom/client/wrappers/ReactDOMTextarea.js
@@ -174,7 +174,11 @@ var ReactDOMTextarea = {
       if (newValue !== node.value) {
         node.value = newValue;
       }
-    } else if (props.defaultValue) {
+      if (props.defaultValue == null) {
+        node.defaultValue = newValue;
+      }
+    }
+    if (props.defaultValue) {
       node.defaultValue = props.defaultValue;
     }
   },
```

Other than that, all looks good.

**Comment by facebook-github-bot-2** [comment]
@jimfb updated the pull request.

**Comment by spicyj** [comment]
It looks like input updateWrapper is now:

```js
    if (value != null) {
      var newValue = '' + value;
      if (newValue !== node.value) {
        node.value = newValue;
      }
    } else {
      if (props.value == null && props.defaultValue != null) {
        node.defaultValue = '' + props.defaultValue;
      }
    }
```

whereas textarea updateWrapper is:

```js
    if (value != null) {
      var newValue = '' + value;
      if (newValue !== node.value) {
        node.value = newValue;
      }
      if (props.defaultValue == null) {
        node.defaultValue = newValue;
      }
    }
    if (props.defaultValue) {
      node.defaultValue = props.defaultValue;
    }
```

Is there a reason these are different? I would have thought we'd want the same exact behavior.

Do we have tests for when both value and defaultValue are specified? What if defaultValue is `''`? It looks like the textarea code will incorrectly treat that as unspecified.

**Comment by jimfb** [comment]
They are different because inputs set value properly during reconcilation.  This is what I wanted to do with textareas also (indeed, my prior implementation DID, and it worked well!), but you guys told me to do the sketchy hack where a textarea returns `{children: initialValue}` instead of always reflecting the current/correct value.

You asked me to always return the initial value instead of the actual value, because you didn't like me changing `setTextContent` to check if the value actually changed before changing the value (which was necessary because of a bug in IE9).  I don't like the solution you and sebastian advocated for, but I needed to choose my battles in the interest of moving this diff forward, so I capitulated, but that's the reason for the difference.

With regards to the defaultValue being the emptyString... you are correct, that should be a null check, I'll update it and add a test for that situation.  That is an extreme edge case, since the default value for defalutValue is the empty string, it would require someone to set the defaultValue and then change the defaultValue to the empty string - which is very unlikely (but valid) thing to do.  Updating now.

**Comment by facebook-github-bot-2** [comment]
@jimfb updated the pull request.

**Comment by facebook-github-bot-3** [comment]
@jimfb updated the pull request.

**Comment by zpao** [comment]
Are we targeting 15 or 16 with this?

**Comment by jimfb** [comment]
I don't have a super strong preference.  Should be safe for 15, but whatever works.

File: src/renderers/dom/shared/HTMLDOMPropertyConfig.js (hunk 10 above)
Comment (zpao) [inline src/renderers/dom/shared/HTMLDOMPropertyConfig.js]: Can you followup on this now?

File: src/renderers/dom/shared/ReactDOMComponent.js [hunk 23]
```diff
@@ -623,7 +633,17 @@ ReactDOMComponent.Mixin = {
...
+          inputPostMount,
+          this
+        );
+        break;
       case 'textarea':
+        transaction.getReactMountReady().enqueue(
+          textareaPostMount,
+          this
+        );
+        break;
```
Comment (zpao) [inline src/renderers/dom/shared/ReactDOMComponent.js]: So I just came back here due to a merge conflict and perhaps I'm missing something but doesn't this change mean we'll stop autofocusing inputs and textareas?

Comment (spicyj) [inline src/renderers/dom/shared/ReactDOMComponent.js]: That's what it looks like to me. @jimfb?

Comment (jimfb) [inline src/renderers/dom/shared/ReactDOMComponent.js]: https://github.com/facebook/react/pull/6986

**Comment by TheLudd** [comment]
Hello
I noticed that in react `15.2.0` (but not in `15.1.0`) there is a change in how checkboxes are rendered. And I suspect it might have something to do with this change. 
In version `15.2.0` rendered checkbox inputs will always have the property `value="on"` unless value is specified to be something else. 
I wonder if this is intentional and/or wanted. It causes errors in my application/lib where I make assumptions based on if a checkbox has a value set or not. Now they always have values...

**Comment by gaearon** [comment]
If you have an issue with the latest version please file a new issue. Thanks!
Maybe @aweary or @nhunzaker could help with older versions.

File: src/renderers/dom/client/wrappers/ReactDOMInput.js [hunk 24]
```diff
@@ -214,17 +213,45 @@ var ReactDOMInput = {
...
+        node.defaultChecked = !!props.defaultChecked;
+      }
     }
   },
+
+  postMountWrapper: function(inst) {
+    // This is in postMount because we need access to the DOM node, which is not
+    // available until after the component has mounted.
+    var node = ReactDOMComponentTree.getNodeFromInstance(inst);
+    node.value = node.value; // Detach value from defaultValue
```
Comment (zyy7259) [inline src/renderers/dom/client/wrappers/ReactDOMInput.js]: I'm trying to understand the logic here. Could somebody tell what "detach" means here?

Comment (hayesgm) [reply src/renderers/dom/client/wrappers/ReactDOMInput.js]: If I recall from way back when, once you call the setter for `value`, it then ignores changes to the `defaultValue`. In this case, we set the value to the same value, which has this effect.

Comment (zyy7259) [reply src/renderers/dom/client/wrappers/ReactDOMInput.js]: Thanks for the explanation
