### PR TITLE
DevTools shows unsupported renderer version dialog

### LINKED ISSUE #16462: DevTools: Fully disable 0.14 support
It’s confusing that 0.14 or earlier is in half-working state where it displays a tree (but incorrectly). We should detect it and fully disable if it doesn’t work. Or fix it.

If we go the route of disabling support:
1. DevTools should show a warning message that clearly indicates the version of React isn't supported. (This is probably a good idea for v13 and older anyway.)
2. DevTools should not throw any errors.

---
Originally reported by @gaearon via https://github.com/bvaughn/react-devtools-experimental/issues/384

### PR DESCRIPTION
**Pull request by bvaughn**
Rather than partially supporting v14, DevTools now shows an unsupported dialog with a link to instructions on how to downgrade DevTools to v3:

Screen Shot 2019-09-25 at 1 27 17 PM

I decided on this approach to detecting versions by looking at all v14 and v15 minor releases and by referencing [the old DevTools logic](https://github.com/facebook/react-devtools/blob/d839081f79f681617df7584a8ffd2f4163fa40b9/backend/attachRenderer.js#L24-L76).

I tested all minor release of v15 and v16 to ensure that the dialog didn't get shown. I tested the latest release of v14 and verified that it did.

Resolves #16462

### CODE REVIEW

File: packages/react-devtools-shared/src/devtools/store.js [hunk 1]
```diff
@@ -337,6 +344,10 @@ export default class Store extends EventEmitter<{|
     return this._supportsReloadAndProfile && this._isBackendStorageAPISupported;
   }
 
+  get unsupportedRendererVersionDetected(): boolean {
```
Comment (trueadm) [inline packages/react-devtools-shared/src/devtools/store.js]: Is it normal that we use getters vs generic functions?

Comment (bvaughn) [reply packages/react-devtools-shared/src/devtools/store.js]: In the DevTools `Store` I guess it is. Any reason to prefer one over the other?

Comment (bvaughn) [reply packages/react-devtools-shared/src/devtools/store.js]: In DevTools `Store` I guess it is. Any reason to prefer one over the other?

Comment (trueadm) [reply packages/react-devtools-shared/src/devtools/store.js]: I guess it's fine as this won't be used on unsupported browsers anyway.

Comment (bvaughn) [reply packages/react-devtools-shared/src/devtools/store.js]: Nah, DevTools has the benefit of only being used in Chrome & Firefox
