### PR TITLE
Fallback to event.srcElement for IE9

### LINKED ISSUE #12506: Possible incorrect event.target on number inputs in IE9?
Since React 16.0.0, it looks like there might be a case where `event.target` on a change event in IE9 reports as the window, but I can't reproduce it outside of the DOM test fixtures.

*Steps to reproduce*

1. Open this build of the fixtures: http://react-ie-9-target-issues.surge.sh in IE9
2. Enter text into an input
3. Observe that the `event.target.value` is the window, as recorded by the fixture

I can not reproduce this using the following CodePen:

https://codepen.io/nhunzaker/pen/dmeoxJ?editors=1010
Viewable in IE9 here: https://s.codepen.io/nhunzaker/debug/dmeoxJ/PNrvYLevqQbM

Here's a diff of my changes with master:
https://github.com/facebook/react/compare/master...nhunzaker:ie9-target-issue

Any idea what's going on? Here's what I think I need to check next:

- [x] Differences in rAF polyfill
- [x] Differences in map/set polyfill

_This list will probably grow_

### PR DESCRIPTION
**Pull request by nhunzaker**
It looks like we accidentally removed a fallback condition for the event target in IE9 when we dropped some support for IE8. This commit adds the event target specific support code back to getEventTarget.js

Fixes #12506

**Test Plan**

1. Open IE9
2. Visit http://react-nh-fix-ie9-target.surge.sh/number-inputs
3. Try to enter text into the inputs

**Local Behavior:** Includes this fix. `event.target` falls back to `event.srcElement` and text correctly updates
**16.4.0 Behavior:** Text does not update because event.target.value references the window, which is always undefined.

http://react-nh-fix-ie9-target.surge.sh/number-inputs?version=16.4.0

*Note: It's a bummer that IE9 can't fetch our latest tags... I'll try to do something about that.*

### CODE REVIEW

File: packages/react-dom/src/events/getEventTarget.js [hunk 1]
```diff
@@ -15,7 +15,9 @@ import {TEXT_NODE} from '../shared/HTMLNodeType';
  * @return {DOMEventTarget} Target node.
  */
 function getEventTarget(nativeEvent) {
-  let target = nativeEvent.target || window;
+  // Fallback to nativeEvent.srcElement for IE9
+  // https://github.com/facebook/react/issues/12506
+  let target = nativeEvent.target || nativeEvent.srcElement || window;
```
Comment (nhunzaker) [inline packages/react-dom/src/events/getEventTarget.js]: Should we have an internal unit test for this?

Comment (jquense) [reply packages/react-dom/src/events/getEventTarget.js]: I'd really like to track down the reason for this so we don't accidentally remove it again as well. Everything I can find suggests that `srcElement` should _not_ be needed in IE9, so I'm wondering where the issue is coming from. I haven't found much some-places suggest that when `attachEvent` is used it follows the ie8 event model (with target undefined), I wonder if some branches are still hitting attachEvent?

Comment (jquense) [reply packages/react-dom/src/events/getEventTarget.js]: the change polyfill uses it, Perhaps that's the root cause? I think we could use `addEventListener` there...

Comment (nhunzaker) [reply packages/react-dom/src/events/getEventTarget.js]: Interesting... I actually remove that listener in #12505. I'll hunt!

**Comment by nhunzaker** [comment]
@jquense I bow to your mastery of the DOM. Using addEventListener addressed the issue as well obviated my PR to fix undo in IE9 (#12505).

**Comment by nhunzaker** [comment]
Well actually... 🤦‍♂️ I didn't update the event listener name when I went to addEventListener. Here we go again...

**Comment by nhunzaker** [comment]
@jquense looks like `propertychange` only fires if you assign `input.onpropertychange` or use `attachEvent`.

Still: the false positive suggests that there's something goofy going on here. I'll investigate why the `onpropertychange` handler appears not to be necessary (also demonstrated in #12505).

**Comment by jquense** [comment]
I was afraid it'd all coming tumbling down if we moved one piece :p I can try and take a closer look as well a bit later if it helps at all

**Comment by aweary** [comment]
If we get rid of `onpropertychange` in https://github.com/facebook/react/pull/12505 then we shouldn't need this fix right?

**Comment by nhunzaker** [comment]
@aweary Correct. This is just temporarily addresses the event target issue in IE9 until we can figure out if `onpropertychange` can go.

**Comment by gaearon** [comment]
It wasn't accidental, I removed it in https://github.com/facebook/react/pull/11515 because I thought it's IE8-only. Sorry.

**Comment by nhunzaker** [comment]
@gaearon we also approved it :D. It looks like we need this as long as we use `onpropertychange`, which emits an MSEventObject circa IE8.

It sounds like (from #12505) removing `onpropertychange` is going to be a can of worms. I don't know when the next patch release is, but it would be cool to get this out in the next patch, if we can.

CI is failing because of danger. Is there a way to fix that?

**Comment by aweary** [comment]
Fixing this for IE9 is pretty low priority (it's been broken for a long time and nobody reported it), so it may be worth spending more time on a better solution if we think we can find one.

**Comment by nhunzaker** [comment]
@gaearon sure enough.

**Comment by nhunzaker** [comment]
@aweary This isn't much of a change to revert if we sort that out, but I think it's probably fine if we want to just worry about what to do with `onpropertychange`.

**Comment by gaearon** [comment]
Let's just get this in for now, it's a simple fix and now has a GH issue link.
Happy to merge a more comprehensive solution later.
