### PR TITLE
Scheduling Profiler: Redesign with DevTools styling

### LINKED ISSUE #19676: Bug: Broken Scheduling Profiler landing styles
## Steps To Reproduce

1. Build the Scheduling Profiler.
2. Open responsive mode on the browser.
3. Observe the 'zoomed in' behavior. 

## The current behavior

The page currently isn't responsive on smaller viewports, has reduced card width than original, slightly misaligned image and overflows on desktop, adding a scrollbar to the page.

The latest PR #19665 seems to have introduced these issues (while fixing some of the old ones).

#### Chrome

image

#### Firefox

image

cc: @bvaughn, @taneliang

### PR DESCRIPTION
**Pull request by taneliang**
## Summary

Adopt DevTools styling in the scheduling profiler and show a persistent toolbar at the top of the page.

image

Resolves #19676.

cc @bvaughn, @kartikcho

### High-Level Goals

Design: Match React DevTools's design, so that we carry the same brand and level of professionalism.

Code: Revamp `App` code structure and CSS to resemble the `DevTools` component -- this is intended to make it slightly easier to merge the scheduling profiler into DevTools when the time comes.

Future expansion: Create space on the canvas page to display the React version (with a view towards #19668) and other profile metadata e.g. profile name and browser type.

Misc features:

- Display an import button even after a profile has been loaded.
- Add an import error dialog.

### Implementation Breakdown

This is a large PR, but a lot of the code is copied verbatim from `react-devtools-shared`.

- Replaces the existing `ImportPage`, mainly with `ImportButton`
- Fork these from `react-devtools-shared` unchanged: Button, ButtonIcon, Icon, ModalDialog, ReactLogo, TabBar, Tooltip, root.css, utils/storage.js
- Fork these from `react-devtools-shared` with modifications:
	- Settings: I've modified this to remove its dependency on BridgeContext and StoreContext, both of which are not used in the scheduling profiler. I've left the list of CSS variables unchanged even though most of them aren't used as far as I can tell.
	- hooks.js: Removed unused hooks and add a `useBrowserTheme` hook for auto dark mode 🎉 
- Inject a new `DEVTOOLS_VERSION` variable similar to DevTools', but computed from the scheduling profiler's package.json instead.
- Overhaul `App.js` with the rough component hierarchy and same CSS styles as `DevTools.js`
- Create a new `SchedulingProfiler` component following `Profiler.js`.

If we decide to accept this PR, we'll want to adapt #19690's help text to the new design and code structure.

### Questions

- Should we import code from `react-devtools-shared` instead of forking their implementations?
- Are there any standard sources for the DevTools icons? I did a cursory search and found an icon in the Chromium source code, but I'm not sure where the others are from.
- If we want to continue forking the implementations, should we delete unused code or leave them around? I'd imagine that leaving them around will ease the eventual merging as the diff will be minimized.

### TODO

- [x] Resolve questions above
- [x] Place dark mode behind a new feature flag; the profiler canvas does not support dark mode. We'll leave comfortable sizing there; even though the canvas doesn't support comfortable sizing, I think people may appreciate having the rest of the UI text scale.

## Test Plan

Before import (equivalent to the old `ImportPage`):

| Before | After |
|-|-|
|image|image|

After import:

| Before | After |
|-|-|
|image|image|

Because we're using DevTools code, there's built-in support for configurable (auto!) dark mode and display density. Unfortunately, this is not very useful now because the profiler canvas doesn't have support for CSS variables yet. I'll hide it behind a feature flag, but this is what it looks like now:

Settings page:

image

Comfortable dark:

image

Compact dark:

image

Compact dark:

image

Comfortable dark:

image

Hidden image when viewport is shorter than 600px:

image

New import failure dialog:

image

### Known Issues

It's possible to hover over the canvas content even if the settings dialog is up. I can fix that in a separate PR to prevent this PR from bloating further.

image

### CODE REVIEW

**Comment by bvaughn** [comment]
This is in my queue to review. I was on PTO last week though and I have a lot of catch up to do. I'll try to get to it sometime in the next couple of days. :smile:

There is a Yarn lockfile conflict that might be nice to fix when you get the chance though.

**Comment by taneliang** [comment]
No problem, take your time! 😄

I've rebased on master and fixed the conflict, and made 2 tiny changes:

- Bumped the Reach packages to their latest versions
- Removed the version string from the toolbar as I doubt users will want/need to see it. The version number can still be found in the settings panel.
image

**Comment by taneliang** [comment]
Also hid the dark mode setting behind a new scheduling profiler feature flag `enableDarkMode`.

App no longer goes into dark mode even if the app was previously set to Auto or Dark

image

Theme setting is now also hidden

image

Dark mode still available when `enableDarkMode = true`

image

**Comment by taneliang** [comment]
I'm rebasing this on master

**Comment by bvaughn** [comment]
> * Should we import code from react-devtools-shared instead of forking their implementations?

Importing seems nice!

> * Are there any standard sources for the DevTools icons? I did a cursory search and found an icon in the Chromium source code, but I'm not sure where the others are from.

Most of them come from Material UI: https://material-ui.com/components/material-icons/

> * If we want to continue forking the implementations, should we delete unused code or leave them around? I'd imagine that leaving them around will ease the eventual merging as the diff will be minimized.

No strong preference, but I also think using `react-devtools-shared` seems nice so maybe this question doesn't apply.

File: packages/react-devtools-scheduling-profiler/src/hooks.js [hunk 1]
```diff
@@ -0,0 +1,199 @@
...
+export function useBrowserTheme(): BrowserTheme {
+  const [theme, setTheme] = useState<BrowserTheme>('light');
+
+  useEffect(() => {
+    const handlePreferredColorSchemeChange = (event: MediaQueryListEvent) => {
+      setTheme(event.matches ? 'dark' : 'light');
+    };
+
+    const mediaQueryList = window.matchMedia('(prefers-color-scheme: dark)');
+    mediaQueryList.addEventListener('change', handlePreferredColorSchemeChange);
```
Comment (bvaughn) [inline packages/react-devtools-scheduling-profiler/src/hooks.js:188]: I don't think this picks up on dark mode if it's already set (only if the user changes their system theme *after* the profiler has been opened). At least that seems to be the behavior on OSX (the "change" event won't get fired).

We could *also* check `window.matchMedia(DARK_MODE_QUERY).matches` in the effect and update, but then we might have to render twice (once for the default "light" and then again for "dark").

I think this might be a nice opportunity to use the `useMutableSource` hook! :smile: It will handle all of this for us. Here's how you'd use it:

```js
import {
  unstable_createMutableSource as createMutableSource,
  unstable_useMutableSource as useMutableSource,
  useEffect,
  useState,
} from 'react';

export type BrowserTheme = 'dark' | 'light';

const DARK_MODE_QUERY = '(prefers-color-scheme: dark)';

const getSnapshot = window =>
  window.matchMedia(DARK_MODE_QUERY).matches ? 'dark' : 'light';

const darkModeMutableSource = createMutableSource(
  window,
  () => window.matchMedia(DARK_MODE_QUERY).matches,
);

const subscribe = (window, callback) => {
  const mediaQueryList = window.matchMedia(DARK_MODE_QUERY);
  mediaQueryList.addEventListener('change', callback);
  return () => {
    mediaQueryList.removeEventListener('change', callback);
  };
};

export function useBrowserTheme(): BrowserTheme {
  return useMutableSource(darkModeMutableSource, getSnapshot, subscribe);
}
```

File: packages/react-devtools-scheduling-profiler/src/TabBar.js [hunk 2]
```diff
@@ -0,0 +1,133 @@
+/**
```
Comment (bvaughn) [inline packages/react-devtools-scheduling-profiler/src/TabBar.js:1]: Let's use `react-devtools-shared/src/devtools/views/TabBar.js` and `react-devtools-shared/src/devtools/views/TabBar.css` rather than fork.

**Review by bvaughn — COMMENTED** [review]
I'm going to sit down the review now since most of what I'm writing is "use the shared thing rather than fork" 😁  I'd be happy to make that change myself, or you could. Your call!

**Comment by bvaughn** [comment]
Eh, screw it :smile: I'll hop in and help since it's after hours for you. Give me a few minutes and I'll push a commit that does my won nits.

File: packages/react-devtools-scheduling-profiler/src/App.js [hunk 3]
```diff
@@ -7,22 +7,32 @@
...
+import '@reach/menu-button/styles.css';
+import '@reach/tooltip/styles.css';
 
 import * as React from 'react';
-import {useState} from 'react';
 
-import ImportPage from './ImportPage';
-import CanvasPage from './CanvasPage';
+import {ModalDialogContextController} from './ModalDialog';
+import {SettingsContextController} from './Settings/SettingsContext';
```
Comment (bvaughn) [inline packages/react-devtools-scheduling-profiler/src/App.js:18]: I'm not convinced the settings dialog is worth the hassle of the forked contexts and files. For now, I'm going to just rip it out :D

File: packages/react-devtools-scheduling-profiler/src/hooks.js (hunk 1 above)
Comment (taneliang) [reply packages/react-devtools-scheduling-profiler/src/hooks.js:188]: Wow, cool! I didn't know this existed 😆

Comment (bvaughn) [reply packages/react-devtools-scheduling-profiler/src/hooks.js:188]: It's not released yet in stable, but DevTools uses prerelease APIs :smile:

https://github.com/reactjs/rfcs/blob/master/text/0147-use-mutable-source.md

**Comment by taneliang** [comment]
>  Give me a few minutes and I'll push a commit that implements my own nits.

Thanks! I gotta get back to my art history class readings 😆 Let me know if there's anything I can do! I'll be happy to follow up on anything tomorrow afternoon.

**Review by bvaughn — APPROVED** [review]
👍

File: packages/react-devtools-scheduling-profiler/src/hooks.js [hunk 4]
```diff
@@ -53,6 +52,8 @@ export function useBrowserTheme(): void {
         default:
           throw Error(`Unsupported theme value "${theme}"`);
       }
+    } else {
+      updateThemeVariables('light', documentElements);
```
Comment (bvaughn) [inline packages/react-devtools-scheduling-profiler/src/hooks.js:56]: @taneliang This should be `theme` not `'light'` right?

Comment (bvaughn) [reply packages/react-devtools-scheduling-profiler/src/hooks.js:56]: Ah this was outside of the feature flag conditional. My apologies.

Comment (taneliang) [reply packages/react-devtools-scheduling-profiler/src/hooks.js:56]: Oh I think we want `'light'` to prevent the app from going into dark mode?
