### PR TITLE
DevTools: Fixed potential cache miss when insepcting elements

### LINKED ISSUE #22241: [DevTools Bug] Could not inspect element with id "219". Error thrown:Cached data for element "219" not found
### Website or app

employer-test.apna.co

### Repro steps

The error occurred at InspectedElementContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:37563:3)
    at Suspense
    at ErrorBoundary_ErrorBoundary (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:36097:5)
    at div
    at InspectedElementErrorBoundaryWrapper (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:36542:3)
    at NativeStyleContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:38972:3)
    at div
    at div
    at OwnersListContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:34323:3)
    at SettingsModalContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:34764:3)
    at Components_Components (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40911:52)
    at ErrorBoundary_ErrorBoundary (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:36097:5)
    at div
    at div
    at ThemeProvider (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:36215:3)
    at PortaledContent (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:36249:5)
    at div
    at div
    at div
    at ThemeProvider (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:36215:3)
    at SchedulingProfilerContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:42093:3)
    at ProfilerContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40537:3)
    at TreeContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:29185:3)
    at SettingsContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:29796:3)
    at ModalDialogContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:36605:3)
    at DevTools_DevTools (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:51354:3)

### How often does this bug happen?

Often

### DevTools package (automated)

react-devtools-extensions

### DevTools version (automated)

4.18.0-f58bbcf9a

### Error message (automated)

Could not inspect element with id "219". Error thrown:Cached data for element "219" not found

### Error call stack (automated)

_No response_

### Error component stack (automated)

```text
at InspectedElementContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:37563:3)
    at Suspense
    at ErrorBoundary_ErrorBoundary (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:36097:5)
    at div
    at InspectedElementErrorBoundaryWrapper (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:36542:3)
    at NativeStyleContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:38972:3)
    at div
    at div
    at OwnersListContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:34323:3)
    at SettingsModalContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:34764:3)
    at Components_Components (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40911:52)
    at ErrorBoundary_ErrorBoundary (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:36097:5)
    at div
    at div
    at ThemeProvider (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:36215:3)
    at PortaledContent (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:36249:5)
    at div
    at div
    at div
    at ThemeProvider (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:36215:3)
    at SchedulingProfilerContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:42093:3)
    at ProfilerContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40537:3)
    at TreeContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:29185:3)
    at SettingsContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:29796:3)
    at ModalDialogContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:36605:3)
    at DevTools_DevTools (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:51354:3)
```

### GitHub query string (automated)

```text
https://api.github.com/search/issues?q=Could not inspect element with id . Error thrown:
Cached data for element  not found in:title is:issue is:open is:public label:"Component: Developer Tools" repo:facebook/react
```

### PR DESCRIPTION
**Pull request by bvaughn**
If the DevTools UI is closed and reopened, the in-memory inspected element cache will be reset. The backend assumes this data is cached though, and may send a "no-change" response if DevTools are re-opened and the element is re-inspected.

To fix this, the frontend sends an explicit "force" flag to tell the backend to resend the full data.

Resolves #22241

### CODE REVIEW

**Comment by bvaughn** [comment]
For some reason, tests are failing on CI:
```
FAIL  packages/react-devtools-shared/src/__tests__/inspectedElement-test.js (5.581 s)
  ● InspectedElement › should properly recover from a cache miss on the frontend

    Cannot find module 'react-devtools-shared/src/inspectEdelementMutableSource' from 'packages/react-devtools-shared/src/__tests__/inspectedElement-test.js'

      437 |     const {
      438 |       clearCacheForTests,
    > 439 |     } = require('react-devtools-shared/src/inspectEdelementMutableSource');
          |     
```

Running the same command locally, all tests pass.
```
yarn test --build --project=devtools -r=experimental --ci
```

Not sure what's going on here.

File: packages/react-devtools-shared/src/__tests__/inspectedElement-test.js [hunk 1]
```diff
@@ -384,6 +384,67 @@ describe('InspectedElement', () => {
...
+    });
+
+    const {
+      clearCacheForTests,
+    } = require('react-devtools-shared/src/inspectedElementMutableSource');
+    clearCacheForTests();
+
+    targetRenderCount = 0;
+    inspectedElement = await inspectElementAtIndex(1);
+    // TODO expect(targetRenderCount).toBe(1);
```
Comment (jstejada) [inline packages/react-devtools-shared/src/__tests__/inspectedElement-test.js:444]: why is this assertion commented out? what is the TODO?

File: packages/react-devtools-shared/src/backend/legacy/renderer.js [hunk 2]
```diff
@@ -694,8 +694,9 @@ export function attach(
     requestID: number,
     id: number,
     path: Array<string | number> | null,
+    forceFullData: boolean,
```
Comment (jstejada) [inline packages/react-devtools-shared/src/backend/legacy/renderer.js:697]: apologies if i've missed this context from before; what is the story behind the legacy renderer? how much do we need to support it? and is this also being exercised in the tests?

File: packages/react-devtools-shared/src/inspectedElementMutableSource.js [hunk 3]
```diff
@@ -62,8 +62,15 @@ export function inspectElement({
   rendererID: number,
 |}): Promise<InspectElementReturnType> {
   const {id} = element;
+
+  // This could indicate that the DevTools UI has been closed and reopened.
+  // The in-memory cache will be clear but the backend still thinks we have cached data.
+  // In this case, we need to tell it to resend the full data.
+  const forceFullData = !inspectedElementCache.has(id);
```
Comment (jstejada) [inline packages/react-devtools-shared/src/inspectedElementMutableSource.js:69]: nit: i wonder if a name like `resetCachedElement` or similar would convey more precisely the intent of this argument? i feel like `forceFullData` seems a little vague: which data? what does it mean that it's full?

Comment (jstejada) [reply packages/react-devtools-shared/src/inspectedElementMutableSource.js:69]: just kind of thinking out loud: is there any instance where we *wouldn't* want the backend to send back the full data even when the element isn't cached in the frontend?

**Review by jstejada — APPROVED** [review]
cool! thanks for the test!

**Comment by jstejada** [comment]
> Cannot find module 'react-devtools-shared/src/inspectEdelementMutableSource'

@bvaughn looks like that path has a typo? `inspectEdelement`

File: packages/react-devtools-shared/src/__tests__/inspectedElement-test.js (hunk 1 above)
Comment (bvaughn) [reply packages/react-devtools-shared/src/__tests__/inspectedElement-test.js:444]: Oops I was testing and forgot I left it commented out.

File: packages/react-devtools-shared/src/backend/legacy/renderer.js (hunk 2 above)
Comment (bvaughn) [reply packages/react-devtools-shared/src/backend/legacy/renderer.js:697]: Bare minimal support.

I didn't add a test for this because I thought it would be a big hassle 😅

File: packages/react-devtools-shared/src/inspectedElementMutableSource.js (hunk 3 above)
Comment (bvaughn) [reply packages/react-devtools-shared/src/inspectedElementMutableSource.js:69]: > is there any instance where we wouldn't want the backend to send back the full data even when the element isn't cached in the frontend?

No, I don't think so.

The term "full data" comes from the types of response the backend sends:
* hydrated-path
* *no-change
* *not-found
* full-data

**Comment by bvaughn** [comment]
> > Cannot find module 'react-devtools-shared/src/inspectEdelementMutableSource'
> 
> @bvaughn looks like that path has a typo? `inspectEdelement`

It did, but that was fixed in a previous commit. :)
