### PR TITLE
validateDOMNesting: Allow hr as child of select

### LINKED ISSUE #27572: Bug: 'Warning: validateDOMNesting: <hr> cannot appear as a child of <select>' – but this is now valid HTML
The latest version of Chrome and Safari support `hr` elements as children of `select` elements, and the HTML spec has been updated – but React warns about this as it used to be invalid HTML.

- https://developer.chrome.com/blog/hr-in-select
- https://webkit.org/blog/14445/webkit-features-in-safari-17-0/#:~:text=Horizontal%20rules%20inside%20select%20elements
- https://html.spec.whatwg.org/#the-select-element-2:~:text=Zero%20or%20more%20option%2C%20optgroup%2C%20hr%2C%20and%20script%2Dsupporting%20elements.
- https://html.spec.whatwg.org/#the-select-element-2:~:text=Occasionally%20it%20can%20be%20useful%20to%20have%20a%20separator%3A

Screenshot of before and after with hr in select. The after image has dividers between groups.

React version: `18.2.0`

## Steps To Reproduce

1. Add a `hr` element as a child of `select`

## The current behavior

`Warning: validateDOMNesting: <hr> cannot appear as a child of <select>`

## The expected behavior

No `validateDOMNesting` warning.

### PR DESCRIPTION
**Pull request by SouSingh**
fix #27572

### CODE REVIEW

**Comment by philwolstenholme** [comment]
@sophiebits, @SouSingh got to this before I did :) 

(re: https://github.com/facebook/react/issues/27572)

**Review by sophiebits — APPROVED** [review]
thank you!

File: packages/react-dom-bindings/src/client/validateDOMNesting.js [hunk 1]
```diff
@@ -244,7 +244,7 @@ function isTagValidWithParent(tag: string, parentTag: ?string): boolean {
   switch (parentTag) {
     // https://html.spec.whatwg.org/multipage/syntax.html#parsing-main-inselect
     case 'select':
-      return tag === 'option' || tag === 'optgroup' || tag === '#text';
+      return tag === 'option' || tag === 'optgroup' || tag === '#text' || tag === 'hr';
```
Comment (sophiebits) [inline packages/react-dom-bindings/src/client/validateDOMNesting.js:247]:
```suggestion
      return (
        tag === 'hr' ||
        tag === 'option' ||
        tag === 'optgroup' ||
        tag === '#text'
      );
```
