### PR TITLE
Fix UMD bundles, making safe to use as required modules

### LINKED ISSUE #7482: Master UMD builds don’t work as CommonJS using Webpack alias config
Not sure what’s up yet but putting this up so I don’t forget to check it later.
In the past, I could put this into Webpack config:

```js
	resolve: {
		alias: {
			react: 'react/dist/react',
			'react-dom': 'react-dom/dist/react-dom',
		},
      }
```

Many people do that to improve build times.

This works with 0.14.x and 15.3.0 but not in master.
Most likely related to recent @sebmarkbage changes.

It fails like this:

screen shot 2016-08-12 at 14 55 55

Seems like it claims to be a UMD shim but assumes global environment (whereas a true UMD shim would detect environment and fallback to `require` when available).

cc @zpao

### PR DESCRIPTION
**Pull request by zpao**
I think this fixes the problem. There's a giant comment in there explaining why and how.

I want to stress that this is a short-term solution. It works and the reasoning is sound but I'm not happy that we need this. It's probably time to start using webpack to bundle but that would have taken me much longer to go do.

Byte-wise this should be fine. We're just adding the code that you can see in there. Since we do this after the bundle process is done, that `require('react')` isn't analyzed.

## Todo:
- [x] Look for any other expected globals in shims
- [x] Use this in other bundles
- [x] Look into the RequireJS situation. I honestly don't care much about that but we should probably make it work. It would require rejiggering the wrapper (since we couldn't execute the UMDed module immediately)

cc @facebook/react-core 

Fixes #7482 

## Test Plan:
- Made a hello world app with webpack and aliased `react` and `react-dom`.
- Ran the same hello world using the dist files directly (so React & ReactDOM were globals).

### CODE REVIEW

**Comment by zpao** [comment]
The other case we have is ReactWithAddons, which has a shim that uses a global ReactDOM. However we've never supported using ReactWithAddons as a drop-in replacement in a require system. It should continue to work fine when using globals (eg script tags) just not replacing `require('react/addons')`. We'd get into a circular dep situation.

**Comment by zpao** [comment]
Ok, got this working and tested for ReactDOM/Server. I haven't tested the AMD stuff (meh) but I think it's right now. @gaearon gave me the thumbs up so I'm going to just merge and get 15.4 RC out.

File: grunt/config/browserify.js [hunk 1]
```diff
@@ -62,6 +62,52 @@ function simpleBannerify(src) {
   );
 }
 
+// What is happening here???
+// I'm glad you asked. It became really to make our bundle splitting work.
```
Comment (Aweary) [inline grunt/config/browserify.js]: It became really what?! 😄

Comment (zpao) [inline grunt/config/browserify.js]: Too late! I pressed merge.

It became really "hard". Or maybe I wrote "annoying"? I'm going to leave the mystery in there for now :)

File: grunt/config/browserify.js [hunk 2]
```diff
@@ -62,6 +62,52 @@ function simpleBannerify(src) {
...
+function wrapperify(src) {
+  return `
+;(function(f) {
+  // CommonJS
+  if (typeof exports === "object" && typeof module !== "undefined") {
+    f(require('react'));
+
+  // RequireJS
+  } else if (typeof define === "function" && define.amd) {
+    require(['react'], f);
```
Comment (gaearon) [inline grunt/config/browserify.js]: I think this should be define, not require.

Comment (gaearon) [inline grunt/config/browserify.js]: Looked in the docs and you're right. 😅
