### PR TITLE
Fixed failing unit tests in browsers that don't support WebComponents

### LINKED ISSUE #3919: Load webcomponents.js differently
Our tests currently only pass in the browser when running in Chrome. This is because it supports WebComponents already. However they fail in every other browser. I think this is because of when webcomponents.js is actually loaded. It's currently getting packaged into react-test because we're requiring it. It creates a new `Node` which is resulting in nodes we create with `createNodeFromMarkup` to have a different prototype than what is expected in WebComponents. WebComponents's new Node prototype has a different implementation of `insertBefore` which does an `instanceof Node` check which our nodes are failing. I think if we loaded webcomponents.js into the browser before we loaded JS, the node we create for markup wrapping would have the right prototype.

### PR DESCRIPTION
**Pull request by jimfb**
As per https://github.com/facebook/react/issues/3919, our tests currently only pass in the browser when running in Chrome because when webcomponents.js is actually loaded, it's currently getting packaged into react-test because we're requiring it. It creates a new Node which is resulting in nodes we create with createNodeFromMarkup to have a different prototype than what is expected in WebComponents. WebComponents's new Node prototype has a different implementation of insertBefore which does an instanceof Node check which our nodes are failing.

This PR explicitly checks for PhantomJS (probably not strictly necessary, since we had the try-catch there before, but Paul asked for a check).  Also loads webcomponents.js for tests before any of the other javascript.

There are still a couple of tests failing in my Firefox, but presumably that's unrelated.  We can investigate those tests further tomorrow.  In the mean time, this diff should be ready to land.

cc @zpao 

Fixes #3919

### CODE REVIEW

File: src/renderers/dom/client/__tests__/ReactMount-test.js [hunk 1]
```diff
@@ -20,9 +20,12 @@ describe('ReactMount', function() {
   var WebComponents = undefined;
 
   try {
-    WebComponents = require('WebComponents');
+    if (!/PhantomJS/.test(window.navigator.userAgent)) {
+      WebComponents = require('WebComponents');
+    }
   } catch(e) {
-    /* leave WebComponents undefined */
+    // Parse error expected on super old/sketchy browsers
```
Comment (zpao) [inline src/renderers/dom/client/__tests__/ReactMount-test.js]: Old yes, sketchy no. I would clarify and just say "engines that don't support setters"

File: src/renderers/dom/client/__tests__/ReactMount-test.js [hunk 2]
```diff
@@ -20,9 +20,12 @@ describe('ReactMount', function() {
   var WebComponents = undefined;
 
   try {
-    WebComponents = require('WebComponents');
+    if (!/PhantomJS/.test(window.navigator.userAgent)) {
```
Comment (zpao) [inline src/renderers/dom/client/__tests__/ReactMount-test.js]: This is the wrong check. We aren't using Phantom when we run these with `grunt test --debug`. We shouldn't require it in any case where we're in a real browser (I think we have some other test like this but I can't find it at the moment, perhaps just checking if `jest` is defined would work)

Comment (jimfb) [inline src/renderers/dom/client/__tests__/ReactMount-test.js]: No, I think the opposite is true.  We DO want to require it in any case where we're in a real browser.  The polyfill will detect if the browser supports webcomponents, and if the browser does not support them, it will polyfill them.  Either way, we want to run this test in any browser that might support webcomponents (either natively or as a result of a polyfill).

One could argue that this test is unnecessary (because webcomponents will fail to load in PhantomJS anyway), which will result in the catch block, but we do want this in real browsers.

Comment (zpao) [inline src/renderers/dom/client/__tests__/ReactMount-test.js]: No, that's why we're loading it in test/index.html

File: src/renderers/dom/client/__tests__/ReactMount-test.js (hunk 1 above)
Comment (jimfb) [inline src/renderers/dom/client/__tests__/ReactMount-test.js]: Done.

File: src/renderers/dom/client/__tests__/ReactMount-test.js (hunk 2 above)
Comment (jimfb) [inline src/renderers/dom/client/__tests__/ReactMount-test.js]: Oh, yeah, you're right!

**Comment by jimfb** [comment]
@zpao updated.

File: src/renderers/dom/client/__tests__/ReactMount-test.js [hunk 3]
```diff
@@ -17,12 +17,16 @@ describe('ReactMount', function() {
   var React = require('React');
   var ReactMount = require('ReactMount');
   var ReactTestUtils = require('ReactTestUtils');
-  var WebComponents = undefined;
+  var WebComponents = WebComponents;
 
   try {
-    WebComponents = require('WebComponents');
+    if(WebComponents === undefined && jest !== undefined) {
```
Comment (zpao) [inline src/renderers/dom/client/__tests__/ReactMount-test.js]: space after `if`
