### PR TITLE
[Bugfix] Pending state is always user-blocking

### LINKED ISSUE #17272: When calling a useTransition startTransition callback outside of event handlers, isPending is never set to true
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

`isPending` is never set to true when calling `startTransition` within `useEffect`, but it *does* work properly when within a `useLayoutEffect`.

https://codesandbox.io/s/usetransition-useeffect-issues-p1j9s

Here's the correct behavior (accomplished via `useLayoutEffect`):

good

Here's the incorrect behavior (via `useEffect`):

bad

Note the difference is that the opacity never changes to 0.4 (which is determined based on the `isPending` state).

**What is the expected behavior?**

I expect them to both behave the same (at least as far as the user can observe).

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

- react@0.0.0-experimental-f6b8d31a7
- react-dom@0.0.0-experimental-f6b8d31a7

### PR DESCRIPTION
**Pull request by acdlite**
Fixes a bug where `isPending` is only set to `true` if `startTransition` is called from inside an input event. That's usually the case, but not always.

Now it works regardless of where you call it.

Fixes #17272

### CODE REVIEW

**Comment by gaearon** [comment]
Btw we track this in https://github.com/facebook/react/issues/17272

File: packages/react-reconciler/src/ReactFiberHooks.js [hunk 1]
```diff
@@ -1157,65 +1159,62 @@ function updateDeferredValue<T>(
...
+      }
     },
     [value, config],
   );
   return prevValue;
 }
 
+function startTransition(setPending, config, callback) {
+  const priorityLevel = getCurrentPriorityLevel();
+  runWithPriority(
```
Comment (sebmarkbage) [inline packages/react-reconciler/src/ReactFiberHooks.js]: I feel like we do this in a couple of internal places which seems like a very heavy weight way to do this. Going through the scheduler to do this. This adds to my suspicion that reading priorities from scheduler is the wrong model. It's not that scheduler dictates the priorities but it sometimes can be used as a default.

File: packages/react-reconciler/src/ReactFiberHooks.js [hunk 2]
```diff
@@ -1157,65 +1159,62 @@ function updateDeferredValue<T>(
...
+    priorityLevel < UserBlockingPriority ? UserBlockingPriority : priorityLevel,
+    () => {
+      setPending(true);
+    },
+  );
+  runWithPriority(
+    priorityLevel > NormalPriority ? NormalPriority : priorityLevel,
```
Comment (sebmarkbage) [inline packages/react-reconciler/src/ReactFiberHooks.js]: Similarly here, it's not obvious to me that calling startTransition should change the running "current" queue of the scheduler. It should only change the priority inside React. They're not necessarily 1:1.

File: packages/react-reconciler/src/__tests__/ReactTransition-test.internal.js [hunk 3]
```diff
@@ -0,0 +1,102 @@
...
+let ReactFeatureFlags;
+let React;
+let ReactNoop;
+let Scheduler;
+let Suspense;
+let useState;
+let useTransition;
+let act;
+
+describe('ReactHooksWithNoopRenderer', () => {
```
Comment (gaearon) [inline packages/react-reconciler/src/__tests__/ReactTransition-test.internal.js]: Copy paste name

File: packages/react-reconciler/src/ReactFiberHooks.js (hunk 1 above)
Comment (acdlite) [reply packages/react-reconciler/src/ReactFiberHooks.js]: I agree, it's on my list of things to consider during expiration times refactor. Didn't want to couple it to this bugfix.
