### PR TITLE
[Flight] Don't hang after resolving cyclic references

### LINKED ISSUE #34751: Bug: RSC `renderToReadableStream/createFromReadableStream` gets stuck for certain objects on development
React version: 19.2

(This didn't reproduce on 19.1.1. Based on old reproduction https://github.com/hi-ogawa/react-router-templates/commit/e6eddd0a3393a2379f238224be1fc85d71efd2c9, it reproduced since at least 19.2.0-canary-19baee81-20250725.)

## Steps To Reproduce

When serializing and deserializing certain objects with the same object reference as a property and as a prop, `createFromReadableStream` gets stuck.

```tsx
import { renderToReadableStream } from "react-server-dom-xxx/server.edge";
import { createFromReadableStream } from "react-server-dom-xxx/client.edge";

async function test1() {
  // serialize same `obj` reference as top-level object and as prop
  const obj = {};
  function Test(_props: { obj: {} }) {
    return "test";
  }
  const original = {
    obj: obj,
    node: <Test obj={obj} />,
  }
  console.log("[original]", original);
  const stream = renderToReadableStream(original);
  console.log("[stream]", stream);
  const restored = await createFromReadableStream(stream); // 👈 this gets stuck
  console.log("[restored]", restored);
}
```

Interestingly, it works if the order of properties are flipped, for example:

```tsx
  const original = {
    node: <Test obj={obj} />,
    obj: obj,
  }
```

This happens only on development. I initially observed this behavior on react-router https://github.com/remix-run/react-router/issues/14085 and minimized a reproduction to the above pattern.

Link to code example:
- parcel https://github.com/hi-ogawa/reproductions/tree/main/react-router-14085-rsc-dup-obj-parcel
- vite https://github.com/hi-ogawa/reproductions/tree/main/react-router-14085-rsc-dup-obj

## The current behavior

`createFromReadableStream` gets stuck

## The expected behavior

`createFromReadableStream` can deserialize stream

### PR DESCRIPTION
**Pull request by unstubbable**
When we've resolved a cyclic reference in a blocked chunk, this might have fully unblocked the chunk. In that case, we must not re-add listeners to the chunk, and wake it instead (using the remaining listeners).

fixes #34751

### CODE REVIEW

File: packages/react-client/src/ReactFlightClient.js [hunk 1]
```diff
@@ -624,6 +624,12 @@ function wakeChunkIfInitialized<T>(
                 rejectListeners.splice(rejectionIdx, 1);
               }
             }
+            // The status might have changed after fulfilling the reference.
+            return wakeChunkIfInitialized(
```
Comment (sebmarkbage) [inline packages/react-client/src/ReactFlightClient.js]: We should try to avoid recursion when not necessary. For example, a pattern we typically use is check if something is resolved first and then initialize and then check if something is initialized instead of a single switch.

In this case, there can also be a lot of listeners when there's a lot of references to the same thing so in theory you can actually stack overflow because of this recursion.

Instead, you should check if the status has changed to initialized or errored here and if so call `wakeChunk` or `rejectChunk` respectively.
