### PR TITLE
Use the virtual target for change events to avoid restoring controlled state on the real target

### LINKED ISSUE #10420: <select>'s onChange event fires with incorrect selectedIndex, value
**Do you want to request a *feature* or report a *bug*?**
Report a bug.

**What is the current behavior?**
`<select>` element's `onChange` event is fired with incorrect `selectedIndex` and `value`, like it hasn't actually changed. This happens only if the element has been rendered under another React DOM root, see the example in the link below.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
https://jsfiddle.net/martinsb/wd54vmmj/7/

**What is the expected behavior?**
`onChange` callback handlers should receive events with those values that user has actually selected. In the test case above, for example, when choosing "Two", I expect to have the following console output: `Change event, selectedIndex: 1, value: 2`

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
The bug is observed with `react` and `react-dom` packages version `16.0.0-beta.3`. Latest stable version (`15.6.1`) works just fine.

### PR DESCRIPTION
**Pull request by sebmarkbage**
Fixes #10420

The problem is that we try to restore the controlled value after the `oninput` event. So we've restored it to its previous value by the time we fire `onChange`. So the controlling component doesn't have a chance to update it.

This ensures that we "restore controlled state" on the wrapper instead of the real target - which is a noop.

### CODE REVIEW

File: fixtures/dom/src/components/fixtures/selects/index.js [hunk 1]
```diff
@@ -24,8 +48,14 @@ class SelectFixture extends React.Component {
             <option value="">Select a color</option>
             <option value="red">Red</option>
             <option value="blue">Blue</option>
-            <option value="gree">Green</option>
```
Comment (nhunzaker) [inline fixtures/dom/src/components/fixtures/selects/index.js]: 🙈. I wonder who did this.

**Comment by sebmarkbage** [comment]
I think this could be related to: https://github.com/facebook/react/commit/0b220d0f04c9fea472c7cf8a7837322388728ca6

@jquense Do you have an idea why that would be? Input events no longer fire `onChange` on `<select />`?

**Comment by sebmarkbage** [comment]
Actually, nevermind, what I saw might have just been related to the fixtures setup in there. I'll dig deeper.

**Comment by sebmarkbage** [comment]
Actually, nevermind the nevermind, this does bisect cleanly to that commit so it is related somehow.

**Comment by sebmarkbage** [comment]
@jquense This fix seems to fix it but I'm not sure if that breaks something else. https://github.com/facebook/react/pull/10444/commits/2348742f0baccca745b2f76a2720706a56eafce1

The fixture test seems to work, but the fixture select seems broken. :)

**Comment by jquense** [comment]
arg this is was beyond weird. yeah I originally had #10238 do this but ran it the issue you are seeing on the fixture select (https://github.com/facebook/react/pull/10238#issuecomment-316832051)

I am honestly not sure why it's happening. The value on the input ends up being empty by the time the onInput runs even tho it was correct for the `onChange` (or maybe its the other way around). I didn't spend to much time trying to figure it out since it seemed fine to keep the old behavior.

Let me poke at it...

**Comment by jquense** [comment]
Maybe the problem is we don't have corresponding setup calls in https://github.com/sebmarkbage/react/blob/2348742f0baccca745b2f76a2720706a56eafce1/src/renderers/dom/fiber/ReactDOMFiberComponent.js#L544 ?

**Comment by sebmarkbage** [comment]
So one issue is that `targetInst` here can be the surrounding `<div />` instead of the `<select />`. https://github.com/sebmarkbage/react/blob/2348742f0baccca745b2f76a2720706a56eafce1/src/renderers/dom/shared/eventPlugins/ChangeEventPlugin.js#L140

That's because `extractEvents` gets called first for the inner subtree, and then later for the outer subtree. In the inner subtree, the deepest target instance is the div.

**Comment by jquense** [comment]
With both events it only seems to break in the case where you change locations onChange. What I see is:

- `onInput` fires with the correct `value` on `event.target`
- `Header.handleFixtureChange` fires and sets `window.location`
- `onChange` fires with the previous `value` on `event.target` (WAT?)

At no point though does the `input.value` set descriptor get hit, so something isn't inadvertently resetting the value in React. it really seems like like the event is firing with the wrong value. This also happens in FF though so it is maybe not some undefined behavior

**Comment by sebmarkbage** [comment]
I think the issue is that this returns the wrong thing and a change event gets fired on the surrounding "div". https://github.com/facebook/react/blob/master/src/renderers/dom/shared/eventPlugins/ChangeEventPlugin.js#L172

Because `targetNode` is the "div" and then it tries to do a "restore". But the "restore" works against the native event target so it restores the value.

**Comment by sebmarkbage** [comment]
This ensures that they're consistent for the nested vs not case: https://github.com/facebook/react/pull/10444/commits/43e46198db4f5e98f87186a0bdb158eccfa7ab02

However, this only works because the happen to ignore the restore event properly. The fact that this worked in the normal case seems super fragile to me. Is there another nesting where this breaks? So I'm not super happy with this solution. :/

**Comment by sebmarkbage** [comment]
I think I'm going to merge this because this solves this particular issue.

I think we've discovered other issues here. If there is a change listener, higher up in the tree, then it will get invoked as a "change" event. I don't know what kind of consequences that will have.

**Comment by jquense** [comment]
> That's because extractEvents gets called first for the inner subtree, and then later for the outer subtree. In the inner subtree, the deepest target instance is the div.

ah that is tricky :/ is the underlying problem that the additional change event fires? I was seeing extractEvents called for the select first, then the div. The extractEvents shouldn't fire at all for the div right?

**Comment by sebmarkbage** [comment]
If someone uses `dispatchEvent` to dispatch a "change" event on something arbitrary that the browser wouldn't. Such as a custom-element. Should that be picked up by a React `onChange` listener above it? ¯\\\_(ツ)\_/¯

**Comment by sebmarkbage** [comment]
I think the issue is that this is now always true. https://github.com/sebmarkbage/react/blob/2348742f0baccca745b2f76a2720706a56eafce1/src/renderers/dom/shared/eventPlugins/ChangeEventPlugin.js#L165

It used to be that we sometimes would fall into the case where this was false for unknown targets.

**Comment by sebmarkbage** [comment]
Hm. I'm going to change my patch a bit. I don't think we want to pass the virtual target as the event target in the event object. We don't do that elsewhere.

With regard to when to fire this. I think we probably don't want to bubble the event on any blur which I think it what will happen now, right?

**Comment by sebmarkbage** [comment]
There's something off about the way we do bubbling and how we create custom events. We extract events once per subtree so that we can do the bubbling within that subtree. That means that we have to recreate the same event for each subtree. Ideally using the nativeEventTarget as the basis for all decisions so it's consistent. However, we can't do that right now because the change event plugin's `extractEvents` function is not idempotent because `updateValueIfChanged` changes the value when observed.

I'm tempted to leave it semi-broken as is now so we don't break it more and then revisit semantics in 17.

The workaround to get sane semantics is to use Portals for now.
