### PR TITLE
Fixed edge case bug in Profiler

### LINKED ISSUE #23283: [DevTools Bug] Could not find node with id "18" in commit tree
### Website or app

https://github.com/ModelSaber/ModelSaber.Main

### Repro steps

Just try and load the 2/5 and 3/5 report from a reload and start profiling instance.

Change `REACT_APP_API_URL` to `https://apimodelsaber.rainemods.io` in order to launch the app without needing the full .NET 6 environment and the corresponding data in the postgres database.

### How often does this bug happen?

Every time

### DevTools package (automated)

react-devtools-extensions

### DevTools version (automated)

4.23.0-e28a0db22

### Error message (automated)

Could not find node with id "18" in commit tree

### Error call stack (automated)

```text
at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:25574:13
    at Map.forEach (<anonymous>)
    at RankedChartBuilder_getChartData (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:25570:24)
    at ProfilingCache_ProfilingCache.getRankedChartData (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:25686:11)
    at CommitRankedAutoSizer (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43680:32)
    at gi (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:15400:7)
    at zj (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:16741:7)
    at jl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:19201:86)
    at il (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:18756:11)
    at hl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:18748:23)
```

### Error component stack (automated)

```text
at CommitRankedAutoSizer (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43659:34)
    at div
    at div
    at div
    at SettingsModalContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:35975:3)
    at Profiler_Profiler (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:53276:34)
    at ErrorBoundary_ErrorBoundary (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:37375:5)
    at div
    at div
    at ThemeProvider (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:37518:3)
    at PortaledContent (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:37548:5)
    at div
    at div
    at div
    at ThemeProvider (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:37518:3)
    at TimelineContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:42700:3)
    at ProfilerContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:42146:3)
    at TreeContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:30256:3)
    at SettingsContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:30878:3)
    at ModalDialogContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:37927:3)
    at DevTools_DevTools (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:53807:3)
```

### GitHub query string (automated)

```text
https://api.github.com/search/issues?q=Could not find node with id  in commit tree in:title is:issue is:open is:public label:"Component: Developer Tools" repo:facebook/react
```

### PR DESCRIPTION
**Pull request by bvaughn**
Resolves #23283

The core of this change is to audit all of the places the DevTools backend bails out without sending operations to make sure they all use the _exact same logic_ to avoid the possibility that we would send a profiling update without an associated operations array (or the other way around).

I can repro the bug that was originally reported [in Code Sandbox](https://github.com/facebook/react/issues/23283#issuecomment-1058480056) but [not in a unit test](https://github.com/facebook/react/pull/24031#issuecomment-1063056497). However one of our pre-existing tests_does_ show an updated snapshot after this change. (A commit that was previously filtered is no longer filtered.) The old code used to bail out in `handleCommitFiberRoot()` because `currentCommitProfilingMetadata.durations` was empty, but the new code _doesn't_ bail out because there are `pendingRealUnmountedIDs`.

### CODE REVIEW

File: packages/react-devtools-shared/src/__tests__/__snapshots__/profilingCache-test.js.snap [hunk 1]
```diff
@@ -3279,8 +3283,12 @@ Object {
           1,
           0,
           2,
-          1,
+          5,
           4,
+          11,
+          10,
+          8,
+          7,
```
Comment (bvaughn) [inline packages/react-devtools-shared/src/__tests__/__snapshots__/profilingCache-test.js.snap:3291]: I didn't anticipate this change. (Some change, maybe, but this specific change seems odd to me.)

**Comment by bvaughn** [comment]
I think the core of why it's difficult to repro this issue in a test is that the mock Scheduler does not provide a way to advance the timer (and thus change the tree base duration) for built- in component types like Suspense. This causes the old bailout logic to work for the unit tests (since both operations and profiling durations are empty) whereas the real, in-the-browser code _usually_ picks up on small tree base duration differences.

**Review by lunaruan — APPROVED** [review]
