### PR TITLE
Initialize React prop name/attribute name mapping without Map

### LINKED ISSUE #12349: React adds "className" to DOM instead of "class" in IE11
**Do you want to request a *feature* or report a *bug*?**
It is a bug

**What is the current behavior?**
React adds "className" to the DOM instead of "class" property. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

Open the link below in IE11 and inspect the DOM. There will be the following h1 - `<h1 className="test-ie11-bug">Hello React :)</h1>`
https://vydimitrov.github.io/react-simple-boilerplate/

Link to the test repo:
https://github.com/vydimitrov/react-simple-boilerplate

**What is the expected behavior?**
To add "class" to DOM when an element has property "className"

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React 16.3.0-alpha.1
Internet Explorer 11 - version 11.540.15063.0

It works as expected in React 16.2.0

### PR DESCRIPTION
**Pull request by aweary**
Fixes #12349. See https://github.com/facebook/react/issues/12349#issuecomment-372184873.

Using `new Map(iterable)` isn't supported in IE11, so it ends up trying to iterate through an empty map and these attributes don't get defined in properties. Since this is only run once on startup inlining the `attributeName` array is probably fine.

### CODE REVIEW

File: packages/react-dom/src/shared/DOMProperty.js [hunk 1]
```diff
@@ -224,12 +224,8 @@ const properties = {};
...
 // A few React string attributes have a different name.
 // This is a mapping from React prop names to the attribute names.
-new Map([
-  ['acceptCharset', 'accept-charset'],
-  ['className', 'class'],
-  ['htmlFor', 'for'],
-  ['httpEquiv', 'http-equiv'],
-]).forEach((attributeName, name) => {
+['acceptCharset', 'className', 'htmlFor', 'httpEquiv'].forEach((name, i) => {
+  const attributeName = ['accept-charset', 'class', 'for', 'http-equiv'][i];
```
Comment (jquense) [inline packages/react-dom/src/shared/DOMProperty.js]: might be clearer if it was an array of array pairs? Like maybe just the argument to the original map. Less likely to accidentally shift one array but not the other
