### PR TITLE
Fix a memory leak in ReactComponentTreeDevtool

### LINKED ISSUE #6750: New ReactPerf doesn’t free memory in DEV when not profiling
We purge it [here](https://github.com/facebook/react/blob/b11540ccb2321aeb7259fcf0b3a38aeeea35231d/src/isomorphic/ReactDebugTool.js#L88-L89) but this code doesn’t run because of the [early exit](https://github.com/facebook/react/blob/b11540ccb2321aeb7259fcf0b3a38aeeea35231d/src/isomorphic/ReactDebugTool.js#L53-L57).

Need to fix this and add a test case to make sure we don’t regress on it.

### PR DESCRIPTION
**Pull request by gaearon**
`ReactDebugTool` used to only call `purgeUnmountedComponents()` while profiling, so information about unmounted instances kept accumulating when not profiling.

Additionally, unmounting in React Native and rendering to string did not correctly clean up the devtool.

Finally, the tests tested the wrong behavior and relied on explicit `purgeUnmountedComponent()` calls.

To fix this, we:

* Test specifically that unmounting is enough to clean up the tree devtool.
* Add missing `onBeginFlush` and `onEndFlush` calls to server and native rendering so `ReactDebugTool` knows when to copy the tree.

Fixes #6750.

Reviewers: @sebmarkbage @spicyj.

### CODE REVIEW

File: src/isomorphic/devtools/ReactComponentTreeDevtool.js [hunk 1]
```diff
@@ -106,6 +106,11 @@ var ReactComponentTreeDevtool = {
   },
 
   purgeUnmountedComponents() {
+    if (ReactComponentTreeDevtool._preventPurging) {
```
Comment (gaearon) [inline src/isomorphic/devtools/ReactComponentTreeDevtool.js]: Not a big fan of these but I’m not sure how else we can test the expected tree during server rendering, if `ReactDebugTool` cleans it up right before the batch. Alternatively we can make those integration tests instead in `ReactPerf-test`, but I like how comprehensive the suite for `ReactComponentDebugTool` is, so I don’t want to replicate the same complexity in `ReactPerf-test`.

Comment (spicyj) [inline src/isomorphic/devtools/ReactComponentTreeDevtool.js]: Could you add another devtool for the test that checks the state at an appropriate time? If not or if that's too clunky, I think this seems fine too.

**Comment by spicyj** [comment]
Thanks.

**Comment by facebook-github-bot-4** [comment]
@gaearon updated the pull request.

File: src/isomorphic/devtools/ReactComponentTreeDevtool.js (hunk 1 above)
Comment (gaearon) [inline src/isomorphic/devtools/ReactComponentTreeDevtool.js]: I’d keep it this way for now. I’m not sure about this reliance on flush events anyway (https://github.com/facebook/react/pull/6046#discussion_r61482538), so I’d rather avoid relying on the order in which devtools are called for now.
