### PR TITLE
Fixed scheduler setTimeout fallback

### LINKED ISSUE #14352: useEffect is broken for React Native with JSC
As reported in open source (facebook/react-native/issues/21967), the `useEffect` hook is broken for React Native when using JavaScriptCore (which affects both iOS and Android).

This is because the [`setTimeout` branch of `scheduler`](https://github.com/facebook/react/blob/c2a2d8a539bf02e40c43d36adc2826e228f30955/packages/scheduler/src/Scheduler.js#L463-L495) specifies a [5000ms delay](https://github.com/facebook/react/blob/c2a2d8a539bf02e40c43d36adc2826e228f30955/packages/scheduler/src/Scheduler.js#L483). This 5000ms is _supposed to be the maximum expiration time_, but in this fork it _ends up being the minimum callback time_ (unless another state update forces us to sync-flush pending callbacks). Since `useEffect` is passive, this means React won't call it until after a few seconds have passed.

I assume we (React team) haven't noticed this because we're typically using the `postMessage` implementation, but with JavaScriptCore– React Native ends up using the `setTimeout` fork.

I think this was broken by commit 4d17c3f (PR #13740) which intentionally changed the delay under the (mistaken) assumption that it would only impact unit tests.

If we want to avoid using `setTimeout` for React Native, I think we'll need to add a `scheduler` implementation that does not require `postMessage` or `MessageChannel`, since JavaScript Core does not support either.

### PR DESCRIPTION
**Pull request by bvaughn**
Resolves #14352 (and facebook/react-native/issues/21967)

* Restores a working `setTimeout` based fallback for the `scheduler` package.
* Relocates test-specific code into a new NPM package, `jest-mock-scheduler`.
* Updates tests.

I tested and verified that these updates to `scheduler` fix the reported React Native `useEffects` bug.

I've also published a 0.0.0 release to [`jest-mock-scheduler`](http://npmjs.com/package/jest-mock-scheduler) to reserve the name.

### CODE REVIEW

File: packages/scheduler/src/Scheduler.js [hunk 1]
```diff
@@ -449,39 +449,42 @@ var shouldYieldToHost;
...
+  cancelHostCallback = windowImpl[1];
+  shouldYieldToHost = windowImpl[2];
+  getCurrentTime = windowImpl[3];
+} else if (typeof global !== 'undefined' && global._schedMock) {
+  // Dynamic injection, only for testing purposes.
+  var globalImpl = global._schedMock;
+  requestHostCallback = globalImpl[0];
+  cancelHostCallback = globalImpl[1];
+  shouldYieldToHost = globalImpl[2];
+  getCurrentTime = globalImpl[3];
```
Comment (bvaughn) [inline packages/scheduler/src/Scheduler.js]: This is a little awkward. I could combine these branches?

File: packages/scheduler/src/__tests__/Scheduler-test.js [hunk 2]
```diff
@@ -30,6 +30,9 @@ describe('Scheduler', () => {
     jest.useFakeTimers();
     jest.resetModules();
 
+    const JestMockScheduler = require('jest-mock-scheduler');
+    JestMockScheduler.mockRestore();
```
Comment (bvaughn) [inline packages/scheduler/src/__tests__/Scheduler-test.js]: This convention seemed fairly inline with existing Jest mock packages.

**Comment by bvaughn** [comment]
> Can you tell more about the intended audience of `jest-mock-scheduler`?

For the moment– we are the audience (React team and a few Facebook engineers working in www).

It makes it more convenient to test updates at a finer grain (advancing Jest timers a little bit, verify some things, then a little bit more). Seemed like the easiest path forward to replacing the `setTimeout` branch of `scheduler` with a functional fallback without breaking existing tests.

**Comment by gaearon** [comment]
I mean more like, do you expect product developers to ever need it? Does it help testing things like passive effects?

**Comment by bvaughn** [comment]
I'm not sure yet how useful it will end up being. @acdlite has thought about this before. Maybe he has a better intuition.

File: packages/scheduler/src/Scheduler.js (hunk 1 above)
Comment (gaearon) [reply packages/scheduler/src/Scheduler.js]: Let's combine.

File: packages/jest-mock-scheduler/package.json [hunk 3]
```diff
@@ -0,0 +1,27 @@
...
+  },
+  "homepage": "https://reactjs.org/",
+  "peerDependencies": {
+    "jest": "^23.0.1",
+    "scheduler": "^0.11.0"
+  },
+  "files": [
+    "LICENSE",
+    "README.md",
+    "build-info.json",
```
Comment (gaearon) [inline packages/jest-mock-scheduler/package.json]: What is this?

Comment (bvaughn) [reply packages/jest-mock-scheduler/package.json]: `build-info` is metadata managed and used by our release scripts.

File: packages/scheduler/src/Scheduler.js (hunk 1 above)
Comment (bvaughn) [reply packages/scheduler/src/Scheduler.js]: Sure, combined in 9a19b875d

File: packages/jest-mock-scheduler/package.json (hunk 3 above)
Comment (gaearon) [reply packages/jest-mock-scheduler/package.json]: What's in it? Sorry if I missed it somewhere. Do we include it in all packages?

File: packages/jest-mock-scheduler/index.js [hunk 4]
```diff
@@ -0,0 +1,10 @@
+/**
+ * Copyright (c) Facebook, Inc. and its affiliates.
+ *
+ * This source code is licensed under the MIT license found in the
+ * LICENSE file in the root directory of this source tree.
+ */
+
+'use strict';
```
[the remark this answers is not in the document]
Comment (gaearon) [reply packages/jest-mock-scheduler/index.js]: yea

File: packages/jest-mock-scheduler/package.json (hunk 3 above)
Comment (bvaughn) [reply packages/jest-mock-scheduler/package.json]: Just some metadata about this build, e.g.
https://unpkg.com/react@canary/build-info.json

File: packages/jest-mock-scheduler/package.json [hunk 5]
```diff
@@ -0,0 +1,27 @@
+{
+  "name": "jest-mock-scheduler",
+  "version": "0.1.0",
+  "description": "Jest matchers and utilities for testing the scheduler package.",
```
[the remark this answers is not in the document]
Comment (bvaughn) [reply packages/jest-mock-scheduler/package.json]: Sure!

File: scripts/rollup/bundles.js [hunk 6]
```diff
@@ -396,6 +396,15 @@ const bundles = [
     externals: ['jest-diff'],
   },
 
+  /******* Jest Scheduler (experimental) *******/
+  {
+    bundleTypes: [NODE_DEV, NODE_PROD, FB_WWW_DEV, FB_WWW_PROD],
+    moduleType: ISOMORPHIC,
+    entry: 'jest-mock-scheduler',
+    global: 'JestMockScheduler',
+    externals: ['jest-diff'],
```
[the remark this answers is not in the document]
Comment (bvaughn) [reply scripts/rollup/bundles.js]: I assumed this was required for some reason, since it was listed as a dependency for the `jest-react` package (even though that package didn't reference it anywhere that I saw).

File: packages/jest-mock-scheduler/index.js (hunk 4 above)
[the remark this answers is not in the document]
Comment (bvaughn) [reply packages/jest-mock-scheduler/index.js]: Cool. That was definitely just copypasta.

File: scripts/rollup/bundles.js (hunk 6 above)
[the remark this answers is not in the document]
Comment (gaearon) [reply scripts/rollup/bundles.js]: Probably copypasta too.

[the remark this answers is not in the document]
Comment (bvaughn) [reply scripts/rollup/bundles.js]: Oh well. We can rip it out in of both then.

[the remark this answers is not in the document]
Comment (bvaughn) [reply scripts/rollup/bundles.js]: #14372

**Comment by def14nt** [comment]
Have you read the NPM terms?

>>>
A few examples of unacceptable content:

5. Content that exists only to "reserve" a name, whether a package name, user name, or organization name. The Dispute Policy governs how npm handles such cases of "squatting".
>>>
