### PR TITLE
[compiler] Allow ref access in callbacks passed to event handler props

### LINKED ISSUE #35040: Bug:  Getting `Cannot access refs during render` error from event handler.
So on react official documentations, I found, it recommend to avoid direct read  or write during render on ref.  

Here is the docs link (under pitfall)-
https://react.dev/reference/react/useRef

And here I also found that ref is safe to use on event handler or effect.

`You can read or write refs from event handlers or effects instead.`

So, we can read `ref.current` from a onSubmit handler as it is a event handler. But when I combine it with `react-hook-form` I am getting the lint error with following context-

```
error  Error: Cannot access refs during render

React refs are values that are not needed for rendering. Refs should only be accessed outside of re
nder, such as in event handlers or effects. Accessing a ref value (the `current` property) during r
ender can cause your component not to update as expected (https://react.dev/reference/react/useRef)
```

So What I am doing on my code(see code)-

```javascript
const onSubmit: SubmitHandler<ReceiptFormInput> = async (value) => {
    let sigUrl: string;
    if (sig) {
        const { blob } = await upload(ref.current?.toFile());
        sigUrl = blob?.url || ""
    } else {
        sigUrl = item.signature
    }
    if (template) {
        mutate({
            ...value,
            templateId: template.templateId,
            previewUrl: template.previewUrl,
            signature: sigUrl,
            id: item.id
        });
    }
}
```

this onSubmit handler is triggering from `form`

```javascript
<form onSubmit={handleSubmit(onSubmit)}>
...
</form>
```

So here handleSubmit is coming from `react-hook-form` to disable default behavior.

We already discussed about this issues from `nextjs` discussion. Following is the link of that discussion

https://github.com/vercel/next.js/discussions/85677

### PR DESCRIPTION
**Pull request by kolvian**
## Summary

Fixes #35040. The React compiler incorrectly flags ref access within event handlers as ref access at render time. For example, this code would fail to compile with error "Cannot access refs during render":

```tsx
  const onSubmit = async (data) => {
    const file = ref.current?.toFile(); // Incorrectly flagged as error
  };

  <form onSubmit={handleSubmit(onSubmit)}>
```
This is a false positive because any built-in DOM event handler is guaranteed not to run at render time. This PR only supports built-in event handlers because there are no guarantees that user-made event handlers will not run at render time.

## How did you test this change?

I created 4 test fixtures which validate this change:
* allow-ref-access-in-event-handler-wrapper.tsx - Sync handler test input
* allow-ref-access-in-event-handler-wrapper.expect.md - Sync handler expected output
* allow-ref-access-in-async-event-handler-wrapper.tsx - Async handler test input
* allow-ref-access-in-async-event-handler-wrapper.expect.md - Async handler expected output

All linters and test suites also pass.

### CODE REVIEW

**Review by josephsavona — CHANGES_REQUESTED** [review]
Thanks for the PR! The approach here works in some cases, but it's encoding some important information — which values can be inferred as event handlers — in an-hoc way. The way we would typically handle this is by adding types to represent a concept, inferring the types appropriately in InferTypes, and then using the type information in later passes.

So the way to go here would be to add a BuiltinEventHandlerId shapeId (see ObjectShape.ts with all the BuiltIn...Id constants), then update InferTypes to infer the types of JsxExpression props as `{kind: 'Function', shapeId: BuiltinEventHandlerId, ...}` using similar logic to what you have here. Ie, for primitive tags where the prop is a named prop starting with "on". 

Then, ValidateNoRefAccessInRender can allow ref-accessing functions to flow into expressions if the result is known to be an event handler. Then you can add an extra case into the logic at https://github.com/facebook/react/blob/main/compiler/packages/babel-plugin-react-compiler/src/Validation/ValidateNoRefAccessInRender.ts#L521C21-L553, along the lines of

```js
  const isRefLValue = isUseRefType(instr.lvalue.identifier);
+ const isEventHandlerLValue = isEventHandlerType(instr.lvalue.identifier);
...
  if (
    isRevLValue ||
+   isEventHandlerLValue ||
...
```

Finally, all of this should only be enabled behind a feature flag, which you can add in Environment.ts: `enableInferEventHandlers`, false by default. Put the logic in InferTypes behind this feature flag (the ValidateNoRefAccess changes will only take effect if the type is inferred, which it won't be w/o the feature).

File: packages/react-debug-tools/src/__tests__/ReactHooksInspection-test.js [hunk 1]
```diff
@@ -20,6 +20,10 @@ function normalizeSourceLoc(tree) {
       node.hookSource.lineNumber = 0;
       node.hookSource.columnNumber = 0;
     }
+    // Normalize Promise objects to hide internal symbols
+    if (node.value instanceof Promise) {
+      node.value = Object.create(Promise.prototype);
+    }
```
Comment (josephsavona) [inline packages/react-debug-tools/src/__tests__/ReactHooksInspection-test.js]: unrelated, please revert

**Comment by kolvian** [comment]
Thanks for the detailed review! I made some changes, was just wondering if the current string-based check is robust enough for the React compiler or if I should find some other checking method. Some alternatives I explored were type annotation-based checks (but these aren't available by the time the InferTypes runs) and hardcoded lists of supported event handlers, but these aren't extensible and would need to be maintained. I also added a check that makes sure that the component isn't a web component (would have a hyphen), which is the only edge case I can think of. If there are any others I can definitely include them.

**Comment by Samdevelop25** [comment]
Add null checks to completeSegment to prevent race condition

File: compiler/packages/babel-plugin-react-compiler/src/__tests__/fixtures/compiler/error.ref-value-in-event-handler-wrapper.tsx [hunk 2]
```diff
@@ -0,0 +1,28 @@
+// @enableInferEventHandlers
+// @validateRefAccessDuringRender
```
Comment (josephsavona) [inline compiler/packages/babel-plugin-react-compiler/src/__tests__/fixtures/compiler/error.ref-value-in-event-handler-wrapper.tsx]: just noticed this - all the @ pragmas need to be on the first line (also the same fix in other files). I think the reason you're getting errors is that validateRefAccessDuringRender is on by default

**Comment by josephsavona** [comment]
We reviewed as a team and are aligned on the direction here, i actually came here to merge and noticed one small thing to fix first, see above comment

**Comment by kolvian** [comment]
> accepting but please address the comment so that we can merge

should be fixed now @josephsavona

**Comment by josephsavona** [comment]
Thanks again!
