### PR TITLE
Fix ReactMarkupChecksum.addChecksumToMarkup() adds checksum to comments

### LINKED ISSUE #6209: renderToString() fails to terminate comment node
Run this:
```js
let html = renderToString(<div>foo</div>)
```
Get this:
```
<div data-reactroot="" data-reactid="1" data-react-checksum="-1450897250">foo</div>
```
Not sure if this is a bug but I thought `data-reactid` and friends are gone in `v15`, no?

Also when testing `v15` with an old project using `v0.14.7` - which has a much complex scenario, `renderToString()` returned following causing a blank page:

```
<!-- react-empty: 1 -- data-react-checksum="1336804998">
```

Just wondering is the behavior for server rendering changing in `v15`? Thanks.

### PR DESCRIPTION
**Pull request by sairion**
`ReactMarkupChecksum.addChecksumToMarkup()` should not add checksum to
comment markup, which is generated from components returns null. This
fixes #6209.

### CODE REVIEW

File: src/renderers/dom/server/ReactMarkupChecksum.js [hunk 1]
```diff
@@ -25,11 +27,15 @@ var ReactMarkupChecksum = {
   addChecksumToMarkup: function(markup) {
     var checksum = adler32(markup);
 
-    // Add checksum (handle both parent tags and self-closing tags)
-    return markup.replace(
-      TAG_END,
-      ' ' + ReactMarkupChecksum.CHECKSUM_ATTR_NAME + '="' + checksum + '"$&'
-    );
+    // Add checksum (handle both parent tags, comments and self-closing tags)
+    if (markup.match(COMMENT_START)) {
```
Comment (zpao) [inline src/renderers/dom/server/ReactMarkupChecksum.js]: Let's make this `.test` - we don't need the match results. Otherwise this looks good, thanks!

**Comment by zpao** [comment]
Thanks!
