### PR TITLE
Fix:- Fixed dev tools inspect mode on Shadow dom

### LINKED ISSUE #26200: Bug:  React dev tools inspect element of hover does not work on shadow elements
Using react while making a shadow DOM and then using react devtools inspect element feature does not work as expected video and codesandbox below

**sandboxLink**
https://stackblitz.com/edit/react-zqp67t?file=src/App.js

**while attaching shadowroot**

https://user-images.githubusercontent.com/72331432/219961254-65c9e84c-9774-441f-9eec-e9ef58f1382d.mp4

**without attaching  root**

https://user-images.githubusercontent.com/72331432/219961266-b276063e-e0f4-4f30-b614-0af3876a9916.mp4

### PR DESCRIPTION
**Pull request by Biki-das**
Fixes #26200 

### PR explanation

I tried to induce the change by the `event.composed` to check whether the event was created in a  ShadowRoot, And replaced `pointerOver` with `pointerMove`,  pointerOver event did not fired correctly

Before PR:-

https://github.com/facebook/react/assets/72331432/67a33dcd-447f-4c68-9c3c-ad954baddeb8

After PR:-

https://github.com/facebook/react/assets/72331432/9f986ff2-785f-4cba-a504-44f82ea9fc5a

### CODE REVIEW

**Comment by Biki-das** [comment]
cc @mondaychen @lunaruan

File: packages/react-devtools-shared/src/backend/views/Highlighter/index.js [hunk 1]
```diff
@@ -151,14 +151,23 @@ export default function setupHighlighter(
...
+  function onPointerMove(event: MouseEvent) {
     event.preventDefault();
     event.stopPropagation();
 
-    const target = ((event.target: any): HTMLElement);
+    const target: HTMLElement = ((event.composed
+      ? event.composedPath()[0]
+      : event.target): any);
+    if (lastHoveredNode === target) return;
+    lastHoveredNode = target;
```
Comment (hoxyq) [inline packages/react-devtools-shared/src/backend/views/Highlighter/index.js:170]: If we could listen to `pointerover` event, do we need this kind of optimization? Or what is the purpose of it?

File: packages/react-devtools-shared/src/backend/views/Highlighter/index.js [hunk 2]
```diff
@@ -151,14 +151,23 @@ export default function setupHighlighter(
...
-  function onPointerOver(event: MouseEvent) {
+  let lastHoveredNode: HTMLElement | null = null;
+  function onPointerMove(event: MouseEvent) {
     event.preventDefault();
     event.stopPropagation();
 
-    const target = ((event.target: any): HTMLElement);
+    const target: HTMLElement = ((event.composed
+      ? event.composedPath()[0]
+      : event.target): any);
```
Comment (hoxyq) [inline packages/react-devtools-shared/src/backend/views/Highlighter/index.js:168]: Should we add some check that `target` != null?

**Review by hoxyq — CHANGES_REQUESTED** [review]
Hey @Biki-das, thanks for your contribution!

Overall, I am okay with this solution, but some small changes/discussions required to proceed

File: packages/react-devtools-shared/src/backend/views/Highlighter/index.js (hunk 1 above)
Comment (Biki-das) [reply packages/react-devtools-shared/src/backend/views/Highlighter/index.js:170]: this basically check if the target node  is the same as the lasthoverednode and if it is , then we are doing an early return for the same, this can help us to prevent extra dom calculations happening on it if the hovered node has not changed!

File: packages/react-devtools-shared/src/backend/views/Highlighter/index.js (hunk 2 above)
Comment (Biki-das) [reply packages/react-devtools-shared/src/backend/views/Highlighter/index.js:168]: the null check wont be necessary in my opinion as the above code expression
```
(event.composed ? event.composedPath()[0] : event.target
```
is already responsible for checking the occurrence  of null or undefined value

**Comment by Biki-das** [comment]
@hoxyq ping!

File: packages/react-devtools-shared/src/backend/views/Highlighter/index.js [hunk 3]
```diff
@@ -74,7 +74,7 @@ export default function setupHighlighter(
       window.removeEventListener('mouseover', onMouseEvent, true);
       window.removeEventListener('mouseup', onMouseEvent, true);
       window.removeEventListener('pointerdown', onPointerDown, true);
-      window.removeEventListener('pointerover', onPointerOver, true);
+      window.removeEventListener('pointermove', onPointerMove, true);
```
[the remark this answers is not in the document]
Comment (hoxyq) [reply packages/react-devtools-shared/src/backend/views/Highlighter/index.js:77]: The last time I debugged it, `pointerover` was emitted each time when I hovered over some element inside shadow-root with mode = open.

I will double-check that tomorrow and return with more feedback

[the remark this answers is not in the document]
Comment (hoxyq) [reply packages/react-devtools-shared/src/backend/views/Highlighter/index.js:77]: Yes, in case when multiple components are inside shadow root, hovering over them will not fire multiple `pointerover` events.

Overall, looks good to me, thanks for working on this. I will leave 1 small comment, can merge after this changed

[the remark this answers is not in the document]
Comment (Biki-das) [reply packages/react-devtools-shared/src/backend/views/Highlighter/index.js:77]: thanks @hoxyq

File: packages/react-devtools-shared/src/backend/views/Highlighter/index.js (hunk 2 above)
[the remark this answers is not in the document]
Comment (Biki-das) [reply packages/react-devtools-shared/src/backend/views/Highlighter/index.js:168]: sure

File: packages/react-devtools-shared/src/backend/views/Highlighter/index.js [hunk 4]
```diff
@@ -197,4 +200,12 @@ export default function setupHighlighter(
     // because those are usually unintentional as you lift the cursor.
     {leading: false},
   );
+
+  function getEventTarget(event: MouseEvent): HTMLElement {
+    if (event.composed) {
+      return (event.composedPath()[0]: any);
+    }
+
```
Comment (Biki-das) [inline packages/react-devtools-shared/src/backend/views/Highlighter/index.js:208]: @hoxyq the return types were any earlier so should not be an issue!

**Review by hoxyq — APPROVED** [review]

**Comment by Jack-Works** [comment]
I made the same bug fix last year. See https://github.com/facebook/react/pull/25518

Why my PR is totally ignored by the React team but this PR gets merged in one week? I feel very uncomfortable about this. 🙁

**Comment by Biki-das** [comment]
> I made the same bug fix last year. See https://github.com/facebook/react/pull/25518
> 
> Why my PR is totally ignored by the React team but this PR gets merged in one week? I feel very uncomfortable about this. 🙁

😅 whoa! We had the same approach to this problem! @Jack-Works , really feeling bad for this, the react team actually is very busy to respond, i just happened to tag a few people around the team who were actively making changes!

**Comment by Jack-Works** [comment]
> > I made the same bug fix last year. See #25518
> > Why my PR is totally ignored by the React team but this PR gets merged in one week? I feel very uncomfortable about this. 🙁
> 
> 😅 whoa! We had the same approach to this problem! @Jack-Works , really feeling bad for this, the react team actually is very busy to respond, i just happened to tag a few people around the team who were actively making changes!

Yes, we also use ShadowDOM a lot. Currently, we're patching the `react-devtools` in our `node_modules` for months.

I often go to all PRs I made in the big project to see if there is a merge conflict so I can resolve it, then I found my PR conflicts today.

I'm happy to see this issue get fixed so I can remove the patch, but I feel hurt about the team's community governance.

**Comment by hoxyq** [comment]
> I made the same bug fix last year. See #25518
> 
> Why my PR is totally ignored by the React team but this PR gets merged in one week? I feel very uncomfortable about this. 🙁

Hey @Jack-Works, I am sorry about that. The issue https://github.com/facebook/react/issues/25519 was overlooked for a long time, I just started to maintain DevTools around 2 months ago. It is just a coincidence that @Biki-das tagged me to review his PR.

We really value any contributions, feel free to tag me in any issues / PRs related to DevTools. It might take some time for me to respond, but this will be in my queue.

This fix should be included in next React DevTools release, which I am planning to ship in the next 1-2 weeks.
