### PR TITLE
Remove usereducer eager bailout

### LINKED ISSUE #15088: useReducer - eagerReducer optimization discussion/questions
I'd like to continue the discussion started by me under a recent blog post by Dan as encouraged by Dan 😉 https://github.com/gaearon/overreacted.io/commit/99bfdca459ff4094ee523c7419b58989d18bc594#r32694433

Just to summarize what I've stumbled upon when experimenting with useReducer after reading that hoisted & declared in render reducers are treated differently (I've wanted to explore how they are handled by React):
1. I have no idea how to reenter eagerReducer calculation after first scheduled work (& after render gets fully processed & committed). This might very well be just me not understanding how fibers work - but currently I'm confused by this. It doesn't enter this code branch because `fiber.expirationTime` is not 0 (NoWork) and the work gets scheduled right away. Any pointers regarding this? Is this valid? Might this be a bug somewhere?
2. The logic around reducer bailouts is somewhat iffy for me - maybe it's just a matter of mentioning those in the documentation:
- not every reducer update can bailout from rendering. If the action queue gets processed in the render phase then it's just not possible, we are already rendering after all. 
- action queue gets processed in the render phase for reducers declared inside render, this means that any new state computation might depend on the "fresh" props. This is not the case for the bailout mechanism though - it's only possible to perform a bailout when dispatching an action (so when we do not have access to the fresh props). Should this restriction be mentioned in the docs? IMHO this behaviour is inconsistent - for the greater good, so it's acceptable but I think it should be documented because it's slightly inconsistent & people might trip over this.

**Note** I'm happy to provide documentation changes if needed, I'd like to discuss those points first to get a better understanding of things.

### LINKED ISSUE #17953: Bug: Calculating eager state from a reducer and not re rendering if the state does not change causes bug in this example.
React version: 16.8.0

## Steps To Reproduce

Link to code example:
https://codesandbox.io/s/usereducer-wfcmq Link to codesandbox.

## The current behavior
Initially step is 0. So for every step react does not rerender due to this https://github.com/facebook/react/blob/master/packages/react-reconciler/src/ReactFiberHooks.js#L1347. But state updates are queued. So when `step` changes all the state updates are done and hence creates a bug by adding the new step prop.

https://overreacted.io/a-complete-guide-to-useeffect/#why-usereducer-is-the-cheat-mode-of-hooks

### LINKED ISSUE #21416: Bug: useReducer reducer function gets called twice (possible memory leak)
React version: 17.0.2

## Steps To Reproduce

1. Create a counter reducer with a top limit (top limit is set externally using a prop or state)
2. Return the current state if the count reaches the top limit
3. Try to increment the counter by calling `dispatch({type:'INCREMENT'})` a few times after the counter has reached the top limit
4. Set the top limit to a greater number
5. You'll see that after increasing the top limit, the reducer callback will be called as much as you'd tried to increment the counter in step 3 and the counter will increment that much

Link to code example: [CODE SANDBOX](https://codepen.io/hosseini44444/pen/abpeXYa)

## The current behavior
After setting the top limit to a higher limit, the previous `INCREMENT` actions which are called before and the reducer have returned the intact state, will be called again and the reducer function will be called as much as you've tried before and the counter will increase that much.

## The expected behavior
After setting the top limit to a higher limit, the previous `INCREMENT` actions which are called before, must not be called again and the Reducer function must not be called again and the counter must stay the same.

### PR DESCRIPTION
**Pull request by josephsavona**
## Remove eager bailout mechanism for useReducer

Both `useState` and `userReducer` have an eager bailout mechanism that attempts to avoid a re-render by checking if the state/reducer update is a no-op. Per @acdlite there are some flaws with the eager bailout mechanism for useReducer specifically, so this PR removes the eager bailout for `useReducer` and keeps it for `useState`. 

Changes:
* Forked `dispatchAction()` into `dispatchReducerAction()` and `dispatchSetState()`, updated call sites to use one of the new names.
* Removed the eager bailout mechanism from `dispatchReducerAction()`.
* Remove `eagerReducer` from the Update type, replacing it with `hasEagerState` to tell if there's an eager state update. 

## How did you test this change?

Followed the contribution guidelines: yarn test/lint/flow

Closes #15088
Closes #21419
Closes #21416
Closes #17953

### CODE REVIEW

File: packages/react-reconciler/src/__tests__/ReactHooksWithNoopRenderer-test.js [hunk 1]
```diff
@@ -3867,6 +3867,8 @@ describe('ReactHooksWithNoopRenderer', () => {
     });
   });
 
+  // TODO: delete now that we removed the eager bailout optimization? or do we want to keep this
+  // around in some capacity?
```
Comment (acdlite) [inline packages/react-reconciler/src/__tests__/ReactHooksWithNoopRenderer-test.js:3871]: Yeah could be useful as a way to document the current behavior, or in case we ever add it back. You can retitle to "useReducer does not eagerly bail out of state updates."

**Review by acdlite — APPROVED** [review]
Looks great! Good to merge assuming CI passes

**Comment by gaearon** [comment]
Does this make tests from https://github.com/facebook/react/pull/15198/ pass?

**Comment by josephsavona** [comment]
> Does this make tests from #15198 pass?

@gaearon Yup! I just added them.

**Comment by gaearon** [comment]
Did you verify they failed on main? Just to make sure this is actually the fix for that problem

**Comment by josephsavona** [comment]
> Did you verify they failed on main? Just to make sure this is actually the fix for that problem

Oops no - i went back and checked and the first new test case fails on main.

File: packages/react-reconciler/src/__tests__/ReactHooksWithNoopRenderer-test.js [hunk 2]
```diff
@@ -3911,12 +3910,116 @@ describe('ReactHooksWithNoopRenderer', () => {
...
+      setDisabled(false);
+    });
+    expect(Scheduler).toHaveYielded([
+      'Render disabled: false',
+      'Render count: 0',
+    ]);
+    expect(ReactNoop).toMatchRenderedOutput('0');
+  });
+
+  it('useReducer should apply potential no-op changes if made relevant by other updates in the batch', () => {
```
Comment (josephsavona) [inline packages/react-reconciler/src/__tests__/ReactHooksWithNoopRenderer-test.js:3973]: This passed on main, but it seems like a good test of priority of eager bailout vs updates from a parent.

File: packages/react-reconciler/src/__tests__/ReactHooksWithNoopRenderer-test.js [hunk 3]
```diff
@@ -3911,12 +3910,116 @@ describe('ReactHooksWithNoopRenderer', () => {
...
+    expect(Scheduler).toHaveYielded(['Render count: 0']);
+    expect(ReactNoop).toMatchRenderedOutput('0');
+
+    act(() => {
+      // Enabling the updater should *not* replay the previous increment() actions
+      setDisabled(false);
+    });
+    expect(Scheduler).toHaveYielded([
+      'Render disabled: false',
+      'Render count: 0',
```
Comment (josephsavona) [inline packages/react-reconciler/src/__tests__/ReactHooksWithNoopRenderer-test.js:3968]: this failed on main, with `'Render count: 3'`

**Comment by josephsavona** [comment]
@acdlite, @gaearon any idea why CI is failing with "Error: Could not find commit for: 1e621bf25d9f57a456ac897d9da7cca8b99772e7"?

**Comment by acdlite** [comment]
Thanks for working on this, @josephsavona!
