### PR TITLE
DevTools: Reload all roots after Fast Refresh force remount

### LINKED ISSUE #21469: [DevTools Bug]: Children list grows indefinitely when adding/removing useEffect
### Website or app

Please checkout the linked branch not `main`
https://github.com/eps1lon/react-devtools-repro-no-matching-node/tree/repro/elements-leaking
Repro steps and screen recording included in the repro

### Repro steps

1. Clone repro
1. yarn
1. yarn start
1. Open app page
1. open devtools
1. Uncomment the `useEffect` block i.e. add an effect
1. inspect `Component` element
1. comment `useEffect` block i.e. remove the effect
1. Repeat comment/uncomment to see that children grow indefinitely

### How often does this bug happen?

Every time

### DevTools package (automated)

_No response_

### DevTools version (automated)

_No response_

### Error message (automated)

Could not inspect element with id 4

### Error call stack (automated)

_No response_

### Error component stack (automated)

_No response_

### GitHub query string (automated)

_No response_

Might be a duplicate of https://github.com/facebook/react/issues/21436#issuecomment-835406075 since the repro steps are the same. But depending on what the effect is doing, the behavior is different.

### PR DESCRIPTION
**Pull request by bvaughn**
## Resolves some cases of #21442 as well as #21469 and (I think) #21436

Alternative for #21506 that does not require a React + Refresh bugfix release.

Unlike #21506, this PR works around the corrupted Store state by detecting a broken Fast Refresh remount and forcefully dropping the root and re-mounting the entire tree. This prevents Fibers from getting duplicated in the Store (and in the Components tree). The benefit of this approach is that it doesn't rely on an update or change in behavior to Fast Refresh. (This workaround is pretty dirty, but since it's a DEV-only code path, it's probably okay.)

### Note that this change doesn't fix _all_ of the reported issues (see https://github.com/facebook/react/issues/21442#issuecomment-843090050) but it does fix _some of them_.

---

This PR also slightly refactors the way DevTools assigns and manages unique IDs for Fibers in the backend by removing the indirection of a "primary Fiber" and instead mapping both the primary and alternate.

It also removes the previous cache-on-read behavior of `getFiberID` and splits the method into three separate functions for different use cases:
1. `getOrGenerateFiberID` – Like the previous function, this method returns an ID _or_ generates and caches a new one if the Fiber hasn't been seen before.
2. `getFiberIDUnsafe` – This function returns an ID if one has already been generated _or_ `null` if not. (It can be used to e.g. log a message about a Fiber without potentially causing it to leak.)
3. `getFiberIDThrows` – This function returns an ID if one has already been generated _or_ it throws. (It can be used to guarantee expected behavior rather than to silently cause a leak.)

---

The PR also adds some basic integration tests for Fast Refresh + DevTools, including one that fails without this fix:
Screen Shot of failed integration test running against main branch

### CODE REVIEW

File: packages/react-devtools-shared/src/backend/renderer.js [hunk 1]
```diff
@@ -1601,6 +1656,18 @@ export function attach(
       );
     }
 
+    const unsafeID = getFiberIDUnsafe(fiber);
+    if (fiber._debugNeedsRemount) {
+      if (unsafeID === null) {
+        // This is a case we can't recover from.
+        setTimeout(() => {
+          // TODO (bvaughn) Document this
+          updateComponentFilters([]);
```
Comment (bvaughn) [inline packages/react-devtools-shared/src/backend/renderer.js:1665]: This is a hack to test out the idea.

**Comment by bvaughn** [comment]
I think I'm going to land this change and see if it helps within Facebook. It fixes at least _some_ of the problem causes, though not all of them.
