### PR TITLE
Make sure that `select` has `multiple` attribute set to appropriate state before appending options

### LINKED ISSUE #13222: Select multiple - does not scroll to selected item(items)
*bug*
In react@15 we could set "value" or "defaultValue", and selected element scrolled into view.
https://codesandbox.io/s/6vx637r10n

But in react@16 this does not work.
https://codesandbox.io/s/7jqqz3zmo1

### PR DESCRIPTION
**Pull request by segoddnja**
Applying multiple options to `select` node before it's multiple attribute is set to `true` leads to the first option be selected by default, event in the case there is no `value` or `defaultValue` passed in the props.

It leads to another undesired outcome. As setting real `selected` attributes values happens in the post mount wrapper, browser does not scroll list to selected option if it is outside of the select.

fixes #13222

### CODE REVIEW

**Comment by react-linter** [comment]
ReactDOM: size: :small_red_triangle:+0.1%, gzip: 0.0%


  <details>
  <summary>Details of bundled changes.</summary>

  <p>Comparing: 0154a79fedef38a824a837c535bc853013dd4588...2abb23244fc54535e009f427b5592180289037ae</p>


  
## react-dom
File | Filesize Diff | Gzip Diff | Prev Size | Current Size | Prev Gzip | Current Gzip | ENV
 ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  --- 
react-dom.development.js | +0.1% | +0.1% | 641.25 KB | 641.59 KB | 150.38 KB | 150.48 KB | UMD_DEV
**react-dom.production.min.js** | **:small_red_triangle:+0.1%** | **0.0%** | **96.08 KB** | **96.14 KB** | **31.09 KB** | **31.1 KB** | **UMD_PROD**
react-dom.development.js | +0.1% | +0.1% | 637.38 KB | 637.73 KB | 149.2 KB | 149.31 KB | NODE_DEV
**react-dom.production.min.js** | **:small_red_triangle:+0.1%** | **:small_red_triangle:+0.1%** | **96.07 KB** | **96.13 KB** | **30.61 KB** | **30.63 KB** | **NODE_PROD**
ReactDOM-dev.js | +0.1% | +0.1% | 644.68 KB | 645.03 KB | 147.58 KB | 147.7 KB | FB_WWW_DEV
**ReactDOM-prod.js** | **:small_red_triangle:+0.1%** | **:small_red_triangle:+0.1%** | **278.74 KB** | **278.95 KB** | **52.13 KB** | **52.16 KB** | **FB_WWW_PROD**
react-dom.profiling.min.js | +0.1% | +0.1% | 97.2 KB | 97.26 KB | 31.02 KB | 31.04 KB | NODE_PROFILING
ReactDOM-profiling.js | +0.1% | +0.1% | 282.04 KB | 282.25 KB | 52.85 KB | 52.88 KB | FB_WWW_PROFILING

  </details>
  
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by nhunzaker** [comment]
Awesome. Thank you for getting to the bottom of this!

I'm looking into whether or not this is the best place to ensure `multiple` is set on a select before options are added. In the meantime, I'd like to figure out how to get test coverage on this.

Could you check to see if JSDOM sets the scroll position on multi-selects? If so, I'd like to add a test for this here:
https://github.com/facebook/react/blob/master/packages/react-dom/src/__tests__/ReactDOMSelect-test.js 

Otherwise, I'd like to get manual dom test fixture for this. These live here:
https://github.com/facebook/react/tree/master/fixtures/dom

And we should add a test case to this module:
https://github.com/facebook/react/blob/master/fixtures/dom/src/components/fixtures/selects/index.js

Please let me know if you hit a snag, I'd be happy to provide additional assistance!

**Comment by segoddnja** [comment]
@nhunzaker No problem. I think there is really not so much options where to ensure that `select` has appropriate `multiple` value. It creates instance by `createInstance` method call and appends children right after this. So `createInstance` and `createElement` only two places where is possible to do this.

> Could you check to see if JSDOM sets the scroll position on multi-selects?

I don't think it is possible to do with JSDOM. And even if it had been possible it would have been tested only against JSDOM. Do not see much sense in this.

I've added manual dom fixture.

File: fixtures/dom/src/components/fixtures/selects/index.js [hunk 1]
```diff
@@ -158,6 +158,25 @@ class SelectFixture extends React.Component {
             </form>
           </div>
         </TestCase>
+
+        <TestCase title="A multiple selec being scrolled to first selected option">
```
Comment (gaearon) [inline fixtures/dom/src/components/fixtures/selects/index.js]: Typo: selec

**Comment by gaearon** [comment]
Can this be colocated with other ReactDOMFiberSelect logic?

**Comment by segoddnja** [comment]
> Can this be colocated with other ReactDOMFiberSelect logic?

I don't think so. At least I don't see a way how to do this.

**Comment by nhunzaker** [comment]
Just to recap, the issue is that the `multiple` attribute needs to be set before the `option` children elements are appended.

It looks like we were actually doing this in the `postMountHook`:
https://github.com/facebook/react/blob/master/packages/react-dom/src/client/ReactDOMFiberSelect.js#L174-L183

But, by this point, the option items are already appended to the select:

image

What if we made a `createHook`, and switched on the tag, similar to `postMountHook`?

That could look like:

```javascript
export function createElement(
  type: string,
  props: Object,
  rootContainerElement: Element | Document,
  parentNamespace: string,) {
  // ...
  switch (type) {
    case 'select'
      ReactDOMFiberSelect.createHook(props);
      break;
  }
}
```

Though for this case, since it's the only element so far that has an issue, maybe we could just use an `if`

**Comment by gaearon** [comment]
>the multiple attribute needs to be set before the option children elements are appended.

The comment should say this.

File: packages/react-dom/src/client/ReactDOMFiberComponent.js [hunk 2]
```diff
@@ -378,6 +378,12 @@ export function createElement(
       // See discussion in https://github.com/facebook/react/pull/6896
       // and discussion in https://bugzilla.mozilla.org/show_bug.cgi?id=1276240
       domElement = ownerDocument.createElement(type);
+      // Make sure that `select` has `multiple` attribute set to appropriate state before appending options
+      // To prevent first option be initialy made selected
+      // see more details in https://github.com/facebook/react/issues/13222
```
Comment (nhunzaker) [inline packages/react-dom/src/client/ReactDOMFiberComponent.js]: This isn't perfect, but could you update this comment to read like:

```javascript
// Normally attributes are assigned in `setInitialDOMProperties`, however the `multiple`
// attribute on `select`s needs to be added before `option`s are inserted. This prevents 
// a bug where the `select` does not scroll to the correct option because singular 
// `select` elements automatically pick the first item.
// See https://github.com/facebook/react/issues/13222
```

@gaearon Could this be clearer?

File: packages/react-dom/src/client/ReactDOMFiberComponent.js [hunk 3]
```diff
@@ -378,6 +378,12 @@ export function createElement(
...
+      if (type === 'select' && !!props.multiple) {
```
Comment (gaearon) [inline packages/react-dom/src/client/ReactDOMFiberComponent.js]: In this context `!!` is redundant. You can drop it.

File: packages/react-dom/src/client/ReactDOMFiberComponent.js (hunk 2 above)
Comment (gaearon) [inline packages/react-dom/src/client/ReactDOMFiberComponent.js]: Please change the comment to the suggestion in the discussion thread

File: packages/react-dom/src/client/ReactDOMFiberComponent.js [hunk 4]
```diff
@@ -378,6 +378,12 @@ export function createElement(
...
+        domElement.setAttribute('multiple', 'true');
```
Comment (nhunzaker) [inline packages/react-dom/src/client/ReactDOMFiberComponent.js]: We use property assignment in [the postMountWrapper](https://github.com/facebook/react/blob/master/packages/react-dom/src/client/ReactDOMFiberSelect.js#L176), could you do the same here?

**Comment by gaearon** [comment]
What if `props.multiple` changes during an update, but we insert a child into it before the change? Is that also going to cause the same issue?

File: packages/react-dom/src/client/ReactDOMFiberComponent.js (hunk 4 above)
Comment (segoddnja) [reply packages/react-dom/src/client/ReactDOMFiberComponent.js]: `postMountWrapper` attempts to update options, but as at this moment select doesn't have any child appended, it makes no sense, it will iterate over empty options collection. However it should not cause any problems so if you think it is better approach I can do this change.

**Comment by aweary** [comment]
Could we consider changing the order back to match React 15? [I brought this up a while back](https://github.com/facebook/react/issues/12200#issuecomment-364565875) but there was no follow up on it. Was reordering these operations intentional?

**Comment by segoddnja** [comment]
@gaearon Google chrome scrolls to selected option only once.
```
const s = document.createElement('select');
s.multiple = true;
for(let i = 0; i < 10; i++) {
  const o = document.createElement('option');
  o.text = i;
  o.value = i;
  s.appendChild(o);
}
//Scroll down to selected option
s.options[9].selected = true;
//Do not scroll up to selected option
s.options[9].selected = false;
s.options[0].selected = true;
```

So any further changes won't change scroll position.

**Comment by gaearon** [comment]
>Could we consider changing the order back to match React 15? I brought this up a while back but there was no follow up on it. Was reordering these operations intentional?

Reordering was done in https://github.com/facebook/react/commit/ea3420471f0e79b2212b95159d6959d221a52ca1 as far as I can see. Ironically it was partially done because of `<select>`:

>Finally, we need the ability to update an instance after all the children
have been insertion. Such as `<select value={...} />`. I called this
finalizeInitialChildren.

That said we can probably split setting initial properties in two phases as well (before and after appending the children). Do we have a proposal for which ones should go where?

**Comment by segoddnja** [comment]
I do not know about other cases when it is necessary to assign properties before appending the children. As it turned out this issue (as well as solution) was known long time ago. So, probably there are some other related issues in the list.

**Comment by gaearon** [comment]
What about the suggested fix in https://github.com/facebook/react/pull/12242#discussion_r194028432? Would that also solve the issue?

**Comment by segoddnja** [comment]
Well, it solves only issue described in the pull request title. But, this change doesn't fix the scrolling issue.

**Comment by nhunzaker** [comment]
> What if props.multiple changes during an update, but we insert a child into it before the change? Is that also going to cause the same issue?

I'm not sure, but:

> That said we can probably split setting initial properties in two phases as well (before and after appending the children). Do we have a proposal for which ones should go where?

What if we just placed a hook here:
https://github.com/facebook/react/blob/28cd494bdfcae0282e596211e982e120f60168f9/packages/react-dom/src/client/ReactDOMHostConfig.js#L191

Maybe something like:

```javascript
// ... createInstance()
  const domElement: Instance = createElement(
    type,
    props,
    rootContainerInstance,
    parentNamespace,
  );
  precacheFiberNode(internalInstanceHandle, domElement);
  updateFiberProps(domElement, props);
  
  // Open to a better name
  setPropsBeforeChildren(type, props, domElement)

  return domElement;
}
```

Then in ReactDOMFiberComponent: 

```javascript
setPropsBeforeChildren(type, props, domElement) {
  if (type === 'select' && props.multiselect) {
    select.multiselect = true
  }
}
```

**Comment by gaearon** [comment]
@nhunzaker Is your suggestion technically different except code organization? I'm fine with either tbh.

**Comment by gaearon** [comment]
I guess a separate function makes it a bit harder to miss why we're doing it. And GCC will inline it anyway.

**Comment by nhunzaker** [comment]
@gaearon I don't think it introduces anything new. Purely code organization. 

Honestly I'm okay with this how it is, though I do think it's worth starting catalog why these sorts of fixes need to happen at specific points in the process for a later refactor. There isn't really great place for a fix like this and adding an extra layer of indirection doesn't feel right.

File: packages/react-dom/src/client/ReactDOMFiberComponent.js [hunk 5]
```diff
@@ -384,6 +384,14 @@ export function createElement(
       // See discussion in https://github.com/facebook/react/pull/6896
       // and discussion in https://bugzilla.mozilla.org/show_bug.cgi?id=1276240
       domElement = ownerDocument.createElement(type);
+      // Normally attributes are assigned in `setInitialDOMProperties`, however the `multiple`
+      // attribute on `select`s needs to be added before `option`s are inserted. This prevents
+      // a bug where the `select` does not scroll to the correct option because singular
+      // `select` elements automatically pick the first item.
+      // See https://github.com/facebook/react/issues/13222
+      if (type === 'select' && props.multiple) {
+        domElement.setAttribute('multiple', 'true');
```
Comment (nhunzaker) [inline packages/react-dom/src/client/ReactDOMFiberComponent.js]: Just for consistence with [ReactDOMFiberSelect](https://github.com/facebook/react/blob/master/packages/react-dom/src/client/ReactDOMFiberSelect.js#L176), can you assign this as a property, like:

```javascript
domElement.multiple = true
```

**Comment by gaearon** [comment]
Might want to start a document with a list of hacks for any input type and reasons for them.

**Comment by nhunzaker** [comment]
Sounds good. I'll start a markdown document and add it to the fixtures. Maybe it could be hosted along side a public version of the fixtures using Netlify (need to circle back to that too).

**Comment by nhunzaker** [comment]
@gaearon This looks good on my end and I have verified it locally.

**Comment by nhunzaker** [comment]
@segoddnja I pushed a small commit to remove an unused ref just now, but I believe this is good to merge.
