### PR TITLE
Shares debugID information across modules

### LINKED ISSUE #7927: Changing state too quickly cause error with shallow render
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
Running `ReactTestUtils.createRenderer().render()` causes react to throw an exception:
```
Warning: Exception thrown by hook while handling onSetChildren: Invariant Violation: Expected onBeforeMountComponent() parent and onSetChildren() to be consistent (3 has parents 0 and 2).
Invariant Violation: Expected onBeforeMountComponent() parent and onSetChildren() to be consistent (3 has parents 0 and 2).
```

I have the same issue when using both `Component` and `PureComponent`.
I do *not* see the error when using `ReactTestUtils.renderToDocument()`.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**
Could not figure out how to use `ReactTestUtils` in that JSFiddle example even though react-with-addons is loaded.

Here's the code I used in my project to reproduce it:
```jsx
import React, { Component, PureComponent } from 'react'
import { render } from 'react-dom'
import ReactTestUtils from 'react-addons-test-utils'

class Root extends Component {
	componentWillMount() {
		this.testBreak()
		setTimeout(this.testBreak.bind(this), 10)
	}

	testBreak() {
		var i = 0, l = 50
		while(i <= l) {
			this.setState({ test: `this will break testing ${++i}` })
		}
	}

	render() {
		return (
			<div>
				{/* You need more than one nested element for this to break */}
				<div>First div</div>
				<div>Second div</div>
			</div>
		)
	}
}

render(
	<Root />
, document.getElementById('root'))

class TestReactElement extends PureComponent {
	render() { return (
		<div>{this.props.name}</div>
	)}
}

const testRender = (name) => {
	let renderer = ReactTestUtils.createRenderer()
	renderer.render(<TestReactElement name={name} />)
}

testRender('Test 1')
testRender('Test 2')
testRender('Test 3')
```

It works fine so long as I run `testRender()` once. As soon as it's run 2 or more times, the error pops up.

In my project, TAP output is being listened to from a `console.log` wrapper and `state` is being updated when a new one comes in. So while my reproducible example is contrived, it's real-world bug when running tests in my project.

**What is the expected behavior?**
The expected behavior is that no error occurs in the console when running multiple shallow test renders while at the same time React is updating the state of an element rendered to the DOM.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
`15.3.0` and `15.3.2`. Windows 10 64-bit v1607 (and updates up to October 10th, 2016). I've not tried this in previous versions of React. Verified it displays the error in Chrome `54.0.2840.50 beta-m (64-bit)` and Firefox `50.0b5`.

### PR DESCRIPTION
**Pull request by goatslacker**
Prior to this, React was using a nextDebugID variable that was locally
scoped to both `instantiateReactComponent` and `ReactShallowRenderer`.
This caused problems when the debugIDs would collide, the `itemMap` in
`ReactComponentTreeHook` would be overwritten and tests would fail
with the message "Expected onBeforeMountComponent() parent and
onSetChildren() to be consistent".

This change shares the debugID with both modules thus preventing any
collisions in the future.

Fixes #7927

Ideally this would be in the next (hotfix?) release of React 15.x as this is preventing us (Airbnb) from upgrading at the moment.

### CODE REVIEW

**Comment by Aweary** [comment]
Thanks for the PR  @goatslacker, looks reasonable to me. `15.4.0` is close to release, I'm not sure if it's too late to get this in though.

**Comment by goatslacker** [comment]
Emailed the CLA info.

File: src/shared/utils/getNextDebugID.js [hunk 1]
```diff
@@ -0,0 +1,9 @@
+'use strict';
```
Comment (Aweary) [inline src/shared/utils/getNextDebugID.js]: We need to add the header document comment here like the other files ([example](https://github.com/facebook/react/blob/master/src/shared/utils/deprecated.js#L1-L13)). 

Without the `@providesModule` comment the haste module system doesn't know where to find this file and tests fail.

Comment (goatslacker) [inline src/shared/utils/getNextDebugID.js]: Done :) I'll sign the CLA today.

**Comment by gaearon** [comment]
Thanks.

**Comment by gaearon** [comment]
Out in 15.4.0.
