### PR TITLE
Error boundaries

### LINKED ISSUE #2461: Error boundaries: Recover from errors thrown in `render`
So I'm trying to put some graceful error handling in case 1 of my views crap out:

``` jsx
var MyGoodView = React.createClass({
  render: function () {
    return <p>Cool</p>;
  }
});

var MyBadView = React.createClass({
  render: function () {
    throw new Error('crap');
  }
});

try {
  React.render(<MyBadView/>, document.body);
} catch (e) {
  React.render(<MyGoodView/>, document.body);
}
```

However, `MyGoodView` does not get rendered w/ the following stack trace:

stack trace

Seems like error throw React in a bad state where `renderedComponent` is `undefined`, thus cannot be unmounted. How do I handle this scenario?

### PR DESCRIPTION
**Pull request by jimfb**
Implements error boundaries for initial render, which allow React components to become isolation boundaries.  If a child of an error bounadry crashes, the error boundary has the ability to handle the error and render something different (like an error message or a frown face).  This allows application authors to partition their app into regions, and a crash in a single region won't take down the entire page/application.

Fixes #2461

### CODE REVIEW

File: src/core/__tests__/ReactErrorBoundaries-test.js [hunk 1]
```diff
@@ -0,0 +1,98 @@
...
+        };
+        return (
+          <div>
+            <Inquisitive ref={ref} />
+            <Angry />
+          </div>
+        );
+      }
+      handleError(e) {
+        this._errorMessage = e.message;
```
Comment (spicyj) [inline src/core/__tests__/ReactErrorBoundaries-test.js]: Does setState work here? If not, can we make it work?

Comment (jimfb) [inline src/core/__tests__/ReactErrorBoundaries-test.js]: `setState` does not work there.  Among other things, we rollback the transaction after calling handleError.  I'll try to figure out a way to make it work before merging.

**Comment by jimfb** [comment]
Now with setState support.  Ready to merge this piece and move on to updates?  @sebmarkbage @spicyj

File: src/renderers/shared/reconciler/ReactCompositeComponent.js [hunk 2]
```diff
@@ -278,6 +284,44 @@ var ReactCompositeComponentMixin = {
     this._pendingReplaceState = false;
     this._pendingForceUpdate = false;
 
+    var markup;
+    if (inst.handleError) {
+      var checkpoint = transaction.checkpoint();
+      try {
+        markup = this.performInitialMount(renderedElement, nativeParent, nativeContainerInfo, transaction, context);
```
Comment (koulmomo) [inline src/renderers/shared/reconciler/ReactCompositeComponent.js]: mostly out of curiosity.

according to: https://github.com/petkaantonov/bluebird/wiki/Optimization-killers#2-unsupported-syntax `try`/`catch`/`finally` make their containing function unoptimizable (in V8 at least).

Is there a reason you don't use the suggested workaround of isolating the `try`/`catch`/`finally` statements into minimal functions?

Comment (spicyj) [inline src/renderers/shared/reconciler/ReactCompositeComponent.js]: Yeah, we should probably do that – though I don't like making the stack deeper unnecessarily because it hampers debugging, and performance in the case that an exception *is* thrown is probably not a huge concern. Would be nice if the common path was broken up intelligently though.

Comment (sebmarkbage) [inline src/renderers/shared/reconciler/ReactCompositeComponent.js]: This only adds a single stack frame to the boundary, not every component so I think it is probably fine.

File: src/renderers/shared/reconciler/ReactCompositeComponent.js [hunk 3]
```diff
@@ -106,9 +113,8 @@ var ReactCompositeComponentMixin = {
     this._pendingReplaceState = false;
     this._pendingForceUpdate = false;
 
-    this._renderedNodeType = null;
+    this._caughtError = NO_ERROR;
```
Comment (sebmarkbage) [inline src/renderers/shared/reconciler/ReactCompositeComponent.js]: rm

File: src/renderers/shared/reconciler/ReactCompositeComponent.js [hunk 4]
```diff
@@ -99,6 +105,7 @@ var ReactCompositeComponentMixin = {
     this._instance = null;
     this._nativeParent = null;
     this._nativeContainerInfo = null;
+    this._renderedNodeType = null;
```
Comment (sebmarkbage) [inline src/renderers/shared/reconciler/ReactCompositeComponent.js]: Why move? Is there anything else that shares this hidden class?

File: src/renderers/shared/reconciler/ReactCompositeComponent.js [hunk 5]
```diff
@@ -278,6 +284,44 @@ var ReactCompositeComponentMixin = {
     this._pendingReplaceState = false;
     this._pendingForceUpdate = false;
 
+    var markup;
+    if (inst.handleError) {
```
Comment (sebmarkbage) [inline src/renderers/shared/reconciler/ReactCompositeComponent.js]: `unstable_handleError`

**Comment by jimfb** [comment]
@sebmarkbage Now with a unit test to assert the event handlers (eg. `onClick`) never get added.

File: src/renderers/shared/reconciler/ReactCompositeComponent.js [hunk 6]
```diff
@@ -278,6 +277,58 @@ var ReactCompositeComponentMixin = {
...
+      // Roll back to checkpoint, handle error (which may add items to the transaction), and take a new checkpoint
+      transaction.rollback(checkpoint);
+      this._instance.unstable_handleError(e);
+      if (this._pendingStateQueue) {
+        this._instance.state = this._processPendingState(this._instance.props, this._instance.context);
+      }
+      checkpoint = transaction.checkpoint();
+      
+      this._renderedComponent.unmountComponent();
+      transaction.rollback(checkpoint);
```
Comment (sebmarkbage) [inline src/renderers/shared/reconciler/ReactCompositeComponent.js]: This one is interesting. Can this actually happen? Doesn't matter if we do it as a precaution since we're already in a slow path. Just curious.

**Comment by sebmarkbage** [comment]
shipit

**Comment by jnak** [comment]
YAYYYYY!!!

**Comment by slorber** [comment]
can't wait for the 0.15 release hahaha

**Comment by benjie** [comment]
Awesome; great work! Really looking forward to trying this out!

**Comment by davidbarton** [comment]
Awesome thanks!

**Comment by bvaughn** [comment]
This is fantastic! :)

**Comment by abhinavsingi** [comment]
Been waiting for it for so long!

**Comment by mhart** [comment]
Much of a performance hit with this?

**Comment by jimfb** [comment]
@mhart Should be virtually none.

**Comment by mhart** [comment]
@jimfb – cool, good to know! Thanks.

Now that I look at it in more detail it looks like the try/catch is happening at the mount stage, and not for each child render (is that correct?) – which certainly allays my initial fears.

**Comment by gaearon** [comment]
Is there an intention to also add error boundary checks for component updates?

I really want to kill [react-transform-catch-errors](https://github.com/gaearon/react-transform-catch-errors) but unfortunately the current error boundary implementation doesn’t satisfy my use case.

I am interested in catching errors occurring when a person hot reloads `render()` function and introduces an exception to it. I would then “retry” rendering the failed component on the next hot reload.

It would look like this:

feb 15 2016 18 54

Currently, error boundaries only handle “broken, later fixed” part of the equation, but no the “OK, but later broke”. From the technical point of view, it is equivalent to `render()` throwing only on the first update:

```js
let calls = 0;

// ...

render() {
  calls++;
  if (calls === 1) {
    throw new Error('Yo');
  }
  return <NormalStuff />
}
```

If there is a desire to support this I can look into implementing this.

**Comment by ericclemmons** [comment]
@gaearon's use-case is my own as well.  With component playgrounds, it's easy for fixtures to be passed into a `render()` and generate an error, often making recovery require a refresh.

**Comment by jimfb** [comment]
@gaearon @ericclemmons https://github.com/facebook/react/pull/6020

**Comment by slorber** [comment]
+1 i use hot reload and not yet "react-transform-catch-errors" and it's a pain because on any single render error due to bad transient code it requires an erroir even if I fix the code and hot-reload it

**Comment by jstejada** [comment]
is this inside the release candidate?

**Comment by AndrewIngram** [comment]
It _feels_ like this is also the solution for implementing 404 and 401 views when using React Router. ie if a child route throws a special class of exception (eg NotFoundError or UnauthorizedError), any parent route can catch it and render the appropriate component.  Assuming I'm right, when this feature is fully implementing, the biggest issue with using React Router will be solved.

**Comment by pluma** [comment]
@AndrewIngram you'd still need to detect the error state to set the proper response status when rendering on the server, though.

**Comment by tommoor** [comment]
Is there any intent to remove the `unstable` prefix and turn this into a documented API?

**Comment by gaearon** [comment]
It's not fully working yet: crashes in updates don't stop at the boundary. I intend to look into corresponding PR soon but API is likely to stay unstable_ until we use it for a while ourselves.
