### PR TITLE
Fix Issue with Undefined Lazy Imports By Refactoring Lazy Initialization Order

### LINKED ISSUE #18768: Bug: `React.lazy` throws undefined instead of an `Error` object
React version: 16.13.1

## Steps To Reproduce

```js
import React, { Suspense, lazy } from "react";

const Async = lazy(() => {}); // <------

let App = () => {
	return (
		<Suspense fallback={"Loading"}>
			<Async />
		</Suspense>
	);
};

export default App;
```

Link to code example: https://codesandbox.io/s/elegant-fermi-bxwtb

Might be related to https://github.com/facebook/react/issues/15019, https://github.com/facebook/react/pull/15222

## Context

I know that this is incorrect code, but `lazy(() => {import(...)})` is a rather easy typo to make.
The main reason why I'm bringing this is up is that other tools (like JSDOM and Codesandbox with the link above) expect an `Error` object to be thrown. 

## The current behavior

**Input**: `const Async = lazy(async () => ({}));`
**Error**: (this is correct)
```
Warning: lazy: Expected the result of a dynamic import() call. Instead received: [object Object]

Your code should look like: 
  const MyComponent = lazy(() => import('./MyComponent'))
```

**Input**: `const Async = lazy(() => ({}));`
**Error**: (the exception is not an `Error` object)
```
Uncaught {}
```

**Input**: `const Async = lazy(() => {});`
**Error**:  (the exception is not an `Error` object)
```
Uncaught undefined
```

## The expected behavior

**Input**: `const Async = lazy(async () => ({}));`
**Error**:
```
Warning: lazy: Expected the result of a dynamic import() call. Instead received: [object Object]

Your code should look like: 
  const MyComponent = lazy(() => import('./MyComponent'))
```

**Input**: `const Async = lazy(() => ({}));`
**Error**:
```
Warning: lazy: Expected the result of a dynamic import() call. Instead received: undefined

Your code should look like: 
  const MyComponent = lazy(() => import('./MyComponent'))
```

**Input**: `const Async = lazy(() => {});`
**Error**:
```
Warning: lazy: Expected the result of a dynamic import() call. Instead received: [object Object]

Your code should look like: 
  const MyComponent = lazy(() => import('./MyComponent'))
```

### PR DESCRIPTION
**Pull request by sebmarkbage**
This is an alternative to #21639 which might fix #18768. Needs unit tests.

We should be pretty careful about using try/catch. It doesn't come without caveats:

- Browsers have been known to deopt them. This is getting less of an issue but not sure it's non-zero issue.
- It breaks debugging using break on uncaught exceptions.
- Even relying on it suggests an anti-pattern because you're likely executing in some outside execution context that doesn't have the right stacks or component stacks.
- We support suspense almost everywhere during the render. This means that technically anything that catches must know whether to forward it or not.
- It's often easiest to avoid it and instead just letting the general purpose system deal with it.

In general the lazy protocol is pretty simple. You just call the function and it either throws, suspends or gives you the value. It also works recursively. And since that is all happen directly on the same stack you have the full JS stack and component stack for how you got there. For example the ctor part can suspend or throw. You can also throw in the .then function potentially if it's a non-standard thenable which we support for the purpose of higher performance sync resolution.

To fix the outer resolution I simply moved the timing of when we set the flag. This is generally how you'd solve these kinds of bugs. Moving the timing of the mutation. So now we just keep it as uninitialized until we've called the thenable and so we know it's a thenable. So when we set the value, we know it'll suspend the next time we call it. This also lets this call throw and it'll also rethrow at the same place every time similar to how if the ctor throws. So you always get the right stack.

The other thing I changed is that when we resolve the `.default` property in the resolving path, we don't have the right stack so it'll be tricky to debug it. Sure, this generally happens inside React so it's not a very useful stack anyway. Therefore I instead moved this resolution to when the lazy value is read. That way it just works. It's a tiny bit slower during the reread perhaps but in general the reconciler diffs the lazy wrapper and not the resolved value anyway. It's also how this whole suspense thing is supposed to work in general. Any "transform" of a value is applied during "render" after you read it. The underlying lazy thing (that is also what React "sees" in the promise passed to React) is the module object itself. Maybe it's unfortunate that this created a memory dependency on the whole module but it's supposed to be in the module cache anyway.

Another thing I noticed is that we warn for `undefined` values but it's not invalid to import undefined from another module. E.g. Flight creates lazy values that return undefined all the time. It's not useful as an Element Type which is the previous only usage, but now it's allowed as a Node too where undefined is allowed.

```
const lazyNode = React.lazy(() => import(...));

<div>{lazyNode}</div>
```

I changed the early warning to check for `in`. We can also check for `undefined` if we want specifically for element types to give a better error message but that should be checked in the reconciler where we know how we'll use it.

### CODE REVIEW

File: packages/react/src/ReactLazy.js [hunk 1]
```diff
@@ -53,29 +53,17 @@ function lazyInitializer<T>(payload: Payload<T>): T {
     const ctor = payload._result;
     const thenable = ctor();
     // Transition to the next state.
-    const pending: PendingPayload = (payload: any);
-    pending._status = Pending;
```
Comment (gaearon) [inline packages/react/src/ReactLazy.js:57]: What if it was a sync thenable though? Wouldn't you miss it due to `if (payload._status === Pending) {` check in `onFulfill`?

Comment (sebmarkbage) [reply packages/react/src/ReactLazy.js:57]: Yea I fixed it here. https://github.com/facebook/react/pull/21642/commits/cc42e7b0fc429ce9ed8a5b5f7340d1ae0b483309

That check is really unnecessary. It's more of a safety thing in case someone has a bad thennable. We could probably remove it.

File: packages/react/src/ReactLazy.js [hunk 2]
```diff
@@ -53,43 +53,64 @@ function lazyInitializer<T>(payload: Payload<T>): T {
...
-                  "ort('./MyComponent'))",
-                moduleObject,
-              );
-            }
-          }
+        if (payload._status === Pending || payload._status === Uninitialized) {
           // Transition to the next state.
           const resolved: ResolvedPayload<T> = (payload: any);
           resolved._status = Resolved;
-          resolved._result = defaultExport;
```
Comment (gaearon) [inline packages/react/src/ReactLazy.js:78]: This change needs to be in lockstep right? Not that it affects anything but I remember some pain rolling out a change to lazy on RN. Maybe it's not hard anymore now that we check in the bundles.

**Review by gaearon — APPROVED** [review]

File: packages/react/src/ReactLazy.js (hunk 2 above)
Comment (sebmarkbage) [reply packages/react/src/ReactLazy.js:78]: Note that this is only changing one package so there's no lockstep. This is a nice feature of the new protocol. The reconciler just calls the function and expects a value (or throw or suspense). The implementation of this is can be whatever - like Flight has a different one.

Comment (gaearon) [reply packages/react/src/ReactLazy.js:78]: Oh ok this is nice.
