### PR TITLE
RN findNodeHandle no longer adds props directly to read-only owner

### LINKED ISSUE #10518: [Fiber] Calling ReactNative.findNodeHandle() in render() crashes in DEV
Found this while working on https://github.com/facebook/react/pull/10517.
See https://github.com/facebook/react/pull/10517#issuecomment-324292856 for more details.

screen shot 2017-08-23 at 1 20 31 pm

screen shot 2017-08-23 at 1 20 56 pm

Now **I know this has been fixed in https://github.com/facebook/react/pull/10448 but that’s not the whole story**.

Even if we fixed the Stack-assuming `getName()` call, we still can't put arbitrary fields on a fiber:

screen shot 2017-08-23 at 1 21 55 pm

For the reference, [this](https://github.com/facebook/react/blob/6ab2869a20e5e9a6f1f0ac02da34692dac9c1c9d/src/renderers/dom/shared/findDOMNode.js#L37-L40) is how we work around the problem in ReactDOM.

### PR DESCRIPTION
**Pull request by bvaughn**
Resolves #10518.

Builds on top of #10511 to avoid causing merge conflicts for #10511 or #10517.

screen shot 2017-08-23 at 8 16 48 am

### CODE REVIEW

File: src/renderers/native/findNodeHandle.js [hunk 1]
```diff
@@ -61,10 +60,10 @@ import type {ReactInstance} from 'ReactInstanceType';
 function findNodeHandle(componentOrHandle: any): any {
   if (__DEV__) {
     // TODO: fix this unsafe cast to work with Fiber.
```
Comment (bvaughn) [inline src/renderers/native/findNodeHandle.js]: For now, I'm copying what we do in [`findDOMNode`](https://github.com/facebook/react/blob/6ab2869a20e5e9a6f1f0ac02da34692dac9c1c9d/src/renderers/dom/shared/findDOMNode.js#L35) but I left this TODO in place.
