### PR TITLE
Fix null node issue in ReactCSSTransitionGroup

### LINKED ISSUE #6619: TypeError using ReactCSSTransitionGroup
React 0.14.8
We see this in browser tests but never manually triggered, so bug is seemingly timing sensitive.

```
Uncaught TypeError: Cannot read property 'classList' of null CSSCore.js:38
CSSCore.addClass @ CSSCore.js:38
React.createClass.flushClassNameQueue @ ReactCSSTransitionGroupChild.js:116
```

`component.isMounted()` is `true`, but in these cases `ReactDOM.findDOMNode(this)` then returns null here
https://github.com/facebook/react/blob/master/src/addons/transitions/ReactCSSTransitionGroupChild.js#L116

### PR DESCRIPTION
**Pull request by keyanzhang**
Fixes #6619. Thanks for reviewing! CC @spicyj

### CODE REVIEW

File: src/addons/transitions/ReactCSSTransitionGroupChild.js [hunk 1]
```diff
@@ -102,8 +102,9 @@ var ReactCSSTransitionGroupChild = React.createClass({
     }
   },
 
-  queueClass: function(className) {
+  queueClass: function(className, nodeRef) {
     this.classNameQueue.push(className);
+    this.nodeRef = nodeRef;
```
Comment (spicyj) [inline src/addons/transitions/ReactCSSTransitionGroupChild.js]: Is it ever possible that this is already set to a different node?

**Comment by spicyj** [comment]
lgtm, thanks!

**Comment by facebook-github-bot-5** [comment]
@keyanzhang updated the pull request.
