### PR TITLE
Fixed removing attributes during custom element update. Fixes #6747

### LINKED ISSUE #6747: Attributes on custom elements are not removed during the diff
We are trying to adopt custom elements for some parts of your UI and ran into the issue that during an update to the tree, custom attributes on the the custom elements are not removed correctly as can be seen here: http://jsbin.com/ferohipaje/edit?html,output (you will need to click on "false" and then inspect the DOM node in the dev tools of the browser).

I've tracked the issue to the `_updateDOMProperties` method in `ReactDOMComponent.js`. It seems that there is a special check in the loop for `nextProps`:

```js
else if (isCustomComponent(this._tag, nextProps)) {
  if (!RESERVED_PROPS.hasOwnProperty(propKey)) {
    DOMPropertyOperations.setValueForAttribute(getNode(this), propKey, nextProp);
  }
}
```

But the corresponding section is missing for `lastProps` (deleting), which results in the incorrect behavior.

I'm starting the work on the patch.

### PR DESCRIPTION
**Pull request by grassator**
I've tried to follow the same approach as the `nextProps` takes, which involved adding a new method to explicitly delete the attribute without all the checks React does.

I would be happy to any necessary changes and hope it can be merged soon.

Thanks

Fixes #6747.

### CODE REVIEW

**Comment by jimfb** [comment]
Looks good to me ( 👍 )

**Comment by grassator** [comment]
@jimfb Thanks for a such a quick review!

I would really appreciate if you could let me know on the next steps so I can either setup our infrastructure around my fork, or wait for merge to master / next release. Thanks in advance.

**Comment by jimfb** [comment]
@grassator Merged into master.  This should make it into one of the upcoming releases.

**Comment by grassator** [comment]
@jimfb Thanks a lot for an expedited handling — it's really appreciated.

File: src/renderers/dom/shared/DOMPropertyOperations.js [hunk 1]
```diff
@@ -207,6 +207,24 @@ var DOMPropertyOperations = {
...
+   * Deletes an attributes from a node.
+   *
+   * @param {DOMElement} node
+   * @param {string} name
+   */
+  deleteValueForAttribute: function(node, name) {
+    node.removeAttribute(name);
+    if (__DEV__) {
+      ReactDOMInstrumentation.debugTool.onDeleteValueForProperty(node, name);
+      ReactInstrumentation.debugTool.onNativeOperation(
```
Comment (gaearon) [inline src/renderers/dom/shared/DOMPropertyOperations.js]: Note: this method was renamed in #6754 which causes tests to fail now.

**Comment by grassator** [comment]
@gaearon sorry about that—I didn't know about upcoming rename.

**Comment by gaearon** [comment]
Yea, no problem!
