### PR TITLE
Account for another DevTools + Fast Refresh edge case

### LINKED ISSUE #21436: Error: "Cannot add node "1" because a node with that id is already in the Store."
### Which website or app were you using when the bug happened?

Please provide a link to the URL of the website (if it is public), a CodeSandbox (https://codesandbox.io/s/new) example that reproduces the bug, or a project on GitHub that we can checkout and run locally.

### What were you doing on the website or app when the bug happened?

If possible, please describe how to reproduce this bug on the website or app mentioned above:
1. 
2. 
3. 

### Generated information

DevTools version: 4.13.1-93782cfed2

Call stack:
(none)

Component stack:
(none)

GitHub URL search query:
https://api.github.com/search/issues?q=Cannot%20add%20node%20%20because%20a%20node%20with%20that%20id%20is%20already%20in%20the%20Store.%20in%3Atitle%20is%3Aissue%20is%3Aopen%20is%3Apublic%20label%3A%22Component%3A%20Developer%20Tools%22%20repo%3Afacebook%2Freact

### PR DESCRIPTION
**Pull request by bvaughn**
DevTools now 'untrack' Fibers (cleans up the ID-to-Fiber mapping) after a slight delay in order to support a Fast Refresh edge case:
1. Component type is updated and Fast Refresh schedules an update+remount.
2. flushPendingErrorsAndWarningsAfterDelay() runs, sees the old Fiber is no longer mounted (it's been disconnected by Fast Refresh), and calls untrackFiberID() to clear it from the Map.
3. React flushes pending passive effects before it runs the next render, which logs an error or warning, which causes a new ID to be generated for this Fiber.
4. DevTools now tries to unmount the old Component with the new ID.

The underlying problem here is the premature clearing of the Fiber ID, but DevTools has no way to detect that a given Fiber has been scheduled for Fast Refresh. (The '_debugNeedsRemount' flag won't necessarily be set.)

The best we can do is to delay untracking by a small amount, and give React time to process the Fast Refresh delay.

Resolves #21436 and #21442

### CODE REVIEW

**Comment by bvaughn** [comment]
Okay well this change causes one of the legacy Suspense stress tests to fail so I'm not sure what to do next. 😦

File: packages/react-devtools-shared/src/__tests__/FastRefreshDevToolsIntegration-test.js [hunk 1]
```diff
@@ -257,4 +259,6 @@ describe('Fast Refresh', () => {
           <Component> ⚠
     `);
   });
+
+  // TODO (bvaughn) Write a test that checks in between the steps of patch
```
Comment (bvaughn) [inline packages/react-devtools-shared/src/__tests__/FastRefreshDevToolsIntegration-test.js:263]: Would be nice to catch the additional error case (fixed by this PR) in a test.

File: packages/react-devtools-shared/src/backend/renderer.js [hunk 2]
```diff
@@ -726,6 +726,13 @@ export function attach(
         'color: purple;',
         'color: black;',
       );
+      console.log(
+        new Error().stack
+          .split('\n')
+          .slice(1)
+          .join('\n'),
+      );
```
Comment (bvaughn) [inline packages/react-devtools-shared/src/backend/renderer.js:734]: This isn't necessary as part of the PR but I found it helpful when debugging things.

File: packages/react-devtools-shared/src/backend/renderer.js [hunk 3]
```diff
@@ -2319,6 +2381,10 @@ export function attach(
     const current = root.current;
     const alternate = current.alternate;
 
+    // Flush any pending Fibers that we are untracking before processing the new commit.
+    // If we don't do this, we might end up double-deleting Fibers in some cases (like Legacy Suspense).
+    untrackFibers();
```
Comment (bvaughn) [inline packages/react-devtools-shared/src/backend/renderer.js:2386]: The Store stress test for legacy Suspense caught this issue 👍🏼

**Comment by bvaughn** [comment]
I'm going to merge this so I can test it internally within FB.

**Comment by lazcanocode** [comment]
Thank you so much
