### PR TITLE
`react-hooks/rules-of-hooks`: Add support for `do/while` loops

### LINKED ISSUE #28713: Bug: `react-hooks/rules-of-hooks` does not support `do/while` loops
React version: 18.2.0

## Steps To Reproduce

1. Use a hook inside a `do/while` loop. 

2. You'll see that it's not considered a violation of the rule.

Code example:

```
function ComponentWithHookInsideDoWhile() {
	do {
		useHookInsideLoop();
	} while (true);
}
```

## The current behavior

The `react-hooks/rules-of-hooks` does not consider hook usage inside a `do/while` loop a violation.

## The expected behavior

I expected that I'd see the following ESLint error:

```
React Hook useHookInsideLoop() may be executed more than once. 
Possibly because it is called in a loop. 
React Hooks must be called in the exact same order in every component render.
```

### PR DESCRIPTION
**Pull request by tyxla**
## Summary

Currently, `react-hooks/rules-of-hooks` does not support `do/while` loops - I've also reported this in https://github.com/facebook/react/issues/28713.

This PR takes a stab at adding support for `do/while` by following the same logic we already have for detecting `while` loops. 

After this PR, any hooks called inside a `do/while` loop will be considered invalid.

We're also adding some unit tests to confirm that the behavior is working as expected.

Fixes #28713.

## How did you test this change?

I've added unit tests that cover the case and verified that they pass by running:

```
yarn test packages/eslint-plugin-react-hooks/__tests__/ESLintRulesOfHooks-test.js --watch
```

I've also verified that the rest of the tests continue to pass by running:

```
yarn test
```

and

```
yarn test --prod
```

### CODE REVIEW

**Comment by tyxla** [comment]
@eps1lon I noticed you've been working on the ESLint rules, will you have a chance to take a look? Thanks 🙌

**Comment by tyxla** [comment]
Bump! This is still a relevant addition to the existing ESLint plugin IMHO.

**Comment by tyxla** [comment]
cc @mofeiZ perhaps? Sorry for the direct ping, but no one ever replied to this one, and I still think it's useful.

**Comment by josephsavona** [comment]
We need to figure out our strategy for the ESLint plugin. React Compiler also implements the conditional hook call check for all loop types, using a robust general-purpose approach based on the control flow graph. Long-term we expect to replace the existing plugin w the compiler-powered version. 

But we can take a look and see if it makes sense to proceed here in the meantime. I haven’t had a chance to look at the code yet though.

**Comment by josephsavona** [comment]
> I'd be happy to come up with a fix for it if that same bug is present

I appreciate the offer! But what I meant is that React Compiler already correctly handles do..while and all other forms of loops when detecting conditional hooks. But definitely try it out and let us know if you see any issues!

In the meantime we’ll review the code here.

**Comment by tyxla** [comment]
Not stale IMHO.

File: packages/eslint-plugin-react-hooks/src/RulesOfHooks.js [hunk 1]
```diff
@@ -300,7 +300,14 @@ export default {
...
 
-          cache.set(segment.id, paths);
+          // If our segment is reachable then there should be at least one path
+          // to it to the end of our code path.
+          if (segment.reachable && paths === BigInt('0')) {
+            cache.delete(segment.id);
+          } else {
+            cache.set(segment.id, paths);
+          }
+
```
Comment (mofeiZ) [inline packages/eslint-plugin-react-hooks/src/RulesOfHooks.js:310]: Is there a repro that requires changing the caching logic? When I checked out this PR locally and reverted these lines, no fixtures changed.

If this is necessary, could you add a case to ESLintRulesOfHooks-test?

File: packages/eslint-plugin-react-hooks/src/RulesOfHooks.js [hunk 2]
```diff
@@ -272,7 +272,7 @@ export default {
           if (pathList.has(segment.id)) {
             const pathArray = Array.from(pathList);
             const cyclicSegments = pathArray.slice(
-              pathArray.indexOf(segment.id) + 1,
+              pathArray.indexOf(segment.id) - 1,
```
Comment (mofeiZ) [inline packages/eslint-plugin-react-hooks/src/RulesOfHooks.js:275]: Question here: `slice(pathArray.indexOf(segment.id))` makes sense -- we want to include the cyclic segment itself when adding to `cyclic`. What's the logic for also including the previous segment in pathsHistory?

I do see that this test case doesn't error, just trying to understand. Could we also add this to ESLintRulesOfHooks-test to be complete?
```js
function ComponentWithHookInsideLoop() {
  do {
	  foo();
  } while (useHookInsideLoop());
}
```

**Review by mofeiZ — COMMENTED** [review]
@tyxla left a few questions. I agree with @josephsavona, react compiler-based eslint does correctly detect and fix this, but we know that not everyone has upgraded yet

File: packages/eslint-plugin-react-hooks/src/RulesOfHooks.js (hunk 2 above)
Comment (tyxla) [reply packages/eslint-plugin-react-hooks/src/RulesOfHooks.js:298]: Thanks for the test - it covers precisely why we want to include the previous segment. 

I've added the test in https://github.com/facebook/react/pull/28714/commits/dc7a41f13caf21c907a3ff089e68974d6245e05f.

File: packages/eslint-plugin-react-hooks/src/RulesOfHooks.js (hunk 1 above)
Comment (tyxla) [reply packages/eslint-plugin-react-hooks/src/RulesOfHooks.js]: I'm pretty sure that back when I was running the automated tests, they were hanging without this. However, this no longer occurs, so I've removed it in https://github.com/facebook/react/pull/28714/commits/33cb28f5307bc1be5412d32c46a2686e2ebae7ec. Thanks for catching it!

**Comment by tyxla** [comment]
@mofeiZ, thanks for the review and the valuable feedback! 

I've addressed it all, and this PR should be ready for one last look. 👀

File: packages/eslint-plugin-react-hooks/src/RulesOfHooks.js [hunk 3]
```diff
@@ -324,6 +324,7 @@ export default {
           }
 
           cache.set(segment.id, paths);
+
```
Comment (mofeiZ) [inline packages/eslint-plugin-react-hooks/src/RulesOfHooks.js:327]: super nit: could we remove this whitespace change to keep blame history clean?

Comment (tyxla) [reply packages/eslint-plugin-react-hooks/src/RulesOfHooks.js]: Sure thing, done in [0f822bf](https://github.com/facebook/react/pull/28714/commits/0f822bfeb6eb40f6c42eec1ceaacbce154564aea)

**Review by mofeiZ — APPROVED** [review]
thanks for the fix and new test fixtures @tyxla!

File: packages/eslint-plugin-react-hooks/src/RulesOfHooks.js (hunk 2 above)
Comment (skratchdot) [reply packages/eslint-plugin-react-hooks/src/RulesOfHooks.js:298]: i'm not 100% sure, but i think this may have introduced some false positives for other use-cases:
https://github.com/facebook/react/issues/31687#issuecomment-2529150548

**Comment by tyxla** [comment]
@Mathias-S thanks for the report! We might need to take this a different way.

I think I might have a quick solution as I played with a few alternative solutions before. Stay tuned.

**Comment by tyxla** [comment]
Follow up fix in https://github.com/facebook/react/pull/31720, @Mathias-S please take a look when you get a chance.
