### PR TITLE
Shallow render components that define contextTypes

### LINKED ISSUE #3696: Shallow renderer fails when component has `contextTypes`
I am trying to render a component using the preliminary shadow renderer support in TestUtils. A simple reproducible test case of my issue is this

```
    var Foo = React.createClass({
      contextTypes: {
        foo: React.PropTypes.object
      },

      render: function() {
        return null;
      }
    });

    var renderer = TestUtils.createRenderer();
    renderer.render(<Foo/>);
```

When I run this in my Jest test, I get:

```
  - TypeError: Cannot read property 'foo' of undefined
        at ReactCompositeComponentMixin._maskContext (/Users/.../node_modules/react/lib/ReactCompositeComponent.js:336:43)
        at ReactCompositeComponentMixin._warnIfContextsDiffer (/Users/.../node_modules/react/lib/ReactCompositeComponent.js:538:31)
        at ReactCompositeComponentMixin.mountComponent (/Users/.../node_modules/react/lib/ReactCompositeComponent.js:162:12)
```

It looks like this error is thrown whenever the component being rendered has `contextTypes`. I thought perhaps the context was required (although I haven't had any problems omitting it in my actual app), but even when using `withContext` I get the same exception.

### PR DESCRIPTION
**Pull request by graue**
You now no longer have to pass an undocumented extra argument to the shallow renderer for rendering components with contextTypes to work.

Fixes #3696

### CODE REVIEW

File: src/test/ReactTestUtils.js [hunk 1]
```diff
@@ -369,6 +370,9 @@ assign(
 );
 
 ReactShallowRenderer.prototype.render = function(element, context) {
+  if (!context) {
+    context = emptyObject;
+  }
```
Comment (zpao) [inline src/test/ReactTestUtils.js]: So… it looks like we don't have any tests that actually test using `context` :/

**Comment by zpao** [comment]
Thanks for the quick fix! My inline comment is just an observation, not something we need to do here.

**Comment by graue** [comment]
You're welcome :) Yeah, actually passing context is broken right now — filed #3721 for that. But this will fix the case where the component under test supports optional context.

**Comment by anyong** [comment]
Using react-router and have the line `contextTypes: { router: React.PropTypes.func }` in my component gives me a test that says `Cannot read property 'func' of undefined`. Is this related?

**Comment by graue** [comment]
@anyong: Sounds like a different problem. If you can create a new issue (ideally with a minimal example that shows the bug, like #3696), we'd appreciate it :)
