### PR TITLE
DevTools encoding supports multibyte characters (e.g. "🟩")

### LINKED ISSUE #22422: [DevTools Bug]: Emoji as visual helper produce strange symbole
### Website or app

https://codesandbox.io/s/react-playground-forked-j4niq

### Repro steps

Emoji seem supported but produce strange symbole

image

To test emoji on Window Os, use `[win]+[.]` 🟩

### How often does this bug happen?

Every time

### DevTools package (automated)

_No response_

### DevTools version (automated)

_No response_

### Error message (automated)

_No response_

### Error call stack (automated)

_No response_

### Error component stack (automated)

_No response_

### GitHub query string (automated)

_No response_

### PR DESCRIPTION
**Pull request by bvaughn**
Changes our text encoding approach to properly support multibyte characters following [this algorithm](https://stackoverflow.com/questions/4877326/how-can-i-tell-if-a-string-contains-multibyte-characters-in-javascript). Based on [benchmarking](https://jsbench.me/x6ku2p436b/1), this new approach is roughly equivalent in terms of performance (sometimes slightly faster, sometimes slightly slower).

I also considered using `TextEncoder`/`TextDecoder` for this, but it was [_much_ slower](https://jsben.ch/5tnt1) (~85%).

Resolves #22422

### CODE REVIEW

**Comment by bvaughn** [comment]
Based on a few benchmarks, the `TextEncoder`/`TextDecoder` approach _is slower_ (~85% slower), but it's unclear how much of an overall impact this will have on actual DevTools performance (as we don't encode long strings often).

* https://jsbench.me/boktzulhew/1
* https://jsben.ch/5tnt1

**Comment by eps1lon** [comment]
Would it make sense to check whether we even need `TextEncoder` and transmit the enconding mechanism (`TextEncoder` or `codePointAt`)?

You could start encoding with the old `codePointAt` strategy and once you detect a surrogate pair (`/[\uD800-\uDFFF]/.test(character)` (source: https://stackoverflow.com/a/4885062/3406963)), deopt to `TextEncoder`. 

Or maybe it's faster to test this up-front.

**Comment by bvaughn** [comment]
Testing and conditionally using `TextDecoder`/`TextEncoder` speeds things up _a little bit_ but not much:
https://jsbench.me/jpku2ofvaw/1

It's possible we could improve perf a bit more using the experimental [`encodeInto`](https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder/encodeInto) method but I'm not sure how much.

I think I have found an alternate approach though that I will try instead. Hold tight.

**Comment by bvaughn** [comment]
Okay. I believe the latest commit is roughly the same performance (benchmark shows sometimes slightly faster, sometimes slightly slower) as what we had before, but it also handles special characters.

https://jsbench.me/x6ku2p436b/1

Credit for this encoding approach goes to Tim Down:
https://stackoverflow.com/questions/4877326/how-can-i-tell-if-a-string-contains-multibyte-characters-in-javascript

One additional thing I noticed while testing this (using a `Map` for a cache at least) was that the addition of caching actually made perf _worse_ (as shown in the above benchmark) so I've also removed the LRU cache.

File: packages/react-devtools-shared/src/__tests__/store-test.js [hunk 1]
```diff
@@ -101,6 +101,19 @@ describe('Store', () => {
...
+  it('should handle multibyte character strings', () => {
+    const Component = () => null;
+    Component.displayName = '🟩💜🔵';
+
+    const container = document.createElement('div');
+
+    act(() => legacyRender(<Component />, container));
+    expect(store).toMatchInlineSnapshot(`
+      [root]
+          <🟩💜🔵>
```
Comment (bvaughn) [inline packages/react-devtools-shared/src/__tests__/store-test.js:113]: This test verifies the before/after result of the fix in this PR.
```diff
    -     <🟩�💜�🔵�>
    +     <🟩💜🔵>
```

File: packages/react-devtools-shared/src/utils.js [hunk 2]
```diff
@@ -50,16 +49,9 @@ import {localStorageGetItem, localStorageSetItem} from './storage';
 import {meta} from './hydration';
 
 import type {ComponentFilter, ElementType} from './types';
-import type {LRUCache} from 'react-devtools-shared/src/types';
 
 const cachedDisplayNames: WeakMap<Function, string> = new WeakMap();
 
-// On large trees, encoding takes significant time.
-// Try to reuse the already encoded strings.
-const encodedStringCache: LRUCache<string, Array<number>> = new LRU({
```
Comment (lunaruan) [inline packages/react-devtools-shared/src/utils.js:59]: Why did we decide to remove this cache? It seems like the new encoding algorithm takes comparable time?

**Review by lunaruan — APPROVED** [review]

File: packages/react-devtools-shared/src/utils.js (hunk 2 above)
Comment (bvaughn) [reply packages/react-devtools-shared/src/utils.js:59]: I mentioned this in the PR description:
> Also based on the same benchmark, removing the encoding cache further speeds things up, so this PR also removes that.

If you look at the [original benchmark](https://jsbench.me/x6ku2p436b/1) you can see that the one with the cache is slower. However after thinking about that again this afternoon, I realized that this was b'c of how I setup the benchmark (the cache Map was being recreated each time). Setting it up in the _before_ block (so it's reused between test runs) makes the test with cache a little faster.

_That being said_, that's not really an accurate benchmark either because the cache will never have 100% hit rate after the first few encodings. I'm not really sure of the best way to measure this 😁

Comment (bvaughn) [reply packages/react-devtools-shared/src/utils.js:59]: If I make the original list _really long_ (several hundred strings, each one 50-70 characters), then the difference between the two implementations (cache and no cache) is _less_:

<table>
<tr>
	<td>Main branch
	<td>2848.22 ops/s ± 1.84%
	<td>30.68 % slower
<tr>
	<td>This PR
	<td>2343.15 ops/s ± 0.96%<
	<td>42.97 % slower
<tr>
	<td>This PR with caching
	<td>4108.83 ops/s ± 1.05%
	<td>Fastest
</table>

But even in this case, _with a lot of caching hits_, the difference in performance isn't that great. And it may be worth pointing out that this test uses native `Map` (which is probably faster than our `LRU` library, since that's also managing caching eviction).

So I'm tempted to just remove this caching layer for now.

Wondering if @gaearon has any thoughts. I _believe_ he added the cache.

Comment (bvaughn) [reply packages/react-devtools-shared/src/utils.js]: I'll re-add the cache for now, so the changes in this PR are minimal. We can always remove it later.
