### PR TITLE
Fix ESLint crash on empty react effect hook

### LINKED ISSUE #20343: [eslint-plugin-react-hooks] Bug: ESLint crashes if there's a `useEffect` / `useLayoutEffect` invocation without any arguments.
eslint-plugin-react-hooks version: 4.2.0

## Steps To Reproduce

I know it shouldn't exist in production code, but it's annoying while editing some files.

```js
import React, { useEffect } from "react";

const App = () => {
  useEffect(); // <-
  return null;
};

export default App;
```

Link to code example: https://codesandbox.io/s/polished-sun-3wr27?file=/src/App.js

## The current behavior

ESLint crashed.

```
TypeError: Cannot read property 'type' of undefined
```

## The expected behavior

ESLint doesn't crash but reports an error instead.

### PR DESCRIPTION
**Pull request by ChrisRu**
## Summary

ESLint crashes due to the `eslint-plugin-react-hooks` plugin, when an empty (no arguments) `useEffect`, `useLayoutEffect`,  `useMemo` or `useCallback` is written.

If any of these hooks are empty during runtime, React will also throw a TypeError, so this should also be a lint warning in my opinion.

To resolve this crash, a check is added to see if there is any callback supplied and creates a lint warning if there isn't one.

Resolves #20343

## Test Plan

I built the `eslint-plugin-react-hooks` bundle and copied it into the node_modules of my test project, which fixed the crashes.

I also verified this new lint check didn't impact custom hooks and it didn't. 

I added a test case for these empty hooks to check if the correct problem is shown by ESLint. I also ran the tests for the whole repository to ensure there were no other problems.

### CODE REVIEW

File: packages/eslint-plugin-react-hooks/__tests__/ESLintRuleExhaustiveDeps-test.js [hunk 1]
```diff
@@ -1692,6 +1692,42 @@ const tests = {
...
+          useEffect()
+          useLayoutEffect()
+          useCallback()
+          useMemo()
+        }
+      `,
+      errors: [
+        {
+          message:
+            'React Hook useEffect will crash when called with no arguments. ' +
```
Comment (rickhanlonii) [inline packages/eslint-plugin-react-hooks/__tests__/ESLintRuleExhaustiveDeps-test.js:1707]: How about we explain the requirement instead of the behavior? Something like:

> React Hook useEffect requires an effect callback. Did you forget to pass a callback to the hook?

**Review by rickhanlonii — COMMENTED** [review]
Looks good, but can we update the message?

File: packages/eslint-plugin-react-hooks/__tests__/ESLintRuleExhaustiveDeps-test.js (hunk 1 above)
Comment (ChrisRu) [reply packages/eslint-plugin-react-hooks/__tests__/ESLintRuleExhaustiveDeps-test.js]: Yes, that's much better. Thanks!

**Review by rickhanlonii — APPROVED** [review]
LGTM, thanks!
