### PR TITLE
Reset inspected element cache in the event of an error

### LINKED ISSUE #21819: [DevTools] Improve "retry" function for inspected component props/state/hooks
Currently if an error occurs when inspecting a component, an error overlay is shown in the right hand side of DevTools along with a "dismiss" button to allow the inspection to be retried. However, currently this "retry" does not clear the entry from the cache and so it will immediately fail again if the same component is re-selected. We should clear the cache entry so that we actually retry when the modal is dismissed

### PR DESCRIPTION
**Pull request by bvaughn**
This prevents React from immediately erroring again when re-rendering (since the previous error would have been stored in the Suspense cache)

Resolves #21819

### CODE REVIEW

File: packages/react-devtools-shared/src/inspectedElementCache.js [hunk 1]
```diff
@@ -63,6 +63,19 @@ function getRecordMap(): WeakMap<Element, Record<InspectedElementFrontend>> {
...
+ *
+ * This function should only be called during render (since it reads from Context)
+ * and the callback it returns should be called prior to render.
+ */
+export function getClearElementCallback(element: Element): () => void {
+  const map = getRecordMap();
+  return function clearElementCallback(): void {
+    map.delete(element);
+  };
+}
```
Comment (bvaughn) [inline packages/react-devtools-shared/src/inspectedElementCache.js:77]: This is the part I'm asking for feedback about: What is our recommended pattern for clearing (either an entry or entirely) the Suspense cache before retrying a render? Feels a little awkward to do it this way. Maybe there's a better/easier way?

Comment (bvaughn) [reply packages/react-devtools-shared/src/inspectedElementCache.js:77]: Maybe I should use the `refresh` API for this instead, and just pass an `undefined` value.
