### PR TITLE
Fix a crash when using dynamic children in <option> tag

### LINKED ISSUE #11911: React DOM crashes when <option> contains three interpolated value if one is a conditional.
**Do you want to request a *feature* or report a *bug*?** 

Bug 

**What is the current behavior?**

React DOM crashes when `<option>` contains three interpolated value if one is a conditional. 

Reproduction: https://jsfiddle.net/0opjvycp/ 

1. Change the value of the `<select>`
2. React crashes with `NotFoundError: Node was not found` 

From what I can tell, the conditional value is necessary, and it must be three interpolated values. 

**What is the expected behavior?**

React should not crash. 

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React DOM 16.2 and 16.0. I think this worked in 15.6 - https://jsfiddle.net/mrwkmuqc/ does not crash

### PR DESCRIPTION
**Pull request by Slowyn**
fix #11911 

I had to move `validateDOMNesting` into the flattening process so it causes a different warning message. I'm not sure if this is a right approach.

## The problem
After the investigation, I got that the reason of crash was desynchronization of Fiber and real node.
`<option />` flattens its children, while Fiber does not. So we can pass into `<option />` an array of children e.g.
```
['some', <div>5</div>, null, ' string']
```
It flattens to a string
```
'some string'
```
But Fiber keeps links to all children. Let's assume that `null` depends on some state. Fiber will try to update children using `insertBefore`, but as we don't have a real node in DOM, it caused a runtime error.

## Solution
`<option />`'s children should be a string and we have to filter children. The simplest solution was to allow react to set content as a direct text child. It solves the issue and makes a behavior of `<option />` like in React v.15.*.*. Unfortunately, this solution leads us to skip `validateDOMNesting`.

### CODE REVIEW

File: packages/react-dom/src/__tests__/ReactDOMOption-test.js [hunk 1]
```diff
@@ -41,9 +41,7 @@ describe('ReactDOMOption', () => {
     expect(() => {
       node = ReactTestUtils.renderIntoDocument(el);
     }).toWarnDev(
-      '<div> cannot appear as a child of <option>.\n' +
-        '    in div (at **)\n' +
-        '    in option (at **)',
+      '<div> cannot appear as a child of <option>.\n' + '    in option (at **)',
```
Comment (Slowyn) [inline packages/react-dom/src/__tests__/ReactDOMOption-test.js]: This is a behavior change and I'm not sure how to avoid this with this solution.

Comment (nhunzaker) [reply packages/react-dom/src/__tests__/ReactDOMOption-test.js]: I think this is okay. Particularly since the problem is still identified in the message (even if the nest doesn't show up).

Comment (nhunzaker) [reply packages/react-dom/src/__tests__/ReactDOMOption-test.js]: @aweary or @gaearon Do you anticipate any problems with changing this warning text?

File: packages/react-dom/src/client/ReactDOMFiberOption.js [hunk 2]
```diff
@@ -17,14 +18,23 @@ function flattenChildren(children) {
...
       return;
     }
     if (typeof child === 'string' || typeof child === 'number') {
       content += child;
+      return;
+    }
+    if (__DEV__) {
+      // We do not have HostContext here
+      // but we can put some parent information at least
+      // Also this cause a bit different message than it was previously
```
Comment (gaearon) [inline packages/react-dom/src/client/ReactDOMFiberOption.js]: Nit: “a bit different message” would become meaningless after merging this PR. Let’s ensure any comments are helpful to future readers.

**Comment by Slowyn** [comment]
My IDE automatically insert an empty row at the end of file -_-
I've "reverted" `scripts/rollup/results.json`  and removed the unnecessary comment.

File: packages/react-dom/src/client/ReactDOMFiberOption.js [hunk 3]
```diff
@@ -17,14 +18,22 @@ function flattenChildren(children) {
...
     if (child == null) {
       return;
     }
     if (typeof child === 'string' || typeof child === 'number') {
       content += child;
+      return;
+    }
+    if (__DEV__) {
+      // We do not have HostContext here
+      // but we can put some parent information at least
```
Comment (nhunzaker) [inline packages/react-dom/src/client/ReactDOMFiberOption.js]: Nit: Could you reformat this like:

```
    // We do not have HostContext here, but we can at least
    // put some parent information
```

**Comment by Slowyn** [comment]
I can try to write a test. I think It's a case for `DOMSelect-test`, right?

**Comment by nhunzaker** [comment]
Yep!

**Comment by gaearon** [comment]
Can you push the code that doesn't work so I can take a look?

**Comment by Slowyn** [comment]
Sorry, I wasn't able to push right away.
I forgot to pass `ancestorInfo` when was making the screenshot., but passing `ancestorInfo` wouldn't change the result.

**Comment by react-linter** [comment]
ReactDOM: size: :small_red_triangle:+0.1%, gzip: :small_red_triangle:+0.1%


  <details>
  <summary>Details of bundled changes.</summary>

  <p>Comparing: ca0941fce3a03592530f6111f77cbc9c0daf79af...931417b4748da1ee0775130398723804201e6d77</p>


  
## react-dom
File | Filesize Diff | Gzip Diff | Prev Size | Current Size | Prev Gzip | Current Gzip | ENV
 ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  --- 
react-dom.development.js | +0.1% | 0.0% | 641.2 KB | 641.54 KB | 150.36 KB | 150.37 KB | UMD_DEV
**react-dom.production.min.js** | **:small_red_triangle:+0.1%** | **:small_red_triangle:+0.1%** | **96.08 KB** | **96.17 KB** | **31.09 KB** | **31.13 KB** | **UMD_PROD**
react-dom.development.js | +0.1% | 0.0% | 637.34 KB | 637.68 KB | 149.18 KB | 149.19 KB | NODE_DEV
**react-dom.production.min.js** | **:small_red_triangle:+0.1%** | **:small_red_triangle:+0.1%** | **96.07 KB** | **96.16 KB** | **30.61 KB** | **30.66 KB** | **NODE_PROD**
ReactDOM-dev.js | +0.1% | 0.0% | 644.68 KB | 645.06 KB | 147.58 KB | 147.58 KB | FB_WWW_DEV
**ReactDOM-prod.js** | **:small_red_triangle:+0.1%** | **0.0%** | **278.74 KB** | **279.02 KB** | **52.13 KB** | **52.15 KB** | **FB_WWW_PROD**
react-dom.profiling.min.js | +0.1% | +0.1% | 97.2 KB | 97.29 KB | 31.02 KB | 31.05 KB | NODE_PROFILING
ReactDOM-profiling.js | +0.1% | +0.1% | 282.04 KB | 282.29 KB | 52.85 KB | 52.88 KB | FB_WWW_PROFILING

  </details>
  
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

File: packages/react-dom/src/__tests__/ReactDOMSelect-test.js [hunk 4]
```diff
@@ -545,6 +545,48 @@ describe('ReactDOMSelect', () => {
     expect(node.options[2].selected).toBe(false); // gorilla
   });
 
+  it('should not fail', () => {
```
Comment (gaearon) [inline packages/react-dom/src/__tests__/ReactDOMSelect-test.js]: This is very vague.

Comment (Slowyn) [reply packages/react-dom/src/__tests__/ReactDOMSelect-test.js]: Yeah, It's some temporary "name" until we get a full working version.
Going to change it to some concrete form 😄 

Have you taken a look on `anccestorInfo` in current case?

Comment (Slowyn) [reply packages/react-dom/src/__tests__/ReactDOMSelect-test.js]: What about this description: "Options with stateful children; it should change its state properly and shouldn't fail"
What do you think?

**Comment by gaearon** [comment]
Seems like the reason this doesn't work is because the host context we get is from option's parent, not option itself.

**Comment by react-linter** [comment]
ReactDOM: size: 0.0%, gzip: 0.0%


  <details>
  <summary>Details of bundled changes.</summary>

  <p>Comparing: ca0941fce3a03592530f6111f77cbc9c0daf79af...7ccf3ce6e5bf31e1b91d37e304757894139070db</p>


  
## react-dom
File | Filesize Diff | Gzip Diff | Prev Size | Current Size | Prev Gzip | Current Gzip | ENV
 ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  --- 
react-dom.development.js | +0.1% | 0.0% | 641.2 KB | 641.56 KB | 150.36 KB | 150.38 KB | UMD_DEV
**react-dom.production.min.js** | **0.0%** | **0.0%** | **96.08 KB** | **96.1 KB** | **31.09 KB** | **31.1 KB** | **UMD_PROD**
react-dom.development.js | +0.1% | 0.0% | 637.34 KB | 637.7 KB | 149.18 KB | 149.2 KB | NODE_DEV
**react-dom.production.min.js** | **0.0%** | **0.0%** | **96.07 KB** | **96.08 KB** | **30.61 KB** | **30.62 KB** | **NODE_PROD**
ReactDOM-dev.js | +0.1% | 0.0% | 644.68 KB | 645.07 KB | 147.58 KB | 147.6 KB | FB_WWW_DEV
**ReactDOM-prod.js** | **0.0%** | **0.0%** | **278.74 KB** | **278.76 KB** | **52.13 KB** | **52.13 KB** | **FB_WWW_PROD**
react-dom.profiling.min.js | 0.0% | 0.0% | 97.2 KB | 97.22 KB | 31.02 KB | 31.02 KB | NODE_PROFILING
ReactDOM-profiling.js | 0.0% | 0.0% | 282.04 KB | 282.06 KB | 52.85 KB | 52.85 KB | FB_WWW_PROFILING

  </details>
  
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by Slowyn** [comment]
@gaearon I thought that loosing of host context is connected with some operations (e.g. `children = null`) when a child is detected as a direct text child.
Maybe it's a silly question, but I was wondering about the warning:
```
'<div> cannot appear as a child of <option>.\n' +
        '    in div (at **)\n' +
        '    in option (at **)',
```
` '    in div (at **)\n'` Is this an indecation on current child or parent?

**Comment by gaearon** [comment]
Host context is pushed onto the stack when we "begin" a fiber, and popped when we "complete" it. In this case `<option>` itself was being "completed" by the time we finalize its props, so only `<option>`'s own parent context was on the stack (and not the context it provides for *its* children).

That's expected behavior and in most cases it makes sense because we tend to process children independently. Option is a weird edge case where we post-process children after we've already "completed" them (or, to be more accurate, we've never "began" them in the first place now that we treat them as text content).

**Comment by exogen** [comment]
FYI, I just upgraded React and I suspect this change (or one of the other `<option>` PRs) caused a backwards incompatibility within the 16.x channel.

Despite the HTML `<option>` tag only allowing strings for labels, all that *should* matter in React is what makes it to the final HTML output. For instance, these should (and used to) work:

```
<option><React.Fragment>Label A</React.Fragment></option>

import { FormattedMessage } from 'react-intl';
<option><FormattedMessage>{msg => "Label B"}</FormattedMessage></option>

const MyLabel = () => "Label C";
<option><MyLabel /></option>
```

All three of the above will render `[object Object]` as the option label now. Due to using the middle technique above in our app, some of our forms unfortunately started doing this.

**Comment by gaearon** [comment]
This works again in 18 if you specify `value` for `<option>`.
