### PR TITLE
[DevTools] upgrade to Manifest V3

### LINKED ISSUE #24522: [DevTools] Manifest version 2 is deprecated
### Website or app

https://developer.chrome.com/blog/mv2-transition/

### Repro steps

Use latest React DevTools with Electron (Chromium) (18.2.0 / Chromium 100)

```
  (node:80082) ExtensionLoadWarning: Warnings loading extension at ./node_modules/electron-devtools-vendor/extensions/react-developer-tools:
    Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.
```

### How often does this bug happen?

Every time

### DevTools package (automated)

_No response_

### DevTools version (automated)

_No response_

### Error message (automated)

_No response_

### Error call stack (automated)

_No response_

### Error component stack (automated)

_No response_

### GitHub query string (automated)

_No response_

### PR DESCRIPTION
**Pull request by mondaychen**
## Summary

resolves #24522

To upgrade to Manifest V3, one of the biggest issue is that we are no longer allowed to add a script element with code in textContent so that it would run synchronously. It's necessary for us because we need to inject a global hook for react reconciler to detect whether devtools exist.
To do that, we'll leverage a new API `chrome.scripting.registerContentScripts` in V3. Particularly, we rely on the "world" option (added in Chrome v102 [commit](https://chromium.googlesource.com/chromium/src/+/e5ad3451c17b21341b0b9019b074801c44c92c9f)) to run it in the "main world" on the page.

This PR also renames a few content script files so that it's easier to tell them apart from other extension scripts and understand the purpose of each of them.  

Manifest V3 is not yet ready for Firefox, so we need to keep some code for compatibility.

## How did you test this change?

`yarn build:chrome && yarn test:chrome`
`yarn build:edge && yarn test:edge`
`yarn build:firefox && yarn test:firefox`

### CODE REVIEW

**Comment by SijaanX** [comment]
@mondaychen Too bad your code looks exactly like mine, but I forgot to delete the XHR request which isn't supported.
I feel like I missed this one badly, worked on it for over a month to understand extension :(.

URGHHHH

**Comment by SijaanX** [comment]
@mondaychen  I have only a slight difference, with the injected install hook.

I made a new file as you did, but I copied the whole script (including the installhook(window)) and pasted it into the file.

You imported it from `import {installHook} from 'react-devtools-shared/src/hook';`. Which way is better?

I did it this way because I wanted to keep it independent of other repo's. Please let me know wha tyou think.

Again, I feel like I missed this one badly@@@@

**Comment by mondaychen** [comment]
@SijaanX 
> I did it this way because I wanted to keep it independent of other repo's

`react-devtools-shared/src/hook` is also used in other places such as standalone app and inline version of devtools. It's better to keep it there.

I understand and appreciate that you'd love to contribute. But we have a hard deadline and cannot keep waiting. Like I've suggested in the issue, if you did make significant progress but want my help, it's better to create a branch on your own fork so that I can see it, and communicate with me clearly and timely. In that way, even if you could not finish the entire thing on your own, as long as I were able to finish the work on top of yours, you will still get credits. 
Also in the future I'd suggest you work on something not assigned to a team member. It's way easier when you are not "racing" with a developer who has more context and is working on this project full-time.

File: packages/react-devtools-extensions/src/contentScripts/prepareInjection.js [hunk 1]
```diff
@@ -96,56 +104,27 @@ window.addEventListener('pageshow', function({target}) {
...
-  injectCode(rendererCode);
-}
+// The legacy way to inject the global hook in Manifest V2 extensions.
+// In V3, we use chrome.scripting.registerContentScripts instead (see background.js)
+if (IS_FIREFOX) {
+  // If we have just reloaded to profile, we need to inject the renderer interface before the app loads.
+  if (
+    sessionStorageGetItem(SESSION_STORAGE_RELOAD_AND_PROFILE_KEY) === 'true'
+  ) {
+    injectCodeSync(chrome.runtime.getURL('build/renderer.js'));
```
Comment (mondaychen) [inline packages/react-devtools-extensions/src/contentScripts/prepareInjection.js:114]: @lunaruan originally we inject renderer code conditionally (only when that session storage value is `'true'`) like this. However, as we change to register it in background.js in V3, there's seem to be no way we can check this value. I've changed it to conditionally **run** it in renderer.js.
In theory this change would slow down the page when you don't need to load renderer.js, but in my test run the impact looks pretty minimal.

File: packages/react-devtools-extensions/src/background.js [hunk 2]
```diff
@@ -2,17 +2,41 @@
...
 'use strict';
 
+import {IS_FIREFOX} from './utils';
+
 const ports = {};
 
-const IS_FIREFOX = navigator.userAgent.indexOf('Firefox') >= 0;
+if (!IS_FIREFOX) {
+  // Manifest V3 method of injecting content scripts (not yet supported in Firefox)
+  // Note: the "world" option in registerContentScripts is only available in Chrome v102+
```
Comment (lunaruan) [inline packages/react-devtools-extensions/src/background.js:11]: Should we have a fallback for Chrome < v102?. Ex. maybe it's okay for older Chrome versions to have a race condition or block when using React DevTools (with a warning to install the newer version)

File: packages/react-devtools-extensions/src/background.js [hunk 3]
```diff
@@ -63,19 +90,35 @@ function doublePipe(one, two) {
...
+        '16': chrome.runtime.getURL(`icons/16-${reactBuildType}.png`),
+        '32': chrome.runtime.getURL(`icons/32-${reactBuildType}.png`),
+        '48': chrome.runtime.getURL(`icons/48-${reactBuildType}.png`),
+        '128': chrome.runtime.getURL(`icons/128-${reactBuildType}.png`),
+      },
+    });
+    chrome.browserAction.setPopup({
+      tabId: tabId,
+      popup: chrome.runtime.getURL(`popups/${reactBuildType}.html`),
+    });
```
Comment (lunaruan) [inline packages/react-devtools-extensions/src/background.js:106]: Instead of repeating code here, maybe we can instead do something like

```
const browserAction = IS_FIREFOX ? chrome.browserAction : chrome.action;
...
```

File: packages/react-devtools-extensions/src/background.js [hunk 4]
```diff
@@ -123,9 +166,6 @@ chrome.runtime.onMessage.addListener((request, sender) => {
     // This is sent from the hook content script.
     // It tells us a renderer has attached.
     if (request.hasDetectedReact) {
-      // We use browserAction instead of pageAction because this lets us
-      // display a custom default popup when React is *not* detected.
-      // It is specified in the manifest.
```
Comment (lunaruan) [inline packages/react-devtools-extensions/src/background.js:128]: Sanity check: Did we test to make sure this works in manifest v3? (Assuming we did but leaving it here just in case!)

File: packages/react-devtools-extensions/src/background.js (hunk 2 above)
Comment (mondaychen) [reply packages/react-devtools-extensions/src/background.js:11]: Yeah good point. Let me try find a good place to do that

File: packages/react-devtools-extensions/src/background.js (hunk 3 above)
Comment (mondaychen) [reply packages/react-devtools-extensions/src/background.js:106]: Sure. When I coded this I thought it would be temporary but it turns out Firefox is pretty behind in V3 and this might stay for quite a while

File: packages/react-devtools-extensions/src/background.js (hunk 4 above)
Comment (mondaychen) [reply packages/react-devtools-extensions/src/background.js:128]: Yes. I did check that

**Comment by mondaychen** [comment]
@lunaruan updated!

**Comment by lunaruan** [comment]
Sorry for the belated review! This looks good. One thing though: We don't want React DevTools to slow down the initial page load. Could we add a before/after profiling trace to make sure that the page load time has not changed?

**Comment by mondaychen** [comment]
Performance impact (tested with cached [reactjs.org](https://reactjs.org/), Chrome perf tab "start profiling & reload")

With MV3 (this PR): about 700ms
image

With MV2 (main branch): about 840ms
image

With no extension installed: about 690ms
image


My test perf results on other pages are similar. My conclusion is that this change brings improvement on initial page load time.

File: packages/react-devtools-shared/src/devtools/views/Components/Tree.js [hunk 5]
```diff
@@ -344,6 +344,22 @@ export default function Tree(props: Props): React.Node {
     clearErrorsAndWarningsAPI({bridge, store});
   };
 
+  const zeroElementsNotice = (
+    <div className={styles.ZeroElementsNotice}>
+      <p>Loading elements from the React app...</p>
```
Comment (lunaruan) [inline packages/react-devtools-shared/src/devtools/views/Components/Tree.js:349]: Maybe 'Loading React Element Tree' ?

File: packages/react-devtools/README.md [hunk 6]
```diff
@@ -105,8 +105,13 @@ Or you could develop with a local HTTP server like [`serve`](https://www.npmjs.c
 
 **If your app is inside an iframe, a Chrome extension, React Native, or in another unusual environment**, try [the standalone version instead](https://github.com/facebook/react/tree/main/packages/react-devtools). Chrome apps are currently not inspectable.
 
+**If your React DevTools tab is showing an empty tree**, please read the "the issue with Chrome v101 and earlier versions" part below.
```
Comment (lunaruan) [inline packages/react-devtools/README.md:108]: Maybe `If your Components tab is empty, refer to "Chrome v101 ad earlier" section below`?

**Review by lunaruan — COMMENTED** [review]
Looks good! Just a few comments/nits!

File: packages/react-devtools-extensions/chrome/manifest.json [hunk 7]
```diff
@@ -21,31 +21,43 @@
...
   },
   "permissions": [
-    "file:///*",
-    "http://*/*",
-    "https://*/*"
+    "storage",
+    "scripting"
+  ],
+  "host_permissions": [
+    "<all_urls>"
```
[the remark this answers is not in the document]
Comment (mondaychen) [reply packages/react-devtools-extensions/chrome/manifest.json:52]: I think either way is fine. We should keep this synced with "matches" of "content_scripts" which has always been <all_urls>. Let's just keep it?

File: packages/react-devtools-extensions/chrome/manifest.json [hunk 8]
```diff
@@ -21,31 +21,43 @@
...
-    "panel.html",
-    "build/react_devtools_backend.js",
-    "build/renderer.js"
+    {
+      "resources": [
+        "main.html",
+        "panel.html",
+        "build/react_devtools_backend.js",
+        "build/proxy.js",
+        "build/prepareInjection.js",
```
[the remark this answers is not in the document]
Comment (mondaychen) [reply packages/react-devtools-extensions/chrome/manifest.json]: You are right, we don't need to :)

File: packages/react-devtools/README.md [hunk 9]
```diff
@@ -105,12 +105,12 @@ Or you could develop with a local HTTP server like [`serve`](https://www.npmjs.c
 
 **If your app is inside an iframe, a Chrome extension, React Native, or in another unusual environment**, try [the standalone version instead](https://github.com/facebook/react/tree/main/packages/react-devtools). Chrome apps are currently not inspectable.
 
-**If your React DevTools tab is showing an empty tree**, please read the "the issue with Chrome v101 and earlier versions" part below.
+**If your Components tab is empty, refer to "Chrome v101 and earlier" section below**, please read the "the issue with Chrome v101 and earlier versions" part below.
 
 **If you still have issues** please [report them](https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools). Don't forget to specify your OS, browser version, extension version, and the exact instructions to reproduce the issue with a screenshot.
 
 ### The Issue with Chrome v101 and earlier versions
```
Comment (lunaruan) [inline packages/react-devtools/README.md:112]: Probably want tor ename this to "Chrome v101 and earlier" to match with the above text (or change the above text)

File: packages/react-devtools-extensions/firefox/manifest.json [hunk 10]
```diff
@@ -31,7 +31,10 @@
     "main.html",
     "panel.html",
     "build/react_devtools_backend.js",
-    "build/renderer.js"
+    "build/proxy.js",
+    "build/prepareInjection.js",
```
Comment (lunaruan) [inline packages/react-devtools-extensions/firefox/manifest.json:35]: Can you remove this too?

**Review by lunaruan — APPROVED** [review]
A couple of nits but looks good! Just to verify, you tested on Edge, Chrome, and Firefox right?

File: packages/react-devtools-extensions/src/background.js [hunk 11]
```diff
@@ -2,17 +2,41 @@
 
 'use strict';
 
+import {IS_FIREFOX} from './utils';
+
 const ports = {};
 
-const IS_FIREFOX = navigator.userAgent.indexOf('Firefox') >= 0;
+if (!IS_FIREFOX) {
+  // Manifest V3 method of injecting content scripts (not yet supported in Firefox)
```
Comment (willdurand) [inline packages/react-devtools-extensions/src/background.js:10]: Hi. Not sure if this is the best place to mention it but this is now supported in Firefox and, in fact, feature detection works generally better than user-agent detection. This extension should be trivial to "port" on Firefox MV3 ;-)

Comment (mondaychen) [reply packages/react-devtools-extensions/src/background.js:10]: Thanks for letting me know! Unfortunately we are extremely understaffed now, so we won't be able to improve it soon. I'll make it as a TODO and hope we'll find time.
