### PR TITLE
Interaction tracking follow up

### LINKED ISSUE #13512: Node/UMD bundles are broken on master
See https://github.com/facebook/react/pull/13509#pullrequestreview-150683126.
We'll need to remember to fix it one way or the other before cutting a release.

### PR DESCRIPTION
**Pull request by bvaughn**
Follow up for PR #13253. Resolves #13512

* **Reduce new dependencies** by merging the new interaction-tracking package into the (not yet released) react-scheduler package (final name TBD).
* **Avoid breaking backwards compatibility**.
  * The react-scheduler API has been _inlined_ for UMD React bundle and re-exported via `React.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED` so that renderers can safely use the new API without requiring any new `<script>` tags to be added. A UMD fork has been added to redirect react-scheduler imports to `React.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED` instead.
  * This react-scheduler API has been _re-exported_ from the shared NPM package for the CJS React bundle. I've added hard `dependencies` on react-scheduler to each reconciler renderer (e.g. react-dom, react-native, react-test-renderer) so that CJS updates will just work without requiring any additional `npm install` steps.
* **Enable the new API to be accessed from UMD bundles** by adding a UMD bundle for the react-scheduler package that (lazily) forwards methods to the `React.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED` export. Lazy forwards are important so that the `<script>` tags can be declared in the future-safe order (ie. react-scheduler before react). 

All methods for the new react-scheduler package (including interaction tracking APIs) have been prefixed with "unstable_" since they're new and relatively unproven.

As part of this change, the react-scheduler code (which used to be inlined into individual renderers) has been moved to the react package. This makes it look like the react UMD bundle has grown more than it has (rather, there is a corresponding decrease in e.g. react-dom). [Here are some diffs](https://gist.github.com/bvaughn/d900b1b3cff04ca939bbefbf60702fc5) that show the various CJS and UMD changes (NOTE these diffs reflect suspense being enabled so they may be a bit larger than otherwise expected.)

I've added a new Rollup plugin ([`scripts/rollup/plugins/strip-unused-imports.js`](https://github.com/bvaughn/react/blob/interaction-tracking-follow-up/scripts/rollup/plugins/strip-unused-imports.js)) to strip unused imports from production bundles so that production react-dom won't have any references to the tracking API.

I've also added a new fixture ([`fixtures/tracking/index.html`](https://github.com/bvaughn/react/blob/interaction-tracking-follow-up/fixtures/tracking/index.html) and [`fixtures/tracking/script.js`](https://github.com/bvaughn/react/blob/interaction-tracking-follow-up/fixtures/tracking/script.js)) to ensure that the UMD bundles are wired up correctly.

### Non-blocking follow up work
- [ ] Decide on a name for the react-scheduler package.
- [ ] Decide on the version of the initial react-scheduler release and update `package.json`s. (I assume 16.5 but for now I've left as 0.1).
- [ ] Agree on the entry point names for tracking and tracking-subscription APIs. (Currently they're `react-scheduler/tracking` and `react-scheduler/tracking-subscriptions` but I'm not married to these.)

### CODE REVIEW

File: scripts/rollup/build.js [hunk 1]
```diff
@@ -408,6 +408,33 @@ function shouldSkipBundle(bundle, bundleType) {
...
+  if (!isProduction) {
+    return;
+  }
+
+  const codeIn = fs.readFileSync(filePath, 'utf-8');
+  let codeOut = codeIn;
+
+  pureExternalModules.forEach(module => {
+    const regExp = new RegExp(
+      `(?<!= *)require\\(["']${module}["']\\)[,;]`,
```
Comment (gaearon) [inline scripts/rollup/build.js]: What does the first part of this do?

**Comment by bvaughn** [comment]
> Have we figured out why? It might be that we need to update Rollup to get some upstream bugfix. Or maybe there's something simple we can fix ourselves and send it to them.

No. I'm doing what the docs say to do wrt `treeshake.pureExternalModules`.

We can't update the Rollup version to see if it's fixed without addressing circular dependency issues between `ReactFiberScheduler` > `ReactFiberBeginWork` > `ReactFiberClassComponent` which I'd rather not tackle at the moment.

File: scripts/rollup/build.js (hunk 1 above)
Comment (bvaughn) [reply scripts/rollup/build.js]: It's a negative look behind to make sure the required module isn't being assigned to a variable.

**Comment by bvaughn** [comment]
> But I think we should only merge once we've figured out why this happens on the Rollup side.

As best I can tell, it just looks like a bug.

We're using Rollup 0.52.1 but the latest version is 0.65.0.

I don't think we can upgrade past 0.53 or 0.54 (I forget) without hitting the circular dependency issue, and that small upgrade doesn't fix the bug.

File: scripts/rollup/build.js (hunk 1 above)
Comment (bvaughn) [reply scripts/rollup/build.js]: To be clear, this is definitely a hack. ☹️ I'm just not sure how to strip the unused import any other way. And if it's important to us to avoid importing the 816 byte interaction-tracking production bundle.

**Comment by react-linter** [comment]
<details>
  <summary>Details of bundled changes.</summary>

  <p>Comparing: 6e4f7c788603dac7fccd227a4852c110b072fe16...3021a811a972c331b2cfc3f6211e54987db39ca3</p>


  
## interaction-tracking
File | Filesize Diff | Gzip Diff | Prev Size | Current Size | Prev Gzip | Current Gzip | ENV
 ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  --- 
interaction-tracking.profiling.min.js | n/a | n/a | 0 B | 2.13 KB | 0 B | 778 B | NODE_PROFILING
InteractionTracking-dev.js | n/a | n/a | 0 B | 6.58 KB | 0 B | 1.82 KB | FB_WWW_DEV
**InteractionTracking-prod.js** | **n/a** | **n/a** | **0 B** | **758 B** | **0 B** | **406 B** | **FB_WWW_PROD**
InteractionTracking-profiling.js | n/a | n/a | 0 B | 3.96 KB | 0 B | 965 B | FB_WWW_PROFILING
interaction-tracking-subscriptions.profiling.min.js | n/a | n/a | 0 B | 1.33 KB | 0 B | 520 B | NODE_PROFILING
InteractionTrackingSubscriptions-dev.js | n/a | n/a | 0 B | 4.46 KB | 0 B | 1.05 KB | FB_WWW_DEV
**InteractionTrackingSubscriptions-prod.js** | **n/a** | **n/a** | **0 B** | **457 B** | **0 B** | **311 B** | **FB_WWW_PROD**
InteractionTrackingSubscriptions-profiling.js | n/a | n/a | 0 B | 2.91 KB | 0 B | 590 B | FB_WWW_PROFILING

  </details>
  
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by gaearon** [comment]
>As best I can tell, it just looks like a bug.

It would still be good to figure out the exact cause if it doesn't take more than 10 minutes. For example by removing all code in ReactDOM except the import. Seeing if the result still includes the import. If it still reproes, you could create a small repro for rollup.

**Comment by bvaughn** [comment]
I already spent well over 10 minutes trying to track down the exact cause 😄

I mainly want to unblock a sync for now. Seems like we can file a repro with Rollup later?

**Comment by gaearon** [comment]
Sure. It's just that if we don't have the incentive we usually don't do that for many months. Since this introduces some complexity and fragility a self-imposed incentive could be helpful.

**Comment by bvaughn** [comment]
That's a good catch Dan. I have not yet added deps for interaction-tracking to `package.json`. I'll do that with a follow up commit here in a sec.

**Comment by bvaughn** [comment]
I scanned all build modules and confirmed that only the following files reference the `interaction-tracking` package:

* react-dom.development.js / react-dom.production.min.js / react-dom.profiling.min.js
* ReactDOM-dev.js / ReactDOM-prod.js / ReactDOM-profiling.js
* ReactNativeRenderer-dev.js / ReactNativeRenderer-prod.js / ReactNativeRenderer-profiling.js
* ReactFabric-dev.js / ReactFabric-prod.js / ReactFabric-profiling.js
* react-test-renderer.development.js / react-test-renderer.production.min.js
* ReactTestRenderer-dev.js
* react-reconciler.development.js / react-reconciler.production.min.js / react-reconciler-persistent.development.js / react-reconciler-persistent.production.min.js

I've updated the corresponding `package.json` to add this dependency.

My gut tells me that the best compromise to address deduplication concerns and non-backwards-breaking release for `react-dom` and co is to lock the version dep for `interaction-tracking` to match the version of react and co. So this is what I've done. (Happy to discuss this and/or change it. I don't feel strongly.)

Since this is a new, relatively unproven package– if we release it with a > 1.0 version, I should probably also rename the exported methods with an `unstable_` prefix for now.

**Comment by TrySound** [comment]
Can't you just skip circular dependency warnings in `onwarn` callback? Or something is changed in rollup behaviour?

**Comment by bvaughn** [comment]
It's not a warning. It's a runtime error.

**Comment by bvaughn** [comment]
I just pushed the React re-export change. An added benefit was that I was able to revert the Rollup strip-unused-require hack.

**Comment by bvaughn** [comment]
We already had test cases for the interaction-tracking package when the feature flag was enabled and disabled, but I went ahead and added another test that would cover the built bundle– just to ensure that the functionality that was common across all builds (e.g. tracked functions are run, wrapped functions are run, etc.) works.

**Comment by bvaughn** [comment]
Yay! Packaging fixture is happy now too.

**Comment by sebmarkbage** [comment]
Why do we have to reexport it on CJS builds? I don’t care about UMD builds because they’re a shit show regardless.

But let’s minimize the damage.

**Comment by sebmarkbage** [comment]
I think this should go on the secrets object and then we export a new script tag for interaction tracking that only re-exports that api.

There should be no public api for this on React even if it is temporarily packaged in it. That’s how we did it with React and ReactDOM back in the day. Everything was actually in React bundle.

Seems like that strategy worked well

**Comment by gaearon** [comment]
In CJS we have another concern: versioning. If you have two versions of `interaction-tracking` (one from `react-dom/node_modules` and another required by your app) they won't see each other. I figured that we already "solved" this to the best of our ability with `react` package (which is at least a peer) so we can fall back on it for this.

**Comment by sebmarkbage** [comment]
The goal of this package, just like the react-scheduler is to make it universal and used outside React and hopefully eventually part of the platform.

It seems to me that both of these new packages need to become peers for that to happen.

**Comment by sebmarkbage** [comment]
Since deferredUpdates is gone, the async strategy requires access to the scheduler. Seems like we imminently need a solution that brings it out of React too.

**Comment by gaearon** [comment]
>It seems to me that both of these new packages need to become peer dependencies for that to happen.

Yeah. But that would be a breaking change for `react-dom` so it's unfeasible until 17. Even there I'm skeptical about forcing React users to install extra packages for things they may not plan to use (like `interaction-tracking`).

>The goal of this package, just like the react-scheduler is to make it universal and used outside React and hopefully eventually part of the platform.

It can still be used universally by itself if React re-exports it. But it's a migration path to that. I don't know how you plan to make it a peer now because `require()`ing a new package is a breaking change.

`react/scheduler` and `react/interaction-tracking` is another potential compromise.

**Comment by bvaughn** [comment]
Actually I guess I can respond to this:

> Why do we have to reexport it on CJS builds? I don’t care about UMD builds because they’re a shit show regardless.

We need to access it in a consistent way from renderers. Accessing it by importing e.g. "interaction-tracking" then it would break the UMD build _unless_ we somehow re-mapped such imports to `React.unstable_interactions`.

Maybe this would be possible with our Rollup forks system and some sort of shim. I could investigate it tomorrow if you feel it's worth looking into. This would result in kind of a weird combination of `package.json` dependencies though– both react and e.g. react-dom would need to depend on the interaction-tracking package, even though it would only be used in one bundle type.

**Comment by sebmarkbage** [comment]
> it would break the UMD build unless we somehow re-mapped such imports to React.unstable_interactions.

The secrets thing seems better but let's first figure out the CJS thing.

> Even there I'm skeptical about forcing React users to install extra packages for things they may not plan to use (like interaction-tracking).

My concern is that it seems like we're trying to force this in as an intermediate step but we don't have a viable plan for how this is supposed to work in the future. So I don't understand if this intermediate step even makes that upgrade path viable.

Why does it have to be `react` that takes on the dependency? There's nothing in `react` that should depend on `interaction-tracking`. If we forget about UMD for a sec, is there any reason to put it in there?

What exactly is the breakage if the renderers take on a hard dependency on interaction-tracking and we ask *others* to add it as a peer dep. These should dedupe anyway, no? Especially since `react-dom` should be a peer dep too.

If we can't solve this, this might be a good reason to just publish this as 17. The reason we don't release majors often is because of the breaking changes inside of them are a pain to upgrade. Not because releasing majors by its own is a bad thing.

**Comment by gaearon** [comment]
I’ve never thought about making something *both* a dep and a peer. That could work. It’s still going to generate backlash though. React is already one too many packages.

**Comment by gaearon** [comment]
Wait. I misunderstood what Seb was saying.

>What exactly is the breakage if react-dom takes on a hard dependency on interaction-tracking and we ask others to add it as a peer dep. These should dedupe anyway, no? Especially since react-dom should be a peer dep too.

Who are the "others"? Component library builders? App builders? Who adds `react-dom` as a peer today?

**Comment by bvaughn** [comment]
Reading between the lines a bit on what Seb is saying, I think he might be okay with this change if I...
* Move the `interaction-tracking` re-exports from `unstable_interactions` to the SECRET_INTERNALS object.
* Make React reference the methods from SECRET_INTERNALS, so UMD build at least doesn't runtime error (but it also won't "support" interactions)
* Encourage everyone else to reference them by importing the `interaction-tracking` module directly

This would still leave the NPM dependency on `react` but...I think that might be the best we can do for 16.x

**Comment by bvaughn** [comment]
Made the change I described above via bb61480. Let me know your thoughts!

File: packages/react-reconciler/src/ReactFiberRoot.js [hunk 2]
```diff
@@ -12,13 +12,17 @@ import type {ExpirationTime} from './ReactFiberExpirationTime';
...
 import {createHostRootFiber} from './ReactFiber';
 import {NoWork} from './ReactFiberExpirationTime';
+import ReactSharedInternals from 'shared/ReactSharedInternals';
 import {enableInteractionTracking} from 'shared/ReactFeatureFlags';
 
-const {getThreadID} = React.unstable_interactions;
+// Access the interaction-tracking API from React's internal re-export.
+// This will be a re-export of the interaction-tracking package for CJS bundles,
+// And an embedded version for UMD bundles.
+// This is being done in order to break backwards compat for existing UMD apps.
```
Comment (gaearon) [inline packages/react-reconciler/src/ReactFiberRoot.js]: *not* to break? 😄

**Comment by sebmarkbage** [comment]
To that I’d an optional UMD script tag that reexports interaction tracking.

I think the UMD world is significantly different from CJS that we can make various hacks and intermediate solutions there that works completely different from the CJS world.

My concern is that I don’t think this solution makes sense for CJS. By coupling them we’re limiting us to the lowest common denominator. I’d prefer dropping UMD bundles than letting it leak into CJS.

File: packages/react/package.json [hunk 3]
```diff
@@ -21,6 +21,7 @@
     "node": ">=0.10.0"
   },
   "dependencies": {
+    "interaction-tracking": "16.4.3-alpha.0",
```
Comment (gaearon) [inline packages/react/package.json]: Is the plan to unpin this? If this is pinned then there is a high risk of duplication.

**Comment by gaearon** [comment]
@sebmarkbage 

Would you be satisfied if `react-dom` had `interaction-tracking` as a dependency (not a peer) for now, and `__SECRET` hack was used for UMD only (like we already do for `assign`)?

**Comment by sebmarkbage** [comment]
@gaearon I was thinking that react-dom has a strong dependency. No peer. But less churny renderers that nobody is using switches to peer (maybe even art).

Any library that uses findDOMNode or unstable_batchedUpdates must already use a peer dep. I thought it was pretty common. If you take on a strong dep, it’s at the root.

**Comment by sebmarkbage** [comment]
Yes. But I think we need to think of this from the perspective of scheduler. Interaction tracking is esoteric and advanced.

Async mode is useless without scheduler so we need it now.

File: packages/react-reconciler/src/ReactFiberRoot.js (hunk 2 above)
Comment (bvaughn) [reply packages/react-reconciler/src/ReactFiberRoot.js]: Haha damnit.

File: packages/react/package.json (hunk 3 above)
Comment (bvaughn) [reply packages/react/package.json]: Ah, yeah. I'll change it to "^16.4.3-alpha.0"

**Comment by gaearon** [comment]
Wild idea. Can interaction tracking be a *part* of scheduler? Branding-wise.

**Comment by sebmarkbage** [comment]
Thought: Should interaction tracking and scheduling be part of the same package? While they’re independent they’re close in problem space.

**Comment by gaearon** [comment]
lol

**Comment by bvaughn** [comment]
I'm a little confused on what the suggested path forward is here. I think you're suggesting...

1. Remove the "interaction-tracking" dependency from "react"
2. Add it as a _dependency_ to "react-dom", "react-native", and "react-test-renderer"
3. Add it as a _peer dependency_ to other renderers (e.g. "react-art")

I'm not sure how the first point is supposed to work, unless we do some bundle-type-specific hack to `ReactSharedInternals`.

**Comment by gaearon** [comment]
Regarding the scheduler: I like the idea of rolling `interaction-tracking` into it because we already have a few good names to choose from for the scheduler package, and they look more in line with what you'd expect installing React.

**Comment by bvaughn** [comment]
Not that this is the most important thing, but this PR blocks a lot of things (e.g. syncs, Web Speed testing) so bigger scope changes like rolling interaction-tracking into the scheduler should weigh that consideration.

**Comment by bvaughn** [comment]
I don't personally see interaction-tracking as specific to _scheduling_ any more than it's specific to react though, so that decision seems a bit arbitrary to me.

**Comment by gaearon** [comment]
RN syncs are blocked by npm package, right? So getting this wrong seems like more maintenance cost later.

If we don't want to get it right here, but need to unblock, we could also revert the previous PR or temporarily comment out the integration points.

**Comment by bvaughn** [comment]
RN syncs are blocked by an alpha package being pushed to NPM (so the bar is low). At the moment, I feel a higher sense of urgency for www sync 😄

**Comment by gaearon** [comment]
I think we're pretty close to something we're all happy with though. If we roll them together it's one package less to worry about. So that makes it a bit simpler.

**Comment by bvaughn** [comment]
The decision to combine them feels arbitrary to me. Aside from the convenience of having "one less package to worry about" I don't see them as fundamentally related. 😄

Plus we will still have to decide how to handle this new combined package. Seems like the same questions would need to be answered?

**Comment by gaearon** [comment]
They're related in the sense that whatever solution we pick here will have to be consistent with what we'll do for `scheduler`. So we might as well fix them together. It'll be bad if we come up with one solution for `interaction-tracking` but then find that it doesn't work well for scheduler and now we need to rethink both.

**Comment by sebmarkbage** [comment]
Web Speed and the Chrome team both have projects that combine these. So organizationally at least it seems to be a pattern.

These are also both things that would be better as part of the platform than in user space. That’s why we want others to use them. So if we ever get there we could hopefully replace them as a unit.

So they’re more like “platform”.

In terms of peer deps, I do sympathize with the concern of having too many of them.

**Comment by bvaughn** [comment]
Maybe? We seem somewhat okay with the concept of saying "interaction tracking just won't work for UMD builds" but I would guess we'd be less comfortable saying "scheduling won't work for UMD builds". Even if we decided the same solution should be applied– that doesn't necessarily suggest to me that they need to be combined into a single package.

If we did combine, maybe a more generic package name would be appropriate? Scheduling doesn't imply interaction tracking or vice versa.

**Edit** Just saw Seb's "platform" comment. Maybe that could be part of the package monicker?

**Comment by gaearon** [comment]
My main concern is that if we plan to make it a peer dep in 17, 

```
yarn add react react-dom schedule interaction-tracking
```

just doesn't make sense to me. It is too strange to explain.

This works for me:

```
yarn add react react-dom schedule
```

because we've been talking about scheduling for a long time and it's part of our message.

**Comment by bvaughn** [comment]
I agree with that concern, but I still don't think "schedule" implies anything to do with interaction-tracking.

Another option would be to just give up on the idea of interaction-tracking being used outside of React and bundle it into "react" itself so it doesn't add another dependency of any kind. (I don't think this is a good option, just voicing it.)

**Comment by bvaughn** [comment]
Maybe I just need to change the way I am thinking about this. Maybe I can come to think of it as _tracking scheduled work_ rather than an interaction, then it would make more sense to combine packages.

**Comment by gaearon** [comment]
Yeah that's how I thought about it.

**Comment by sebmarkbage** [comment]
That makes sense since the API even has threads in it.

**Comment by bvaughn** [comment]
A downside of this is that the scheduler API seems way less solidified at this point. (It doesn't yet support priorities? We haven't even picked an NPM package name?)

I'm willing to combine these two, but it seems like we'd have a few pressing decisions to make before we could move forward. 😅

**Comment by gaearon** [comment]
It can just have `unstable_` on each method for now. :P

**Comment by bvaughn** [comment]
I also think, at least from looking at the code, that our short term plan for the scheduler was to just embed it in each renderer, which wouldn't work for interaction-tracking.

**Comment by gaearon** [comment]
I think Seb's point was that now that we removed `deferredUpdates`, you can't properly schedule deferred updates in `AsyncMode`. The intended strategy was scheduler but as you said, we just embed it right now. Why not fix it and make it work if we'll have to do it for async anyway.

**Comment by bvaughn** [comment]
> Why not fix it and make it work if we'll have to do it for async anyway.

Sounds like we should. I'm just a bit concerned about time– since it's seeming less likely that I'll be able to land a sync this week, the more scope we pull in 😄 Maybe doing it now (rather than "soon") is still the right choice though.

**Comment by bvaughn** [comment]
Disregard my previous comment. I have a path forward.

**Comment by bvaughn** [comment]
Here is the new plan:

* **Reduce new dependencies** by combining interaction-tracking and react-scheduler packages (as react-scheduler)
* **Avoid breaking backwards compat** by exporting new, combined react-scheduler API from React SECRET_INTERNALS object
  * The new API will be _inlined_ for the UMD React bundle so that renderers can access the new API methods without any new `<script>` tags.
  * This new API will be _re-exported_ from the shared NPM package for the CJS React bundle. We'll add hard `dependencies` on react-scheduler to each reconciler renderer (e.g. react-dom, react-native, react-test-renderer) so that CJS updates will just work.
* **Support accessing the new API with UMD bundles** by creating a UMD bundle for the new react-scheduler package that (lazily) forwards methods to the React SECRET_INTERNALS object so that UMD users _can_ use the new API if they choose to add a `<script>` tag

**Comment by gaearon** [comment]
>This new API will be re-exported from the shared NPM package for the CJS React bundle. We'll add hard dependencies on react-scheduler to each reconciler renderer (e.g. react-dom, react-native, react-test-renderer) so that CJS updates will just work.

Do we even need to read that "secret" in CJS? Why not make direct imports from `react-dom` and friends to `scheduler`?

The approach I'm suggesting is the same as `assign`. In `react-reconciler` source code, always import `react-scheduler`. But [make a fork like this just for UMD](https://github.com/facebook/react/blob/master/packages/shared/forks/object-assign.umd.js) and [configure UMD bundles to use it](https://github.com/facebook/react/blob/b3d8c5376f1e0510963262d26e5029a9c463922f/scripts/rollup/forks.js#L26-L39).

This way the hack is contained to UMDs.

**Comment by bvaughn** [comment]
Sure. That seems reasonable. It shouldn't matter much since there's only two places we import the package anyway (`ReactFiberRoot` and `ReactFiberScheduler`)

**Comment by bvaughn** [comment]
Hm, small snag in the "lazy" method forwarding proposal for the UMD tracking bundle– `__interactionsRef` and `__subscriberRef` values are exported constants.

I would have to change the package to export getters for these in order to be able to lazily forward them. I guess that's probably okay.

**Comment by bvaughn** [comment]
Ok! My most recent commit touches a lot of files. Most of it is just rote, renaming "interaction-tracking" to e.g. "react-scheduler/tracking".

This commit implements [the plan I mentioned above](https://github.com/facebook/react/pull/13509#issuecomment-417484954) and also adds a simple UMD test fixture to verify that the API methods are forwarded correctly.

I've run a build locally and tested that fixtures/packaging works correctly. I've also tested the "suspense" demo (with DevTools) and run `yarn test` in all of its various permutations. I've also hand inspected `react` and `react-dom` bundles to make sure the CJS and UMD files contain what I would expect them to.

File: packages/react/src/ReactSharedInternals.js [hunk 4]
```diff
@@ -6,13 +6,52 @@
...
+    clear,
+    getCurrent,
+    getThreadID,
+    track,
+    wrap,
+  },
+  SchedulerTrackingSubscriptions: {
+    subscribe,
+    unsubscribe,
+  },
```
Comment (gaearon) [inline packages/react/src/ReactSharedInternals.js]: These will hang from `React` secret exports in CJS too even though CJS `ReactDOM` doesn't use it, is that correct?

In that case I think maybe it's time to fork this file into the UMD and normal versions. Or 
make a `__UMD__` constant (might be simpler). It would be unfortunate to have all these names being unminifiable for an object that ends up being unused.

**Comment by bvaughn** [comment]
[Here are some gists](https://gist.github.com/bvaughn/d900b1b3cff04ca939bbefbf60702fc5) that show the various CJS and UMD changes.

File: packages/react/src/ReactSharedInternals.js (hunk 4 above)
Comment (bvaughn) [reply packages/react/src/ReactSharedInternals.js]: Yes that's true. I considered forking but it felt gross. Maybe a __UMD__ constant would be less gross. 😄 Lemme look into that.

Comment (gaearon) [reply packages/react/src/ReactSharedInternals.js]: Not sure if this is correct but might be the reason.

screen shot 2018-08-31 at 7 04 48 pm

Comment (bvaughn) [reply packages/react/src/ReactSharedInternals.js]: The PR blurb mentions the reason I believe we're seeing this:
> As part of this change, the react-scheduler code (which used to be inlined into individual renderers) has been moved to the react package. This makes it look like react has grown more than it has (rather, there is a corresponding decrease in e.g. react-dom).

Comment (bvaughn) [reply packages/react/src/ReactSharedInternals.js]: But this would only impact the UMD bundle ^

**Comment by bvaughn** [comment]
I just re-built locally, without `enableSuspense` enabled this time, and here's the delta I'm seeing:
```
┌───────────────────────────────────────────────────────────────────────────┬───────────┬──────────────┬────────┬───────────┬──────────────┬────────┐
│ Bundle                                                                    │ Prev Size │ Current Size │ Diff   │ Prev Gzip │ Current Gzip │ Diff   │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ react.development.js  (UMD_DEV)                                           │ 57.7 KB   │ 83.71 KB     │ +45.1% │ 15.91 KB  │ 22.72 KB     │ +42.8% │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ react.production.min.js  (UMD_PROD)                                       │ 7.05 KB   │ 9.67 KB      │ +37.2% │ 2.98 KB   │ 4.04 KB      │ +35.7% │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ react.development.js  (NODE_DEV)                                          │ 48.34 KB  │ 53.77 KB     │ +11.2% │ 13.56 KB  │ 14.88 KB     │ +9.7%  │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ react.production.min.js  (NODE_PROD)                                      │ 5.59 KB   │ 6.12 KB      │ +9.5%  │ 2.42 KB   │ 2.64 KB      │ +8.8%  │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ react-dom.development.js  (UMD_DEV)                                       │ 626.47 KB │ 646.38 KB    │ +3.2%  │ 145.79 KB │ 151.22 KB    │ +3.7%  │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ react-dom.production.min.js  (UMD_PROD)                                   │ 94.25 KB  │ 94.49 KB     │ +0.3%  │ 30.53 KB  │ 30.94 KB     │ +1.4%  │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ react-dom.development.js  (NODE_DEV)                                      │ 610.84 KB │ 641.85 KB    │ +5.1%  │ 141.79 KB │ 149.91 KB    │ +5.7%  │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ react-dom.production.min.js  (NODE_PROD)                                  │ 92.74 KB  │ 94.25 KB     │ +1.6%  │ 29.52 KB  │ 30.61 KB     │ +3.7%  │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ react-dom-test-utils.development.js  (UMD_DEV)                            │ 45.27 KB  │ 45.07 KB     │ -0.4%  │ 12.47 KB  │ 12.23 KB     │ -1.9%  │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ react-dom-test-utils.production.min.js  (UMD_PROD)                        │ 10.4 KB   │ 10.65 KB     │ +2.3%  │ 3.83 KB   │ 3.94 KB      │ +2.9%  │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ react-dom-test-utils.development.js  (NODE_DEV)                           │ 40.13 KB  │ 44.79 KB     │ +11.6% │ 11.04 KB  │ 12.16 KB     │ +10.1% │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ react-dom-test-utils.production.min.js  (NODE_PROD)                       │ 9.68 KB   │ 10.44 KB     │ +7.9%  │ 3.61 KB   │ 3.88 KB      │ +7.4%  │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ react-dom-unstable-native-dependencies.development.js  (UMD_DEV)          │ 61.45 KB  │ 60.26 KB     │ -1.9%  │ 16.17 KB  │ 15.76 KB     │ -2.6%  │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ react-dom-unstable-native-dependencies.production.min.js  (UMD_PROD)      │ 11.35 KB  │ 11.22 KB     │ -1.2%  │ 3.91 KB   │ 3.87 KB      │ -1.1%  │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ react-dom-unstable-native-dependencies.development.js  (NODE_DEV)         │ 57.11 KB  │ 59.93 KB     │ +4.9%  │ 14.9 KB   │ 15.63 KB     │ +4.9%  │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ react-dom-unstable-native-dependencies.production.min.js  (NODE_PROD)     │ 10.68 KB  │ 10.97 KB     │ +2.7%  │ 3.66 KB   │ 3.78 KB      │ +3.4%  │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ react-dom-server.browser.development.js  (UMD_DEV)                        │ 102.54 KB │ 104.02 KB    │ +1.4%  │ 26.88 KB  │ 27.83 KB     │ +3.5%  │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ react-dom-server.browser.production.min.js  (UMD_PROD)                    │ 15.1 KB   │ 15.33 KB     │ +1.5%  │ 5.78 KB   │ 5.86 KB      │ +1.5%  │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ react-dom-server.browser.development.js  (NODE_DEV)                       │ 91.85 KB  │ 100.15 KB    │ +9.0%  │ 24.63 KB  │ 26.85 KB     │ +9.0%  │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ react-dom-server.browser.production.min.js  (NODE_PROD)                   │ 14.46 KB  │ 15.23 KB     │ +5.3%  │ 5.53 KB   │ 5.81 KB      │ +5.0%  │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ react-dom-server.node.development.js  (NODE_DEV)                          │ 93.77 KB  │ 102.07 KB    │ +8.9%  │ 25.16 KB  │ 27.38 KB     │ +8.8%  │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ react-dom-server.node.production.min.js  (NODE_PROD)                      │ 15.27 KB  │ 16.04 KB     │ +5.0%  │ 5.82 KB   │ 6.11 KB      │ +5.0%  │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ react-art.development.js  (UMD_DEV)                                       │ 408.05 KB │ 438.57 KB    │ +7.5%  │ 91.03 KB  │ 98.22 KB     │ +7.9%  │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ react-art.production.min.js  (UMD_PROD)                                   │ 81.12 KB  │ 85.46 KB     │ +5.4%  │ 25.01 KB  │ 26.32 KB     │ +5.2%  │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ react-art.development.js  (NODE_DEV)                                      │ 333.9 KB  │ 370.46 KB    │ +10.9% │ 72.12 KB  │ 81.19 KB     │ +12.6% │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ react-art.production.min.js  (NODE_PROD)                                  │ 45.48 KB  │ 50.23 KB     │ +10.5% │ 14.16 KB  │ 15.58 KB     │ +10.0% │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ react-test-renderer.development.js  (UMD_DEV)                             │ 341.05 KB │ 382.28 KB    │ +12.1% │ 73.8 KB   │ 83.7 KB      │ +13.4% │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ react-test-renderer.production.min.js  (UMD_PROD)                         │ 45.92 KB  │ 51.58 KB     │ +12.3% │ 14.22 KB  │ 15.88 KB     │ +11.7% │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ react-test-renderer.development.js  (NODE_DEV)                            │ 331.88 KB │ 378.01 KB    │ +13.9% │ 71.07 KB  │ 82.64 KB     │ +16.3% │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ react-test-renderer.production.min.js  (NODE_PROD)                        │ 45.03 KB  │ 51.3 KB      │ +13.9% │ 13.76 KB  │ 15.71 KB     │ +14.1% │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ react-test-renderer-shallow.development.js  (UMD_DEV)                     │ 24.36 KB  │ 24.29 KB     │ -0.3%  │ 6.5 KB    │ 6.61 KB      │ +1.7%  │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ react-test-renderer-shallow.production.min.js  (UMD_PROD)                 │ 7.15 KB   │ 7.17 KB      │ +0.3%  │ 2.34 KB   │ 2.35 KB      │ +0.2%  │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ react-test-renderer-shallow.development.js  (NODE_DEV)                    │ 14.41 KB  │ 19.48 KB     │ +35.2% │ 3.61 KB   │ 5.42 KB      │ +50.4% │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ react-test-renderer-shallow.production.min.js  (NODE_PROD)                │ 7.19 KB   │ 7.87 KB      │ +9.4%  │ 2.35 KB   │ 2.61 KB      │ +11.4% │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ react-noop-renderer.development.js  (NODE_DEV)                            │ 17.93 KB  │ 23.35 KB     │ +30.2% │ 4.69 KB   │ 5.33 KB      │ +13.6% │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ react-noop-renderer.production.min.js  (NODE_PROD)                        │ 6.67 KB   │ 8.75 KB      │ +31.2% │ 2.57 KB   │ 3.04 KB      │ +18.2% │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ react-reconciler.development.js  (NODE_DEV)                               │ 324.11 KB │ 366.29 KB    │ +13.0% │ 68.62 KB  │ 79.3 KB      │ +15.6% │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ react-reconciler.production.min.js  (NODE_PROD)                           │ 45.15 KB  │ 49.79 KB     │ +10.3% │ 13.49 KB  │ 15.08 KB     │ +11.8% │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ react-reconciler-persistent.development.js  (NODE_DEV)                    │ 322.73 KB │ 364.85 KB    │ +13.1% │ 68.04 KB  │ 78.73 KB     │ +15.7% │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ react-reconciler-persistent.production.min.js  (NODE_PROD)                │ 45.16 KB  │ 49.8 KB      │ +10.3% │ 13.49 KB  │ 15.09 KB     │ +11.8% │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ react-reconciler-reflection.development.js  (NODE_DEV)                    │ 11.57 KB  │ 14.76 KB     │ +27.6% │ 3.56 KB   │ 4.62 KB      │ +29.8% │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ react-reconciler-reflection.production.min.js  (NODE_PROD)                │ 2.26 KB   │ 2.55 KB      │ +13.1% │ 1 KB      │ 1.13 KB      │ +13.0% │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ react-is.development.js  (UMD_DEV)                                        │ 4.67 KB   │ 4.73 KB      │ +1.1%  │ 1.29 KB   │ 1.31 KB      │ +1.1%  │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ react-is.production.min.js  (UMD_PROD)                                    │ 1.89 KB   │ 1.93 KB      │ +2.1%  │ 787 B     │ 802 B        │ +1.9%  │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ react-is.development.js  (NODE_DEV)                                       │ 4.49 KB   │ 4.54 KB      │ +1.2%  │ 1.23 KB   │ 1.25 KB      │ +1.2%  │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ react-is.production.min.js  (NODE_PROD)                                   │ 1.84 KB   │ 1.88 KB      │ +2.2%  │ 719 B     │ 735 B        │ +2.2%  │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ simple-cache-provider.development.js  (NODE_DEV)                          │ 7.47 KB   │ 8.89 KB      │ +18.9% │ 2.36 KB   │ 2.86 KB      │ +21.6% │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ simple-cache-provider.production.min.js  (NODE_PROD)                      │ 1.63 KB   │ 1.64 KB      │ +0.5%  │ 827 B     │ 833 B        │ +0.7%  │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ create-subscription.development.js  (NODE_DEV)                            │ 5.5 KB    │ 8 KB         │ +45.3% │ 1.93 KB   │ 2.77 KB      │ +43.9% │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ create-subscription.production.min.js  (NODE_PROD)                        │ 2.53 KB   │ 2.82 KB      │ +11.5% │ 1.2 KB    │ 1.32 KB      │ +9.7%  │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ React-dev.js  (FB_WWW_DEV)                                                │ 48.56 KB  │ 51.38 KB     │ +5.8%  │ 13.26 KB  │ 14.22 KB     │ +7.2%  │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ React-prod.js  (FB_WWW_PROD)                                              │ 13.39 KB  │ 14.07 KB     │ +5.1%  │ 3.75 KB   │ 3.96 KB      │ +5.8%  │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ ReactDOM-dev.js  (FB_WWW_DEV)                                             │ 620.02 KB │ 663.63 KB    │ +7.0%  │ 141.13 KB │ 151.92 KB    │ +7.7%  │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ ReactDOM-prod.js  (FB_WWW_PROD)                                           │ 269.43 KB │ 289 KB       │ +7.3%  │ 50.56 KB  │ 53.85 KB     │ +6.5%  │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ ReactTestUtils-dev.js  (FB_WWW_DEV)                                       │ 41.52 KB  │ 41.88 KB     │ +0.9%  │ 11.24 KB  │ 11.21 KB     │ -0.2%  │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ ReactDOMUnstableNativeDependencies-dev.js  (FB_WWW_DEV)                   │ 57.32 KB  │ 57.63 KB     │ +0.5%  │ 14.69 KB  │ 14.58 KB     │ -0.8%  │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ ReactDOMUnstableNativeDependencies-prod.js  (FB_WWW_PROD)                 │ 26.25 KB  │ 26.68 KB     │ +1.7%  │ 5.34 KB   │ 5.36 KB      │ +0.4%  │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ ReactDOMServer-dev.js  (FB_WWW_DEV)                                       │ 95.57 KB  │ 101.25 KB    │ +5.9%  │ 24.51 KB  │ 26.51 KB     │ +8.2%  │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ ReactDOMServer-prod.js  (FB_WWW_PROD)                                     │ 31.54 KB  │ 33.06 KB     │ +4.8%  │ 7.74 KB   │ 8 KB         │ +3.5%  │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ ReactART-dev.js  (FB_WWW_DEV)                                             │ 326.2 KB  │ 375.41 KB    │ +15.1% │ 68.01 KB  │ 79.97 KB     │ +17.6% │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ ReactART-prod.js  (FB_WWW_PROD)                                           │ 142.16 KB │ 160.82 KB    │ +13.1% │ 24.25 KB  │ 27.48 KB     │ +13.3% │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ ReactNativeRenderer-dev.js  (RN_FB_DEV)                                   │ 457.61 KB │ 497.1 KB     │ +8.6%  │ 100.01 KB │ 109.96 KB    │ +10.0% │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ ReactNativeRenderer-prod.js  (RN_FB_PROD)                                 │ 205.92 KB │ 214.67 KB    │ +4.2%  │ 35.92 KB  │ 37.46 KB     │ +4.3%  │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ ReactNativeRenderer-dev.js  (RN_OSS_DEV)                                  │ 457.32 KB │ 496.83 KB    │ +8.6%  │ 99.95 KB  │ 109.9 KB     │ +10.0% │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ ReactNativeRenderer-prod.js  (RN_OSS_PROD)                                │ 194.12 KB │ 204.49 KB    │ +5.3%  │ 33.94 KB  │ 35.81 KB     │ +5.5%  │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ ReactFabric-dev.js  (RN_FB_DEV)                                           │ 448.58 KB │ 487.28 KB    │ +8.6%  │ 97.78 KB  │ 107.54 KB    │ +10.0% │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ ReactFabric-prod.js  (RN_FB_PROD)                                         │ 186.37 KB │ 197 KB       │ +5.7%  │ 32.59 KB  │ 34.31 KB     │ +5.3%  │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ ReactFabric-dev.js  (RN_OSS_DEV)                                          │ 448.61 KB │ 487.32 KB    │ +8.6%  │ 97.79 KB  │ 107.56 KB    │ +10.0% │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ ReactFabric-prod.js  (RN_OSS_PROD)                                        │ 186.4 KB  │ 197.03 KB    │ +5.7%  │ 32.61 KB  │ 34.33 KB     │ +5.3%  │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ ReactTestRenderer-dev.js  (FB_WWW_DEV)                                    │ 337.73 KB │ 383.12 KB    │ +13.4% │ 70.65 KB  │ 81.68 KB     │ +15.6% │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ ReactShallowRenderer-dev.js  (FB_WWW_DEV)                                 │ 15.14 KB  │ 17.79 KB     │ +17.5% │ 3.73 KB   │ 4.69 KB      │ +25.8% │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ ReactIs-dev.js  (FB_WWW_DEV)                                              │ 4.56 KB   │ 4.62 KB      │ +1.3%  │ 1.26 KB   │ 1.27 KB      │ +0.7%  │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ ReactIs-prod.js  (FB_WWW_PROD)                                            │ 3.67 KB   │ 3.72 KB      │ +1.5%  │ 999 B     │ 1012 B       │ +1.3%  │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ react-scheduler.development.js  (UMD_DEV)                                 │ 19.17 KB  │ 15.54 KB     │ -18.9% │ 5.74 KB   │ 4.66 KB      │ -18.9% │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ react-scheduler.production.min.js  (UMD_PROD)                             │ 3.16 KB   │ 2.87 KB      │ -9.2%  │ 1.53 KB   │ 1.28 KB      │ -16.4% │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ react-scheduler.development.js  (NODE_DEV)                                │ 14.11 KB  │ 15.35 KB     │ +8.8%  │ 4.25 KB   │ 4.62 KB      │ +8.6%  │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ react-scheduler.production.min.js  (NODE_PROD)                            │ 2.76 KB   │ 2.79 KB      │ +1.0%  │ 1.35 KB   │ 1.22 KB      │ -9.9%  │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ SimpleCacheProvider-dev.js  (FB_WWW_DEV)                                  │ 7.87 KB   │ 7.92 KB      │ +0.6%  │ 2.39 KB   │ 2.4 KB       │ +0.2%  │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ SimpleCacheProvider-prod.js  (FB_WWW_PROD)                                │ 3.63 KB   │ 3.65 KB      │ +0.5%  │ 1.1 KB    │ 1.11 KB      │ +0.9%  │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ react-noop-renderer-persistent.development.js  (NODE_DEV)                 │ 18.05 KB  │ 23.46 KB     │ +30.0% │ 4.71 KB   │ 5.34 KB      │ +13.5% │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ react-noop-renderer-persistent.production.min.js  (NODE_PROD)             │ 6.69 KB   │ 8.77 KB      │ +31.1% │ 2.58 KB   │ 3.04 KB      │ +18.1% │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ react-dom.profiling.min.js  (NODE_PROFILING)                              │ 93.65 KB  │ 97.11 KB     │ +3.7%  │ 29.86 KB  │ 31.21 KB     │ +4.5%  │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ ReactNativeRenderer-profiling.js  (RN_OSS_PROFILING)                      │ 196.66 KB │ 211.65 KB    │ +7.6%  │ 34.48 KB  │ 37.18 KB     │ +7.8%  │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ ReactFabric-profiling.js  (RN_OSS_PROFILING)                              │ 188.62 KB │ 202.98 KB    │ +7.6%  │ 33.07 KB  │ 35.63 KB     │ +7.7%  │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ ReactScheduler-dev.js  (FB_WWW_DEV)                                       │ 14.11 KB  │ 15.57 KB     │ +10.3% │ 4.26 KB   │ 4.66 KB      │ +9.2%  │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ ReactScheduler-prod.js  (FB_WWW_PROD)                                     │ 7.62 KB   │ 7.72 KB      │ +1.3%  │ 2.06 KB   │ 1.9 KB       │ -7.5%  │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ react.profiling.min.js  (NODE_PROFILING)                                  │ 0 B       │ 6.12 KB      │ n/a    │ 0 B       │ 2.64 KB      │ n/a    │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ React-profiling.js  (FB_WWW_PROFILING)                                    │ 0 B       │ 14.07 KB     │ n/a    │ 0 B       │ 3.96 KB      │ n/a    │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ ReactDOM-profiling.js  (FB_WWW_PROFILING)                                 │ 0 B       │ 295.42 KB    │ n/a    │ 0 B       │ 55.26 KB     │ n/a    │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ ReactNativeRenderer-profiling.js  (RN_FB_PROFILING)                       │ 0 B       │ 220.09 KB    │ n/a    │ 0 B       │ 38.66 KB     │ n/a    │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ ReactFabric-profiling.js  (RN_FB_PROFILING)                               │ 0 B       │ 202.94 KB    │ n/a    │ 0 B       │ 35.61 KB     │ n/a    │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ react-scheduler-tracking.development.js  (UMD_DEV)                        │ 0 B       │ 7.75 KB      │ n/a    │ 0 B       │ 2.4 KB       │ n/a    │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ react-scheduler-tracking.production.min.js  (UMD_PROD)                    │ 0 B       │ 836 B        │ n/a    │ 0 B       │ 470 B        │ n/a    │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ react-scheduler-tracking.development.js  (NODE_DEV)                       │ 0 B       │ 7.55 KB      │ n/a    │ 0 B       │ 2.33 KB      │ n/a    │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ react-scheduler-tracking.production.min.js  (NODE_PROD)                   │ 0 B       │ 690 B        │ n/a    │ 0 B       │ 378 B        │ n/a    │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ react-scheduler-tracking.profiling.min.js  (NODE_PROFILING)               │ 0 B       │ 1.86 KB      │ n/a    │ 0 B       │ 793 B        │ n/a    │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ ReactSchedulerTracking-dev.js  (FB_WWW_DEV)                               │ 0 B       │ 7.15 KB      │ n/a    │ 0 B       │ 2.05 KB      │ n/a    │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ ReactSchedulerTracking-prod.js  (FB_WWW_PROD)                             │ 0 B       │ 859 B        │ n/a    │ 0 B       │ 416 B        │ n/a    │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ ReactSchedulerTracking-profiling.js  (FB_WWW_PROFILING)                   │ 0 B       │ 4.02 KB      │ n/a    │ 0 B       │ 1019 B       │ n/a    │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ react-scheduler-tracking-subscriptions.development.js  (UMD_DEV)          │ 0 B       │ 5.49 KB      │ n/a    │ 0 B       │ 1.57 KB      │ n/a    │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ react-scheduler-tracking-subscriptions.production.min.js  (UMD_PROD)      │ 0 B       │ 619 B        │ n/a    │ 0 B       │ 394 B        │ n/a    │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ react-scheduler-tracking-subscriptions.development.js  (NODE_DEV)         │ 0 B       │ 5.27 KB      │ n/a    │ 0 B       │ 1.49 KB      │ n/a    │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ react-scheduler-tracking-subscriptions.production.min.js  (NODE_PROD)     │ 0 B       │ 429 B        │ n/a    │ 0 B       │ 301 B        │ n/a    │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ react-scheduler-tracking-subscriptions.profiling.min.js  (NODE_PROFILING) │ 0 B       │ 470 B        │ n/a    │ 0 B       │ 327 B        │ n/a    │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ ReactSchedulerTrackingSubscriptions-dev.js  (FB_WWW_DEV)                  │ 0 B       │ 4.82 KB      │ n/a    │ 0 B       │ 1.19 KB      │ n/a    │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ ReactSchedulerTrackingSubscriptions-prod.js  (FB_WWW_PROD)                │ 0 B       │ 442 B        │ n/a    │ 0 B       │ 304 B        │ n/a    │
├───────────────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────┼───────────┼──────────────┼────────┤
│ ReactSchedulerTrackingSubscriptions-profiling.js  (FB_WWW_PROFILING)      │ 0 B       │ 578 B        │ n/a    │ 0 B       │ 338 B        │ n/a    │
└───────────────────────────────────────────────────────────────────────────┴───────────┴──────────────┴────────┴───────────┴──────────────┴────────┘
```

**Comment by bvaughn** [comment]
Just noticed that the scheduler UMD bundle looks unexpected. Give me a few to dig into this.

File: packages/react/src/ReactSharedInternals.js (hunk 4 above)
Comment (gaearon) [reply packages/react/src/ReactSharedInternals.js]: Aaah I forgot it's measuring UMD

**Comment by bvaughn** [comment]
Some stuff has changed since you gave the PR a 👍 @gaearon – want me to hold off on merging until you've 👍again?

File: scripts/rollup/build.js [hunk 5]
```diff
@@ -349,6 +352,9 @@ function getPlugins(
           renaming: !shouldStayReadable,
         })
       ),
+    // HACK to work around the fact that Rollup isn't removing unused, pure-module imports.
+    // Note that this plugin must be called after closure applies DCE.
+    isProduction && stripUnusedImports(pureExternalModules),
```
Comment (gaearon) [inline scripts/rollup/build.js]: We still need this right?

File: scripts/rollup/forks.js [hunk 6]
```diff
@@ -114,12 +114,57 @@ const forks = Object.freeze({
...
+  'react-scheduler': (bundleType, entry, dependencies) => {
     switch (bundleType) {
       case FB_WWW_DEV:
       case FB_WWW_PROD:
       case FB_WWW_PROFILING:
         return 'shared/forks/ReactScheduler.www.js';
+      case UMD_DEV:
+      case UMD_PROD:
+        if (dependencies.indexOf('react') === -1) {
+          // For CJS bundles, use the shared NPM package.
```
Comment (gaearon) [inline scripts/rollup/forks.js]: This comment doesn’t seem to make sense inside UMD conditionn

**Comment by bvaughn** [comment]
> There’s a lot here but I can review and test in more details on Monday. Either way we can probably get this in and then maybe iterate on top. To unbreak master.

Sounds great.

> What is the primary motivation for keeping interactions and interaction subscriptions separate? It feels like some of the complexity is just because these are two separate entry points. Is it to save bundle size? Something else?

Seb was a big fan of this idea to split them up. It does save a little bit on bundle size, but more importantly I think, it removes a lot of iteration and error-catching complexity from the main tracking module in the (most likely) event that you aren't using subscriptions.

File: scripts/rollup/build.js (hunk 5 above)
Comment (bvaughn) [reply scripts/rollup/build.js]: Yup, if we want to avoid a no-op side require being in a production bundle. At least making it a plug-in like @TrySound suggested should be a bit faster since it doesn't have to do any extra file IO

File: scripts/rollup/forks.js (hunk 6 above)
Comment (bvaughn) [reply scripts/rollup/forks.js]: Hah, you're right.

Comment (bvaughn) [reply scripts/rollup/forks.js]: I meant for that comment to be in the below `default` case. I just rebased and cleaned that one up.

**Comment by gaearon** [comment]
>It does save a little bit on bundle size, but more importantly I think, it removes a lot of iteration and error-catching complexity from the main tracking module in the (most likely) event that you aren't using subscriptions.

If the concern is in implementation complexity why not keep them as separate files but re-export from both in a single entry point? Conceptually they’re related.

**Comment by gaearon** [comment]
Wanna unify then? Seems like this would simplify the bundling setup and UMDs.

**Comment by bvaughn** [comment]
> Wanna unify then? Seems like this would simplify the bundling setup and UMDs.

I'm trying this locally now. If it's not too churny, I'll push it here. Else I might do it via a follow up.

**Comment by bvaughn** [comment]
As things are currently written, this would have a bit of an impact. During initialization, the subscriptions module registers itself as a subscriber with the tracking module's `subscriberRef.current` so that it can work. This will cause tracking module to call a bunch of subscriber functions even if nothing is using them.

I think this is avoidable though by just delaying registration until the first time a subscriber is added.

**Comment by bvaughn** [comment]
Looks like it turned out to just simplify a bunch of small things 😄 So done~

**Comment by bvaughn** [comment]
Local testing/fixtures look good. My test app seems happy. Hand inspected the bundles and they look good. Assuming CI is happy– I'm going to land this and we can iterate on it more on Monday if anything else pops up. 😄 I'm feeling good about these changes though!

**Comment by bvaughn** [comment]
CI failure is due to Yarn registry again. Restarting...

File: packages/react-scheduler/npm/umd/react-scheduler-tracking.js [hunk 7]
```diff
@@ -0,0 +1,95 @@
...
+
+  function unstable_wrap() {
+    return global.React.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED.SchedulerTracking.unstable_wrap.apply(
+      this,
+      arguments
+    );
+  }
+
+  return Object.freeze({
+    __getInteractionsRef: __getInteractionsRef,
```
Comment (gaearon) [inline packages/react-scheduler/npm/umd/react-scheduler-tracking.js]: It would be nice to have some automatic check that verifies the list of exports matches the list of commonjs exports 1:1

Comment (gaearon) [reply packages/react-scheduler/npm/umd/react-scheduler-tracking.js]: (I understand you added a fixture but someone could add a method to CJS API, and forget to test it in fixture)

Comment (bvaughn) [reply packages/react-scheduler/npm/umd/react-scheduler-tracking.js]: Yeah, that's reasonable. Although I think the bundled UMD solution is pretty nice, I'm not very happy with these "shims" and the way they kind of bypass our normal build system.

I'm not sure how to add an automated check without increasing the hackiness. Any ideas?

Comment (gaearon) [reply packages/react-scheduler/npm/umd/react-scheduler-tracking.js]: A node script that imports all bundles after build and verifies their exports match up.

Or a Jest test if you can figure out a way to import the entry point shim.

**Comment by bvaughn** [comment]
I've run all of the CI scripts/checks locally, so I'm going to go ahead and land this without waiting for the Yarn registry issue to be resolved.

File: packages/react-scheduler/npm/umd/react-scheduler-tracking.js (hunk 7 above)
Comment (bvaughn) [reply packages/react-scheduler/npm/umd/react-scheduler-tracking.js]: Whoops, this comment just came through. I'll tackle this with a follow up :)
