### PR TITLE
[DevTools] Enable minimal support in pages with `sandbox` Content-Security-Policy

### LINKED ISSUE #29647: [DevTools Bug]: devtools does not works on null origin(sandbox)
### Website or app

none

## How to reproduce?
Using the development version of React on a local server with sandbox specified in the Content-Security-Policy header reproduces this problem.
For example, in webpack-dev-server, apply the following configuration: 
```ts
  devServer: {
    headers: {
      "Content-Security-Policy": "sandbox allow-scripts",
      "Access-Control-Allow-Origin": "*",
    },
  },
```

### How often does this bug happen?

Every time

### DevTools package (automated)

_No response_

### DevTools version (automated)

_No response_

### Error message (automated)

_No response_

### Error call stack (automated)

_No response_

### Error component stack (automated)

_No response_

### GitHub query string (automated)

_No response_

### LINKED ISSUE #34268: [DevTools Bug]: devtools does not works on null origin(sandbox)
### Website or app

Please refer to 'How to reproduce'.

### Repro steps

Save the following code as `server.js` , then run the command:
`node server.js 1234 --sandbox`
and open `http://127.0.0.1:1234` in your browser.
When you check the Developer Tools, you'll notice that the React Components tab doesn't appear.

```js
const http = require("http");

const args = process.argv.slice(2);
const withSandbox = args.includes("--sandbox");
if (args.length < 1) {
  console.error("Usage: node server.js <port> [--sandbox]");
  process.exit(1);
}

const html = `
<!DOCTYPE html>
<html>
  <head>
    <title>Hello</title>
  </head>
  <body>
    <div id="root"></div>
    <script crossorigin src="https://unpkg.com/react@18/umd/react.development.js"></script>
    <script crossorigin src="https://unpkg.com/react-dom@18/umd/react-dom.development.js"></script>
    <script>
      const App = () => React.createElement("h1", {}, "Hello, React${
        withSandbox ? " (sandbox enabled)" : ""
      }");
      ReactDOM.createRoot(document.getElementById("root")).render(App());
    </script>
  </body>
</html>`;

const port = parseInt(args[0], 10);
if (Number.isNaN(port) || port <= 0) {
  console.error("Invalid port:", args[0]);
  process.exit(1);
}
const sendRes = (req, res, status, contentType, body) => {
  res.statusCode = status;
  res.setHeader("Content-Type", contentType + "; charset=utf-8");
  if (withSandbox)
    res.setHeader("Content-Security-Policy", "sandbox allow-scripts");
  if (req.method !== "OPTIONS ") res.end(body);
};

http
  .createServer((req, res) => {
    if (req.url === "/") {
      sendRes(req, res, 200, "text/html", html);
    } else {
      sendRes(req, res, 404, "text/plain", "404 Not Found");
    }
  })
  .listen(port, () => {
    console.log(
      `Server listening on port ${port}${
        withSandbox ? " (sandbox enabled)" : ""
      }`
    );
  });
```

I submitted a ticket over a year ago, but since it has not yet been resolved, I have resubmitted it with detailed information on how to reproduce the issue.
related #29647

### How often does this bug happen?

Every time

### DevTools package (automated)

_No response_

### DevTools version (automated)

_No response_

### Error message (automated)

_No response_

### Error call stack (automated)

```text

```

### Error component stack (automated)

```text

```

### GitHub query string (automated)

```text

```

### PR DESCRIPTION
**Pull request by mochiya98**
# Summary

fix #34268, close #29647 (duplicated)

The current implementation uses `chrome.devtools.inspectedWindow.eval()` , which can be blocked by a page's Content Security Policy (CSP). To handle this, I implemented a fallback mechanism that, if eval fails, attempts to evaluate the code in a Content Script.

Because Content Scripts do not have access to the `Developer Tools Console API` (e.g., inspect(), $0), some features (e.g. focusing a specified DOM node in the Elements panel) will remain unavailable.  
However, this change still improves a situation where developer tools were completely unusable and will make many features available.

## How to test

Please follow the reproduction steps from the original issue (#34268) to test behavior.  

Note: when you reload the extension, tabs that were already open may not behave correctly. After loading the extension, open a new tab to test.

## Detailed flow of operations

```mermaid
sequenceDiagram
    participant DevTools as DevTools Page<br>(main/index.js)
    participant Background as Background Script<br>(background/messageHandlers.js)
    participant CS as Content Script<br>[ExecutionWorld.ISOLATE]<br>(contentScripts/proxy.js)
    participant Page as Content Script<br>[ExecutionWorld.MAIN]<br>(contentScripts/fallbackEvalContext.js)
    
    alt First, attempt the regular processing
        DevTools->>DevTools: chrome.devtools.inspectedWindow.eval()
    else If it fails due to an error, run the fallback process below. (e.g. CSP Blocked)
        
        Note right of DevTools: Message:<br>{ source: 'devtools-page', payload: {<br>type: 'eval-in-inspected-window',<br>tabId, requestId, scriptId, args, } }
        DevTools->>Background: chrome.runtime.sendMessage()
        
        Note right of Background: Message:<br>{source: 'devtools-page-eval',<br>payload: { scriptId, args, } }
        Background->>CS: chrome.tabs.sendMessage()
        
        Note right of CS: Message:<br>{ source: 'react-devtools-<br>content-script-eval',<br>payload: { requestId, scriptId, args, } }
        CS->>Page: window.postMessage()
        
        Note over Page: Eval in Content Script<br>evalScripts[scriptId].apply(null, args);
        
        Note right of CS: Message:<br>{ source: 'react-devtools-<br>content-script-eval-response',<br>payload: { requestId, response, } }
        Page-->>CS: window.postMessage(Response)
        Note right of Background: Message:<br> response ( {result, error} )
        CS-->>Background: sendResponse()
        Note right of DevTools: { source: 'react-devtools-background',<br>payload: { type: 'eval-in-inspected-<br>window-response',<br>requestId, result, error, } }
        Background-->>DevTools: chrome.runtime.sendMessage()
    end
```

### CODE REVIEW

File: packages/react-devtools-extensions/src/contentScripts/proxy.js [hunk 1]
```diff
@@ -117,3 +117,39 @@ function connectPort() {
...
+});
+
+window.addEventListener('message', event => {
+  if (event.data?.source === 'react-devtools-content-script-eval-response') {
+    const {requestId, response} = event.data.payload;
+    const callback = evalRequestCallbacks.get(requestId);
+    if (callback) {
+      callback(response);
+      evalRequestCallbacks.delete(requestId);
+    }
```
Comment (eps1lon) [inline packages/react-devtools-extensions/src/contentScripts/proxy.js]: Should this error if there's no callback registered with that request ID?

File: packages/react-devtools-extensions/src/contentScripts/proxy.js [hunk 2]
```diff
@@ -117,3 +117,39 @@ function connectPort() {
...
+  }
+});
+
+window.addEventListener('message', event => {
+  if (event.data?.source === 'react-devtools-content-script-eval-response') {
+    const {requestId, response} = event.data.payload;
+    const callback = evalRequestCallbacks.get(requestId);
+    if (callback) {
+      callback(response);
+      evalRequestCallbacks.delete(requestId);
```
Comment (eps1lon) [inline packages/react-devtools-extensions/src/contentScripts/proxy.js:162]: Maybe wrap the `callback(response)` in `try-finally` so that we don't leak callbacks if they error.

File: packages/react-devtools-extensions/src/contentScripts/proxy.js (hunk 1 above)
Comment (mochiya98) [reply packages/react-devtools-extensions/src/contentScripts/proxy.js]: If no callback is provided, do nothing. Logging an error here would show up in the user's page console and could cause unnecessary confusion. This is a rare edge case that shouldn't occur in normal operation, so this is sufficient, I think.

File: packages/react-devtools-extensions/src/contentScripts/proxy.js (hunk 2 above)
Comment (mochiya98) [reply packages/react-devtools-extensions/src/contentScripts/proxy.js:162]: Whoops, this is definitely a problem. I’ll fix it. Thank you.

**Comment by mochiya98** [comment]
Thank you.

That certainly seems like a good improvement.
I consolidated all eval processing into `src/evalScripts.js`, updated the callers, and added the license header and Flow definitions.

File: packages/react-devtools-extensions/src/contentScripts/proxy.js (hunk 1 above)
Comment (eps1lon) [reply packages/react-devtools-extensions/src/contentScripts/proxy.js]: We also log errors in the user console for other backend failures so that's not a concern.

Comment (mochiya98) [reply packages/react-devtools-extensions/src/contentScripts/proxy.js]: Thank you. Honestly, I still have concerns about logging this to the user's page console, but I respect your opinion and will add the error-logging.

**Comment by rearchitec** [comment]
@eps1lon @hoxyq +1 on this. 
We can't use DevTools at all in our CSP-restricted environment. 
This would be a significant improvement for enterprise users. 
 Is there anything blocking this?

**Comment by eps1lon** [comment]
Sorry for the delay. We had to deal with some urgent security vulnerabilities and then the holidays further delayed a response.

Validated that this works. What is unclear to me is why this works. `chrome.devtools.inspectedWindow.eval` allows running in the content script context via `useContentScriptContext: true` (https://developer.chrome.com/docs/extensions/reference/api/devtools/inspectedWindow). Isn't that the same as manually executing the code in a content script like this PR does? Feels like some unnecessary security ceremony on Chrome's part or a bypass of `Content-Security-Policy: sandbox`. @mochiya98 Can you explain the difference? Or does `useContentScriptContext: true` not work because it runs in the context of proxy.js which is isolated?

**Comment by mochiya98** [comment]
To be honest, I don't have complete insight into Chrome's internals, but based on my testing with a simpler implementation using only a main world content script before this PR, it appears that `useContentScriptContext: true` always evaluates in the Isolated world regardless of the execution world type of the injected content scripts. So I don't think the presence of an Isolated world content script like proxy.js is relevant here. I also tried various values for `contextSecurityOrigin`, but it didn't change the behavior.

So while this implementation is more complex, I believe it's unavoidable due to Chrome's security constraints.
