### PR TITLE
Profiler actualDuration bugfix

### LINKED ISSUE #13309: Profiler durations are sometimes incorrect
While working on the DevTools profiler, I've noticed that durations are sometimes incorrect. This seems to be vaguely related to high/low priority state updates. Need to track this down more so I'm filing an issue for myself.

### PR DESCRIPTION
**Pull request by bvaughn**
While testing the new DevTools profiler, I noticed that sometimes– in larger, more complicated applications– an incorrect value was being reported for `actualDuration` (often too large, occasionally negative).

Unfortunately I was unable to capture the problem in a test, but I believe it has something to do with the way I was tracking render times across different priorities and roots. So this PR replaces the old approach with a simpler one that I believe is more robust.

Anecdotally, the timing problems I was able to reproduce before in my test app(s) are no longer happening after this change. I think the code is also easier to read and reason about now.

Resolves #13309

### CODE REVIEW

**Comment by react-linter** [comment]
ReactDOM: size: 0.0%, gzip: -0.0%


  <details>
  <summary>Details of bundled changes.</summary>

  <p>Comparing: 00cd4444e2a8ad3c48188b5c0e3db37842d867f0...c771d23686873bb4f96d1d272a7a1bebd80beb65</p>


  
## react-dom
File | Filesize Diff | Gzip Diff | Prev Size | Current Size | Prev Gzip | Current Gzip | ENV
 ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  --- 
react-dom.development.js | -0.5% | -0.6% | 641.68 KB | 638.46 KB | 150.61 KB | 149.76 KB | UMD_DEV
**react-dom.production.min.js** | **0.0%** | **-0.0%** | **95.9 KB** | **95.92 KB** | **31.08 KB** | **31.08 KB** | **UMD_PROD**
react-dom.development.js | -0.5% | -0.6% | 637.82 KB | 634.6 KB | 149.43 KB | 148.58 KB | NODE_DEV
**react-dom.production.min.js** | **0.0%** | **0.0%** | **95.89 KB** | **95.9 KB** | **30.61 KB** | **30.61 KB** | **NODE_PROD**
ReactDOM-dev.js | -0.5% | -0.6% | 644.96 KB | 641.77 KB | 147.77 KB | 146.85 KB | FB_WWW_DEV
**ReactDOM-prod.js** | **:small_red_triangle:+0.3%** | **0.0%** | **277.69 KB** | **278.48 KB** | **52.1 KB** | **52.12 KB** | **FB_WWW_PROD**
react-dom.profiling.min.js | +0.1% | -0.0% | 97.02 KB | 97.07 KB | 31.01 KB | 31.01 KB | NODE_PROFILING
ReactDOM-profiling.js | -0.1% | -0.2% | 280.98 KB | 280.57 KB | 52.82 KB | 52.71 KB | FB_WWW_PROFILING

## react-art
File | Filesize Diff | Gzip Diff | Prev Size | Current Size | Prev Gzip | Current Gzip | ENV
 ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  --- 
react-art.development.js | -0.8% | -0.9% | 427.11 KB | 423.9 KB | 96.47 KB | 95.61 KB | UMD_DEV
**react-art.production.min.js** | **-0.0%** | **-0.0%** | **83.25 KB** | **83.24 KB** | **25.75 KB** | **25.74 KB** | **UMD_PROD**
react-art.development.js | -0.9% | -1.1% | 359.63 KB | 356.42 KB | 79.41 KB | 78.55 KB | NODE_DEV
**react-art.production.min.js** | **-0.0%** | **-0.1%** | **48.23 KB** | **48.23 KB** | **15.15 KB** | **15.13 KB** | **NODE_PROD**
ReactART-dev.js | -0.9% | -1.1% | 349.71 KB | 346.52 KB | 74.25 KB | 73.42 KB | FB_WWW_DEV
**ReactART-prod.js** | **:small_red_triangle:+0.1%** | **:small_red_triangle:+0.1%** | **148.93 KB** | **149.11 KB** | **25.42 KB** | **25.44 KB** | **FB_WWW_PROD**

## react-test-renderer
File | Filesize Diff | Gzip Diff | Prev Size | Current Size | Prev Gzip | Current Gzip | ENV
 ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  --- 
react-test-renderer.development.js | -0.9% | -1.1% | 362.85 KB | 359.64 KB | 79.68 KB | 78.81 KB | UMD_DEV
react-test-renderer.development.js | -0.9% | -1.1% | 358.98 KB | 355.77 KB | 78.7 KB | 77.84 KB | NODE_DEV
ReactTestRenderer-dev.js | -0.9% | -1.1% | 363.98 KB | 360.78 KB | 77.63 KB | 76.79 KB | FB_WWW_DEV

## react-reconciler
File | Filesize Diff | Gzip Diff | Prev Size | Current Size | Prev Gzip | Current Gzip | ENV
 ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  --- 
react-reconciler.development.js | -0.9% | -1.2% | 347.97 KB | 344.76 KB | 75.3 KB | 74.44 KB | NODE_DEV
**react-reconciler.production.min.js** | **0.0%** | **-0.0%** | **47.44 KB** | **47.45 KB** | **14.37 KB** | **14.36 KB** | **NODE_PROD**
react-reconciler-persistent.development.js | -0.9% | -1.2% | 346.59 KB | 343.38 KB | 74.75 KB | 73.88 KB | NODE_DEV
**react-reconciler-persistent.production.min.js** | **0.0%** | **-0.0%** | **47.45 KB** | **47.46 KB** | **14.37 KB** | **14.37 KB** | **NODE_PROD**

## react-native-renderer
File | Filesize Diff | Gzip Diff | Prev Size | Current Size | Prev Gzip | Current Gzip | ENV
 ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  --- 
ReactNativeRenderer-dev.js | -0.7% | -0.8% | 482.14 KB | 478.94 KB | 106.48 KB | 105.61 KB | RN_FB_DEV
**ReactNativeRenderer-prod.js** | **-0.4%** | **-0.2%** | **213.76 KB** | **212.84 KB** | **37.44 KB** | **37.37 KB** | **RN_FB_PROD**
ReactNativeRenderer-dev.js | -0.7% | -0.8% | 481.88 KB | 478.68 KB | 106.43 KB | 105.56 KB | RN_OSS_DEV
**ReactNativeRenderer-prod.js** | **-0.4%** | **-0.2%** | **203.8 KB** | **202.89 KB** | **35.82 KB** | **35.75 KB** | **RN_OSS_PROD**
ReactFabric-dev.js | -0.7% | -0.8% | 472.36 KB | 469.15 KB | 104.05 KB | 103.17 KB | RN_FB_DEV
**ReactFabric-prod.js** | **:small_red_triangle:+0.1%** | **-0.0%** | **194.92 KB** | **195.16 KB** | **34.27 KB** | **34.27 KB** | **RN_FB_PROD**
ReactFabric-dev.js | -0.7% | -0.8% | 472.39 KB | 469.19 KB | 104.07 KB | 103.19 KB | RN_OSS_DEV
**ReactFabric-prod.js** | **:small_red_triangle:+0.1%** | **-0.0%** | **194.95 KB** | **195.2 KB** | **34.29 KB** | **34.28 KB** | **RN_OSS_PROD**
ReactNativeRenderer-profiling.js | -0.6% | -0.4% | 207.31 KB | 206.05 KB | 36.51 KB | 36.35 KB | RN_OSS_PROFILING
ReactFabric-profiling.js | -0.0% | -0.3% | 197.97 KB | 197.89 KB | 34.91 KB | 34.8 KB | RN_OSS_PROFILING
ReactNativeRenderer-profiling.js | -0.6% | -0.4% | 217.23 KB | 215.97 KB | 38.13 KB | 37.97 KB | RN_FB_PROFILING
ReactFabric-profiling.js | -0.0% | -0.3% | 197.93 KB | 197.85 KB | 34.89 KB | 34.78 KB | RN_FB_PROFILING

  </details>
  
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

File: packages/react-reconciler/src/ReactProfilerTimer.js [hunk 1]
```diff
@@ -42,155 +35,47 @@ function recordCommitTime(): void {
...
-      warningWithoutStack(
-        false,
-        'Cannot start base timer that is already running. ' +
-          'This error is likely caused by a bug in React. ' +
-          'Please file an issue.',
-      );
+  if (profilerStartTime >= 0) {
+    const elapsedTime = now() - profilerStartTime;
+    fiber.actualDuration += elapsedTime;
+    if (overrideBaseTime) {
```
Comment (bvaughn) [inline packages/react-reconciler/src/ReactProfilerTimer.js]: Base time is a little awkward to handle. Before, we were only including "begin" phase work in the base time value– and this PR continues that behavior, because I wasn't sure how to preserve the behavior we wanted otherwise (without adding an additional field).

The behavior is, essentially:
* When cloning a fiber, copy the base time from the previous render.
* If the fiber bails out, leave that value in place.
* If the fiber renders, override the base time value.
* When the fiber completes, bubble up base times from its children.

Since we are using a single timer to track both the "actual duration" and "base duration" values, and this timer wraps both the "begin" and "render" phases– I opted to only update base time during render (since we know definitively whether we have bailed out or not during that phase).

If this is silly for some reason, or you know of a better way to achieve this, let's chat!

File: packages/react/src/__tests__/ReactProfiler-test.internal.js [hunk 2]
```diff
@@ -895,8 +894,8 @@ describe('Profiler', () => {
             // But it spends time rendering all of the failed subtree also.
             expect(mountCall[1]).toBe('mount');
             // actual time includes: 2 (ErrorBoundary) + 5 (AdvanceTime) + 10 (ThrowsError)
-            // If replayFailedUnitOfWorkWithInvokeGuardedCallback is enbaled, ThrowsError is replayed.
-            expect(mountCall[2]).toBe(flagEnabled && __DEV__ ? 27 : 17);
+            // We don't count the time spent in replaying the failed unit of work (ThrowsError)
+            expect(mountCall[2]).toBe(17);
```
Comment (bvaughn) [inline packages/react/src/__tests__/ReactProfiler-test.internal.js]: This particular detail seems kind of arbitrary.

The PR changes the timing so that we override the actual time spent during the failure with the time spent while retrying it (only for that particular fiber)– but I think this is fine.

File: packages/react/src/__tests__/ReactProfiler-test.internal.js [hunk 3]
```diff
@@ -422,19 +421,19 @@ describe('Profiler', () => {
...
 
-      advanceTimeBy(30); // 25 -> 55
+      advanceTimeBy(30); // 28 -> 58
 
       renderer.update(
         <React.unstable_Profiler id="test" onRender={callback}>
-          <AdvanceTime byAmount={10}>
-            <AdvanceTime byAmount={10} shouldComponentUpdate={false} />
+          <AdvanceTime byAmount={4}>
+            <AdvanceTime byAmount={7} shouldComponentUpdate={false} />
```
Comment (bvaughn) [inline packages/react/src/__tests__/ReactProfiler-test.internal.js]: This change was an unnecessary one but made the test a little stronger since 10&10 could give a false positive.

File: packages/react-reconciler/src/ReactFiberScheduler.js [hunk 4]
```diff
@@ -811,11 +796,28 @@ function completeUnitOfWork(workInProgress: Fiber): Fiber | null {
 
     if ((workInProgress.effectTag & Incomplete) === NoEffect) {
       // This fiber completed.
-      nextUnitOfWork = completeWork(
-        current,
-        workInProgress,
-        nextRenderExpirationTime,
-      );
+      if (enableProfilerTimer) {
+        if (workInProgress.mode & ProfileMode) {
```
Comment (acdlite) [inline packages/react-reconciler/src/ReactFiberScheduler.js]: Nit: Can you combine the `enableProfiler` check with these inner checks? Or do we not trust the build system to strip out the dead code?

Comment (bvaughn) [reply packages/react-reconciler/src/ReactFiberScheduler.js]: Nope, this is just something subjective I've done because it seems to read more clearly that the outer conditional is a feature flag. Happy to combine them if you have a preference.

**Comment by bvaughn** [comment]
Friendly ping 😄
