### PR TITLE
Wrap setInnerHTML in Windows 8 apps (Fixes #441)

### LINKED ISSUE #441: React throws when rendering some HTML tags inside Windows 8 app.
When using React in a JavaScript-based Windows 8 app, some HTML tags will cause an error to be thrown during mounting. For example an audio tag, as shown [here](http://jsfiddle.net/WPn3A/) causes the following error.

> 0x800c001c - JavaScript runtime error: Unable to add dynamic content. A script attempted to inject dynamic content, or elements previously modified dynamically, that might be unsafe. For example, using the innerHTML property to add script or malformed HTML will generate this exception. Use the toStaticHTML method to filter dynamic content, or explicitly create elements and attributes with a method such as createElement.  For more information, see http://go.microsoft.com/fwlink/?LinkID=247104.

This is not a hugely pressing issue, but we should probably offer some way of using window.toStaticHTML where it's available.

### PR DESCRIPTION
**Pull request by stkb**
See #441 

If React is running in a Windows 8 metro app, creates a version of setInnerHTML that uses [execUnsafeLocalFunction](http://msdn.microsoft.com/en-us/library/windows/apps/hh767331.aspx) to bypass the restrictive html-insertion security policy of that javascript runtime.

### CODE REVIEW

File: src/browser/ui/dom/setInnerHTML.js [hunk 1]
```diff
@@ -28,6 +28,15 @@ var setInnerHTML = function(node, html) {
   node.innerHTML = html;
 };
 
+// Win8 apps: Allow all html to be inserted
+if (typeof MSApp !== 'undefined' && MSApp.execUnsafeLocalFunction) {
+    setInnerHTML = function (node, html) {
```
Comment (zpao) [inline src/browser/ui/dom/setInnerHTML.js]: nit: no space after `function` keyword

Comment (zpao) [inline src/browser/ui/dom/setInnerHTML.js]: Also, 2 spaces

**Comment by zpao** [comment]
Seems fine to me apart from the style nits.

**Comment by stkb** [comment]
Thanks, code style now fixed :)

**Comment by zpao** [comment]
Thanks!

**Comment by syranide** [comment]
I don't have access to W8, but could it make sense to wrap the entire transaction in `execUnsafeLocalFunction` rather than each invocation of `setInnerHTML`, i.e. is there are measurable performance overhead? I sincerely doubt it though.

**Comment by syranide** [comment]
There's also [`WinJS.Utilities.setInnerHTMLUnsafe`](http://msdn.microsoft.com/en-us/library/windows/apps/br211696.aspx) which seems like a better method to use for each invocation... unless we intend to wrap the entire transaction in [`MSApp.execUnsafeLocalFunction`](http://msdn.microsoft.com/en-us/library/windows/apps/hh767331.aspx)?

**Comment by stkb** [comment]
Regarding using `WinJS.Utilities.setInnerHTMLUnsafe`, I first considered that but didn't want to use a `WinJS.*` method, since using the WinJS library is not a requirement for writing a javascript Windows 8 app (it's perfectly possible to do it without, and if you don't use it, you still have the `Windows` and `MSApp` global objects but no `WinJS`). After digging deeper I found that [all that function does](https://github.com/winjs/winjs/blob/3b216e2e5727689657ed459fde940053096f03b6/src/js/WinJS/Utilities/_SafeHtml.js#L70) is exactly what the new code in React.js is doing:
``` javascript
setInnerHTMLUnsafe = function (element, text) { 
83             msApp.execUnsafeLocalFunction(function () { 
84                 element.innerHTML = text; 
85             }); 
86         }; 
```

As far as the placement of the wrapping goes, I'm not familiar with the React.js codebase so just chose the safest place for it. I noticed that the setInnerHTML function is used in a couple places in the codebase (as well as some where it isn't yet and I think it should be) so I didn't want to potentially litter the code with lots of checks for `MSApp`. But if you can find a better place for it then fair enough. I haven't done any performance measurements but haven't noticed any sluggishness either.

**Comment by syranide** [comment]
@stkb Aha, good detective work on `setInnerHTMLUnsafe`! As for wrapping transactions higher up, I doubt it's worth it but you never know, I don't ever think you'd be able to "feel it", but it could show up in benchmarks... even though I doubt that too. It's something to consider for the future at least. :)

On another note, I think [createNodesFromMarkup](https://github.com/facebook/react/blob/master/src/vendor/core/createNodesFromMarkup.js) needs to be wrapped as well for this to *really* work? (related #2340) I.e. if you perform an "unsafe update" it will still throw I think...

**Comment by stkb** [comment]
@syranide Agreed it's something in to keep in mind for the future or if anyone has performance problems in Windows apps.

I will take a look at createNodesFromMarkup...

Also forgot to say @zpao thanks for the merge :)
